### ISSUE TITLE
Prepare for Release v0.2.0

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#100]
## Announcing Code Freeze for v0.2.0 Release

Hi all -

Thanks for everyone's contributions to `powerlevel9k`! We have added some significant new features since the v0.1.0 release tag, and I believe now is a good time to prepare for the v0.2.0 release. 

The `next` branch is now frozen except for bug fixes and documentation improvements. If you aren't already using `next`, please switch over to help us test!

Thanks so much for contributing to this project! It makes a huge difference.

## Contributors to-date for v0.2.0:

@dritter 
@labianchin 
@jkoelndorfer 
@giladgo
@christian-schulze
@tusharsrivastava
@natemccurdy 
@dsager

**Comment by bhilburn** [comment]
Hi all -

We have received some great bug fixes / improvements to `next`, and I think we are nearing the release.

I would like to give the README a nice facelift. A part of this will be providing some screenshots of different configurations.

Can you all do me a favor and post a screenshot of your prompt configuration, if you don't mind sharing it? Thanks!

@dritter 
@labianchin 
@jkoelndorfer 
@giladgo
@christian-schulze
@tusharsrivastava
@natemccurdy 
@dsager

**Comment by dritter** [comment]
@bhilburn why don't we collect these screenshots on a new wiki page? I had this in mind for several weeks now.

Just started [this page](https://github.com/bhilburn/powerlevel9k/wiki/Show-off-your-configuration!). Hopefully this is what you had in mind. By having a separate wiki page we motivate others to share their configurations, other users get help and a showcase, and we get some nice screenshots.

**Comment by bhilburn** [comment]
@dritter - Actually, yes, I was going to put most of them in a wiki page. Thanks for getting it started! I do want to take a couple of them and feature them at the top of the README, though.

**Comment by dritter** [comment]
@bhilburn I think besides new screenshots, we need a nice animated gif as many other themes have. That would be a nice-to-have in the readme as well as in the [External themes](https://github.com/robbyrussell/oh-my-zsh/wiki/External-themes) page.

**Comment by bhilburn** [comment]
@dritter - I agree, an animated gif would be nice. Any recommendations for good tools to create them?

**Comment by giladgo** [comment]
@bhilburn LICEcap http://www.cockos.com/licecap/

**Comment by dritter** [comment]
Another option would be [ttystudio](https://github.com/chjj/ttystudio).

If we want videos instead of animated gifs, we could use [asciinema](https://github.com/asciinema/asciinema).

For that I think we need a good script to record the best features. IMHO that should be features that most of our users customize, like flexible segments, overriding colors, the flexibility of the vcs segment, etc.

**Comment by bhilburn** [comment]
Hey all - 

I'm going to update the readme and tag a new release this week. If you haven't already and are up for it, please post your configuration here for our users =)

https://github.com/bhilburn/powerlevel9k/wiki/Show-off-your-configuration!

**Comment by bhilburn** [comment]
v0.2.0 has been tagged and released!!

Thanks for your contributions and help, everyone!

**Comment by dritter** [comment]
Awesome!
The new README looks great! :+1:
