### ISSUE TITLE
Battery foreground colors not working

### ISSUE THREAD

**Issue by vaskark** [bhilburn/powerlevel9k#1002]
Hi. I'm trying to set the battery foreground colors and not having any luck. This is what I have:

POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'

But the foreground remains white in both cases. I even tried including "_FOREGROUND", but without success.

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
Oh-My-ZSH (latest git)
P9K (latest git clone)
URxvt, Tilix, Gnome-Terminal

I'm on Ubuntu Bionic. I should mention that I also have an Arch system in VBox and the colours do show up there, so it might be Ubuntu-specific.

Any help is appreciated. Thanks.

Edit: Hmmm ... seems to be working now. Not sure what I did as I was monkeying with a lot of settings. Feel free to delete.

**Comment by dritter** [comment]
Closing as requested. Glad it is working now.
