### ISSUE TITLE
double-lined theme artefact

### ISSUE THREAD

**Issue by antonavy** [bhilburn/powerlevel9k#1006]
#### Describe Your Issue
What is happening?
I'm trying to use the double-lined theme form. But I see a white arrow at the start of the second line.

https://monosnap.com/file/GmzOrGGLXZtndZAzGMkMpRQ1hzL6wJ

#### Have you tried to debug or fix it?
Tried to move things around, didn't help.

#### Environment Information
This information will help us understand your configuration. 

  - zsh 5.5.1 (x86_64-apple-darwin17.5.0)
  - Using .yadr.
  - Cloned the repo and copied it to .zsh.prompts.
  - Latest to 07.10.2018
  - iTerm2

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - https://monosnap.com/file/EVPDRinN3QqjyhhhorUIiw3xKZyiHF
  - nerdfont-complete
  - https://pastebin.com/bmVgChLt
  - debug/iterm.zsh — https://pastebin.com/XZaVVMaL
  - If this is an icon problem, does the output of `$ get_icon_names` look correct? Not sure what you want me to do here

**Comment by JulienPivard** [comment]
It's fix in #978. Could you try and tel me if it work for you ?

**Comment by dritter** [comment]
Hey @antonavy ,
Could you try the `next` branch as @JulienPivard suggested? Closing this for now. Feel free to reopen, if the issue persists.
