### ISSUE TITLE
Termux 

### ISSUE THREAD

**Issue by ourfor** [bhilburn/powerlevel9k#1007]
I want to hide this information . "grep ...."
![screenshot_2018-10-08-09-35-45-380_com termux](https://user-images.githubusercontent.com/33711476/46589573-ccf52080-cadd-11e8-8914-6fbda94638e1.png)

**Comment by dritter** [comment]
Hey @ourfor ,
Thanks for the bug report. This is fixed on the `next` branch. Could you try that branch?
