### ISSUE TITLE
vi_mode segment not working as KEYMAP parameter no longer being set

### ISSUE THREAD

**Issue by christian-schulze** [bhilburn/powerlevel9k#101]
Unfortunately the `vi_mode` segment has stopped functioning after being merged into the `next` branch,  which I've traced back to the `KEYMAP` parameter no longer being set.

`${KEYMAP}` should evaluate to one of `vicmd|viins|main` but is now blank. I'm pretty new to zsh so if anyone has any ideas please chime in. In the meantime I'll do some more troubleshooting.

**Comment by dritter** [comment]
Strange. The other code in `next` should be completely unrelated. I'll try to double check that later.

**Comment by bhilburn** [comment]
Fixed by merging PR #104.
