### ISSUE TITLE
Unvisible root_indicator using next branch

### ISSUE THREAD

**Issue by qkdreyer** [bhilburn/powerlevel9k#1010]
#### Describe Your Issue
What is happening?
_Root Indicator isn't shown_

![image](https://user-images.githubusercontent.com/717869/46674172-ca78f080-cbdb-11e8-8521-41ff1541ceb5.png)

#### Have you tried to debug or fix it?
_https://github.com/bhilburn/powerlevel9k/compare/master...next_

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using? _zsh 5.3.1 (x86_64-debian-linux-gnu)_
  - Do you use a ZSH framework ? _Oh-My-ZSH_
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? _Git clone_
  - What version of P9k are you using? _next branch_
  - Which terminal emulator do you use? _iTerm2 3.2.3_

#### Issues with Fonts & Icons

  - Which font do you use? _Meslo LG L DZ for Powerline_
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using?
![image](https://user-images.githubusercontent.com/717869/46674464-7d494e80-cbdc-11e8-8c5d-5799d820bf91.png)

  - Please share the contents of `$P9k/debug/font-issues.zsh`.
![image](https://user-images.githubusercontent.com/717869/46674493-905c1e80-cbdc-11e8-8175-0d460c872624.png)

  - If this is an icon problem, does the output of `$ show_defined_icons` look correct?
![image](https://user-images.githubusercontent.com/717869/46674836-66efc280-cbdd-11e8-8d75-10396869e7cf.png)

**Comment by qkdreyer** [comment]
![image](https://user-images.githubusercontent.com/717869/46674748-3dcf3200-cbdd-11e8-891f-acdad2b3c29b.png)

**Comment by amlamarra** [comment]
Just a side note, I'd recommend making the root_indicator on the right prompt off by default. Especially since left prompt already shows you're running as root. And that one's easier to see anyway.

**Comment by bhilburn** [comment]
Fixed by merge of #1016 in `next`!
