### ISSUE TITLE
[VSCode] UI Bug in Visual Studio Code

### ISSUE THREAD

**Issue by menjilx** [bhilburn/powerlevel9k#1030]
Hi,
There are some minor UI bugs when viewing the VSCODE with "Powerlevel9K" & "zsh" integration.

Here's the screenshot
![image](https://user-images.githubusercontent.com/14908836/46948902-2c40cb00-d0b2-11e8-9970-bdde85b4dde4.png)

And here's the comparison when viewing it in the "iTerm"
![image](https://user-images.githubusercontent.com/14908836/46948935-4da1b700-d0b2-11e8-998d-57c2010e8439.png)

The arrow UI is perfectly align-center.

Thanks

**Comment by onaforeignshore** [comment]
If you look at the output in VSCODE, you will notice that all the icons are higher in the line, not just the arrow. Have you looked at [this](https://github.com/bhilburn/powerlevel9k/issues/672#issuecomment-343748848)?

**Comment by menjilx** [comment]
> If you look at the output in VSCODE, you will notice that all the icons are higher in the line, not just the arrow. Have you looked at [this](https://github.com/bhilburn/powerlevel9k/issues/672#issuecomment-343748848)?

I tried it but I'm not sure if my configuration is correct.
SS below.
![image](https://user-images.githubusercontent.com/14908836/46955367-5bad0300-d0c5-11e8-9195-81a1cd699c6d.png)

Thanks @onaforeignshore

**Comment by onaforeignshore** [comment]
`POWERLEVEL9K_DIR_DEFAULT_` is for the default state. There are also other states. These are my settings, but it shows you all the variables for the dir segment.
```zsh
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="27"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="252"
POWERLEVEL9K_DIR_DEFAULT_ICON="\uF115"
POWERLEVEL9K_DIR_DEFAULT_ICON_COLOR="255"
#POWERLEVEL9K_DIR_DEFAULT_BOLD=true

POWERLEVEL9K_DIR_HOME_BACKGROUND="27"
POWERLEVEL9K_DIR_HOME_FOREGROUND="252"
POWERLEVEL9K_DIR_HOME_ICON="\uF46D"
POWERLEVEL9K_DIR_HOME_ICON_COLOR="255"
#POWERLEVEL9K_DIR_HOME_BOLD=true

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="27"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="252"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_ICON="\uF114"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_ICON_COLOR="255"
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BOLD=true

POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="124"
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="252"
#POWERLEVEL9K_DIR_NOT_WRITABLE_ICON=""
POWERLEVEL9K_DIR_NOT_WRITABLE_ICON_COLOR="255"
#POWERLEVEL9K_DIR_NOT_WRITABLE_BOLD=true

POWERLEVEL9K_DIR_ETC_BACKGROUND="55"
POWERLEVEL9K_DIR_ETC_FOREGROUND="252"
#POWERLEVEL9K_DIR_ETC_ICON=""
POWERLEVEL9K_DIR_ETC_ICON_COLOR="255"
#POWERLEVEL9K_DIR_ETC_BOLD=true

POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND="226"
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true

POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND="226"
```

**Comment by menjilx** [comment]
> If you look at the output in VSCODE, you will notice that all the icons are higher in the line, not just the arrow. Have you looked at [this](https://github.com/bhilburn/powerlevel9k/issues/672#issuecomment-343748848)?

this one uses a different theme but thank you for this guide.

**Comment by menjilx** [comment]
> POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="27" POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="252" POWERLEVEL9K_DIR_DEFAULT_ICON="\uF115" POWERLEVEL9K_DIR_DEFAULT_ICON_COLOR="255" #POWERLEVEL9K_DIR_DEFAULT_BOLD=true POWERLEVEL9K_DIR_HOME_BACKGROUND="27" POWERLEVEL9K_DIR_HOME_FOREGROUND="252" POWERLEVEL9K_DIR_HOME_ICON="\uF46D" POWERLEVEL9K_DIR_HOME_ICON_COLOR="255" #POWERLEVEL9K_DIR_HOME_BOLD=true POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="27" POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="252" POWERLEVEL9K_DIR_HOME_SUBFOLDER_ICON="\uF114" POWERLEVEL9K_DIR_HOME_SUBFOLDER_ICON_COLOR="255" #POWERLEVEL9K_DIR_HOME_SUBFOLDER_BOLD=true POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="124" POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="252" #POWERLEVEL9K_DIR_NOT_WRITABLE_ICON="" POWERLEVEL9K_DIR_NOT_WRITABLE_ICON_COLOR="255" #POWERLEVEL9K_DIR_NOT_WRITABLE_BOLD=true POWERLEVEL9K_DIR_ETC_BACKGROUND="55" POWERLEVEL9K_DIR_ETC_FOREGROUND="252" #POWERLEVEL9K_DIR_ETC_ICON="" POWERLEVEL9K_DIR_ETC_ICON_COLOR="255" #POWERLEVEL9K_DIR_ETC_BOLD=true POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND="226" POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND="226"

Thank you so much sir, I got it working now.

![image](https://user-images.githubusercontent.com/14908836/46955757-45537700-d0c6-11e8-8145-571ad4e30229.png)

**Comment by onaforeignshore** [comment]
You're welcome. Please close this issue if you are satisfied.

**Comment by menjilx** [comment]
> You're welcome. Please close this issue if you are satisfied.

On my "iTerm" it works great!
![image](https://user-images.githubusercontent.com/14908836/46956083-fa862f00-d0c6-11e8-8312-dc10fc61224c.png)

But on the VScode it doesn't look good for now.
![image](https://user-images.githubusercontent.com/14908836/46956115-0f62c280-d0c7-11e8-86d7-9ea8504cad69.png)

**Comment by menjilx** [comment]
Here's my configuration

`// terminal configuration

    "terminal.integrated.fontFamily": "Inconsolata-dz for Powerline",
    "terminal.integrated.shell.osx": "zsh",
    "terminal.integrated.enableBell": true,
    "terminal.integrated.showExitAlert": true,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontSize": 14,`

**Comment by onaforeignshore** [comment]
Did you try adding `"terminal.external.osxExec": "iTerm.app",`?

**Comment by menjilx** [comment]
> Did you try adding `"terminal.external.osxExec": "iTerm.app",`?

Yeah, I also tried that and here's the output,
![image](https://user-images.githubusercontent.com/14908836/46957740-c4e34500-d0ca-11e8-9d1d-8da5d9780597.png)

Not that bad though but there's still a bug on the icon part.

**Comment by menjilx** [comment]
Sir @onaforeignshore FINALLY after how many hours debugging the UI bugs.

I got it working, here's my VScode configuration.

`**// terminal configuration
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.fontFamily": "Meslo LG L DZ for Powerline",
    "terminal.integrated.shell.osx": "zsh",
    "terminal.integrated.enableBell": true,
    "terminal.integrated.showExitAlert": true,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.fontSize": 14,**`
