### ISSUE TITLE
Update Font Color

### ISSUE THREAD

**Issue by menjilx** [bhilburn/powerlevel9k#1031]
Hi,
Can someone help me or point me to a tutorial on how to edit/modify the font-color for the current directory? Cause the color blue and black font seems to difficult to read.

Here's the screenshot
![image](https://user-images.githubusercontent.com/14908836/46954865-3370d480-d0c4-11e8-8fb7-e9a2c709a28e.png)

Thank you so much!

**Comment by onaforeignshore** [comment]
Refer to the [Wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization)

**Comment by menjilx** [comment]
FIXED! Thanks sir @onaforeignshore 
Here's the link -> [https://github.com/bhilburn/powerlevel9k/issues/1030#issuecomment-429864014](url)
