### ISSUE TITLE
Battery icon doesn't work after Mojave update

### ISSUE THREAD

**Issue by jack793** [bhilburn/powerlevel9k#1033]
After the update to Mojave OS, open terminal and load zsh give me this error and battery icon/status does not appear:

**_prompt_battery:local:28: not an identifier: 4964_**

zshrc file has the following option:
```
.
.
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator battery)
.
.
```
Anyone encountered same error after SO update?
Please help me, thank u so much!

**Comment by JulienPivard** [comment]
I updated it a few weeks ago and I didn't encounter any problems. Have you try restart your mac ? 
What is the result of this : `/usr/bin/pmset -g batt`  ?

**Comment by jack793** [comment]
it gives me this response:

$ /usr/bin/pmset -g batt                                                                                             
Now drawing from 'AC Power'
 -InternalBattery-0 (id=5374051)	100%; charged; 0:00 remaining present: true

**Comment by jack793** [comment]
ok i ll try thank for this support ❤️

**Comment by dritter** [comment]
Thanks @JulienPivard for the support. :+1:

Closing this issue for now. @jack793 feel free to reopen, if this issue persists on `next`.
