### ISSUE TITLE
Sudo detection does not work

### ISSUE THREAD

**Issue by DickSteelOy** [bhilburn/powerlevel9k#1034]
#### Sudo detection does not work

I made a custom prompt for p9k to show when sudo has been used:

> prompt_sudo_indicator(){
  local color="%F{red}"
  local symbol=""
  if [[ -n "$SUDO_COMMAND" ]]; then
        echo -n "%{$color%}$symbol "
  else
  	echo -n ""
  fi 
}

Using $SUDO_COMMAND does not work for me, I do not get the icon to show up.
Else statement works, so it goes through it just fine.

If I type:

> sudo -s -E

the icon will appear.

My .zshrc is as follows:

> ZSH_THEME="powerlevel9k/powerlevel9k"     
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'dir' 'vcs' 'sudo_indicator')

#### Have you tried to debug or fix it?

I made a script to run in terminal, and that one works perfectly.

> #!/bin/zsh
if [[ -n "$SUDO_COMMAND" ]]; then
        echo  "Sudo used!"
  else
        echo  "Sudo not used!"
fi

#### Environment Information

  - zsh 5.5.1
  - ZSH framework (Oh-My-ZSH)
  - P9k (cloning the repo)
  - Release v0.6.6
  - Gnome-terminal

**Comment by DickSteelOy** [comment]
So, I did more digging on the matter and understand the problem. It was also discussed here before. Sorry.

Marking this closed.

**Comment by bhilburn** [comment]
@DickSteelOy - Glad you're all set! Let us know if anything changes!
