### ISSUE TITLE
What parameters should I use to change the background color and foreground color of the user name?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [bhilburn/powerlevel9k#1043]
![2331](https://user-images.githubusercontent.com/12076232/47636901-eea16f00-db94-11e8-9360-2cf661429813.png)
What parameters should I use to change the background color and foreground color of the user name?

**Comment by bhilburn** [comment]
Hi @Yakumo-Yukari! Check out this page of our wiki:
https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization

If that doesn't fix the issue for you, please re-open and let us know what's wrong!
