### ISSUE TITLE
How to remove AWS icon/legend

### ISSUE THREAD

**Issue by cig0** [bhilburn/powerlevel9k#1044]
#### Describe Your Issue
What is happening?
Is there a way to disable the `AWS: ` legend, without touching the theme file?

Most issues are best explained with a screenshot. Please share one if you can!

<img width="217" alt="screen shot 2018-10-29 at 13 02 29" src="https://user-images.githubusercontent.com/394089/47676895-ff44eb80-db7a-11e8-9a6d-80e642b50cae.png">

#### Have you tried to debug or fix it?
I can do it by editing the theme file, but I'm inclined to think it's not the right approach...

Have you tinkered with your settings, and what happened when you did? Did you find a bit of code that you think might be the culprit? Let us know what you've done so far!

Works as intended when removing `AWS_ICON`:

```
if [[ -n "$aws_profile" ]]; then
    "$1_prompt_segment" "$0" "$2" red white "$aws_profile" 'AWS_ICON'
  fi
```

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using? `zsh 5.6.2 (x86_64-apple-darwin18.0.0)`
  - Do you use a ZSH framework `Oh-My-ZSH`
  - How did you install P9k `cloning the repo`
  - What version of P9k are you using? `0.6.4` (but looking to upgrade to 0.6.6 this weekend)
Note: I moved ahead and upgraded to `0.6.6`, it is working great.

  - Which terminal emulator do you use? `iTerm2 3.2.4`

Thanks!

**Comment by bhilburn** [comment]
@cig0 - The recommended way to do this is to set the `AWS_ICON` to an empty char (`''`). Try it out, and please re-open this issue if you have any problems!

https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#icon-customization
