### ISSUE TITLE
Document support for Powerlevel9k on Linux distros

### ISSUE THREAD

**Issue by ryanwhocodes** [bhilburn/powerlevel9k#1064]
#### Describe Your Issue

I have developers asking me about using Powerlevel9k on Linux distros, such as Arch and Fedora. Could there be a section in the documentation that covers Linux support?

**Comment by JulienPivard** [comment]
In the wiki you have a section Install. I saw an arch section there, but I don't know if it's going to be complete enough for your use. Feel free to tell us what's missing

**Comment by JulienPivard** [comment]
I think this link could help : https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions

**Comment by sambadevi** [comment]
The simplest answer with almost no portability issues would be 
https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#option-1-install-for-vanilla-zsh

Git is installed on most linux distros by default and zsh is usually available in the package-manager of your distro

The only thing that really differs per distro and per console(-emulator) is how to install powerline-fonts or nerd-fonts (if needed).

**Comment by sambadevi** [comment]
@ryanwhocodes I assume this issue can be closed since there wasn’t any activity on this?
