### ISSUE TITLE
`fatal: '...' is outside repository` error when using "vcs" element, in a subdirectory

### ISSUE THREAD

**Issue by Zeta611** [bhilburn/powerlevel9k#1067]
#### Describe Your Issue
I started to encounter
```
fatal: ...: '...' is outside repository
```
error in a *very specific* directory, with the most recent commit.
I find it really strange, since it happens in a folder called "\~/Documents/서울대학교 자료/" and all folders within it.
I wasn't able to reproduce the error—trying non-ASCII characters, folders with spacings—in any other folders outside it.
ANY folders within "\~/Documents/서울대학교 자료/" that are version-controlled with git has this issue.
The issue is as follows:
```
fatal: ~/Documents/서울대학교 자료/test: '~/Documents/서울대학교 자료/test' is outside repository
```
is shown inside a subdirectory `a` within `test`.
It occurs in any subdirectories of a git-controlled directory within `서울대학교 자료`.

<img width="1792" alt="2018-11-15 18 36 42" src="https://user-images.githubusercontent.com/9553691/48546872-bdeb6480-e90c-11e8-8243-ea3bc3d2d717.png">

#### Have you tried to debug or fix it?
The error only occurs with "vcs" segment enabled.
Also, with `.zshrc`
```
zplug "bhilburn/powerlevel9k", \
    use:powerlevel9k.zsh-teme, \
    at:78df520
```
using the commit 78df520, the error is gone.
However, I couldn't reproduce the error occurs in any other directories.

#### Environment Information
This information will help us understand your configuration. 

  - zsh version: zsh 5.6.2
  - zplug 2.4.2
  - via zplug
  - 6cfe8f8
  - iTerm2 Build 3.2.20180825

**Comment by diraol** [comment]
I'm facing the same problem. As far as I could understand, it is happening inside git submodules directories.

![p9k](https://user-images.githubusercontent.com/192702/48600258-50fabd80-e952-11e8-886f-848b3264f43a.png)

**Comment by dritter** [comment]
Thanks for the report @Zeta611 . This is indeed a problem when you are inside a git submodule. @macserv fixed it on `next`, our development branch.

@diraol @Zeta611 Could you try out #1071 ?

**Comment by diraol** [comment]
Tested and approved!

**Comment by Zeta611** [comment]
`next` branch does not fix my issue. Now it doesn't get my unique path and returns:
`__p9k_get_unique_path:31: no matches found: /Users/jay/Documents//ᄉ*/`. `fatal: /Users/jay/Documents/서울대학교 자료/2학기/공학수학 1/LectureNotes: '/Users/jay/Documents/서울대학교 자료/2학기/공학수학 1/LectureNotes' is outside repository` is still showing. It won't even show a NERDFont icon with `P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="\uF719  "`.
Yes, I updated all `POWERLEVEL9K_`'s with `P9K_`'s.
This is what I get with an updated `next` branch:

<img width="946" alt="2018-11-17 09 14 13" src="https://user-images.githubusercontent.com/9553691/48653516-28092400-ea49-11e8-9168-80abe2bce879.png">

**Comment by dritter** [comment]
Hi @Zeta611 , @diraol 's tip should have helped. Could you restart your Machine and see if that helps? If not, could you go a bit more into detail in what you have tried?

**Comment by Zeta611** [comment]
After trying to figure out what's the problem, I found out an odd bug.
If I make a folder with Korean characters in the Finder app (of macOS), the `fatal` error occurs in any git-controlled folder within it.
The folder with a name in Korean characters is not git-controlled, and the git-controlled folder within it is an empty git repository:
<img width="762" alt="2018-11-17 12 11 28" src="https://user-images.githubusercontent.com/9553691/48655969-2730bc00-ea62-11e8-936a-8988d8eae85b.png">

Oddly, if I create a folder with Korean characters *within* a terminal, the error vanishes:
<img width="762" alt="2018-11-17 12 11 28" src="https://user-images.githubusercontent.com/9553691/48655989-82fb4500-ea62-11e8-89ea-2ac8eece1de9.png">

Maybe this is an macOS w/ Korean characters (I haven't tried other languages, but CJK characters might be a problem) issue...?
Is it possible for a folder named within a GUI finder and the one named in a terminal to behave differently?

This is the minimal .zshrc file:
```
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "bhilburn/powerlevel9k", \
    use:powerlevel9k.zsh-theme, \
    at:next

if zplug check bhilburn/powerlevel9k; then
    P9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
fi
zplug load
```

**Comment by onaforeignshore** [comment]
Please do `file -I ` (capital i) for both and paste the results here. My guess is that the file names are encoded differently. From what I have read in my research, macOS does decomposed encoding (e.g. ¨ then e) as opposed to precomposed (ë). See [here](https://stackoverflow.com/a/6153713)

**Comment by Zeta611** [comment]
@onaforeignshore  `file -I 한글 한글2` prints:
```
한글:  inode/directory; charset=binary
한글2: inode/directory; charset=binary
```

I think your guess is right, since making a folder `ä` within a terminal works fine, but `ä2` in the Finder app spits the same error message: `__p9k_get_unique_path:31: no matches found`.

Is there a way to resolve this issue?
Thanks for your help!

**Comment by Zeta611** [comment]
@onaforeignshore I'm using macOS Mojave 10.14.1, and using APFS filetype.. Does the example with `ä` works fine on your mac?

**Comment by onaforeignshore** [comment]
I am using High Sierra 10.13.6 with APFS and it works for me.
<img width="670" alt="screen shot 2018-11-17 at 12 56 53" src="https://user-images.githubusercontent.com/704406/48659332-b214b500-ea68-11e8-9549-88949307e36f.png">

**Comment by Zeta611** [comment]
Although it is odd, this wasn't a problem with 78df520 and prior versions. (I see that there is a huge update going on) Is there a change in code responsible for handling encodings? It seems that both the original issue in the thread regarding the "vcs" element and the unique path problem is related.

**Comment by Zeta611** [comment]
While I'm trying to find out how to resolve this encoding issue, I made an ad hoc fix to suppress the issue.
At least I can identify the directory with the faulty _decomposed_ encoding, which is the one not truncated.
From what I learned after some research, zsh uses `iconv` internally to handle decomposed UTF-8 characters, but how to utilize it is beyond my reach as of now.

**Comment by diraol** [comment]
Should we close this issue and open another one related to the encoding error?

**Comment by dritter** [comment]
@diraol You are right. Closing this. Not sure if we should open a new issue, cause this seems to be a bug in git itself. I get the error even with plain bash.

**Comment by Zeta611** [comment]
@dritter I think the error of mine is more than a git bug, but I also agree with closing the issue. (It is more about an encoding problem in my case.)

**Comment by bhilburn** [comment]
Thanks for chatting through all of this, everyone!
