### ISSUE TITLE
Add missing icons in `awesome-fontconfig`

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#107]
@V1rgul could you add the missing Icons in my [`awesome_fontconfig_cleanup`](https://github.com/dritter/powerlevel9k/tree/awesome_fontconfig_cleanup)-branch? That would be awesome. Unfortunately neither me nor @bhilburn have installed awesome-terminal-fonts the fontconfig way..
Here is a screenshot of the `awesome-patched` configuration:
![bildschirmfoto 2015-09-28 um 20 21 13](https://cloud.githubusercontent.com/assets/1544760/10144671/187340ae-661f-11e5-944c-9a62dccf48e4.png)

**Comment by bhilburn** [comment]
Fixed by #108
