### ISSUE TITLE
Character duplicate when using tab completion

### ISSUE THREAD

**Issue by wicksome** [bhilburn/powerlevel9k#1072]
[![asciicast](https://asciinema.org/a/HKKZRTTEnq6BDFV2JkwYsHRqZ.svg)](https://asciinema.org/a/HKKZRTTEnq6BDFV2JkwYsHRqZ)

The first character is duplicated when I use tab.
I have revised many issues but still reproduced.

I found reason of this issue.
If I add `vi_mode` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`, duplicate charactre.

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status vcs dir newline)
```

![image](https://user-images.githubusercontent.com/5036939/48605116-3b6fad00-e9bf-11e8-8151-c6948d7d0146.png)

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status vcs dir newline vi_mode_joined)
or
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status vcs dir newline vi_mode)
```

![image](https://user-images.githubusercontent.com/5036939/48605147-4de9e680-e9bf-11e8-9c67-7449178ed98a.png)

**Comment by wicksome** [comment]
It works well if except icon setting.

```bash
POWERLEVEL9K_VI_INSERT_MODE_STRING='\u26A1'
POWERLEVEL9K_VI_COMMAND_MODE_STRING='\u26A1'
```

**Comment by wicksome** [comment]
I solve this issue by using iTerm config https://github.com/sindresorhus/pure/issues/39#issuecomment-341653736

**Comment by dritter** [comment]
Awesome finding @wicksome ! I documented it on [our wiki troubleshooting page](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#character-duplication-on-completion).

**Comment by denty** [comment]
How to solve this problem in Terminal.app

**Comment by juliomsilva** [comment]
> How to solve this problem in Terminal.app

check if this can solve your problem.
https://github.com/sindresorhus/pure/issues/39#issuecomment-386371357
