### ISSUE TITLE
Custom ZDOTDIR seems to not be handled

### ISSUE THREAD

**Issue by flohw** [bhilburn/powerlevel9k#1085]
#### Describe Your Issue
* The `PROMPT` variable is unchanged.
* I setup my `ZDOTDIR` variable to `$HOME/.config/zsh/` in that folder I keep my whole zsh configuration into multiple files. I am with arch linux and started my configuration from scratch. I installed the theme as explained in the [installation guide](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#arch-linux) and source the theme file in my `$ZDOTDIR/.zshrc` but my prompt is still the default one: `%m%#`

#### Have you tried to debug or fix it?

* I uncommented the three lines for debug to be sure the file is loaded and it is (but I can't really understand what it does and where the problem might be)
* I tried to run `source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme`

None of the two above attempts worked

I tried to remove my `~/.zshenv` file and create a `~/.zshrc` file with the line to source the theme, it worked properly.

#### Environment Information

* I am with archlinux
* zsh 5.6.2, installed via pacman
* P9k 0.6.6-1
* I use terminator as terminal emulator
* `~/.zshenv` defines `ZDOTDIR` (which equals `$HOME/.config/zsh`)
* `ZDOTDIR/.zshrc` sources the theme file
* `zsh -v` display all my files and p9k theme properly

I would like to do so to be able to configure my zsh environment and be able to use git easily (I use stow to manage my configuraiton, acting like so ease the stow directory structure and management)

I hope someone can help me. Let me know if you need other information.

Thank you ! :smiley:

**Comment by flohw** [comment]
I tried to install with oh my zsh in a custom `$ZDOTDIR` and it worked fine. But I don't know the difference which break the initialization of the prompt. The file seems to be executed from top to bottom: I added "echo 'test'" on the last line of the file and I see "test" on a new term session

**NOTE** I switched from terminator to termite as terminal emulator but nothing has changed.

**Comment by dritter** [comment]
Sourcing the theme in your `.zshrc` is the right thing to do. The `.zshenv` is [read on all invocations](http://zsh.sourceforge.net/Intro/intro_3.html) of ZSH.
Using `ZDOTDIR` does not matter to us, if the path to the theme file is correct.

**Comment by flohw** [comment]
I have a new installation and made the installation process again. It finally worked. I don't know what  changed from last time. I may have a typo somewhere or a maybe a missing package ?
Closing the issue. Sorry to not be able to provide the reason why it didn't worked last time.
