### ISSUE TITLE
Duplicate clock icons

### ISSUE THREAD

**Issue by NickKaramoff** [bhilburn/powerlevel9k#1094]
#### Describe Your Issue

When I load the terminal the clock icons are being duplicated

![image](https://user-images.githubusercontent.com/6566248/48930833-11a90f80-ef04-11e8-8ce7-e6eed5eaca6c.png)

#### Have you tried to debug or fix it?

I tried to move the `source ~/.powerlevel9k/powerlevel9k.zsh-theme` line above the `POWERLEVEL9K_MODE='nerdfont-complete'` in my config, but then it doesn't set the icons for git, context and other elements.

![image](https://user-images.githubusercontent.com/6566248/48930905-79f7f100-ef04-11e8-892f-33c62466cb4e.png)

#### Environment Information

  - _What version of ZSH are you using?_ 5.3 (x86_64-apple-darwin18.0)
  - _Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?_ Yes, oh-my-zsh
  - _How did you install P9k?_ Cloning the repo to the folder in ~
  - _What version of P9k are you using?_ latest one from master branch (2f4b15041fe31d85dc9ef705b818c3a0e6985da3)
  - _Which terminal emulator do you use?_ iTerm2 3.2.3

#### Issues with Fonts & Icons

  - _Which font do you use?_ Fura Mono Medium Nerd Font Complete
  - _Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using?_ `nerdfont-complete`
  - Please share the contents of `$P9k/debug/font-issues.zsh`.
  ```
  functions/colors.zsh:source:4: no such file or directory: functions/colors.zsh
  functions/icons.zsh:source:5: no such file or directory: functions/icons.zsh
  functions/utilities.zsh:source:6: no such file or directory: functions/utilities.zsh
  ===== Font debugging =====
  You are using iTerm2 with Font FuraMonoNerdFontComplete-Medium 14

  Your font settings seem to be all right. If you still have issues,
  it is more likely to be a font issue than a Powerlevel9k related one.
  ```
  - _If this is an icon problem, does the output of `$ get_icon_names` look correct?_ Yep, it displays only once in the list

**Comment by dritter** [comment]
Hi @NickKaramoff !
This is not a font problem, but a configuration one. Looking at your `time` segment, it looks like you configured it differently. What did you set as `POWERLEVEL9K_TIME_FORMAT`? Does this include the clock icon?

**Comment by NickKaramoff** [comment]
@dritter oh shoot, you're right, I didn't even notice it! Thank you, now it's back to being normal
