### ISSUE TITLE
Dependency dejavu-fonts not mentioned yet

### ISSUE THREAD

**Issue by theova** [bhilburn/powerlevel9k#1097]
Hello!

Thanks for your great work on this project! It's just awesome and simplifies my daily work enormous!

#### Issue
If recogniced, that  [dejavu-fonts](https://dejavu-fonts.github.io/) is needed for some symbols (e.g.  '\u2714'  : ✔  or  '\u2717'  : ✗), but could not find that this dependency was mentioned.

#### Desired solution
Just a short note about the need of dejavu-fonts [here](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font).
#### Environment Information
This information will help us understand your configuration. 

 - OS: [parabola GNU/Linux-libre](https://www.parabola.nu/)
  - zsh-verison: zsh 5.6.2 (x86_64-pc-linux-gnu)
  - ZSH framework: Oh-My-ZSH
  - installation of P9k: install package [zsh-theme-powerlevel9k](https://www.parabola.nu/packages/community/x86_64/zsh-theme-powerlevel9k/) of distribution
  - version of P9k: 0.6.6-1
  - terminal emulator: termite

#### Fonts & Icons
  - fonts in use: hack, [awesome-terminal-fonts](https://www.parabola.nu/packages/community/i686/awesome-terminal-fonts/)
  -[font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts): awesome-fontconfig
  - Does the output of `$ get_icon_names` look correct? mostly

**Comment by theova** [comment]
OK. I don't know the technical specifications – I just had a completly fresh Parabola installation and faced this.

If it's rather a problem with this distribution, you may close this.

**Comment by dritter** [comment]
Alright. I close this issue. If someone stumbles upon this problem: Please open a new bug, so we have that documented and a feeling how common this problem is. Maybe we need to investigate this a bit further to know exactly how this works.
Thx @theova
