### ISSUE TITLE
Can't get icons to show in prompt, but see them when opening files.

### ISSUE THREAD

**Issue by hdaugherty** [bhilburn/powerlevel9k#1098]
I want to start off my saying that this issue seems to be the most common one for your project, but I have followed the troubleshooting guide and tried every option possible for my system, and I have read over 10 of the issues that were close to mine. The issue is that I can't seem to get icons to show up for certain items and only get the question mark in a box (The fallback icon, I assume). I am starting python development and that seems to be one of the missing icons along with many others. The deal is when I nano into the icons.zsh file "in iTerm" I can see the icons, but I can't see those same icons in a promt. 

![no_icons_capture](https://user-images.githubusercontent.com/29684757/49008797-c463b280-f13c-11e8-8dcf-55beb61130c1.png)
   - No icons showing when I activate my venv

![no_icons_capture2](https://user-images.githubusercontent.com/29684757/49008824-d80f1900-f13c-11e8-88fa-b13bd3e3ed59.png)
![no_icons_capture3](https://user-images.githubusercontent.com/29684757/49008887-02f96d00-f13d-11e8-93e3-2611638e3be7.png)
![no_icons_capture4](https://user-images.githubusercontent.com/29684757/49008894-07258a80-f13d-11e8-98cb-ffd5c1259157.png)
   -But the icons are showing when i open the icons.zsh file!

#### Have you tried to debug or fix it?
Basically, all I have tried is to do all of the install options for macOS. I have looked around at the powerlevel9k directory and my .zshrc config to see if there was anything I was missing.

#### Environment Information
  - I'm running ZSH 5.6.2_1
  - Oh-My-Zsh
  - I first install with Option 2 for Oh-My-Zsh
  - I used the current master git repo
  - iTerm2

#### Issues with Fonts & Icons
  - I'm using 12pt Meslo LG L DZ Regular for Powerline
  - I am using awesome-mapped-fontconfig as it seems to have the most icons showing in my capture, but I have also tried all of the others.
  - Contents of font-issues.zsh
         `functions/colors.zsh:source:4: no such file or directory: functions/colors.zsh
         functions/icons.zsh:source:5: no such file or directory: functions/icons.zsh
         functions/utilities.zsh:source:6: no such file or directory: functions/utilities.zsh`
  - The output of get_icon_names does not look right; it only shows a few of the icons.

-I have also change my DefaultFontsFallback.plist and tried that method.

- Here is my .zshrc
[zshrc.txt](https://github.com/bhilburn/powerlevel9k/files/2615068/zshrc.txt)

**Comment by dritter** [comment]
The `POWERLEVEL9K_MODE` is pinned at startup. The Theme starts in Oh-My-Zsh with this line: `source $ZSH/oh-my-zsh.sh`. So you need to move your P9K config up, before this line.

**Comment by hdaugherty** [comment]
- get_icon_names now shows all of the icons but I still can't get the python on to show up in the prompt when I have my virtualenv activated. I'm almost there! What could be stopping it from showing in the prompt?
![screencapture 2018-11-26 at 7 17 49 pm](https://user-images.githubusercontent.com/29684757/49050147-00842b00-f1b0-11e8-9b71-a486d3b22edb.png)

**Comment by hdaugherty** [comment]
I am an idiot, thanks for all your help but I see how it is setup by default and it is set to show the virtualenv on the LEFT_PROMPT_ELEMENTS. I got it by setting the variable in .zshrc! Thanks again for getting me in the right direction!

**Comment by leonardosetti** [comment]
Unfortunately I can't find properly icons into my icons.zsh. There is any way to solve that first? 
I'm trying use the powerlevel10k theme in a remote RHEL with zsh 5.7.1

**Comment by romkatv** [comment]
@leonardosetti Please file an issue against powerlevel10k.

**Comment by rakeshshubhu** [comment]
@romkatv I installed powerlevel 10k on windows subsytem linux. I didnt have the icons nor the pointed arrow i was missing fonts. https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k . FOLLWED this guideline

**Comment by romkatv** [comment]
@rakeshshubhu If you are having trouble with powerlevel10k, please file an issue against powerlevel10k.
