### ISSUE TITLE
Way to align right hand segments with edge of terminal

### ISSUE THREAD

**Issue by keirlawson** [bhilburn/powerlevel9k#110]
Using this theme with gnome terminal I am finding there is a one character gap between the right hand segment and the edge of the terminal.  Is there any way to get rid of this?

![zshissue](https://cloud.githubusercontent.com/assets/49213/10333642/3a72d92a-6cdd-11e5-93c6-e34a4b739e28.png)

**Comment by dritter** [comment]
@keirlawson the right hand indent is controlled by the variable `ZLE_RPROMPT_INDENT` in ZSH. I tried once to get rid of the gap by setting it to 0, but it messed up the cursor position. I haven't had time to fix this yet.

From the manpage:

> ZLE_RPROMPT_INDENT
> If  set,  used  to  give the indentation between the right hand side of the right prompt in the line editor as given by RPS1 or RPROMPT and the right hand side of the screen.  If not set, the value 1 is used.
> Typically this will be used to set the value to 0 so that the prompt appears flush with the  right  hand  side of  the screen. This is not the default as many terminals do not handle this correctly, in particular when  the prompt appears at the extreme bottom right of the screen.  Recent virtual terminals are more likely to  > handle this  case  correctly.
>
> Some experimentation is necessary.

**Comment by dritter** [comment]
For the protocol: There was an [interesting conversation](http://www.zsh.org/mla/workers/2013/msg01176.html) on the mailing list in late 2013.

**Comment by bhilburn** [comment]
@keirlawson - It's not just a problem with gnome-terminal - it actually exists in a every emulator I have used ZSH in, to date. As @dritter said, it seems to be a ZSH drawing issue.

@dritter - I don't think we can work around this safely in our theme, as it will change from emulator to emulator. Do you agree? If so, I'm afraid this bug is something we can't address.

**Comment by bhilburn** [comment]
Unfortunately, I don't think this is something we can fix in our theme.

**Comment by dritter** [comment]
@Pk13055 Unfortunately not from our side. At least not easy. There are [workarounds](https://www.zsh.org/mla/workers/2013/msg01176.html) out there, but I haven't tested these in a long time.. Also, I haven't tried setting `ZLE_RPROMPT_INDENT=0` since then. It might work for you. Did you try it out?

**Comment by softmoth** [comment]
`ZLE_RPROMPT_INDENT=-1` works in many cases. Give it a try.

**Comment by macserv** [comment]
It works... but why?  😆  Might have to do some digging on that one.

**Comment by softmoth** [comment]
@macserv, there's a workaround in #871. It's already added to powerlevel9k though,  so you shouldn't be having the extra space.

**Comment by macserv** [comment]
Ha!  I thought something like that might be possible, but I was trying it with a null (\u0000), and that didn’t work.

Anyway, I haven’t pulled in a while, so I’ll check and see if that’s had an effect.  Thanks!
