### ISSUE TITLE
Left_segment_separator seems to be using a different color partially

### ISSUE THREAD

**Issue by tgupta3** [bhilburn/powerlevel9k#1100]
-----

#### Describe Your Issue
What is happening? Left_segment_separator seems to be using a different color partially along the border.

Most issues are best explained with a screenshot. Please share one if you can!

![screenshot from 2018-11-26 20-54-37](https://user-images.githubusercontent.com/7035851/49053316-a8ecbc00-f1bd-11e8-86c6-96ec9c972eb6.png)

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using? You can use `zsh --version` to see this. zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? Oh-my-zsh
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? clone the repo 
  - What version of P9k are you using? I'm on the latest commit =2f4b150
  - Which terminal emulator do you use? Ubuntu terminal (couldn't replicate this on Iterm2/Mac Terminal)

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - Which font do you use? Hack Nerd Font regular (Doesn't show up in terminal preferences, using gnome-tweaks to modify system font and then unchecking custom font from terminal preferences)
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? You can check this with (`echo $POWERLEVEL9K_MODE`). nerdfont-complete
  - If this is an icon problem, does the output of `$ get_icon_names` look correct? Yes

**Comment by tgupta3** [comment]
Please have a look at the left edge of the separator to see a tint of a different color.

**Comment by dritter** [comment]
Hi @tgupta3 !

Thanks for the report, but this is more a font issue, than a P9K one. Fonts render differently on the various Terminal Emulators and there is as far as I can see not much that we can do from our side.. There are already similar issues reported in the NerdFonts issue tracker (https://github.com/ryanoasis/nerd-fonts/issues/272 https://github.com/ryanoasis/nerd-fonts/issues/29 and probably others).
