### ISSUE TITLE
error output for any command in a repository with untracked files

### ISSUE THREAD

**Issue by linuxmaniac** [bhilburn/powerlevel9k#1101]
error is shown if repo has untracked  files.
```+vi-git-untracked:local:8: not valid in this context: <file>```
#### Have you tried to debug or fix it?

same environment but with v0.6.6 show no error

#### Environment Information
This information will help us understand your configuration. 
  - zsh 5.0.2 (x86_64-pc-linux-gnu)
  - oh-My-ZSH
  - installed via git clone (2f4b15041fe31d85dc9ef705b818c3a0e6985da3)

**Comment by dritter** [comment]
Hi @linuxmaniac !

Unfortunately, your ZSH version is [not supported](https://github.com/bhilburn/powerlevel9k/wiki/Minimum-System-Requirements) by us any more.. Any chance you can update to a newer one?

**Comment by linuxmaniac** [comment]
Hi @dritter !

I didn't notice the ZSH requirement, sorry for the noise. Thanks!
