### ISSUE TITLE
pyenv block is not displayed

### ISSUE THREAD

**Issue by horseinthesky** [bhilburn/powerlevel9k#1104]
Hello.
`pyenv` block is not displayed with this settings
```
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv pyenv vcs)
```

but it is displayed with this option
```
POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
```
But with this option, it also displays `system` when system python is enabled.

#### Environment Information
Ubuntu 18.04 LTS
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
oh-my-zsh
p9k installed by cloning the repo
p9k version is 2.1.7 (as far as I understand). I just did `git pull`
emulators: SerureCRT, Putty, Kitty

**Comment by dritter** [comment]
Hi @horseinthesky .
Thanks for the report. Just to get you right: You have a different pyenv activated than `system` and the pyenv segment still does not show up, right? Only if you set `POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true` you see it, but you do not want to see the `system` env, right?

The segment has a shortcut: It shows the `PYENV_VERSION` if it is non-zero. Could you do an `echo x${PYENV_VERSION}x`?
And could you post the output of `pyenv version-name` here?

**Comment by dritter** [comment]
And what about `pyenv version-name`? Does it output anything?
And what is the output of `pyenv version-file-read $(pyenv root)/version`?

**Comment by horseinthesky** [comment]
> And what about `pyenv version-name`? Does it output anything?
> And what is the output of `pyenv version-file-read $(pyenv root)/version`?

`3.7.1` in both cases when I am in env. 
And `system` in both cases when I am in the system.

**Comment by horseinthesky** [comment]
That's strange. I've just noticed that now it's working like it should: displaying python version when it differs from system version and not displaying `system` anymore.
Not sure what I did wrong but it's ok now.

**Comment by horseinthesky** [comment]
Actually, env displays if there is `.python-version` is the directory. Otherwise, it is not displayed.
