### ISSUE TITLE
Change DISK_USAGE color

### ISSUE THREAD

**Issue by The33Coder** [bhilburn/powerlevel9k#1106]
How to change the color of disk indicator?

**Comment by dritter** [comment]
Hi @The33Coder , the `disk_usage` segment is a stateful segment, which means that you need to address the state you want to style. Typical is something like showing the segment in different colors for normal, warning and critical states. You can view a list of valid states and how to build the correct variable name for the `disk_usage` segment in the [wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).

**Comment by The33Coder** [comment]
Thanks, I hadn't seen the Special Segment Colors section
