### ISSUE TITLE
newline segment colors switched

### ISSUE THREAD

**Issue by Biskit1943** [bhilburn/powerlevel9k#1111]
#### Describe Your Issue

After the newline segment the background and the foreground is switched

![powerlevel9k](https://user-images.githubusercontent.com/17250956/49584882-0969bf00-f95d-11e8-8f87-1c31834f22da.png)

This happens also for the right part of the prompt on the newline.

#### What I tried

Setting `POWERLEVEL9K_USER_BACKGROUND` which either does not exist or not work.

Using `urxvt` shows the colors very dark but not switched:
![image](https://user-images.githubusercontent.com/17250956/49585317-500be900-f95e-11e8-82e5-5f83ba3e8f34.png)

#### Environment Information

`zsh 5.6.2 (x86_64-pc-linux-gnu)`
`zplug 2.4.2`
`alacritty 0.2.3`
`rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
`Linux alpha 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux`

Theme config:
```
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_HOME_SUB_ICON="$(print_icon "HOME_ICON")"
POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") "

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"

POWERLEVEL9K_TIME_BACKGROUND='255'
#POWERLEVEL9K_COMMAND_TIME_FOREGROUND='gray'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'

POWERLEVEL9K_ALWAYS_SHOW_USER=true

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable vcs newline user vi_mode virtualenv anaconda pyenv)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time)
POWERLEVEL9K_SHOW_CHANGESET=true
```

zplug usage:
```
POWERLEVEL9K_MODE="nerdfont-complete"
zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
source ~/.zplug/repos/bhilburn/powerlevel9k/powerlevel9k.zsh-theme
source ~/.config/zsh/themes/mytheme.zsh  # Load the P9K theme
```

**Comment by dritter** [comment]
Hi @Biskit1943 !

Thanks for the report. The `user` segment is a [stateful one](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors), so setting `POWERLEVEL9K_USER_BACKGROUND` has no effect. You need to add the state name to that variable.

**Comment by dritter** [comment]
Closing for now. @Biskit1943 feel free to reopen if the problem persists.

**Comment by dritter** [comment]
No worries. TBH, I don't understand what you mean with "switched".. The segments have different fore- and background colors. Do you expect every segment to have the same colors? If yes, that is something you need to configure..
To get a bit more into detail: You use the dir segment, which defaults to a blue background and a black foreground color. After that there is the newline, followed by the user segment which defaults to yellow in the foreground and black in the background..
Or do you mean the subsegment separator right after the newline? We had some trouble in the past, and as far as I remember this was fixed on the `next` branch..

**Comment by Biskit1943** [comment]
With switched I mean that the background that I have in the first line is the foreground of the newline and the same happens to the foreground of the first line and the background of the newline.
This gets more clear when I set the colors in my PyCharm terminal, when I set the background to 00000 and the foreground to fffff. The first line is then black with white font and the newline is white with black font. I will attach an image this afternoon when I'm back from work.

Anyway, how would I configure the user colors to be yellow in the back and black in font?

**Comment by Biskit1943** [comment]
Black foreground
![powerlevel9k](https://user-images.githubusercontent.com/17250956/50095400-c25db280-0215-11e9-9c89-2374d33cac04.png)

White foreground
![powerlevel9k_2](https://user-images.githubusercontent.com/17250956/50095412-c7226680-0215-11e9-8aa7-619f0cc83375.png)

PyCarm settings
![pycharm](https://user-images.githubusercontent.com/17250956/50095477-ef11ca00-0215-11e9-88ee-956ebf0b3c66.png)

As you can see here, if I change the color of the font is in the first image black and the background of the user and input segment are also black.

Ok, I got a bit confused about this. So the right question is, why does the segments have the color of the foreground from the first line?

I know, that I can change them but why are they using the foreground of the newline by default? I you say this is intended I will stop talking about this :smile:
