### ISSUE TITLE
fail install with brew

### ISSUE THREAD

**Issue by cchopin** [bhilburn/powerlevel9k#1115]
Hello,

I'have made a fresh install for zsh and powerlevelk9 and i got lot of error.
I have uninstall all and made install again wiht iterm2, but with the same result
I works with the mac having last mojave version

Thank for help

![image](https://user-images.githubusercontent.com/27963299/49684253-8fa71200-fad1-11e8-8bab-2f921ed87766.png)

**Comment by sambadevi** [comment]
The problem here seems to be your shell. P9K is a theme for zsh however you are inside a bash. You might want to open zsh first before sourcing p9k

**Comment by dritter** [comment]
@sambadevi is right. P9K does not work with bash. @cchopin try it with a proper brew install as @sambadevi suggested. Thanks @sambadevi
