### ISSUE TITLE
win10 wsl

### ISSUE THREAD

**Issue by Teeoo** [bhilburn/powerlevel9k#1130]
> Hello, I have encountered a problem using this theme under win10's WSL

![qq 20190105110032](https://user-images.githubusercontent.com/25023667/50720121-ec521880-10e1-11e9-8eaf-a33821949567.png)

There will be a white strip, I don't know why.

**Comment by floyd68** [comment]
I think It is a same problem as described in :
https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#strange-character--segment-spacing

Try to change your terminal font in WSL terminal propery to single width only fonts.
Or disable right prompt :
https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#disable-right-prompt

**Comment by Teeoo** [comment]
> I think It is a same problem as described in :
> https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#strange-character--segment-spacing
> 
> Try to change your terminal font in WSL terminal propery to single width only fonts.
> Or disable right prompt :
> https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#disable-right-prompt


Ok, I will try
