### ISSUE TITLE
Support for java versions: jenv

### ISSUE THREAD

**Issue by devshawn** [bhilburn/powerlevel9k#1140]
Hi all, just started using powerlevel9k and I'm loving it so far, super customizable.

I'm wondering if there is support for jenv? It would be great if it could be added in the future, as I use it to manage multiple java versions on my machine much like node (nvm). It looks like we have pyenv, rbenv, nvm, so it would be nice to also have [jenv](https://github.com/jenv/jenv). :) 

Currently, if I add `java_version`, I get a message saying I need a JDK installed, probably because all of my java versions are installed through jenv.

**Comment by dritter** [comment]
Hi @devshawn ,

sure, why not? You could do a PR based on our `next` branch.

Thanks

**Comment by devshawn** [comment]
Ah! The current `java_version` works with `jenv` when I added `$HOME/.jenv/bin` to my `PATH`. 

The display correctly switches when using `jenv local 1.8` -> `jenv local 10.0` for example. Yay! 😄
