### ISSUE TITLE
Question: what is 'status'?

### ISSUE THREAD

**Issue by anthonyjdella** [bhilburn/powerlevel9k#1141]
What does 'status' mean in "POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS"?

Sometimes I see a green checkmark icon, other times a number with a red background.

Is there a guide?

**Comment by Syphdias** [comment]
@anthonyjdella you can find details about configuration in the [README.md](https://github.com/bhilburn/powerlevel9k). For segment information use the [links](https://github.com/bhilburn/powerlevel9k#available-prompt-segments) in the README file.

In short, the `status` segment shows return codes (basically what `echo $?` after a command does).
You can find more details [here](https://github.com/bhilburn/powerlevel9k#status).

Example:
![image](https://user-images.githubusercontent.com/16988672/51717709-3758af00-2042-11e9-9888-73ce53896a76.png)

**Comment by dritter** [comment]
Closing this issue as @Syphdias perfectly answered the questions. @anthonyjdella feel free to reopen, if there are questions left.
