### ISSUE TITLE
fonts not installed

### ISSUE THREAD

**Issue by kw-andy** [bhilburn/powerlevel9k#1142]
#### Describe Your Issue
I should have a folder , `.fonts` where I have all my fonts. Yet there are no fonts like `devicons-regular.sh   fontawesome-regular.sh   octicons-regular.sh   pomicons-regular.sh   PowerlineSymbols.otf
devicons-regular.ttf  fontawesome-regular.ttf  octicons-regular.ttf  pomicons-regular.ttf`

See my screenshot

https://gifyu.com/image/wFpM

#### Have you tried to debug or fix it?

Powerlevel9K has been installed.

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using? You can use `zsh --version` to see this: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?: Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? : yes
  - What version of P9k are you using? : how do I know
  - Which terminal emulator do you use? linux terminal

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

**Comment by dritter** [comment]
Hi @kw-andy ,

sorry for the late reply. But this is not a problem of P9K. You should look in your `~/.zshrc` in Line 115 and have a look what is trying to load the fonts there..

**Comment by dritter** [comment]
Closing this for now. @kw-andy feel free to reopen, if it still does not work.
