### ISSUE TITLE
Allow Conditional Segments to Always Be Shown

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#115]
This is a follow-up from #113 

Some segments seem to be helpful in a "server"-like context, and some in a "project"-like one. For example, I work as a web developer and sometimes need to know about the PHP-Version on the server, but on my local machine I just need that information in development project. So if I am outside of that development project (-folder) that segment is not shown.

Maybe we need a variable SHOW_CONDITIONAL_$segment_name, so users can decide if they want to show that segment in a "project"-context or always ("server"-context). In extreme we could let the user decide how that condition looks like (e.g. find -maxdepth 2 -type f -name '*.php' | head -n 1 for a quick lookup of PHP-files).

The bullet-train guys have a similar "project-" approach in some of their segments (like the prompt_virtualenv or prompt_ruby).

I have implemented a first draft in my [improve_rvm](https://github.com/dritter/powerlevel9k/tree/dritter/improve_rvm) branch (and only for the `ruby_version` segment).

/cc @alexlafroscia

**Comment by bhilburn** [comment]
@dritter - I agree, better configuration of conditional segments would be very useful.

As you point out, in the extreme case, users could actually write the conditional statement. We may want to support this, but I don't think this should be the default - most users won't know how to take advantage of it.

I like the option to set an "ALWAYS_SHOW" option, as you modeled in your branch. Do you think there is a good way we can implement one function that can then be used for any segment we want to apply this to (like we did for color settings, for example)?

**Comment by bhilburn** [comment]
@dritter - Any more thoughts on this? It would be a great feature to get into a 0.3.0 release.

**Comment by dritter** [comment]
@bhilburn I think this takes some more time to mature. IMHO this is not ready for the next release. It is too complicated to write the conditions and I am not really content with my approach. I ported most segments to the new format, but I have some concerns about evaluating every piece of information.. Maybe this is a bit over-engineered, but I haven't come up with a better solution.
I need some time to overthink this..

**Comment by bhilburn** [comment]
@dritter - Understood. Let's prioritize this for 0.4.0, then.

**Comment by dritter** [comment]
I changed the milestone to 0.6.0, because this is already fixed there. 🎉

**Comment by bhilburn** [comment]
Closing this one out as its part of @dritter's awesome async work!
