### ISSUE TITLE
clock is not updating

### ISSUE THREAD

**Issue by panosru** [bhilburn/powerlevel9k#1163]
Hello, I noticed today that clock is not updating:

![image](https://user-images.githubusercontent.com/400362/52505220-7fa3cf80-2bf3-11e9-96bb-d48c3e9d771f.png)

```shell
ZSH_THEME="powerlevel9k/powerlevel9k"
P9K_MODE='awesome-patched'

P9K_PROMPT_ON_NEWLINE=true
P9K_RPROMPT_ON_NEWLINE=false
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=""
P9K_PROMPT_ADD_NEWLINE=true
P9K_TIME_FORMAT="%D{\ue184  %d/%m/%y}"
P9K_TIME_ICON=''
P9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS='  '
P9K_VCS_SHOW_CHANGESET=true
P9K_VCS_CHANGESET_HASH_LENGTH=6
P9K_BATTERY_VERBOSE=true
P9K_BATTERY_LOW_THRESHOLD=30
P9K_BATTERY_LOW_ICON_COLOR="red"
P9K_BATTERY_CHARGING_ICON_COLOR="springgreen1"
P9K_BATTERY_CHARGED_ICON_COLOR="white"
P9K_BATTERY_DISCONNECTED_ICON_COLOR="cyan"
P9K_BATTERY_LOW_ICON="\UF240"
P9K_BATTERY_CHARGING_ICON="\UF240"
P9K_BATTERY_CHARGED_ICON="\UF1E6"
P9K_BATTERY_DISCONNECTED_ICON="\UF240"
P9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%K{cyan}%F{black}   `date +%H:%M` %f%k%F{cyan}%f "
P9K_STATUS_CROSS=true
P9K_PHP_VERSION_ICON=$'\uE63D'

P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version time battery)
```

From what I saw on other's scripts in *show off your config* [page](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config), it normally should work, and it used to work, I'm afraid it stopped working after latest zsh upgrade, but I'm not really sure because I noticed it just now...

Thanks in advance!

**Comment by Syphdias** [comment]
Are you sure this ever worked or did you just notice this now?
You fill `P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON` with the evaluated expression which means it is filled with the date when you sourced your `.zshrc`. P9K never sees any `date` command and probably never could unless you used single quotes before. Maybe is was single qutes before you switched to `next`?

For a solution for your problem, you could try the following:
```zsh
P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs newline time)
P9K_PROMPT_ON_NEWLINE=false
```


Also, note that the config site is from P9K-users and anybody can write to it afaik. Config might be for older versions of P9K. I don't know if there is any checking done if it actually works.

PS: I'm a bit confused why you use the time segment in the `P9K_RIGHT_PROMPT_ELEMENTS` as well, but you can display as many watches as you want ;)

**Comment by panosru** [comment]
@Syphdias Indeed you are right... I totally missed that...

My current settings are:
```
ZSH_THEME="powerlevel9k/powerlevel9k"
P9K_MODE='awesome-patched'

P9K_PROMPT_ON_NEWLINE=false
P9K_RPROMPT_ON_NEWLINE=false
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=""
P9K_PROMPT_ADD_NEWLINE=true
P9K_TIME_FORMAT="%D{%H:%M}"
P9K_TIME_BACKGROUND='cyan'
P9K_DATE_FORMAT="%D{\ue184  %d/%m/%y}"
P9K_DATE_ICON=''
P9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS='  '
P9K_VCS_SHOW_CHANGESET=true
P9K_VCS_CHANGESET_HASH_LENGTH=6
P9K_BATTERY_VERBOSE=true
P9K_BATTERY_LOW_THRESHOLD=30
P9K_BATTERY_LOW_ICON_COLOR="red"
P9K_BATTERY_CHARGING_ICON_COLOR="springgreen1"
P9K_BATTERY_CHARGED_ICON_COLOR="white"
P9K_BATTERY_DISCONNECTED_ICON_COLOR="cyan"
P9K_BATTERY_LOW_ICON="\UF240"
P9K_BATTERY_CHARGING_ICON="\UF240"
P9K_BATTERY_CHARGED_ICON="\UF1E6"
P9K_BATTERY_DISCONNECTED_ICON="\UF240"
P9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
P9K_STATUS_CROSS=true
P9K_PHP_VERSION_ICON=$'\uE63D'

P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs newline time)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version date battery)
```

And it looks like that:
![image](https://user-images.githubusercontent.com/400362/52518608-8ebb6980-2c55-11e9-9e11-8c6430f6d01c.png)

The reason I did it with multiline previously is that I don't like that my right prompt is not aligned with my left prompt. I wanted my left and right prompt to be aligned in order to give the feel of the header and below them is where I type my commands :)

**Comment by panosru** [comment]
would be cool if we could use segments in multiline :)

**Comment by Syphdias** [comment]
@panosru I just briefly looked at the code how `P9K_RPROMPT_ON_NEWLINE` works...and it's a bit hacky...

> I wanted my left and right prompt to be aligned in order to give the feel of the header and below them is where I type my commands :)

I think @dritter is working on making newline also available on `RPROMPT` and some other stuff in #856. Looking at his code, I think he is aware of this since he [dynamically](https://github.com/bhilburn/powerlevel9k/pull/856/files#diff-ea5a405f0331722fc10a832209ffe20bR1781) adds `RPROMPT_PREFIX` and `RPROMPT_SUFFIX`.

If you want to hard code it for now, you could apply this patch. I've done very little testing though...
```
diff --git a/generator/default.p9k b/generator/default.p9k
index e115954..b46344f 100644
--- a/generator/default.p9k
+++ b/generator/default.p9k
@@ -395,8 +395,8 @@ ${__P9K_ICONS[MULTILINE_LAST_PROMPT_PREFIX]}"
       # the RPROMPT, we advise it, to go one line up. At the end of RPROMPT, we
       # advise it to go one line down. See:
       # http://superuser.com/questions/357107/zsh-right-justify-in-ps1
-      RPROMPT_PREFIX='%{'$'\e[1A''%}' # one line up
-      RPROMPT_SUFFIX='%{'$'\e[1B''%}' # one line down
+      RPROMPT_PREFIX='%{'$'\e[1A''%}%{'$'\e[1A''%}' # two line up
+      RPROMPT_SUFFIX='%{'$'\e[1B''%}%{'$'\e[1B''%}' # two line down
     else
       RPROMPT_PREFIX=''
       RPROMPT_SUFFIX=''
```

**Comment by panosru** [comment]
@Syphdias first of all, thank you for the effort!

Your patch indeed allows `newline` segment to work on RPROMPT, but that does not solve the aesthetic *issue* I was talking about.

![image](https://user-images.githubusercontent.com/400362/52526461-a6303c00-2cc1-11e9-8923-9e9e11cbd62c.png)

While by putting `newline` on RPROMT brings it on the same level with left, the cursor is under the `time` instead of next to it like it is in my previous screenshots.

I can live with having the RPROMPT at the same level with my `time` and cursor if it is not possible to have a segment in multiline, but it will be really great fi multiline could also support segments in order to have this:
```
P9K_PROMPT_ON_NEWLINE=true
P9K_RPROMPT_ON_NEWLINE=false
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=(time)

P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version date newline battery)
```

instead of this:
```
P9K_PROMPT_ON_NEWLINE=false
P9K_RPROMPT_ON_NEWLINE=false
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=""

P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs newline time)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version date newline battery)
```

**Comment by Syphdias** [comment]
Did you take a look at the PR I referenced? There would be no need to treat `P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON` like `P9K_LEFT_PROMPT_ELEMENTS`.

For your individual problem:
I guess you could pull the prefix and suffix down to be also added if `P9K_PROMPT_ON_NEWLINE` is `false`. Play around a little for yourself ;)

**Comment by panosru** [comment]
@Syphdias based on  your example, I made the following change instead:

```diff
diff --git a/generator/default.p9k b/generator/default.p9k
index e115954..d94e723 100644
--- a/generator/default.p9k
+++ b/generator/default.p9k
@@ -407,6 +407,11 @@ ${__P9K_ICONS[MULTILINE_LAST_PROMPT_PREFIX]}"
     RPROMPT_SUFFIX=''
   fi

+  if [[ $P9K_LEFT_PROMPT_ELEMENTS == *"newline"* ]]; then
+    RPROMPT_PREFIX='%{'$'\e[1A''%}' # one line up
+    RPROMPT_SUFFIX='%{'$'\e[1B''%}' # one line down
+  fi
+
   if [[ "${P9K_DISABLE_RPROMPT:-}" != true ]]; then
     __p9k_unsafe_RPROMPT="${RPROMPT_PREFIX}%f%b%k$(__p9k_build_right_prompt)%{${reset_color}%}${RPROMPT_SUFFIX}"
     RPROMPT='$__p9k_unsafe_RPROMPT'
```

my config:
```
P9K_PROMPT_ON_NEWLINE=false
P9K_RPROMPT_ON_NEWLINE=false
P9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=""

P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs newline time)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version date battery)
```

So basically I check if `newline` is present on left prompt, and adjust the right prompt acordingly, that worked perfectly :)

Thank you very much for the idea, now my prompt looks great again!

**Comment by panosru** [comment]
I did a small change, in case someone has more than one `newline` segment in their left prompt, I count the `newline` segments and adjust the lines accordingly.

```diff
diff --git a/generator/default.p9k b/generator/default.p9k
index e115954..6b85d99 100644
--- a/generator/default.p9k
+++ b/generator/default.p9k
@@ -407,6 +407,21 @@ ${__P9K_ICONS[MULTILINE_LAST_PROMPT_PREFIX]}"
     RPROMPT_SUFFIX=''
   fi

+  # Check if `newline` segment is present in Left Prompt
+  if [[ $P9K_LEFT_PROMPT_ELEMENTS == *"newline"* ]]; then
+    # Get how many times it present
+    TIMES=$(echo $P9K_LEFT_PROMPT_ELEMENTS | tr " " "\n" | grep -c "newline")
+    # Reset RPROMT Prefix and Suffix in case they where modified previously
+    RPROMPT_PREFIX=''
+    RPROMPT_SUFFIX=''
+    # Loop based on `newline` instances
+    for INDEX in $(seq 1 $TIMES)
+    do
+      RPROMPT_PREFIX="$RPROMPT_PREFIX"'%{'$'\e[1A''%}' # add line up
+      RPROMPT_SUFFIX="$RPROMPT_SUFFIX"'%{'$'\e[1B''%}' # add line down
+    done
+  fi
+
   if [[ "${P9K_DISABLE_RPROMPT:-}" != true ]]; then
     __p9k_unsafe_RPROMPT="${RPROMPT_PREFIX}%f%b%k$(__p9k_build_right_prompt)%{${reset_color}%}${RPROMPT_SUFFIX}"
     RPROMPT='$__p9k_unsafe_RPROMPT'
```
This is how my terminal looks now:
![image](https://user-images.githubusercontent.com/400362/52527462-75f09980-2cd1-11e9-8340-e273fb626a7e.png)

In case someone have more than one `newline` segments:
```
P9K_LEFT_PROMPT_ELEMENTS=(os_icon root_indicator dir dir_writable vcs newline newline newline time)
P9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs node_version php_version date battery)
```
![image](https://user-images.githubusercontent.com/400362/52527497-f616ff00-2cd1-11e9-8031-dca74ccfb3ce.png)
