### ISSUE TITLE
VCS segment - removing the repo icon

### ISSUE THREAD

**Issue by ArtFlag** [bhilburn/powerlevel9k#1168]
#### VCS segment - Removing the repo icon

By default, the theme shows the type of repo. In the case of a Git repo, we have this:
<img width="397" alt="screenshot 2019-02-22 at 15 39 04" src="https://user-images.githubusercontent.com/25686502/53249344-28ecca00-36b8-11e9-8468-60dd669e8a12.png">

I haven't been able to find documentation on how to remove this icon, I would like to keep the branch icon though. 

The only alternative I found was to use `POWERLEVEL9K_HIDE_BRANCH_ICON=true` and set the repo type icon variable to the branch icon value.

Is there a cleaner way to do this?

**Comment by dritter** [comment]
Hi @ArtFlag ,

You can just set the variable to a blank value. That would remove the icon. You can get a list of all icons with `get_icon_names`. That should do it.

**Comment by ArtFlag** [comment]
Great, thanks a lot 🙂
