### ISSUE TITLE
vcs_info leaks percent escapes

### ISSUE THREAD

**Issue by romkatv** [bhilburn/powerlevel9k#1202]
Tested on `master` with the default config.

1. `cd` into a git repo and checkout a revision or branch that doesn't have tags on it.
2. `git tag '%E%K{red}'`

Expected: vcs segment shows tag `%E%K{red}`. 
Actual: color mayhem.

**Comment by dritter** [comment]
I reproduced the bug on `next` and fixed them there. We are [close](https://github.com/bhilburn/powerlevel9k/projects/3) to a new release, so I am closing this for now.
