### ISSUE TITLE
Many bugs in dir segment

### ISSUE THREAD

**Issue by romkatv** [bhilburn/powerlevel9k#1206]
I went to optimize `prompt_dir` in Powerlevel10k and noticed that the code is crawling with bugs. Just from the cursory look, here are some.

Tested on `master` with default settings plus whatever is specified in each test case.

1.

```zsh
mkdir ~/'%E%K{red}'
cd ~/'%E%K{red}'
```

Expected content of dir segment: `~/%E%K{red}`.
Actual: color mayhem.

2.

```zsh
mkdir ~/~
cd ~/~
```

Expected content of dir segment: `~/~`.
Actual: `~`.

3.

```zsh
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
mkdir ~/~
cd ~/~
```

Expected content of dir segment: `/~`.
Actual: `~`.

Note that with these settings we'll get `/foo` when we are in `~/foo`. I'm assuming here this is the expected behavior of `POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER` although I cannot imagine why anyone would want this. What's clear is that it should be consistent between `~/foo` and `~/~` but currently it isn't.

4.

```zsh
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=HOME
sudo mkdir /~
cd /~
```

Expected content of dir segment: `/~`.
Actual: `/HOME`.

**Comment by dritter** [comment]
I reproduced the issues on `next` and fixed them there. We are [close](https://github.com/bhilburn/powerlevel9k/projects/3) to a new release, so I am closing this for now. Thanks @romkatv .
