### ISSUE TITLE
removing vcs-detect-changes from POWERLEVEL9K_VCS_GIT_HOOKS unexpectedly removes remote repo icon

### ISSUE THREAD

**Issue by romkatv** [bhilburn/powerlevel9k#1207]
Tested on master with the default config.

1. Clone a repo from github.
2. `cd` into it.
3. Observe the presence of github icon in the vcs prompt.
4. Remove `vcs-detect-changes` from `POWERLEVEL9K_VCS_GIT_HOOKS`. That is, set `POWERLEVEL9K_VCS_GIT_HOOKS=(git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)`. Restart zsh.
5. Repeat steps 1-2.
6. Observe the absence of github icon in the vcs prompt.

Expected: There is a github icon in the vcs prompt in 6.
Actual: There isn't.

That being said, it's undocumented how the presence or absence of hooks affects vcs segment. It would be nice to have it documented. But either way the current behavior is very surprising.

**Comment by dritter** [comment]
This is fixed on `next` with merging #1235 . Closing for now.
