### ISSUE TITLE
virtualenv unset variable virtualenv_path

### ISSUE THREAD

**Issue by buzzsurfr** [bhilburn/powerlevel9k#1211]
#### Describe Your Issue
*NOTE: This is for the `next` branch. This is working in the `master` branch.*

The `virtualenv` segment does not properly display when activating a virtualenv.

#### Have you tried to debug or fix it?

I traced the error to this line:
https://github.com/bhilburn/powerlevel9k/blob/61b665f0e4404e9525c73bff3aae516ae2d9f624/segments/virtualenv/virtualenv.p9k#L32

`$virtualenv_path` does not exist, but this can be changed to `${VIRTUAL_ENV:t}` (same as the prepare_segment on line 34:
https://github.com/bhilburn/powerlevel9k/blob/61b665f0e4404e9525c73bff3aae516ae2d9f624/segments/virtualenv/virtualenv.p9k#L34

I'm submitting a PR, but can close if unneeded for some reason.

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? zsh 5.7.1 (x86_64-apple-darwin17.7.0)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? cloning the repo, checkout branch `next`
  - What version of P9k are you using? branch `next`
  - Which terminal emulator do you use? iTerm2 Build 3.2.7

**Comment by dritter** [comment]
Just realized that this issue was still open, but the PR was already merged. -> closing.

Thanks @buzzsurfr again ;)
