### ISSUE TITLE
f3d2a07 introduces a syntax error?

### ISSUE THREAD

**Issue by martinpelikan** [bhilburn/powerlevel9k#122]
It has been a while since my last update of this theme.  It looks like f3d2a0755ef421b22b8d5f9a8db6d66e2f774ef9 introduces a regression:
```
powerlevel9k.zsh-theme:65: parse error near `|'
```

This causes the powerline-style markup of the segments to not colorize or show special characters. This issue is present in the current version as well:
```
powerlevel9k.zsh-theme:232: parse error near `|'
```

I'll follow up if I find the issue or a fix.

**Comment by martinpelikan** [comment]
My guess is that the 'extension' refers to the SI prefixes and they are supposed to be strings, but are being interpreted as functions or some such thing. This patch should fix it:

```diff
diff --git a/powerlevel9k.zsh-theme b/powerlevel9k.zsh-theme
index c2ee262..f532cd9 100755
--- a/powerlevel9k.zsh-theme
+++ b/powerlevel9k.zsh-theme
@@ -229,7 +229,7 @@ function print_icon() {
 printSizeHumanReadable() {
   local size=$1
   local extension
-  extension=(B K M G T P E Z Y)
+  extension=('B' 'K' 'M' 'G' 'T' 'P' 'E' 'Z' 'Y')
   local index=1
 
   # if the base is not Bytes
```

**Comment by mfarrugi** [comment]
If you are using omzsh common aliases, G is aliased to `| grep` and being expanded. 

Moving the units to strings fixed this for me, thanks!
