### ISSUE TITLE
[DOCS] VCS colour-customisation example is incorrect

### ISSUE THREAD

**Issue by protist** [bhilburn/powerlevel9k#1225]
#### Describe Your Issue
The [documentation](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization) for "Segment Color Customization" gives the example:

    POWERLEVEL9K_VCS_FOREGROUND='021' # Dark blue

However, this didn't work. This old [changelog](https://github.com/bhilburn/powerlevel9k/blob/c4a8118b4574b5746da3cf99ea2b8f11500470ad/CHANGELOG.md#vcs-changes-2) suggests that it is no longer used. I also had a similar experience with `POWERLEVEL9K_VCS_BACKGROUND`.

#### Have you tried to debug or fix it?

Yes, using the "advanced" `POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_{FORE,BACK}GROUND` worked instead. FWIW I found the wording in the documentation confusing:

    # Advanced `vcs` color customization

It implies there is a "basic" version as well, which appears to be deprecated as above.

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? zsh 5.7.1 (x86_64-pc-linux-gnu)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? zim
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? Arch package
  - What version of P9k are you using? 0.6.6
  - Which terminal emulator do you use? terminator

**Comment by dritter** [comment]
Great catch @protist !

I modified the wiki a bit, and
- removed "advanced", to make clear there is no "basic/advanced" configuration.
- exchanged the color code example for a simpler segment (`time` segment it is now).

The color code mistake must there been for ages..
Thanks.
