### ISSUE TITLE
Status segment do not respect user defined colors

### ISSUE THREAD

**Issue by numered** [bhilburn/powerlevel9k#1244]
#### Describe Your Issue
Error status segment do not respect defined background and foreground colors.
![issuestatus](https://user-images.githubusercontent.com/49354456/55677394-b2fa9600-58e6-11e9-9e52-a8a778ef8fac.png)
As seen on the image, the colors are displayed incorectly in the status segment in case of an error, even though in the OK case, everything works perfectly.

#### Have you tried to debug or fix it?

I tried to use the old variables names but that didn't change anything.

#### Environment Information
OS: Ubuntu 18.10
ZSH version: 5.5.1
ZSH framework: Oh-My-ZSH
P9K installation: Cloning the repo
P9K version: Latest `next` commit at this time (110efcb)
Terminal emulator: Tested on Terminator and Ubuntu default terminal

**Comment by Syphdias** [comment]
@numered Can you please provide the config you are setting the colours with?

https://github.com/bhilburn/powerlevel9k/blob/110efcbee73fcaa24fdbc59fb99ee5f53d156768/segments/status/README.md#color-customization

**Comment by numered** [comment]
Just checked, some variable names were changed. Thanks.
