### ISSUE TITLE
Battery segment do not respect user defined icons

### ISSUE THREAD

**Issue by numered** [bhilburn/powerlevel9k#1245]
#### Describe Your Issue
Battery segment do not respect user defined icons.
![issuebattery](https://user-images.githubusercontent.com/49354456/55677434-9d39a080-58e7-11e9-8e23-1cbae775034e.png)
As seen on the image, the battery segment use a symbol different from the configured one.

#### Have you tried to debug or fix it?

I tried to use the old variables names but that didn't change anything.

#### Environment Information

OS: Ubuntu 18.10
ZSH version: 5.5.1
ZSH framework: Oh-My-ZSH
P9K installation: Cloning the repo
P9K version: Latest next commit at this time (110efcb)
Terminal emulator: Tested on Terminator and Ubuntu default terminal

**Comment by Syphdias** [comment]
Hi @numered,

thanks for the bug report. I think I found the source. I'll open a PR tomorrow. Could you try to delete some lines in `$__P9K_DIRECTORY/segments/battery/battery.p9k`? I haven't tested this much, but this is what essentially will happen in the PR.

```diff
diff --git a/segments/battery/battery.p9k b/segments/battery/battery.p9k
index f6a4d868..c3c81fe5 100644
--- a/segments/battery/battery.p9k
+++ b/segments/battery/battery.p9k
@@ -206,7 +206,6 @@ prompt_battery() {
   # override default icon if we are using battery stages
   local overideIcon="" overideBg="" segment
   declare -i offset
-  if [[ -n "$P9K_BATTERY_STAGES" ]] && [[ -n "$P9K_BATTERY_LEVEL_BACKGROUND" ]]; then
     # override default icon if we are using battery stages
     if [[ -n "$P9K_BATTERY_STAGES" ]]; then
       segment=$(( 100.0 / (${#P9K_BATTERY_STAGES} - 1 ) ))
@@ -223,7 +222,6 @@ prompt_battery() {
       offset=$(( (${bat_percent} / $segment) + 1 ))
       overideBg="$(p9k::background_color ${P9K_BATTERY_LEVEL_BACKGROUND[$offset]})"
     fi
-  fi
   unset offset
   # Draw the prompt_segment
   p9k::prepare_segment "$0" "${(U)current_state}" $1 "$2" $3 "${message}" "" "${overideIcon}" "${overideBg}"
```

**Comment by Syphdias** [comment]
@numered Could you check out #1247 to see if it is fixed?

**Comment by dritter** [comment]
#1247 is now merged into `next`. I close this issue for now. @numered please reopen, if this does not fix your issue.
