### ISSUE TITLE
No "Ribbon shape", different color from default, etc.

### ISSUE THREAD

**Issue by pr0ph0z** [bhilburn/powerlevel9k#1253]
Hi there, i'm just installed zsh, and omz. But when I applied the theme to powerlevel9k, it shows not like the example.
Here's the terminal.
![image](https://user-images.githubusercontent.com/17337978/56396052-5a70b480-6267-11e9-9ba1-4c13bb0f7219.png)
OS: Ubuntu 18.04
ZSH Version: 5.4.2
ZSH Framework: Oh-My-ZSH
P9K Installation: Cloning the repo
P9K Version: Latest commit 3dafd79c41f8601b055e607ffefbfe3250c26040

**Comment by sambadevi** [comment]
Hey @pr0ph0z! The missing icons on your prompt are from “incompatible” fonts installed on your system. Or rather fonts which don’t include the Unicode symbols needs to render the segment dividers.
I see that you are using gnome-terminal as your terminal emulator, you might want to install one of the fonts provided by nerdfonts.com or github.com/ryanoasis/nerd-fonts and activate them inside your terminal.

**Comment by pr0ph0z** [comment]
@sambadevi Thank you. It's worked now!
