### ISSUE TITLE
vsc segment error - command not found: prompt_vsc

### ISSUE THREAD

**Issue by AleksanderPopov** [bhilburn/powerlevel9k#1255]
#### Describe Your Issue
What is happening?

Hi guys. I've started having strange issues with `vsc` segment, just about today, after updating zsh and oh-my-zsh and powerlevel9k to master, issue is still there.

![Screen Shot 2019-04-21 at 11 41 26 PM](https://user-images.githubusercontent.com/21224705/56475314-09430980-648f-11e9-80dd-de6e42bfdfc0.png)

#### Have you tried to debug or fix it?

Tried to use debug mode, but is show same error, which means nothing for me.

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? 
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?
 Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)?
clonning the repo into .oh-my-zsh/custom/themes
  - What version of P9k are you using? 
master #3dafd79c41f8601b055e607ffefbfe3250c26040
  - Which terminal emulator do you use? 
iterm2

Also here is my chunk of .zshrc about powerlevel9k properties:
```
POWERLEVEL9K_DIR_PATH_ABSOLUTE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir_writable dir newline vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time date vsc)
POWERLEVEL9K_MODE='nerdfont-complete'
```

**Comment by Syphdias** [comment]
It's `vcs` not `vsc`. Changing to this should fix your problem:
`POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time date vcs)`

**Comment by AleksanderPopov** [comment]
As always. Thank you @Syphdias , closing.
