### ISSUE TITLE
How can I only show the branch of VCS?

### ISSUE THREAD

**Issue by Leviathan1995** [bhilburn/powerlevel9k#1257]
I use powerlevel9k, but I only want to show the branch of VCS, no other messages. How can I only show the branch of VCS? In fact, I think `vcs.zsh` is very slow to scan all of the things.

**Comment by Leviathan1995** [comment]
okay, I solve it, just add this line:
```
POWERLEVEL9K_VCS_GIT_HOOKS=(git-remotebranch)
```

**Comment by romkatv** [comment]
@Leviathan1995 If you keep `POWERLEVEL9K_VCS_GIT_HOOKS` unchanged and enable [Powerlevel10k](https://github.com/romkatv/powerlevel10k/), is it also slow?

**Comment by Leviathan1995** [comment]
@rawkode sorry, I don't do any trying, but what is the difference between `10` with `9`?

**Comment by romkatv** [comment]
@Leviathan1995 Powerlevel10k is supposed to be faster than Powerlevel9k and identical in all other respects.
