### ISSUE TITLE
Can not display Awesome Powerline 

### ISSUE THREAD

**Issue by hhoangna** [bhilburn/powerlevel9k#1273]
I using Terminal on Mac Mojave 13.4.4 
And i installed oh my zsh, p9k, SourceCodePro+Powerline+Awesome font but my terminal display Powerline not Awesome Powerline..
What step i missed?

**Comment by Syphdias** [comment]
Hi @hhoangna, good to hear that you found a solution on your own. Could you post your solution in case someone has the same problem and stumbles upon this thread?
