### ISSUE TITLE
rbenv doesn't respect POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false

### ISSUE THREAD

**Issue by romkatv** [bhilburn/powerlevel9k#1282]
This is on `master`.

To reproduce:

1. Install rbenv.
2. Use `master` branch of Powerlevel9k with `rbenv` as one of the prompt segments.
3. Set `POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false` (this is also the default).
4. Type these commands:

```zsh
rbenv install 2.6.3
rbenv global 2.6.3
rbenv shell 2.6.3
```

Expected behavior: rbenv segment not shown because the current rbenv version is equal to the global rbenv version (both are `2.6.3`).

Actual behavior: rbenv segment shows `2.6.3`.

**Comment by bhilburn** [comment]
Fixed by merge of #1284
