### ISSUE TITLE
Add option to hide TIME_ICON and DATE_ICON in time/date segments

### ISSUE THREAD

**Issue by fishpen0** [bhilburn/powerlevel9k#1294]
I recently updated to a newer version of powerlevel9k and now this little clock icon takes up a ton of space on my shell and I can't remove it by editing the `POWERLEVEL9K_TIME_FORMAT` string since its appended after that is defined.  

https://github.com/bhilburn/powerlevel9k/blob/6d116ab24b974cc8271eaf33c755a916a6f462e4/powerlevel9k.zsh-theme#L1302-L1309

I'd like to hide it with a flag, something like `POWERLEVEL9K_TIME_DISABLE_ICON=1` in my zshrc.  Possibly add the same option for the date segment.

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_TIME_ICON=""
```

**Comment by fishpen0** [comment]
That worked, thanks!  I'll close this.

**Comment by romkatv** [comment]
@fishpen0 I noticed in your dotfiles that you are using a custom prompt segment for kubernetes status instead of the standard `kubecontext` from p9k. Why is that, if you don't mind my asking?
