### ISSUE TITLE
Nerdfont icons not showing

### ISSUE THREAD

**Issue by fabeider** [bhilburn/powerlevel9k#1295]
#### Describe Your Issue
A lot of the icons are not showing

![image](https://user-images.githubusercontent.com/3586692/58667648-fe408c00-830c-11e9-81b1-584919ded578.png)

#### Have you tried to debug or fix it?

Setting the glyphs one by one, using nerd-fonts cheatsheet solved, by my understanding was that it should come by default on Nerd-Fonts

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? Zsh 5.7.1 (x86_64-apple-darwin17.7.0)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? Prezto
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? Prezto theme
  - What version of P9k are you using?
  - Which terminal emulator do you use? iTerm2

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - Which font do you use? I tried with a lot of Nerd-Fonts (Currently FuraCode Nerd Font
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? nerdfont-complete
  - Please share the contents of `$P9k/debug/font-issues.zsh`.
 ===== Font debugging =====
You are using iTerm2 with Font FiraMonoForPowerline-Regular 12

Your font settings seem to be all right. If you still have issues,
it is more likely to be a font issue than a Powerlevel9k related one.

  - If this is an icon problem, does the output of `$ get_icon_names` look correct?
No, lot of icons missing. Screenshot attached

**Comment by romkatv** [comment]
Which icon on the screenshot do you consider to be not showing?

**Comment by fabeider** [comment]
All OS icons for instance. My understanding was that it shows a text as fallback for not finding the icon.
Home and folder icons are missing as well
There are others, not on screen, but I'm not worried about then, since I'm not planning on putting them on my config

**Comment by romkatv** [comment]
Just making a guess. You are expecting `POWERLEVEL9K_ANDROID_ICON` in the output of `get_icon_names` to show as Android logo but you are seeing `And` instead. Is this correct?

If so, try running `POWERLEVEL9K_MODE=nerdfont-complete zsh` and then typing `get_icon_names`. If this displays the icons you want, you need to add `POWERLEVEL9K_MODE=nerdfont-complete` _at the top_ of your `~/.zshrc`. Or you could switch to [Powerlevel10k](https://github.com/romkatv/powerlevel10k/#for-powerlevel9k-users), which allows you to define your options anywhere in the configuration file. It's also much faster.

**Comment by fabeider** [comment]
Running POWERLEVEL9K_MODE=nerdfont-complete zsh messed up all icons
![image](https://user-images.githubusercontent.com/3586692/58668313-f255c980-830e-11e9-81bc-e659e7cf3361.png)

**Comment by fabeider** [comment]
My zshrc
![image](https://user-images.githubusercontent.com/3586692/58668486-760fb600-830f-11e9-830d-9ffda9deb07b.png)

**Comment by romkatv** [comment]
> Running POWERLEVEL9K_MODE=nerdfont-complete zsh messed up all icons

This means your font doesn't support these icons. If you want these icons in your prompt, you need to install a patched font from [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts).

P.S.

Powerlevel10k is bundled with zprezto just like Powerlevel9k. You can switch by changing "powerlevel9k" in `~/.zpreztorc` with "powerlevel10k". These themes are compatible, so you won't need to change any configuration. 10k is just faster. You can always switch back.

**Comment by fabeider** [comment]
Hm, somehow I got it to work.
Apparently, it was the POWERLEVEL9K_MODE=nerdfont-complete placement.
Changing to PowerLevel10k made it work
Many thanks
