### ISSUE TITLE
Default  segment color

### ISSUE THREAD

**Issue by saravntbe** [bhilburn/powerlevel9k#1297]
how to change the default segment color (foreground and background) eg, vcs etc.,

**Comment by romkatv** [comment]
There is no default foreground and background color for `vcs`. You can specify `vcs` colors like this:

```zsh
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=red
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=blue
```

See https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization.

You can also enable light color theme: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#light-color-theme.

**Comment by dritter** [comment]
Closing this for now. @saravntbe feel free to reopen if there are questions left.
Thx @romkatv for the quick reply.
