### ISSUE TITLE
Unable to display custom glyph using custom prompts

### ISSUE THREAD

**Issue by marcuskwan** [bhilburn/powerlevel9k#1299]
#### Describe Your Issue
What is happening?
-> I am unable to display custom glyphs using custom prompts on my terminal. I am a beginner, so I apologize in advance ! 

Most issues are best explained with a screenshot. Please share one if you can!

Top half of zsh file
![image](https://user-images.githubusercontent.com/28922424/58930608-71c81a80-879f-11e9-9d0e-8acce311eccd.png)

Bot half of zsh file 
![image](https://user-images.githubusercontent.com/28922424/58930664-ae941180-879f-11e9-8c0f-50f40ba1cfcc.png)

What iTerm2 looks like 
![image](https://user-images.githubusercontent.com/28922424/58930692-d6837500-879f-11e9-9734-08e3348a03c8.png)

What my font book looks like 
![image](https://user-images.githubusercontent.com/28922424/58931556-74c50a00-87a3-11e9-92b1-18b0c1997eeb.png)

Preferences text pane in iTerm2 based on an article 
![image](https://user-images.githubusercontent.com/28922424/58931446-113adc80-87a3-11e9-9806-165a3af2d5c6.png)

#### Have you tried to debug or fix it?

Have you tinkered with your settings, and what happened when you did? Did you find a bit of code that you think might be the culprit? Let us know what you've done so far!

-> I feel like it has something to do with the way I am writing the code. I also have a suspicion about the fact that the MODE=nerdfont-complete line is different from the font folder I have installed called "Hack Font Nerd". I've googled and looked at the troubleshooting thread, filtered through issues with the keywords of glyph, icon, and custom. 
I have tried: 
- Doing get_icon_info -> I am able to see the icons so I think the fonts are properly installed
- Running POWERLEVEL9K_MODE=nerdfont-complete zsh
- Doing echo on the icon -> I am able to see the icon
- Placing POWERLEVEL_9K MODE at the top of the zsh config file 
- Trying different ways of displaying the custom prompts (Tried displaying just the string "JavaScript" or simply the icon, or leaving out the -n keyword the example custom prompt uses, nothing has worked 
- Placing the custom font code separately after the left and right display configurations. This had no effect

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? You can use `zsh --version` to see this.
-> zsh --version zsh 5.3 (x86_64-apple-darwin18.0)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?
-> I used Oh-My-ZSH, the theme I downloaded was PowerLevel 9K originally, but I've switched to PowerLevel 10k 
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)?
-> I used macOS with homebrew.
  - What version of P9k are you using?
-> Not sure how to check this I'm sorry, but I downloaded it a month ago so I think I am up to date.
  - Which terminal emulator do you use?
-> I am using iTerm2 for customizable themes.

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - Which font do you use?
-> I am using the Hack Nerd Font.
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? You can check this with (`echo $POWERLEVEL9K_MODE`).
-> nerdfont-complete
  - Please share the contents of `$P9k/debug/font-issues.zsh`.
-> I am getting an error of " zsh: no such file or directory: P9k/debug/font-issues.zsh " but I changed P9K to powerlevel9k and I got this: 
![image](https://user-images.githubusercontent.com/28922424/58931249-5ca0bb00-87a2-11e9-8f98-aec3e15609a7.png)
  - If this is an icon problem, does the output of `$ get_icon_names` look correct?
-> Yes, all of them are displaying correctly. 
![image](https://user-images.githubusercontent.com/28922424/58931147-de441900-87a1-11e9-9d0c-744512e9b7a4.png)

**Comment by romkatv** [comment]
You need to add `custom_javascript` to prompt list.

```zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_javascript)
```

In addition, it's better to specify an icon for your custom prompt via a dedicated parameter, similarly to how you've defined its colors.

```zsh
POWERLEVEL9K_CUSTOM_JAVASCRIPT_ICON=$'\ue781'
```

**Comment by marcuskwan** [comment]
@romkatv  Thank you so much!!! 😄 
![image](https://user-images.githubusercontent.com/28922424/58974715-69ef9100-8806-11e9-9d5b-ee81b7f1f306.png)
Also, thank you for your work on PL10K!

**Comment by romkatv** [comment]
My pleasure.

By the way, remove this line from the top of your config:

```zsh
source ~/powerlevel9k/powerlevel9k.zsh-theme
```

Otherwise zsh is wasting time loading p9k only to be overridden by p10k later on. By removing the line nothing should change but zsh should start a little bit faster.

**Comment by marcuskwan** [comment]
@romkatv Done! Much appreciated 😊
