### ISSUE TITLE
git-stash unknown file attribute

### ISSUE THREAD

**Issue by DanielChabrowski** [bhilburn/powerlevel9k#1315]
#### Describe Your Issue
What is happening?
Broken output as seen here: https://i.imgur.com/n9l9fRB.png

Steps to reproduce:
```console
$ git init
$ touch file1
$ git add file1
$ git commit -m "required initial commit for stash"
$ touch file2
$ git add file2
$ git stash
```

I've also managed to get a different error, however, probably unrelated:
```
vi-git-stash:2: bad pattern: stashes=( 0000000000000000000000000000000000000000 efe7684a8fd2b0c3486ba942fc3fc5cddedc1cd2 ...
```

#### Have you tried to debug or fix it?
Removal of `git-stash` from POWERLEVEL9K_VCS_GIT_HOOKS hides the issue as expected.

#### Environment Information
  - What version of ZSH are you using? zsh 5.0.2
  - Do you use a ZSH framework? Oh-My-ZSH (c105c04b6b1ddb917c12eadacb26c252f44ddfad)
  - How did you install P9k? cloning the repo
  - What version of P9k are you using? 3dafd79c41f8601b055e607ffefbfe3250c26040
  - Which terminal emulator do you use? xfce4-terminal
  - git version 2.17.1

**Comment by romkatv** [comment]
Tip: You can drag and drop images into the edit box on GitHub. It won't fix git-stash in Powerlevel9k but it'll make filing issues and commenting on them a bit easier in the future.

**Comment by romkatv** [comment]
I've reproduced this issue with ZSH 5.0.2. However, as per [Minimum System Requirements](https://github.com/bhilburn/powerlevel9k/wiki/Minimum-System-Requirements), the minimum supported version of ZSH is 5.1. There is no error with ZSH 5.1.

**Comment by DanielChabrowski** [comment]
Thanks for checking! There is no issue with zsh 5.5.1 as well so I'll try to upgrade that and move to powerlevel10k since it's visibly faster. The action that could be taken due to this issue could be to add minimum required version directly to README as powerlevel10k does.

Tip: You can use screen capturing tool like sharex or shutter that automatically uploads selected portion of the screen somewhere and puts the link in your clipboard so you don't have to care whether or not something supports dropping images. Much easier imo.
