### ISSUE TITLE
Extra vertical separator in different color for each segment

### ISSUE THREAD

**Issue by sdlins** [bhilburn/powerlevel9k#1317]
#### Describe Your Issue
I have a **vertical separator** in different color for each segment :-/

![Captura de tela de 2019-06-21 20-25-57](https://user-images.githubusercontent.com/412490/59955878-1f575100-9463-11e9-9f71-ba6a6e1f6b99.png)

#### Have you tried to debug or fix it?

I am a noob in terms of oh-my-zsh but I tried some different color configs, specially for OS_ICON and USER_DEFAULT, with no results.

Now, my relevant configs are: 
```bash
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="nerdfont-complete"

# Customizacoes
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user vcs dir_writable)

POWERLEVEL9K_TIME_FOREGROUND='250'
POWERLEVEL9K_TIME_BACKGROUND='240'

POWERLEVEL9K_OS_ICON_FOREGROUND='250'
POWERLEVEL9K_OS_ICON_BACKGROUND='240'

POWERLEVEL9K_USER_DEFAULT_FOREGROUND='240'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='250'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" ↳ "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
```

#### Environment Information

This information will help us understand your configuration.

  - What version of ZSH are you using? 
zsh 5.5.1 (x86_64-ubuntu-linux-gnu)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? 
Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? 
git clone
  - What version of P9k are you using? 
v0.6.7
  - Which terminal emulator do you use? 
Tilix

**Comment by sdlins** [comment]
In my right section I have no problem.

**Comment by romkatv** [comment]
Oh no! Not the vertical separators!

See https://github.com/bhilburn/powerlevel9k/issues/1313.

**Comment by sdlins** [comment]
Thank you @romkatv! I changed the terminal font from "Hack Nerd Font Regular" to other options, including mono, but the only is working fine is "Hack Regular".

A downside is that the icons are smaller. But I still preffer smaller icons than those "vertical" problems.

**Comment by VladimirMikulic** [comment]
@sdlins you can fix some of these small icons by installing all fonts except the last one from here https://github.com/ryanoasis/nerd-fonts/tree/master/src/glyphs.

Now, some of them will still be small, but it's still better than nothing.
