### ISSUE TITLE
Slow loading prompt in some repositories

### ISSUE THREAD

**Issue by martinpelikan** [bhilburn/powerlevel9k#132]
I just checked out https://github.com/ryanoasis/nerd-fonts because of the discussion I saw in #95. (tl;dr: I'm using urxvt and the fallback method doesn't seem to be an option, nerd-fonts provides patched fonts for Ubuntu mono which I like).

Anyway, the prompt takes somewhere between half a second to a second to load. Even when I remove all the segments, this is the case which is a bit strange. My suspicions are: 
1) Logic for non-rendered segments is still being executed, which is wasteful
2) Something in the logic for the VCS prompt scales with repository size (nerd-fonts is 1.8GB), which other themes (such as agnoster) do not do.

Will follow up with any findings I might make, but hopefully this helps if anyone else looks into it!

**Comment by dritter** [comment]
The prompt in my `nerd-fonts` checkout is as fast as in other repositories.. It is slower than in non-VCS folders, but that is normal (VCS_INFO does a lot).

For comparison, my segments are:
`status os_icon load context dir vcs symfony2_version time`

**Comment by dritter** [comment]
@martinpelikan Anything new here? Maybe it is an issue from a ZSH framework you use.. Could you retest it with plain ZSH?

**Comment by dritter** [comment]
Another approach could be to render the `vcs` segment asynchronously like described in [this](http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/) article. This technique is also used by the [pure](https://github.com/sindresorhus/pure) zsh theme. This might be a long-term goal.

**Comment by bhilburn** [comment]
@martinpelikan - Any updates, here? If not, can we close?

**Comment by martinpelikan** [comment]
I haven't had much time to try and reproduce this, and haven't encountered it since opening this issue. Closing this until I have something more concrete to work with. (Also, non-blocking prompts look pretty interesting!)
