### ISSUE TITLE
Overwriting Font size?

### ISSUE THREAD

**Issue by StormPlayzz** [bhilburn/powerlevel9k#1320]
I couldn't find anything related to this, so i figured I'd open an issue. 

In the config you can use %F and %K to set colors temporarily. Can you do the same with the font size?

I want to have one part of a segment with smaller font size, is this possible?

**Comment by romkatv** [comment]
> I want to have one part of a segment with smaller font size, is this possible?

Not possible. Your whole terminal can only use one font at a time. You can write some text to the terminal and then change the font, but the previously written text will change its at the same time.

**Comment by dritter** [comment]
Agreed with @romkatv . This is unfortunately not possible.
