### ISSUE TITLE
Confusion between powerlevel9k and powerlevel10k in customer support requests

### ISSUE THREAD

**Issue by romkatv** [bhilburn/powerlevel9k#1328]
People keep opening issues against powerlevel9k when they are in fact using powerlevel10k. Knowing what they are using is important for effective support. Unfortunately, I cannot always tell from the issue description which theme they are using (the downside of having compatible config options, heh). Moreover, when it becomes apparent that they are using powerlevel10k, it's awkward to continue the conversion on the powerlevel9k forum, and awkward to move it to powerlevel10k.

Do you think we should do something to make it clear from issue descriptions which theme is in use? Or direct powerlevel10k users to the powerlevel10k issue tracker?

**Comment by bhilburn** [comment]
@romkatv - Good point, and agreed. I'll add something to the issue template to try and direct people to the right place.

**Comment by sambadevi** [comment]
@bhilburn @romkatv maybe add some command `p9k::version` to display the current version and "flavour" of powerlevel9k.

Suggested Example Output
```
# when using p9k
$ p9k::version
Powerlevel9k -- P9K version 0.6.7

# when using p10k
$ p9k::version
Powerlevel10k -- P10K version 0.6.7
``` 

And ask for the output of `p9k::version` in the issue template

**Comment by romkatv** [comment]
Good idea. The output can also contain something like this:

```text
To open an issue or to ask for help, please go to http://github.com/...
```

The issue template on p9k can ask people to run `p9k::version`. This way you'll direct p10k users to the p10k issue tracker without revealing the existence of p10k to the users who aren't aware of it.
