### ISSUE TITLE
No warning about change in behavior within the `virtualenv` segment

### ISSUE THREAD

**Issue by alexlafroscia** [bhilburn/powerlevel9k#133]
~~I noticed while testing #119 that the `virtualenv` segment seems to be broken.  I tried it against `master` and `next`, with `master` working fine but `next` being broken.~~

Never mind: it seems that instead of being broken, the condition changed.  While it used to check to see if `$VIRTUAL_ENV_DISABLE_PROMPT` was set, it now checks to see if it is not set to `true` before rendering the segment, and only renders it if is it not true.  There doesn't seem to be any documentation about the change, so this might confuse people that upgrade (like me).

**Comment by alexlafroscia** [comment]
Nevermind: it seems that instead of being broken, the condition changed.  While it used to check to see if `$VIRTUAL_ENV_DISABLE_PROMPT` was set, it now checks to see if it is not set to `true` before rendering the segment, and only renders it if is it not true.  There doesn't seem to be any documentation about the change, so this might confuse people that upgrade.

**Comment by dritter** [comment]
I think we need a changelog..

Sorry for the inconvenience. :(

**Comment by alexlafroscia** [comment]
A changelog would really be perfect.  Since the dev flow nowadays seems to be merging a bunch of things into `next` and then from there into `master` it would be great if that commit got tagged as a release, where you can add notes about changes in there.

**Comment by bhilburn** [comment]
A CHANGELOG is now part of the project. Thanks, guys!

**Comment by alexlafroscia** [comment]
:tada:
