### ISSUE TITLE
message for dritter

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#137]
This is silly, but I can't figure out another way to do this.

@dritter - Will you send me an e-mail so I have your address? You can find my e-mail on my Github profile page. Thanks! =)

**Comment by dritter** [comment]
Done. ;)

**Comment by bhilburn** [comment]
Thanks =)

**Comment by DanielGGordon** [comment]
Evidence of one of Github's biggest drawbacks - little ability to communicate about a project outside of an issue or pull request. I don't know why they don't have a 'chat' section.

I suggest a [Gitter chat room](https://gitter.im) for this project.

**Comment by bhilburn** [comment]
Done!

https://gitter.im/bhilburn/powerlevel9k?utm_source=share-link&utm_medium=link&utm_campaign=share-link
