### ISSUE TITLE
Color capability warning

### ISSUE THREAD

**Issue by sdupille** [bhilburn/powerlevel9k#138]
In powerlevel9k_init() there's this bunch of code :
  # Display a warning if the terminal does not support 256 colors
  local term_colors
  term_colors=$(tput colors)
  if (( term_colors < 256 )); then
    print -P "%F{red}WARNING!%f Your terminal supports less than 256 colors!"
    print -P "You should put: %F{blue}export TERM=\"xterm-256color\"%f in your \~\/.zshrc"
  fi

Unfortunately, on FreeBSD, "tput colors" is the same as "tput col" and returns the number of columns of the terminal. So, I get this :
$ echo $TERM
xterm-256color
$ tput colors
80
// resizing window
$ tput colors
93

So I get the warning every time I open a new shell... even if the environment is nicely configured.

To get the number of colors, the command is :
$ tput Co
256

I suggest to use the command "echotc Co", which is a zsh builtin, to get the color capabilities of the terminal. That command is much more portable than tput.

**Comment by dritter** [comment]
@sdupille great catch! Could you submit a pull request for that?

**Comment by sdupille** [comment]
Hey, I try to submit a pull request, but I can't manage to do it. Sorry, it's my first pull request using github...

Here's the patch, anyway :
index 0d4b3e7..b039f0d 100755
--- a/powerlevel9k.zsh-theme
+++ b/powerlevel9k.zsh-theme
@@ -947,7 +947,7 @@ function zle-keymap-select {
 powerlevel9k_init() {
   # Display a warning if the terminal does not support 256 colors
   local term_colors
-  term_colors=$(tput colors)
+  term_colors=$(echotc Co)
   if (( term_colors < 256 )); then
     print -P "%F{red}WARNING!%f Your terminal supports less than 256 colors!"
     print -P "You should put: %F{blue}export TERM=\"xterm-256color\"%f in your \~\/.zshrc"

**Comment by sdupille** [comment]
OK, pull request created. Hope that's OK.

**Comment by bhilburn** [comment]
As @dritter said, great catch, and thanks for the PR, @sdupille!
