### ISSUE TITLE
Battery displays incorrect time remaining

### ISSUE THREAD

**Issue by Tritlo** [bhilburn/powerlevel9k#151]
In [line 272](https://github.com/bhilburn/powerlevel9k/blob/e79a2ffff002a373f79ee25147df92411d174b26/powerlevel9k.zsh-theme#L272) in the prompt_battery function, there is some attempt at converting the 00:08:47 string that acpi outputs to hours and minutes, but for me, it just outputs an incorrect time, i.e., when acpi says that 00:08:47 is remaining, we get

    $ date -u -d @000847 +%k:%M 
    0:14

which is not the same as the 0:09 that should be reported.

**Comment by Tritlo** [comment]
It seems that it's trying to use 00:08:47 as total seconds, which would amount to 847 seconds, and not 8*60 + 47 = 527 seconds

**Comment by bhilburn** [comment]
Closed by merge of #152.
