### ISSUE TITLE
Virtualenv prompt not showing

### ISSUE THREAD

**Issue by Psykar** [bhilburn/powerlevel9k#159]
https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L869

I believe the test above should be -z on VIRTUAL_ENV_DISABLE_PROMPT not -n?

**Comment by dritter** [comment]
Yep, you are right. This is already fixed in the `next` branch. ;)

**Comment by Psykar** [comment]
So it is!
Meanwhile a workaround is to just set VIRTUAL_ENV_DISABLE_PROMPT to false (which will still work once ```next``` gets merged.

**Comment by SalahAdDin** [comment]
When will be release the new version? My bash doesn't show me the correct virtualenv name:
![seleccion_095](https://cloud.githubusercontent.com/assets/5034215/15267903/1122a9e2-1994-11e6-9f6e-ee0d5eddd8ec.png)

**Comment by bhilburn** [comment]
@SalahAdDin - The new version was released a couple of weeks ago. You can get it either by pulling `master`, or checking out the official 0.4.0 tag: https://github.com/bhilburn/powerlevel9k/releases
