### ISSUE TITLE
Setting for newline after result?

### ISSUE THREAD

**Issue by kevinSuttle** [bhilburn/powerlevel9k#169]
Example: 
<img width="1425" alt="screen shot 2015-12-28 at 1 43 22 pm" src="https://cloud.githubusercontent.com/assets/95672/12023597/04dfe3bc-ad69-11e5-96f2-ef626f701028.png">

I'd prefer to do this without messing with the function internals and injecting a `"\n"` into something. 
Is there/could there be a setting for this? 

Thanks.

**Comment by dritter** [comment]
Well, in other words: you want a newline _before_ the prompt, right?

As I can see, you have no icon on the first line, so you could overwrite this icon with a newline by setting `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n "`. Please note the whitespace after the newline, which is mandatory.

**Comment by kevinSuttle** [comment]
Nice, thanks @dritter!

**Comment by kevinSuttle** [comment]
Actually, the space throws it off, but the newline is there.

<img width="564" alt="screen shot 2015-12-28 at 8 18 04 pm" src="https://cloud.githubusercontent.com/assets/95672/12028128/2b3f1f5a-ada0-11e5-9bd5-84796462f549.png">

**Comment by dritter** [comment]
Oops. Right. Well, there are four things we could do about it:

1. Add the escape sequence to "go left a character" after the whitespace. This should overwrite the whitespace. I am not sure if this escape sequence exists.. 
2. Instead of that custom multiline icon solution, we could add a custom segment that prints the newline first. This is a bad idea, as we would have some issues with an empty segment then.
3. Find out why how to get rid of the whitespace.
4. We could implement a switch for that.

I'll try to find a solution for number 3. This would be most suitable. Backup plan: Number 4.

**Comment by dritter** [comment]
@kevinSuttle Solution number 1 would be `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n\e[1D"

**Comment by dritter** [comment]
Uhm. This is really strange. If I trace the code, the newline gets printed, but I cant see it:
```zsh
+powerlevel9k_prepare_prompts:4> PROMPT=+powerlevel9k_prepare_prompts:4> print_icon MULTILINE_FIRST_PROMPT_PREFIX
+print_icon:1> local icon_name=MULTILINE_FIRST_PROMPT_PREFIX
+print_icon:2> local ICON_USER_VARIABLE=POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX
+print_icon:3> defined POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX
+defined:1> local varname=POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX
+defined:3> typeset -p POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX
+print_icon:4> echo -n '\n'
+powerlevel9k_prepare_prompts:4> PROMPT=+powerlevel9k_prepare_prompts:4> build_left_prompt
+build_left_prompt:1> defined POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
+defined:1> local varname=POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
+defined:3> typeset -p POWERLEVEL9K_LEFT_PROMPT_ELEMENTS
```

Notice the `echo -n '\n'` in the middle.. It doesn't matter how I declare the variable (single quotes, double quotes, implicit newline).

**Comment by kevinSuttle** [comment]
Wow. I had no idea movement escape sequences existed. 

Yeah, I've noticed some weirdness as well. 
Check this out: When you `echo [command] "\n"`, 
it just returns the command, not the output.

<img width="166" alt="screen shot 2015-12-28 at 9 47 52 pm" src="https://cloud.githubusercontent.com/assets/95672/12028887/c64dafdc-adac-11e5-9a31-fc0186a9fba5.png">

**Comment by kevinSuttle** [comment]
Lol, I'm just inventing problems to solve now. Feel free to ignore me. 

```bash
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n\e[1D"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="❯ "
```

![escape-left-pl9k](https://cloud.githubusercontent.com/assets/95672/12028970/66600b18-adae-11e5-9df5-f96634118293.gif)

**Comment by dritter** [comment]
Yep. `echo` takes that parameters as string to output. So if you do `echo ls` it would output `ls`. If you want to do it like that, you need to invoke a subshell: `echo $(ls)`. But that would be quite some overhead, if you just could invoke `ls` directly, as it prints on `STDOUT`.

**Comment by dritter** [comment]
Your second problem comes from moving the cursor around. You need to move the cursor forward one character again:
```zsh
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
# Newline before and move the cursor one character backwards
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n\e[1D"
# Arrow and move the cursor one character forward
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="❯\e[1C"
```

**Comment by dritter** [comment]
The reason why the single newline does not work is a ZSH limitation in context with subshells (from the manpage):
```
COMMAND SUBSTITUTION
       A command enclosed in parentheses preceded by a dollar sign, like `$(...)', or
       quoted with grave accents,  like  ``...`',  is  replaced with its standard output, 
       with any trailing newlines deleted.
```
Moving the cursor around as I suggested earlier isn't probably the best thing to do. For me it feels hacky to do so, but I think I found a simple solution that is much cleaner. Just add an carriage return to the newline: `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n\r"`. As the cursor is already at the beginning, the carriage return will have no effect.

Here is my little script to debug that behavior:
```zsh
#!/usr/bin/env zsh

function testNewline(){
  echo -n "\n$1";
}

function testNewlineWithReturnCode() {
  echo -n "\n$1";
  return 0
}

echo "Testing function calls with newlines"

echo "\nNewline only: $(testNewline)EOL"
echo "Newline with return code: $(testNewlineWithReturnCode)EOL"

echo "\nwith whitespaces:"
echo "Newline only: $(testNewline ' ')EOL"
echo "Newline with return code: $(testNewlineWithReturnCode ' ')EOL"

echo "\nwith carriage returns:"
echo "Newline only: $(testNewline '\r')EOL"
echo "Newline with return code: $(testNewlineWithReturnCode '\r')EOL"
```

@kevinSuttle I hope that does the trick finally for you without moving the cursor around. :)

**Comment by kevinSuttle** [comment]
Nice! Thanks @dritter!

**Comment by kevinSuttle** [comment]
I just learned about this in bash too, btw. 
https://medium.com/@joewalnes/handy-bash-feature-process-substitution-8eb6dce68133#.bkc10k2o1
