### ISSUE TITLE
Configure default segments?

### ISSUE THREAD

**Issue by kevinSuttle** [bhilburn/powerlevel9k#172]
Is it possible to configure the content of the segments (sub-segments)? 

For example, I'd like to be able to hide
- git stash numbers
- battery percentage

<img width="1415" alt="screen shot 2015-12-28 at 10 27 20 pm" src="https://cloud.githubusercontent.com/assets/95672/12029166/63aeb97e-adb2-11e5-8e80-85a1278bb66b.png">

**Comment by dritter** [comment]
Well, the battery segment has an verbose mode indeed. But this just shows the icon (at least it should; see #173 ). There is no switch to hide the battery percentage.

Also, it is not possible to hide the stash number.. I am not sure if you really want that. If you don't care about your stashes, why not clearing them all?

**Comment by bhilburn** [comment]
@kevinSuttle - The functionality showing the detailed git status (like stash number) comes from ZSH's `VCS_INFO` submodule. Unfortunately, there is no easy way to break out things like 'stash number' from other git status readouts - at least not without some significant parsing in our code.

Sorry, @kevinSuttle!

**Comment by kevinSuttle** [comment]
Ah, gotcha. Thanks anyway!
