### ISSUE TITLE
Right segment is offset significantly from right side of terminal

### ISSUE THREAD

**Issue by EdenSG** [bhilburn/powerlevel9k#175]
This seems to occur when `PROMPT_ON_NEWLINE` is active and `MULTILINE_SECOND_PROMPT_PREFIX` contains color or background codes.

Here you see a few terminal sizes - you can see the right segment is a set distance from the edge.
![screen shot 2016-01-01 at 3 10 26 pm](https://cloud.githubusercontent.com/assets/5727389/12072027/46197062-b09a-11e5-9338-63e44ed454a2.png)
![screen shot 2016-01-01 at 3 10 30 pm](https://cloud.githubusercontent.com/assets/5727389/12072028/461a5158-b09a-11e5-8a61-25aef66df0b1.png)
![screen shot 2016-01-01 at 3 10 37 pm](https://cloud.githubusercontent.com/assets/5727389/12072029/461c4ab2-b09a-11e5-9639-6039d1268655.png)

And the issue disappears when the colors are removed:
![screen shot 2016-01-01 at 3 16 53 pm](https://cloud.githubusercontent.com/assets/5727389/12072046/cd3aeeb8-b09a-11e5-9a96-7bf236d7681a.png)

Any idea why this might be?

**Comment by bhilburn** [comment]
@EdenSG - Whoa, weird.

Can you post the setting for `MULTILINE_SECOND_PROMPT_PREFIX` that you are using?

**Comment by EdenSG** [comment]
`POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="$(tput setab 4) $(tput sgr0; tput setaf 4)\ue0b0\ue0b1\ue0b1\ue0b1$(tput sgr0) "`

**Comment by dritter** [comment]
This had the problem as well:
```zsh
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="$(print -P '%K{blue} %k')%F{blue}\ue0b0\ue0b1\ue0b1\ue0b1%f "
```
This didn't:
```zsh
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="$(echo -n '%K{blue} %k')%F{blue}\ue0b0\ue0b1\ue0b1\ue0b1%f "
```
So, this would be the way to go. I couldn't figure out what `tput` does differently. My best guess is that the escape codes `tput` prints out are interpreted by zsh.
```zsh
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{blue} %k%F{blue}\ue0b0\ue0b1\ue0b1\ue0b1%f "
```

**Comment by bhilburn** [comment]
So it doesn't seem like a fix is needed in Powerline  for this. @dritter @EdenSG - thoughts?

**Comment by EdenSG** [comment]
@dritter Sorry, I don't understand what `%k{blue}` does - for me it just literally prints `%K{blue}`. Is there something I'm missing?

**Comment by dritter** [comment]
@EdenSG `%K` and `%F` are color instructions for ZSH. `%K` tells ZSH to start a new background color, `%F`to start a new foreground color. Lowercase `%k` and `%f` end these instructions.

So, as this theme populates the `PROMPT` variable, we could embed such color instructions to tweak the appearance. `POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX` gets read into `PROMPT`, so you don't need to invoke subshells to change the color.

Did you try to set that variable like that, and this printed you `%K{blue}`?
You can test that behavior with `print -P "%K{blue} %k%F{blue}\ue0b0\ue0b1\ue0b1\ue0b1%f "`

**Comment by EdenSG** [comment]
Thanks for your explanation — yes, that seems to work fine, I was omitting the `-P` flag when I tried to print that. 

I don't think the issue is resolved (although probably low priority), just that there's a workaround.

**Comment by Kayant** [comment]
Just wanted to add to this on a similar note with the right prompt. In my case with the right prompt  and new line enabled the below happens which resizing the terminal.
![promptttttt](https://cloud.githubusercontent.com/assets/1627291/12451415/2f3ecae0-bf81-11e5-8cad-4d9df845dbae.png)

With the right prompt disabled it renders fine, with the newline disabled and the right prompted enabled it still happens but with some moving about with resizing the terminal extra prompts are "hidden" which doesn't happen with both new line and right prompt enabled.

**Comment by rjorgenson** [comment]
@Kayant This happens to me too with right prompt and newline, I just got into the habit of clearing whenever I resize the window.

**Comment by EdenSG** [comment]
@Kayant Can confirm that. 
![screen shot 2016-01-20 at 11 07 48 am](https://cloud.githubusercontent.com/assets/5727389/12454903/6c19c650-bf67-11e5-8ef7-bf4a1d52f502.png)

**Comment by dritter** [comment]
@EdenSG @Kayant Yep, this is an issue of ZSH or your Terminal Emulator, not of powerlevel9k.. If you resize your window, the terminal emulator has to recalculate the number of columns over and over again, until your resizing is done. This is the reason why your terminal looks cluttered. If your resizing is done, the repaint is made one last time, so your last line ist correct..

**Comment by Kayant** [comment]
@dritter 

Ah thanks for the info. Time to hunt the source!

**Comment by EdenSG** [comment]
@Kayant @dritter Thanks! The hunt is on...

**Comment by bhilburn** [comment]
Hi @Kayant, @EdenSG -

I would like to close this issue. I tested a number of other themes, and saw the same problem. As @dritter said, it's an issue with the emulator redraw, not the theme itself.

If you find anything that leads you to believe we could fix the problem within the theme, though, please re-open this issue and let us know! It would be great to have a work-around =)

**Comment by jbarnes7952** [comment]
I am experiencing the same issues as @Kayant   
The corruption does not occur with default or agnoster themes.
The corruption presents the same in gnome, xfce and terminator.
