### ISSUE TITLE
Prepare for 0.3.0 Release

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#176]
Hey all -

Okay, I'd like to start the process of making a v0.3.0 release. We've got a lot of great new features, bugfixes, and docs, and I want to get them into our stable branch so our non-dev users can start benefiting from them!

@dritter - Can you double-check the CHANGELOG? I think it may have fallen behind a bit, but need you to confirm.

All - Let me know if you think there are any major outstanding developments that we should wait for!

**Comment by thuandt** [comment]
:+1: 
I'm waiting for new releases.
powerlevel9k is best zsh themes i known

**Comment by bhilburn** [comment]
Adding my configuration to the wiki, now. Way easier to upload images, here, than use the Wiki, so, here we go:

![bhilburn-config](https://cloud.githubusercontent.com/assets/569571/12149820/af22eb06-b45a-11e5-99b3-8a383659fc5f.png)

**Comment by dritter** [comment]
@bhilburn I think the changelog is good so far. As long as we don't add every single change into it. I originally wanted to document BC breaks, new segments and new major concepts.

If we want to document more, than we should mind the changes from #149, #150 and #174.

**Comment by bhilburn** [comment]
I haven't heard anything, so I plan on making the release today!

**Comment by bhilburn** [comment]
Argh! I found a bug while preparing the release!

@dritter - Check this out. We have an extra space when printing tag info in the VCS segment:

![spacing issue](https://cloud.githubusercontent.com/assets/569571/12181909/d4fc8550-b539-11e5-9dbb-1f186f28548a.png)

I know you made some changes to spacing between the last release and now. Any immediate thoughts?

**Comment by dritter** [comment]
Good catch! I've made #178 for that.

**Comment by bhilburn** [comment]
Thanks so much for the quick response, @dritter! Merged!

**Comment by bhilburn** [comment]
Release tag v0.3.0 has been pushed! Thanks so much, everyone, for all of your contributions!

Enjoy, @thuandt! `=)`
