### ISSUE TITLE
Unadvertised OSX dependency with coreutils

### ISSUE THREAD

**Issue by truthbk** [bhilburn/powerlevel9k#182]
Just a quick heads up to let you know you have an unadvertised dependency with coreutils (_realpath_, _readlink_) on OSX (tested on 10.11). 

**`brew install coreutils`** will fix it.

**Comment by dritter** [comment]
Ha! You are right. It is already complicated enough to install the fonts etc. I think we want to reduce the dependencies, so I try to get rid of realpath and readlink..

Thx for the report. :+1:

**Comment by bhilburn** [comment]
Closed by merge of #183
