### ISSUE TITLE
Commits that should be on 0.3.1

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#185]
Hey Ben!

These commits should be cherry-picked to master for the upcoming 0.3.1 release:
63c2bc6541a51058b8ce728c3f4d0ef30632aa07 - Changelog entries
f2b48d4f323f58f522355cd67777f3bc16ee826e - Removed next tag
1ec2919ff5aa366695ace6ed00646c452b9b83b3 - Explanation for Home and Folder icons
c8ce2264982018a9f576d416c997424b5c330c71 - Explanation improvement
31c78b5e47eb2f2343171635b384bb7f93d4c90e - Ruby Icon

And once it is verified: 989a9b3b4b6cf1c254388f5e350a709a01097979

Or do you plan to merge next into master? We have some other commits in next (nothing critical, but not very well tested)..

**Comment by bhilburn** [comment]
@dritter - I'm just going to prep v0.3.1 on `next`. I realize there are a few other changes, but they look fairly low risk.

I believe I have all of the above commits merged into `next`. Let's get #189 and #191 in, and then push out the patch release. How does that sound?

**Comment by dritter** [comment]
Sounds great! :+1:

**Comment by bhilburn** [comment]
@dritter - Okay, all PRs are in, thanks to great dev from @Kayant and @rjorgenson.

Let's test drive the HEAD of `next` for a few days and make sure everything looks good. Once we are reasonably sure it looks stable, I'll push the tag.

**Comment by rjorgenson** [comment]
Found an issue with prompt_load, submitted PR #193

**Comment by bhilburn** [comment]
Okay, #193 merged! Continue testing...

**Comment by bhilburn** [comment]
Resizing @kayant's image to try and get it to render larger on the Github wiki:

![kayants-config](https://cloud.githubusercontent.com/assets/569571/12373633/b73e0de8-bc34-11e5-80af-38d512280601.png)

**Comment by bhilburn** [comment]
Also, has anyone seen anything recently to add to this?

https://github.com/bhilburn/powerlevel9k/wiki/Sightings-In-the-Wild

**Comment by rjorgenson** [comment]
@bhilburn http://youtu.be/_GozEp88OA0

**Comment by bhilburn** [comment]
@rjorgenson - Whoa! This is awesome!!

**Comment by rjorgenson** [comment]
@bhilburn yeah, he has an older video too which was the one I remembered and was looking for - https://www.youtube.com/watch?v=TIkJ5fDz2-g - but this new one is way cooler!

**Comment by dritter** [comment]
@bhilburn @rjorgenson Yes, it seems that world of gnome is a fan of powerlevel9k :)
I already put the link to their google+ post where this video is on in the wiki a couple of days ago.

**Comment by bhilburn** [comment]
Just pushed a big update to the README, as well!

I'll plan on tagging v0.3.1 in a few days as long as we don't find anymore bugs!

**Comment by dritter** [comment]
I like the new readme. Much better to read! :)

**Comment by dritter** [comment]
#197 Should be in 0.3.1 as well.

**Comment by bhilburn** [comment]
#197 has been merged. Thanks, @dritter!

**Comment by bhilburn** [comment]
I would really like to get the #200 enhancement in before the release, but it looks like it needs a small change, first.

Thoughts, @dritter @V1rgul? Otherwise, things are looking stable.

**Comment by V1rgul** [comment]
#200 Updated :)

**Comment by bhilburn** [comment]
@V1rgul - Fantastic!!

v0.3.1 has been released! Fantastic work, everyone!
