### ISSUE TITLE
RUBY_ICON in awesome-fontconfig mode

### ISSUE THREAD

**Issue by thuandt** [bhilburn/powerlevel9k#187]
`RUBY_ICON` should be diamond icon `$'\UF219'` instead `$'\UF247'`

![Diamond icon](http://i.imgur.com/wWVn1Dz.png)

**Comment by dritter** [comment]
@thuandt Great catch! Could you submit a PR for that?

**Comment by bhilburn** [comment]
Closed by merge of #188.
