### ISSUE TITLE
Feature to disable showing git tags in prompt

### ISSUE THREAD

**Issue by bh** [bhilburn/powerlevel9k#190]
The both HEADs of `master` and tag `stage-2016-01-14-16-01-13` are the same. 

My shell looks like this when I am on the `master` branch:
`(mx)  ~/devel/mx/src ->  stage-2016-01-14-16-01-13 ->` 

My workaround to forcing showing "master" is to overwrite the function `vi-git-tagname`
``` javascript
function +vi-git-tagname() {
}
```
` (mx)  ~/devel/mx/src -> stage-2016-01-14-16-01-13 -> function +vi-git-tagname() {}`
` (mx)  ~/devel/mx/src -> master ->`

Is this possible to make this configurable?

Thanks!

**Comment by bhilburn** [comment]
@bh - Just to make sure I understand, you are saying that if you are on the master branch, but the HEAD is also a tag, you want to display the branch name rather than the tag name. Is that correct?

**Comment by dritter** [comment]
Are you sure that this is not a different remote tracking branch? If you have a local branch (e.g. `master`) that tracks a differently named remote branch (e.g. `stage-2016-01-14-16-01-13`) you would get an output like this.
Could you try to overwrite the `+vi-git-remotebranch()` function instead?

But to answer your question: I'll try to make the `VCS` segment more configurable in the 0.4.0 version. Stay tuned!

**Comment by bh** [comment]
@dritter:
It's a git tag:
```
 ~/devel/mx/src -> stage-2016-01-14-16-01-13 -> git br | grep "*"
* master
 ~/devel/mx/src -> stage-2016-01-14-16-01-13 -> git tag foo-bar
 ~/devel/mx/src -> foo-bar ->           
 ~/devel/mx/src -> foo-bar -> +vi-git-remotebranch() {} 
 ~/devel/mx/src -> foo-bar ->    
```
@bhilburn: correct

**Comment by bhilburn** [comment]
I think the solution @dritter is proposing in #198 is a good one. Let's work on this for v0.4.0.

**Comment by dritter** [comment]
@bh Could you double-check that my fix is working on `next`? That would be awesome. :)

**Comment by bh** [comment]
Yeah, works fine!

``` bash
(mx) -> ~/devel/mx/src -> stage-2016-02-10-17-43-31 -> export POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch)
(mx) -> ~/devel/mx/src -> master ->
```
