### ISSUE TITLE
RVM segment icon spacing

### ISSUE THREAD

**Issue by rjorgenson** [bhilburn/powerlevel9k#194]
I noticed that the spacing on the icon for the RVM segment seems off, see screenshot. It's possible this is just due to the font I'm using(SourceCodePro+Powerline+Awesome Regular), anyone else having this issue with their fonts?

<img width="715" alt="screen shot 2016-01-16 at 10 42 43 am" src="https://cloud.githubusercontent.com/assets/44096/12373673/1a5aeaaa-bc3e-11e5-818c-a118d54b9b36.png">

**Comment by dritter** [comment]
Yep, it is pretty close. I'm using SourceCodePro with Awesome as well.
![](https://cloud.githubusercontent.com/assets/1544760/12375135/a17f004a-bcb4-11e5-8273-4e6ba4381955.png)

**Comment by dritter** [comment]
Btw. you have a nice prompt. What must happen, before you put your config in the [wiki](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config)? :smile:

**Comment by rjorgenson** [comment]
thanks, I was planning on posting it up once I wasn't using features that aren't in master, soon!

**Comment by bhilburn** [comment]
Glad you caught this, @rjorgenson! Also happy the fix is easy, hah `=)`

I'll merge the PR as soon as I see it!

**Comment by rjorgenson** [comment]
Added PR #196

**Comment by bhilburn** [comment]
@rjorgenson - Awesome! Merged!

Resolved by #196.

**Comment by rjorgenson** [comment]
Added my config to the wiki, I didn't realize how incredibly long it was now! But I think it demonstrates the customizability of powerlevel9k pretty well =] It also showcases some of the more advanced features.

**Comment by dritter** [comment]
Nice config! :+1: 
The icon you use for the time segment could be a nice default visual identifier.
