### ISSUE TITLE
Invalid date message when battery is at 100%

### ISSUE THREAD

**Issue by theodelrieu** [bhilburn/powerlevel9k#206]
Hello! It seems there is a bug when using the 'time' segment when the battery is fully charged.
I keep getting the message:

`date: invalid date 'until'`

I'm following the branch 'next'.

**Comment by dritter** [comment]
Thx for the report. 
Do you use Mac or Linux?

**Comment by theodelrieu** [comment]
Sorry I forgot to mention that, I run a Debian 8.2 amd64

**Comment by dritter** [comment]
Could you paste the output of `acpi` here?
Internally we do an `acpi | awk '{ print $5 }'` to get the remaining time of your battery and format that with `date`. It looks like under Debian the output of acpi is different..

//cc @rjorgenson

**Comment by theodelrieu** [comment]
That's it, here's the ouptu when charging : `00:03:02`
When fully charged, it just prints : `until`

**Comment by rjorgenson** [comment]
Interesting, I don't have a debian box to test on, but we could add a sanity check for the date string before passing it to date.

**Comment by dritter** [comment]
@rjorgenson Could you submit a PR for that? That would be awesome. :)

**Comment by rjorgenson** [comment]
Hmm, I just looked at this and the bit of code that handles this already has a check to make sure it's only digits ...

```SHELL
    if [[ -f /usr/bin/acpi ]]; then
      local time_remaining=$(acpi | awk '{ print $5 }')
      if [[ $time_remaining =~ rate ]]; then
        local tstring="..."
      elif [[ $time_remaining =~ "[:digit:]+" ]]; then
        local tstring=${(f)$(date -u -d "$(echo $time_remaining)" +%k:%M)}
      fi
    fi
```

It shouldn't actually be trying to pass the 'until' string to the date command. @theodelrieu: could you post the complete output of the acpi command when your battery is charged? Could you also make sure you are on the latest version with the above code block, I know there were some issues with the date parsing in my original linux version since I don't have a linux box to test it on but that was taken care of.

**Comment by theodelrieu** [comment]
Here is the full output, this time the message is different, I will post another if I get my battery to 100%

Battery 0: Unknown, 99%
Battery 1: Charging, 99%, charging at zero rate - will never fully charge.
date: invalid date ‘\ncharging’ 

I pulled the last revision of the repo, the check you mentioned is in the sources

**Comment by rjorgenson** [comment]
Well that's an edge case I was not expecting to see .. Your system is seeing that it has two batteries connected. Do you have a directory in /sys/class/power_supply for both BAT0 and BAT1? Do you in face have two batteries on that machine?

**Comment by theodelrieu** [comment]
I indeed have two batteries, sorry I didn't mention this earlier, I thought it was just a parsing problem.
I was about to open another issue for the double battery support, since the displayed remaining time is incorrect.

This might be the occasion to solve two problems at once :)

**Comment by rjorgenson** [comment]
Hmmm, I'm not sure how that could be done in your case. It doesn't appear
to give any information about the second battery. Do the files in
/sys/class/power_supply/BAT0 contain any information. It's strange that
acpi doesn't know anything about it.

--
Robert Jorgenson

**Comment by theodelrieu** [comment]
Well it seems that the charging state is unknown sometimes, here is the output of acpi right now:

Battery 0: Full, 100%
Battery 1: Full, 100%

**Comment by theodelrieu** [comment]
And here is the output when one battery is fully charged : 

Battery 0: Charging, 100%,  until charged
Battery 1: Unknown, 79%
date: invalid date ‘until’

**Comment by michaeljhopkins** [comment]
I might be able to give some additional info on this problem. 

System:
```
OS: Ubuntu GNOME 16.04
Model: ASUS ROG G751JY
```

In the README it states `(note that it requires acpi on Linux)`. Upon running `sudo apt-get install acpi` I started getting errors after every command.

![](http://i.imgur.com/bzQ71Bl.png)

Removing `acpi` removes the command however battery is still reported correctly. Though I'll confess I'm not sure WHY its being reported correctly.

**Comment by rjorgenson** [comment]
@michaeljhopkins the acpi package is only required to show the time remaining for the battery. The capacity calculation is done from the values in the /sys/class/power_supply/BAT# folder. What version of ACPI do you have and what's the output when you run acpi when it's installed? It seems like they might have changed their output format.

**Comment by michaeljhopkins** [comment]
@rjorgenson The version that is automatically installed with apt-get. So running `apt-cache policy acpi` gets me this. I BELIEVE that would have been the version installed.

```
apt-cache policy acpi
acpi:
  Installed: (none)
  Candidate: 1.7-1
  Version table:
     1.7-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

**Comment by rjorgenson** [comment]
@michaeljhopkins can you re-install it and tell me what it outputs when you run the 'acpi' command with no arguments?

**Comment by bhilburn** [comment]
Hey @michaeljhopkins - Just following up on this issue! Were you able to run `acpi` as @rjorgenson suggested?

**Comment by bhilburn** [comment]
Hi all -

I'm closing this bug due to inactivity. @michaeljhopkins - let us know if you have time to re-open and debug this with us!
