### ISSUE TITLE
Possibility to change the vcs background color upon untracked files

### ISSUE THREAD

**Issue by Falkor** [bhilburn/powerlevel9k#209]
Hi, 

as a former user of the seminal `agnoster` theme, I became addicted to have the prompt change to orange as soon as the current git directory is in a dirty state (including if it comprizes an untracked files). 

With powerlevel9k, I "simply" have an icon `POWERLEVEL9K_VCS_UNTRACKED_ICON` which is displayed while I would have appreciate to have in addition a change in the background color. 

Is there a (simple) way to enforce that ?

**Comment by rjorgenson** [comment]
Hi Falkor,

I believe the functionality you are looking for was just added in pr #204 - is this the behavior you were after?

**Comment by Falkor** [comment]
Arg, my fault, indeed that's precisely what I was looking for. 
Sorry for the noise.
