### ISSUE TITLE
Use zsh 'parse_git_dirty' function to detect dirty repo

### ISSUE THREAD

**Issue by Falkor** [bhilburn/powerlevel9k#210]
I just also noticed a bug in the dirty dectection of git repositories. 

If you are at the root of the repository, untracked files are reported (using`POWERLEVEL9K_VCS_UNTRACKED_ICON`), yet if you are in a sub-directory, somehow the detection fail since the icon is no longer displayed. 

Actually, a reliable way to detect any dirty state is to rely on the `parse_git_dirty()` function that comes with [Oh my Zsh `lib/git.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/git.zsh) library. 

Linked to my issues #209 and #204, it would be great to rely on this function to change the background color of the vcs segment.

**Comment by Falkor** [comment]
See pull request #211

**Comment by bhilburn** [comment]
@Falkor - Unfortunately, we can't use OMZ-specific functions, as `powerlevel9k` is used by many users outside of that framework. You obviously didn't use it in this PR, but I just wanted to provide some insight `=)`

This is a great bug fix & improvement. Thanks so much for the great contribution!

#211 merged!
