### ISSUE TITLE
VCS_MODIFIED_FOREGROUND not applied to text

### ISSUE THREAD

**Issue by bartlibert** [bhilburn/powerlevel9k#213]
I have put the following configuration in my zshrc:

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'

It seems the red color is only applied to the icon of the segment, but not to the part after it.
A picture might make this clearer:
![selection_008](https://cloud.githubusercontent.com/assets/948770/12944453/6f6772f4-cfe7-11e5-8a65-44bc64a2436c.png)

I would expect the entire foreground to be modified.

**Comment by dritter** [comment]
Good catch! I'll have a look on that.

**Comment by bhilburn** [comment]
Fixed in `next` by merge of #214.
