### ISSUE TITLE
"Script location could not be found!" on Windows with prezto

### ISSUE THREAD

**Issue by gaerfield** [bhilburn/powerlevel9k#218]
powerlevel9k.zsh-theme exits with "Script location could not be found!" when sourced as a symlink
It seems, that "if [[ -L symlink]];" fails in cygwin (i.e. [stackoverflow - readlink in cygwin](http://stackoverflow.com/questions/12645662/readlink-in-cygwin)).

**Comment by dritter** [comment]
Thanks for the report!
Just to be clear: This is not really urgent, as it works if you don't use symlinks, right?

On second thought: This is more a cygwin problem, than of powerlevel9k. Sure, we could check for windows (cygwin) and use `cygpath` if so, but this would be quite hacky..

**Comment by gaerfield** [comment]
Correct, this is not urgent. Maybe its rather a bug in cygwin. But this way it's reported and the next guy stumbling on this knows what to do.

**Comment by gaerfield** [comment]
Correct, this is not urgent. Maybe its rather a bug in cygwin. But this way it's reported and the next guy stumbling on this knows what to do.

**Comment by megawebspace** [comment]
Same problem occurs on OS X, too.

**Comment by dritter** [comment]
@megawebspace Could you provide some more information on which circumstances it doesn't work on OSX?

**Comment by megawebspace** [comment]
I have a clean El Capitan, installed Prezto and installed powerlevel9k in a version 3.x.
On _prompt powerlevel9k_ the reported problem_ "Script location could not be found!"_ occurs. Only when in _~/.zprezto/modules/prompt/functions/_ _prompt powerlevel9k_ works and provides me with the theme.

**Comment by dritter** [comment]
@megawebspace Yeah. We had some trouble on prezto loading the theme-functions..
But it should work out of the box, if you have at least ZSH 5.0.8.. What does `zsh --version` gives you?

If the ZSH version is below 5.0.8, and we find a `~/.zprezto/modules/prompt/init.zsh`, we assume that powerlevel9k is linked there. If it is linked there (like `~/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup`), it should work too.

So, if you get the "Script location could not be found!"- message (which comes from ZSH trying to call our functions), I would say that you have a ZSH below 5.0.8 and linked powerlevel9k somewhere else..

**Comment by megawebspace** [comment]
zsh is version 5.0.8.
Will upgrading my zsh version help?

**Comment by dritter** [comment]
@megawebspace No. I think this would not help. But I need to understand your configuration better, to improve the theme.

As far as I know, to install the theme in prezto, you have to link the theme to a file called `prompt_something_setup` in `~/.zprezto/modules/prompt/functions/`, where `something` is usually `powerlevel9k`. What is the name of the link on your machine?

If your link is called `prompt_powerlevel9k_setup`, could you paste the output of `whence -w prompt_powerlevel9k_setup`?

**Comment by megawebspace** [comment]
yes, it's actually called `prompt_something_setup` and `whence -w prompt_powerlevel9k_setup`
outputs `prompt_powerlevel9k_setup: function`

**Comment by dritter** [comment]
@megawebspace Strange. Beginning with ZSH 5.0.8, `whence -v` should be more informative. At least this is what the [release notes](http://zsh.sourceforge.net/releases.html) say (look for "Changes between versions 5.0.7 and 5.0.8").
So a possible solution could be to rely on `whence -v` starting from ZSH 5.0.9.. I'll put that in a PR, so you could have a look if that works.

**Comment by dritter** [comment]
@megawebspace Before I do the PR. What does `whence -v prompt_powerlevel9k_setup` gives you?

**Comment by megawebspace** [comment]
`whence -v prompt_powerlevel9k_setup` gives me `prompt_powerlevel9k_setup is a shell function from  Users/torb/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup`

Right now, I'm using Powerlevel by commenting out two lines in powerlevel9k.zsh-theme

```
#print -P "%F{red}Script location could not be found!%f"
#return 1
```
in
```
# If this theme is sourced as a symlink, we need to locate the true URL`
if [[ -L $0 ]]; then
  # Script is a symlink
  filename="$(realpath -P $0 2>/dev/null || readlink -f $0 2>/dev/null || perl -MCwd=abs_path -le 'print abs_path readlink(shift);' $0 2>/dev/null)"
elif [[ -f $0 ]]; then
  # Script is a file
  filename="$0"
else
  filename="${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k/prompt_powerlevel9k_setup"
  #print -P "%F{red}Script location could not be found!%f"
  #return 1
fi
script_location="$(dirname $filename)"
```

**Comment by Tritlo** [comment]
I'm using prezto and zgen, and it works fine for me. Here is the relevant
line in my config
https://github.com/Tritlo/dotfiles/blob/master/zsh/.zshrc#L111
On mán., 7. mar. 2016 at 12:05, Mr. Uzai <notifications@github.com> wrote:

> whence -v prompt_powerlevel9k_setup gives me prompt_powerlevel9k_setup is
> a shell function from
> Users/torb/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup
>
> Right now, I'm using Powerlevel by commenting out two lines in
> powerlevel9k.zsh-theme
>
> #print -P "%F{red}Script location could not be found!%f"
> #return 1
>
> in
>
> # If this theme is sourced as a symlink, we need to locate the true URL`
> if [[ -L $0 ]]; then
>   # Script is a symlink
>   filename="$(realpath -P $0 2>/dev/null || readlink -f $0 2>/dev/null || perl -MCwd=abs_path -le 'print abs_path readlink(shift);' $0 2>/dev/null)"
> elif [[ -f $0 ]]; then
>   # Script is a file
>   filename="$0"
> else
>   filename="${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/external/powerlevel9k/prompt_powerlevel9k_setup"
>   #print -P "%F{red}Script location could not be found!%f"
>   #return 1
> fi
> script_location="$(dirname $filename)"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhilburn/powerlevel9k/issues/218#issuecomment-193206386>
> .
>
-- 
Matthías Páll Gissurarson

**Comment by dritter** [comment]
@megawebspace What's interesting here is that the path to your powerlevel9k installation lacks the leading slash. So the code thinks the path is relative to your current directory and fails to find the other functions there..
If I do a `whence -v powerlevel9k_init`, I get
`powerlevel9k_init is a shell function from /Users/dr/.oh-my-zsh/custom/themes/powerlevel9k-wip/powerlevel9k.zsh-theme` (note the leading slash). I am on OSX with ZSH 5.2 (but I don't think this makes any difference, if you are at least on 5.0.8).

**Comment by fikovnik** [comment]
I actually have the same problem on OSX with zsh 5.2. I also get 'Script location could not be found!'. However, when I do consecutively `exec zsh`, it works just fine.

```sh
$ whence -v prompt_powerlevel9k_setup
prompt_powerlevel9k_setup is a shell function from /Users/krikava/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup
```

Doing a bit of a debugging, it seems that `$0` when zsh is first launched (by creating a new terminal window or a new tab) is set only to `prompt_powerlevel9k_setup`. If run from `exec zsh`, `$0` is set to `/Users/krikava/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup`.

**Comment by dritter** [comment]
@fikovnik That sounds strange. Do you have any specials in your `.zshrc`? Or have two ZSH's installed (one by OSX, one by Homebrew), and set one as your systemwide Loginshell (in the OSX-Usersettings)? Or as Shell in your iTerm-Settings?

**Comment by bhilburn** [comment]
Hey @fikovnik - Just following up on this issue. We need a bit more info (see @dritter's last post) to figure out what to do, here =)

**Comment by krzysieki** [comment]
I had the same problem on OSX 10.11.4, zsh 5.2 from brew. The problem existed when I had started zsh manually (I set Iterm2 to run zsh on start). 

Changing my shell systemwide to zsh (with chsh) resolved issue.

**Comment by dritter** [comment]
@krzysieki Thx for the info!

What were your iTerm2 Login-settings before you changed the shell with chsh?

Did they look like this:
![iterm_settings_zsh](https://cloud.githubusercontent.com/assets/1544760/14235711/3d9d8ee0-fa06-11e5-852b-2b6c7e6feeab.png)

**Comment by krzysieki** [comment]
It was:
"Command: /bin/zsh"

And /bin/zsh is in version 5.0.8. Additionally I had zsh 5.2 from brew in /usr/local/bin/zsh.
And maybe that was the problem (2 zsh versions installed).

Now I set with chsh my shell globally to "/usr/local/bin/zsh" and in Iterm2 "Login shell" is set and everything works good.

**Comment by bhilburn** [comment]
Okay, so it sounds like it was simply a matter which version of ZSH was getting used. I'm going to close it out.

I don't think we need any updates to the docs based on this... let me know if you feel differently, @dritter.

Thanks for keeping us updated, @krzysieki! It's been very helpful for us, and we are glad you have everything up and running, now.

**Comment by dritter** [comment]
@bhilburn We could add some special instructions on the installation page in the wiki..
But I still need to understand the problem better..

@krzysieki You wrote you had the "same" problem. Could you go more into detail what "the same problem" is?

Is it that you had to start zsh manually to see the theme?
I can reproduce that problem, if I chose command->Login shell in the iTerm settings as command to execute. My login shell is still bash, so that would give me bash on every new iTerm window. That is why I set it to execute zsh on every start of iTerm.

**Comment by krzysieki** [comment]
@dritter, my problem was that powerlevel9k couldn't start on my fresh installation of zsh and prezto (I got 'Script location could not be found!' error)

As I wrote, the problem existed if I had started zsh manually in iTerm window (zsh worked but powerlevel9k didn't) 

When I replaced globally bash with zsh (so I could set iTerm settings to "login shell") powerlevel9k started to work.

Thanks for your work @bhilburn

**Comment by bhilburn** [comment]
@krzysieki - Hm, interesting. It sounds like it's an issue with how iTerm2 was loading the shell, perhaps.

And thanks for your kind words, @krzysieki! @dritter and I have put a lot of time and effort into `powerlevel9k` over the last couple of years, and we are glad you like it!

**Comment by wadkar** [comment]
This is interesting. I am getting similar error when I `ssh` into an ubuntu machine with `zsh 5.0.7`. I am using zgen + prezto. I follow the usual symlink to repo root setup suggested by `prezto`.

I rather not upgrade my zsh and stick wit prezto, what are my options?

**Comment by dritter** [comment]
@wadkar If `whence -w prompt_powerlevel9k_setup` gives you `function` and your prezto is installed at the usual location, it should work out of the box.
If your prezto could not be found, you should get a message, to set the `POWERLEVEL9K_INSTALLATION_PATH` manually:
https://github.com/bhilburn/powerlevel9k/blob/2630526df8275aebe3c5c65af188169ef3e1c94e/powerlevel9k.zsh-theme#L29-L37

Setting the `POWERLEVEL9K_INSTALLATION_PATH` (full path to `powerlevel9k.zsh-theme` file, including the filename itself) is the workaround for this problem. If this does not work, the `whence -w prompt_powerlevel9k_setup` check fails.. Maybe we should refactor this..

**Comment by wadkar** [comment]
I ended up compiling zsh-5.2 from source and I suppose this is no longer an issue for me. But yes, I am up for adding information in wiki/installation pages.

**Comment by rsalmei** [comment]
Sorry, but I've found that it really doesn't work in OSX...
I have clean prezto and p9k installs and it fails.
El Capitain 10.11.6, iTerm 3.0.7, zsh 5.0.8 unique (no brew install), iTerm set to login shell, chsh set to /bin/zsh.

It seems you can't set special parameter $0.
With this block:
```
echo $0
if [[ $(whence -w prompt_powerlevel9k_setup) =~ "function" ]]; then
  autoload -U is-at-least
  echo 1
  if is-at-least 5.0.8; then
    echo 2
    # Try to find the correct path of the script.
    0=$(whence -v $0 | sed "s/$0 is a shell function from //")
    echo $(whence -v $0 | sed "s/$0 is a shell function from //")
...
echo ---
echo $0
# If this theme is sourced as a symlink, we need to locate the true URL
if [[ -L $0 ]]; then
...
```

I get:
```
prompt_powerlevel9k_setup
1
2
/Users/rogerio/.zprezto/modules/prompt/functions/prompt_powerlevel9k_setup
---
prompt_powerlevel9k_setup
Script location could not be found!
```

See? Even if it is correctly identified and set, $0 doesn't get modified.
Could you fix it, please?

**Comment by webkenny** [comment]
Yes, I have also run into the same issue on OS X. @rsalmei are you saying that even with the workaround that @dritter has posted with a hardcoded path to the theme, it still will not work?

**Comment by webkenny** [comment]
I don't know if this will be helpful but this is a debug output from the theme on my OS X setup with Prezto. I didn't want to clog the issue thread so I have a gist for it instead.

https://gist.github.com/webkenny/db6689ed0b033d6f3eeb58ef068fa20d
