### ISSUE TITLE
Double line rendered

### ISSUE THREAD

**Issue by Erowlin** [bhilburn/powerlevel9k#222]
On a clean installation with Oh My Zsh (Clean installation too, no modification yet on the .zshrc file), there are two lines rendered : 

<img width="1276" alt="screenshot 2016-02-27 12 29 42" src="https://cloud.githubusercontent.com/assets/1775878/13372667/ed7b7514-dd4d-11e5-9a8a-b7a8b1f07e1f.png">

I installed the Meslo Powerline font from here : https://github.com/powerline/fonts and it's configured in ITerm2. I tried to restart Iterm, without success. 

Any ideas ?

**Comment by Erowlin** [comment]
I'm closing it, I've found the problem : 

<img width="885" alt="screenshot 2016-02-27 12 37 04" src="https://cloud.githubusercontent.com/assets/1775878/13372685/f8a0ef90-dd4e-11e5-9321-92f007dedf76.png">

In Iterm, the option "Double-Witdh Characters" was enabled, it has to be disabled.

**Comment by bhilburn** [comment]
@Erowlin - Thanks so much for posting the solution to this!

I have copied your solution to our Troubleshooting guide =)

https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting

**Comment by Erowlin** [comment]
Awesome :).
