### ISSUE TITLE
Git status: cherry-or-revert

### ISSUE THREAD

**Issue by smallhadroncollider** [bhilburn/powerlevel9k#224]
Every now and again one of my git repos will show "cherry-or-revert" instead of showing the status. It also doesn't show the commit number like it normally does.

I've tried doing a `git reset --hard` but that doesn't seem to work. The only way to sort it seems to be recloning the repository - but that seems a bit extreme.

Any ideas how to sort it?

![screenshot 2016-03-03 11 06 11](https://cloud.githubusercontent.com/assets/477286/13492445/f4af1d50-e12f-11e5-9b11-b19bc691bde2.png)

**Comment by dritter** [comment]
Yes, the commit hash is not displayed if we trigger `VCS_INFO`'s action formats. This is one thing.

The other thing is how this action formats are triggered. This is not under our control..  It seems to happen, if there exists a `.git/sequencer` folder in your repository ([source](https://github.com/zsh-users/zsh/blob/f7d5ff31ce8d354dd69de619e703b9c0e49f0977/Functions/VCS_Info/Backends/VCS_INFO_get_data_git#L66)). I think this happens, if you do something with multiple commits (like a cherry-pick or revert).

**Comment by smallhadroncollider** [comment]
Ah, ok. Thanks for pointing me in the right direction.

**Comment by dritter** [comment]
What was it then? I am curious.

**Comment by smallhadroncollider** [comment]
As you said, there as a `.git/sequencer` directory. I just removed it and everything went back to normal.

**Comment by dritter** [comment]
Ah. Okay. I thought you had the root cause for the problem. The `sequencer` directory must be created by some command you execute..

**Comment by patcheng** [comment]
I ran into the same issue. From:
http://stackoverflow.com/questions/39620717/what-is-the-git-sequencer-directory

running
```
git revert --quit
``` 
fixed my issue.

**Comment by dritter** [comment]
Thanks for sharing your insights @patcheng ! Much appreciated! :)

**Comment by nuc** [comment]
Same will happen if you tried to cherry-pick a range of commits, and for some reason it failed.

You should either:

```shell
git cherry-pick --continue
```

 if you want to keep on cherry-picking, or:

```shell
git cherry-pick --quit
``` 

to give an end, once and for all..

**Comment by demetrios** [comment]
`git cherry-pick --quit` solved it for me. No idea these were lingering…

**Comment by bhilburn** [comment]
Ah, yeah - git commands that enter iterative states can be tricky. Thanks for sharing, @demetrios!
