### ISSUE TITLE
POWERLEVEL9K_DIR_BACKGROUND no longer working

### ISSUE THREAD

**Issue by domibarton** [bhilburn/powerlevel9k#225]
Hi

Is it possible that `POWERLEVEL9K_DIR_BACKGROUND` is no longer working? I've updated the theme and now I get the default blue prompt :/

Cheers
Domi

**Comment by dritter** [comment]
Yep. That is correct. I added state to this segment, so the variable name changed depending on the state the segment is in. I documented the change in the [changelog](https://github.com/bhilburn/powerlevel9k/blob/master/CHANGELOG.md).
Now it is something like:
```zsh
POWERLEVEL9K_DIR_HOME_BACKGROUND='blue'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='cyan'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='yellow'
```

You can read more about states in the [wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).

**Comment by dritter** [comment]
@domibarton Did this work for you?

**Comment by domibarton** [comment]
Hi

Yep it worked, looks fine now :)
https://github.com/domibarton/config/blob/master/roles/zsh/templates/custom.zshrc.j2

Oops sorry I forgot to close the issue :( my fault!

Thanks & Cheers
D

**Comment by GlaciErrDev** [comment]
Hi!

I've added these variables and nothin happens. Can you help me?
```
POWERLEVEL9K_DIR_HOME_BACKGROUND='blue'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='cyan'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='yellow'
```

**Comment by dritter** [comment]
@GlaciErrDev could you provide a screenshot? And on which version of powerlevel9k are you?

**Comment by GlaciErrDev** [comment]
@dritter I've already fixed it. I don't know why, but after restarting iTerm2 it works well.

**Comment by dritter** [comment]
Great to hear!
Yes, you have to `source` your `~/.zshrc` after setting variables in there.
