### ISSUE TITLE
Unable to get awesome glyphs working

### ISSUE THREAD

**Issue by jaxxstorm** [bhilburn/powerlevel9k#226]
I'm pulling my hair out here because this seems relatively straightforward and yet I can't get it to work.

I've installed this font, which has all the patched glyphs included: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/complete/Meslo%20LG%20M%20Regular%20for%20Powerline%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf

I've selected it as my font in iterm2 and it works.

I've set the following in my ~/.zshrc: `POWERLEVEL9K_MODE='awesome-patched'`

And yet still it shows the powerline fonts rather than the awesome-powerline fonts.

Is there any more debugging I can do here? It seems like I'm missing something obvious

**Comment by dritter** [comment]
The obvious is that `nerd-fonts` is _not_ `awesome-terminal-fonts`. That are completely different projects. You need to install that font (either [patched](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched) or with [fontconfig](https://github.com/gabrielelana/awesome-terminal-fonts)).

**Comment by jaxxstorm** [comment]
I did try those methods as well, and it still doesn't seem to work..

**Comment by dritter** [comment]
Okay. How did you try it?
IMHO the easiest way is the patched mode. In short the steps to install are:

1. Download and Install one of the patched fonts
2. Select the font as ASCII & Non-ASCII-Font in iTerm2
3. Set `POWERLEVEL9K_MODE='awesome-patched'` somewhere before you source the theme (or call your ZSH-Framework, like oh-my-zsh)

Then you should be able to do an `echo $'\uE20E'` and see the Octocat. If not, could you attach a screenshot of your iTerm2 settings (Profiles->Text Window).

**Comment by jaxxstorm** [comment]
Ah-ha! the trick was the fact the mode needs to be called BEFORE the theme in `oh-my-zsh`! it's working now.

Maybe a doc update might help people?

**Comment by dritter** [comment]
@jaxxstorm Yes. Sorry for the unclear instructions. I've tried to improve the [docs](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions/_compare/9106b2560b9e0fe674205e0817cd84f3d41976fe...ef6962030e6db4142edbec21f67513d53e7729e5). Can you have a look, if this is clearer now?

**Comment by jaxxstorm** [comment]
Perfect, thanks!
