### ISSUE TITLE
VCS Modified foreground color missing

### ISSUE THREAD

**Issue by Limeth** [bhilburn/powerlevel9k#236]
The `POWERLEVEL9K_VCS_MODIFIED_FOREGROUND` options is not available, but the wiki says it is.
https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L786

**Comment by dritter** [comment]
Yep. That was a Bug on the `master` branch. This is fixed in `next` with PR #214. ;)

**Comment by Limeth** [comment]
Great. Looking forward to the update.
