### ISSUE TITLE
Bold text as Vi indicator strings

### ISSUE THREAD

**Issue by Limeth** [bhilburn/powerlevel9k#237]
I would like to make my Vi indicator strings bold, but it breaks the theme layout:
http://i.imgur.com/ale5TIh.png

It seems like the characters of the formatting are added to the width, making the right prompt detached.
The last line of the image shows behavior when auto-completion (tab) is triggered. The cursor wouldn't move to the left no matter what I did.

Settings I use:
POWERLEVEL9K_VI_INSERT_MODE_STRING="\e[1mINSERT\e[21m"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="\e[1mNORMAL\e[21m"

**Comment by dritter** [comment]
I don't know why that doesn't work, but what worked on my machine is using ZSHs own formatting sequences:
```zsh
POWERLEVEL9K_VI_INSERT_MODE_STRING="%BINSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="%BNORMAL"
```

**Comment by Limeth** [comment]
How do I disable the bold effect at the end of the string? Is there a reset sequence like `%R`? Are they documented somewhere? I can't seem to find them.

**Comment by bhilburn** [comment]
@Limeth - Disabling bold is `%b`. Give it a shot and let us know if it works?

**Comment by Limeth** [comment]
POWERLEVEL9K_VI_INSERT_MODE_STRING="%BINSERT%b"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="%BNORMAL%b"
This seems to break the layout. When I remove `%b`, the whole line is in bold text and no gap is displayed.
http://imgur.com/baCEqZf

**Comment by dritter** [comment]
@Limeth Interesting. Looks like you found a Bug. :+1: 
I'll have a look into it.

**Comment by Limeth** [comment]
@dritter Thanks for the help.

**Comment by dritter** [comment]
You are welcome! Thanks for the report. :)

**Comment by dritter** [comment]
Okay. This is _very_ interesting. Seems like a Bug in ZSH to me.

If I do an `print -P '%K{black} %F{white}%Bhello%b world'` then only the "hello" is white on black.. So it has nothing to do with powerlevel9k itself.

I filed a report on the [mailing list](http://www.zsh.org/mla/users/2016/msg00270.html).

Until someone fixes this bug, there are some workarounds.

  1. You could start the background color again, after disabling the boldface mode:
  `print -P '%K{black} %F{white}%Bhello%b%K{black} world`

  2. You could use alternative ways of specifying the bold text:
  `print -P '%K{black} %F{white}${fg_bold[white]}hello${fg_no_bold[white]} world'`
  I am not 100% sure if that really works, as I can't really distinguish the bold font from the normal one.. o_0

Hope that helps you. :wink:

**Comment by Limeth** [comment]
Thanks! Using the following values now:
```POWERLEVEL9K_VI_INSERT_MODE_STRING="%BINSERT%b%K{cyan}"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="%BNORMAL%b%K{cyan}"```

Works fine: http://i.imgur.com/qHKDTAO.png
