### ISSUE TITLE
Unsupported characters in tmux?

### ISSUE THREAD

**Issue by Limeth** [bhilburn/powerlevel9k#239]
Hello again. I've stumbled upon another issue, this time I can't seem to get the powerlevel9k theme working with the Terminal Multiplexer. I'm posting it here as an issue, because I was unable to resolve it myself by googling around and am not sure where to post it. Please, redirect me somewhere else, if this is not the correct place to ask for help regarding this issue.

Without tmux: http://i.imgur.com/ctcR5mf.png
With tmux: http://i.imgur.com/2CtMRfT.png

Terminal emulator:
https://launchpad.net/pantheon-terminal

`/etc/default/locale` content:
```
LANG=de_DE.UTF-8
LC_ALL=de_DE.UTF-8
```

`~/.tmux.conf` contains (not only) the following:
```
setw -g utf8 on
set-option -g status-utf8 on
```

Output of `tmux -V` (version):
```
tmux 1.8
```

**Comment by bhilburn** [comment]
@Limeth - I use tmux as well, but don't have any problem with the rendering. I have the same two lines you do (see my config here: https://github.com/bhilburn/dotfiles/blob/master/tmux.conf).

I am running tmux 1.9a, though. I wonder if the version update is important? What OS are you using?

**Comment by Limeth** [comment]
I am running tmux 1.8 on Elementary OS. Anyway, I switched to a different shell, so I no longer need a solution. Feel free to close the issue.
