### ISSUE TITLE
Port to fish-shell

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#24]
Hi!

I'm currently considering to port the theme to fish-shell as I think this would be a nice feature. I'm not sure about this intent as the shells differ substantially. But it might be worth the effort. 
What do you think?

**Comment by bhilburn** [comment]
I don't use the fish shell personally, so it's hard for me to comment. I also don't know how much of the code you could re-use, so your port might end up like more of a re-write? Thoughts?

**Comment by dritter** [comment]
Hopefully it will not end in an complete Rewrite. I mean, there is no vcs_info, which is the major issue. But if the tests work the same, it might be possible..
Second big issue is the prompt itself. Fish shell prompts work by calling a function `fish_prompt`, not by setting a variable..

There are some similar themes in `oh-my-fish` like https://github.com/bpinto/oh-my-fish/tree/master/themes/budspencer or https://github.com/bpinto/oh-my-fish/tree/master/themes/agnoster . I'm sure they will be a great inspiration.

I'll give it a shot at weekend.

**Comment by dritter** [comment]
Okay. I give up on this. :'(
There are vast differences on these shells.

**Comment by DanielGGordon** [comment]
@dritter 
Bash?

**Comment by adam-erickson** [comment]
Probably the closest thing to powerlevel-9k for fish is [bobthefish](https://github.com/oh-my-fish/theme-bobthefish).
