### ISSUE TITLE
SSH session

### ISSUE THREAD

**Issue by miguelcarax** [bhilburn/powerlevel9k#253]
Could be possible to keep the theme appearance within a ssh session? just changing the user and host names. Thanks!

**Comment by dritter** [comment]
There is no easy way powerlevel9k (or any other ZSH-theme) could provide this.

IMHO the only valid way is to install ZSH on the other machine, set your user account there to use this shell, and install powerlevel9k there.. Using a dotfiles repo would allow you to share your powerlevel9k-copy across machines.

I've seen People hacking their SSH to copy a whole bunch of files to the remote machine, when the log in there. But that is really hackish, and error prone (like you would have to check if ZSH is installed and used; copy powerlevel9k over; copy your config, etc).

**Comment by wadkar** [comment]
if its a machine you regularly `ssh` into, its much better to install `zsh` and pull your config files (you track them in a repo, don't you?)

**Comment by bhilburn** [comment]
Yeah, this isn't really something that shell settings, of any form, could solve. What you really need to do is replicate your workflow on the machine you are working on.

To suggest an alternate method, if it works for you, if you are doing development remotely you could simply mount the remote directories with `sshfs` and then use your local workflow for your toolchains. This is a workflow I commonly use to write code on other machines, and it works really well.

Closing out this bug as it's not something we can really fix, but feel free to continue posting alternative solutions! `=)`
