### ISSUE TITLE
Error when shortening path with package name when in a .git directory

### ISSUE THREAD

**Issue by andjscott** [bhilburn/powerlevel9k#271]
When shortening the path in `prompt_dir` with `truncate_with_package_name` and within a `.git` directory errors are shown:
``` 
prompt_dir:27: substring expression: -3 < 0
prompt_dir:27: substring expression: -3 < 0
```
`git rev-parse --git-dir` returns just `.` when in the top level of a`.git` directory so `package_path=${repo_path:0:-4}` fails.

**Comment by bhilburn** [comment]
Should have closed this when I merged #275 two weeks ago.
