### ISSUE TITLE
ls output getting erased

### ISSUE THREAD

**Issue by ogirginc** [bhilburn/powerlevel9k#280]
When `dir` is too long without any truncating applied, if I use `ls`, the output gets erased after a second:
[Asciinema](https://asciinema.org/a/at8z5bzlljqp26xlw5owjt3ac)

Tried using ["\n\"](https://github.com/bhilburn/powerlevel9k/issues/169#issuecomment-167696078) but didn't work.

- Mac OS X 10.11.5
- Both terminal & iTerm2 (3.0.2)

**Comment by bhilburn** [comment]
@ogirginc - Whoa. Weird.

I'm not really sure what to do about this. There isn't anything in our theme code that would blow away the terminal draw. This has to be a bit lower in the stack.

Are you using a framework like `oh-my-zsh`, `prezto`, or anything like that?

(By the way, cool way of showing the bug! I hadn't seen that site before.)

**Comment by ogirginc** [comment]
I am pretty new to z-shell, so not sure, if it is something to do with my set-up ([my dotfiles](https://github.com/ogirginc/dotfiles)).

Yes, I am using `oh-my-zsh`.

**Comment by bhilburn** [comment]
@ogirginc - I haven't forgotten about this, by the way! I'm going to try and dig into this ASAP.

**Comment by bhilburn** [comment]
@ogirginc - Hey! Can you give this branch a shot and let me know if it makes any difference for you?

https://github.com/bhilburn/powerlevel9k/tree/removing-zle-funcs

**Comment by ogirginc** [comment]
@bhilburn - Unfortunately, I have no idea how to install a branch of zsh. Though, I can try, if you are want to guide.

**Comment by bhilburn** [comment]
@ogirginc - Okay, I've merged that branch into `next`. Head into the directory where you cloned the `powerlevel9k` repository, and run this command:

    $ git checkout -b next -t origin/next

Then open a new terminal and see if your problem is fixed =)

**Comment by bhilburn** [comment]
@ogirginc - Were you ever able to test this?

**Comment by bhilburn** [comment]
Closed due to inactivity.
