### ISSUE TITLE
Create documentation for uninstallation of the powerline9k

### ISSUE THREAD

**Issue by riginoommen** [bhilburn/powerlevel9k#283]
Please update the wiki with resetting procedures

**Comment by bhilburn** [comment]
@riginoommen - Just to be sure, by "uninstallation" do you mean selecting a different theme? Is this for a particular framework?

All frameworks have different steps for changing the theme that you are using, and we support a lot of them - hence my question :)

https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions

**Comment by riginoommen** [comment]
@bhilburn Hi i meant the uninstallation procedures.

**Comment by bhilburn** [comment]
@riginoommen - There is no "install" for powerlevel9k - it's just a directory with the code in it. To "uninstall" it, simply delete the directory where you downloaded the code.
