### ISSUE TITLE
font-awesome Fedora

### ISSUE THREAD

**Issue by dbasinge** [bhilburn/powerlevel9k#286]
I'm using fontawesome with awesome-fontconfig using the fontawesome-font -4.6.3 package in the Fedora. Everything work great other an I get the ~ character instead of a home icon glyph, all the other folder icons work fine. Would rather use fontconfig rather than patched if possible. 

echo "\uf015" shows nothing.

Not exactly a powerlevel9k question, but thought this would be the best place to look for help.

Many thanks

**Comment by bhilburn** [comment]
@dbasinge - Just to check, do you get the folder icon if you are in a sub-dir of your home directory?

```
      HOME_ICON                      $'\UF015'              # 
      HOME_SUB_ICON                  $'\UF07C'              # 
```

**Comment by dbasinge** [comment]
Yes I do get a folder icon. Also home icon works if I set it to something else
POWERLEVEL9K_HOME_ICON=$'\UF1D0'

File a bug with Fedora, because I beginning to think it is a bug with the fontawesome Fedora package.

**Comment by bhilburn** [comment]
Yeah, if you see the folder icon just fine, then I agree that there is just something wrong with the font that you got from the Fedora packages. Thanks for reporting!
