### ISSUE TITLE
Not all icon fonts appear until I source .zshrc a 2nd time

### ISSUE THREAD

**Issue by brianjking** [bhilburn/powerlevel9k#291]
https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#falkors-configuration

* iTerm2 version 3.0.4
* macOS 10.11.5
* Oh-my-zsh

![zsh](https://cloud.githubusercontent.com/assets/6786817/16710451/7007acc8-45f4-11e6-87cd-84ae0fffc6fc.gif)

**Comment by rjorgenson** [comment]
@brianjking make sure you're loading p9k after all your settings in your .zshrc file. It looks like the first time it's sourced it's defaulting to not using awesomefonts.

**Comment by brianjking** [comment]
@rjorgenson Thanks, I think I may have figured it out based on your suggestion. Will close later today when I can confirm.

**Comment by bhilburn** [comment]
Hey @brianjking - Were you able to get this working?

**Comment by brianjking** [comment]
Yes, thanks.
