### ISSUE TITLE
FontAwesome does not work with powerlevel9k

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#293]
Hello,
I am running the termite terminal, version 11-3, on Arch Linux.
powerlevel9k works fine with PowerlineSymbols.otf but 
not with font-awesome. I have installed font-awesome like this:

`git clone https://github.com/gabrielelana/awesome-terminal-fonts`

and Then i have copied all fonts and scripts in ./build to 
~/.fonts/

`ls -l ./fonts`
```
-rw-r--r-- 1 chris chris   7387 Jul 20 00:03 devicons-regular.sh
-rw-r--r-- 1 chris chris 125484 Jul 20 00:03 devicons-regular.ttf
-rw-r--r-- 1 chris chris  14234 Jul 20 00:03 fontawesome-regular.sh
-rw-r--r-- 1 chris chris  80652 Jul 20 00:03 fontawesome-regular.ttf
-rw-r--r-- 1 chris chris   8079 Jul 20 00:03 octicons-regular.sh
-rw-r--r-- 1 chris chris  35576 Jul 20 00:03 octicons-regular.ttf
-rw-r--r-- 1 chris chris    369 Jul 20 00:03 pomicons-regular.sh
-rw-r--r-- 1 chris chris   8664 Jul 20 00:03 pomicons-regular.ttf
```

After this I did: `fc-cache -vf ~/.fonts`

I have started a new terminal but I still have the old powerline font.
I have also tried to set fontawesome directly in my terminal. But then I get the following:

![powerlevel9k with fontawesome](https://paste.archlinux.de/GtX/)

Do you have any idea how I can solve this issue?

EDIT:
Ok, I have created ~/.config/fontconfig/10-symbols.conf now. And If I do: `echo "\uf015"`
I get the home-icon. But why is it not in my powerline? I just see ~

**Comment by shibumi** [comment]
Ah ok. Sorry. I should read the FAQ. I forgot to set the font in zshrc.

It's working now.
But I have the icons twice. I have the home icon and ~. Is there a way to only show the home icon instead of "home-icon~"?

**Comment by bhilburn** [comment]
@shibumi - Did you get the double icon issue resolved?

**Comment by shibumi** [comment]
@bhilburn yes everything fine. I just found it that I need powerline-fonts AND font-awesome for displaying it. Without powerline-fonts i can see the home icon but everything else get's blurry.

It's working now. But i have still home-icon + ~ in one line. But I think this is desired, am i right?

![home icon with ~](https://paste.archlinux.de/TOX/)

**Comment by bhilburn** [comment]
Er, yes, but there is usually a space between the two of them. See here:
https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config

**Comment by shibumi** [comment]
@bhilburn Oh ok oO.
Then something is going wrong there, or it's just my font. I have a small fontsize of 9 or something.
Shall I debug this? I don't care so much about it. I am fine with it :)

**Comment by bhilburn** [comment]
If you are happy with it, then I wouldn't worry about it. We just want to be sure that our users get the prompt they want =)
