### ISSUE TITLE
[Feature-Request] SVN support for vcs

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#294]
Hello,
First of all thanks for powerlevel9k. It's awesome! 
I would like to have some SVN support for the vcs.
Where do i need to implement it? In the vcs.sh?
Do you have any tipps? I would really appreciate it if powerlevel9k would 
also has svn support. 

I am not sure how much time I have in future. But maybe I can help with it.
(although I have not much experience with the inbuild zsh functions)

**Comment by bhilburn** [comment]
Hey @shibumi - We're so glad you like it! Thanks for the kind words.

So we actually use ZSH's `VCS_INFO` module to provide VCS suppport, and, thankfully, that module has native support for `svn` - we just need to configure it.

I'll take a look at configuring svn support this weekend and post an update, here.

**Comment by shibumi** [comment]
This would be awesome! Thanks!

**Comment by bhilburn** [comment]
Hey @shibumi - I've pushed a branch that has subversion support turned on. Can you give this a shot and let me know if it works as you anticipate?

Branch: `adding-svn-support`: https://github.com/bhilburn/powerlevel9k/tree/adding-svn-support

**Comment by shibumi** [comment]
@bhilburn 
Hello, thanks. I am currently in China without laptop but I will test it when I am at home.

**Comment by shibumi** [comment]
Hello @bhilburn 
Sorry for the delay. I have tested it:

powerlevel9k has for SVN now the following format:
revision-number projectname revision-number.

As far as I can see you are using the same revision-number twice.
For example when I create a repository and reset it to an older revision both numbers are changing.
I would suggest you are only changing the last number. So that you have a format like this:

maximum-revision-number projectname current revision

Moreover I can see no diferences between different repository status. For example with git the color of the powerline changes when I merge, add, commit something etc. All of these does not exist.

I would like to help you. Do you have any tipps how I can start? I am familiar with bash scripting but these zsh features are new for me.

**Comment by shibumi** [comment]
Ok I have tried a bit around.. but not sure what I am doing wrong. Sorry I never played with zsh in deep:

https://github.com/shibumi/powerlevel9k/commits/adding-svn-support

@bhilburn What am I doing wrong? I have tried to implement a function to detect changes in svn repositories.. but it doesn't work. I think it has something todo with these hooks, right? I have really no idea what I am doing here..

**Comment by shibumi** [comment]
@bhilburn Ok it's working now. The prompt is changing the colour when something is unstaged and the icons will be displayed for staged and untracked. 

But there is still stuff todo:

1. How can I change the colour in the prompt? I can't see the icons when the prompt is yellow because the svn prompt seems to change the font color  to yellow in the last section...
2. There is no information about ahead/behind.. 
3. I want to print the text 'svn' instead of showing a git or hg icon.. How I can do this?
4. ... still more to do

**Comment by bhilburn** [comment]
Merged in #307
