### ISSUE TITLE
powerlevel9k arch linux packages

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#295]
Hello,
I am currently working on a powerlevel9k Arch Linux AUR package.
Could you guys please verify the optional dependencies for the package?
Are these dependencies up to date?
You can find them in the line with `optdepends=`

```
# Maintainer: Christian Rebischke <Chris.Rebischke[at]archlinux[dot]org>
# Contributor: Florian Dejonckheere <florian at floriandejonckheere dot be>
# Contributor:  jyantis <yantis@yantis.net>

_pkgname=powerlevel9k
pkgname=zsh-theme-${_pkgname}
pkgver=0.4.0
pkgrel=2
pkgdesc='Powerlevel9k theme for zsh'
arch=('any')
url='https://github.com/bhilburn/powerlevel9k'
license=('custom')
depends=('zsh')
optdepends=('oh-my-zsh-git: oh-my-zsh integration'
  'prezto-git: Prezto integration'
  'antigen-git: Antigen integration'
  'zpm: ZPM integration'
  'zsh-zim-git: Zim integration'
  'powerline-fonts: icon package'
  'awesome-terminal-fonts: icon package')
source=("https://github.com/bhilburn/powerlevel9k/archive/v${pkgver}.tar.gz")
sha512sums=('169727f6be8eaf9b04499f40738597ae6652bd5adf23b4110f9a169022e2171abab6e288a1293d28f72ebe3e63428b3c99458b8ebbd5b19d27dc87799f644a75')
provides=("zsh-theme-${_pkgname}")
conflicts=("zsh-theme-${_pkgname}")
install="zsh-theme-${_pkgname}.install"

package(){
  cd "${srcdir}/${_pkgname}-${pkgver}"

  # No license
  # Install Readme as License in case in the future some type of license is
  # added
  install -D -m644 README.md "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

  # Install Documentation
  install -D -m644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"

  # Install the theme
  install -D -m644 powerlevel9k.zsh-theme "${pkgdir}/usr/share/zsh-theme-${_pkgname}/${_pkgname}.zsh-theme"

  # Install the utilities
  for FILE in functions/*.zsh; do
    install -D -m644 "${FILE}" "${pkgdir}/usr/share/zsh-theme-${_pkgname}/functions/$(basename ${FILE})"
  done
}

# vim:set et sw=2 ts=2 tw=79:
```

You can find the package here: https://aur.archlinux.org/packages/zsh-theme-powerlevel9k-git/

**Comment by bhilburn** [comment]
Hi @shibumi - Awesome! We are really excited to get `powerlevel9k` into AUR! I was an Arch user for many years. Thanks so much for taking this on as a packager!

Your dependencies list, both for required and optionals, is accurate. I suppose there is the interesting point that while `powerline-fonts` is technically optional, in that `powerlevel9k` *can* work without it, the user really needs it to take advantage of the package. I think we could make a strong argument for `powerline-fonts` being a hard dependency.

Thoughts on this?

**Comment by rjorgenson** [comment]
Not sure if it's installed by default on arch or if it's optional but the battery segment utilizes the 'acpi' command as an optional dependency as well.

**Comment by shibumi** [comment]
Hello @bhilburn and @rjorgenson 
Nice. Ok. Then I will add acpi as optdep and powerline-fonts as hard dependency. I just need to talk with the -git version maintainers. I only maintain the release-version.

https://aur.archlinux.org/packages/zsh-theme-powerlevel9k-git/
https://aur.archlinux.org/packages/zsh-theme-powerlevel9k/

But the -git version seems orphaned. I hope that I can maintain it and then hopefully (if enough people vote for it) move it into the official repositories.

What's about all the other stuff:
```
antigen-git (optional) – Antigen integration
oh-my-zsh-git (optional) – oh-my-zsh integration
prezto-git (optional) – Prezto integration
zpm (optional) – ZPM integration
zsh-zim-git (optional) – Zim integration
```

Does powerlevel9k still need this?

**Comment by bhilburn** [comment]
powerlevel9k doesn't actually need any of those, but it will work with them if the user wants to use them. I think leaving them as "optional" is the right move - how the user configures powerlevel9k will just depend on which (if any) of those they have installed.

https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions

**Comment by shibumi** [comment]
Ok. I understand. Thanks. I have edited the PKGBUILD. I hope the powerlevel9-git package guys reply so that they will change their package also.

**Comment by bhilburn** [comment]
Hey @shibumi - Do you need anything else on this item? Otherwise I'd like to go ahead and close out this issue =)

**Comment by shibumi** [comment]
@bhilburn no everything fine.
