### ISSUE TITLE
command not found: _prompt_segment

### ISSUE THREAD

**Issue by dogjaw2233** [bhilburn/powerlevel9k#299]
whenever the prompt opens just before it returns the error:

prompt_vcs:68: command not found: _prompt_segment

the full output is:

rustystuff git/  master  7s
prompt_vcs:68: command not found: _prompt_segment

dogjaw2233@craigmatic ~/projects/rustystuff                                                                                                                   [9:17:44] 
 dogjaw2233@craigmatic  ~/projects/rustystuff  rustystuff/.                                                                                      ✓  55  09:17:44 

am i missing some dependency? im using oh my zsh by the way

**Comment by bhilburn** [comment]
@dogjaw2233 - Well, this is bizarre.

Can you share your PL9k configuration (if any)? Also, how did you install the powerline fonts? And are you using a framework or just vanilla ZSH?

**Comment by dogjaw2233** [comment]
sorry, I forgot to close the issue. the issue went away after reboot. sorry
for wasting your time.

**Comment by alex-bezek** [comment]
For anyone else that stumbles upon this issue, i had something similar. Running `source ~/.zshrc` would then cause all commands (like `ls`) to print out multiple of this issue
```
prompt_status:32: command not found: _prompt_segment
prompt_history:1: command not found: _prompt_segment
prompt_time:3: command not found: _prompt_segment
prompt_status:32: command not found: _prompt_segment
prompt_dir:245: command not found: _prompt_segment
prompt_rvm:5: command not found: _prompt_segment
```
I found running `login` fixes it. Opening new iterm2 tabs doesn't seem to have this issue as it logs you in when you make a new tab.

**Comment by romkatv** [comment]
Don't use `source ~/.zshrc`. Use `exec zsh` instead.

**Comment by alex-bezek** [comment]
awesome, thanks @romkatv !
