### ISSUE TITLE
[Help] Theme doesn't look how it suppose to

### ISSUE THREAD

**Issue by Adyel** [bhilburn/powerlevel9k#301]
# Hello

Just recently I discovered ZSH and this theme catched my attention. So, I followed the Steps and Installed it. I guess something went wrong or I messed up some steps anyhow my Terminal Theme looks broken. I don't know where to ask help so here I am. Please, can you kindly tell me what's going on ? I installed Every Fonts mentioned there (Don't know how to check if it is installed properly). And this is the result . 
![screenshot from 2016-08-12 02-45-46](https://cloud.githubusercontent.com/assets/4653623/17625533/225fea98-60cb-11e6-8dd4-21f9cbc99b90.png)

And here is my config File 

[zshrc.txt](https://github.com/bhilburn/powerlevel9k/files/415527/zshrc.txt)

I want it to look like [natemccurdy's configuration](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#natemccurdys-configuration)

I'll be very Grateful if anyone can Guide me. Thank you :)

**Comment by controversial** [comment]
You have to actually change the font in Terminal preferences, not just install it.

**Comment by Adyel** [comment]
Yeah, I figured it it. Sorry for silly question. Thanks for the help anyway :+1:
