### ISSUE TITLE
POWERLEVEL9K_MODE isn't updated unless I manually source ~/.zshrc

### ISSUE THREAD

**Issue by controversial** [bhilburn/powerlevel9k#302]
As you can see in this screenshot, I started a new zsh session, then only a second later manually sourced my `~/.zshrc`, and it looks drastically different:
![](http://i.imgur.com/4pn20gb.png)

I'd be fine with this, except for the fact that if I start another `zsh` session, the settings are once more reset until I source `~/.zshrc`:
![](http://i.imgur.com/PMuxsAk.png)

What could be going on here?

**Comment by controversial** [comment]
Also note that this happens on both my terminals, `Terminal.app` and `HyperTerm`, so it's not an issue with my terminal emulator.

**Comment by rjorgenson** [comment]
Most likely you are setting POWERLEVEL9K_MODE after you are loading p9k. All your p9k settings need to come before you load the theme. When you resource it is reloading the theme after the setting was set on the first run.

**Comment by controversial** [comment]
Ok, I'll try this.

**Comment by controversial** [comment]
Works great, thanks
