### ISSUE TITLE
Separator color not as shown in screenshots

### ISSUE THREAD

**Issue by vetional** [bhilburn/powerlevel9k#304]
OS : El Capitan on  Iterm 2
![screenshot](https://cloud.githubusercontent.com/assets/2220512/17693970/3fbe8260-63bf-11e6-8235-5c7936a9bc60.png)

**Comment by bhilburn** [comment]
@vetional: Just to be sure, you have set your iTerm2 font to your powerline font?

**Comment by bhilburn** [comment]
@vetional - Just a ping on this?

**Comment by bhilburn** [comment]
Closed due to inactivity.

**Comment by steakknife** [comment]
```zsh
# ~/.zpreztorc
zstyle ':prezto:module:prompt' theme 'powerlevel9k'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
```

![img](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/acef48e9-92be-44f7-9be5-a822741a3366/00000064.png)

[Font](https://gist.github.com/steakknife/c74538a1e7fb8d1e1e639f4d26723051/raw/360154d120055161bf9c04cbafd8af222305ee65/MonacowithPowerlineandawesome-terminal-icons-Regular.ttf)
