### ISSUE TITLE
Changing background color of custom segment is kinda hard

### ISSUE THREAD

**Issue by gnufied** [bhilburn/powerlevel9k#306]
Been just trying to set background color of my custom segment depending on state and it is perhaps harder than I thought.

I ended up copying one of the `prompt_segment` to implement feature I wanted, but i would be nice to do this easily.

**Comment by bhilburn** [comment]
@gnufied: Just to be clear, you aren't having an issue changing the background color permanently, but rather configuring your custom prompt to have different background colors depending on some internal state, right?

I'm not sure how we could do this easily in a general way that would apply to all custom segments, especially since the conditionals would be different between any two custom prompts. I'll note this as a feature item to mull over & work on, though :)

**Comment by zaneselvans** [comment]
Did anything ever happen with this potential feature?

I'm trying to create a custom prompt segment that indicates whether I am connected to the internet via NordVPN, and if so, what country I am connecting through. I would like to change the background color of the prompt segment based on the connection status (green for connected, red for disconnected) as well as changing the icon (closed padlock for connected, open padlock for disconnected). (See attached screenshot for current setup)

However, I haven't been able figure out or find documentation on how to create and/or access the "state" associated with a custom path segment. Is this an accessible feature?

At first glance, it seemed like this could be done by setting the background color associated with the custom segment conditionally within the function that generates the output for the prompt segment, but it seems like the system doesn't look to see if that variable has changed when the new prompt is re-generated, so the color never changes.
![pl9knordpvn](https://user-images.githubusercontent.com/596279/61821047-875ad780-ae13-11e9-98b0-22c3ac897429.png)

**Comment by romkatv** [comment]
@zaneselvans Can you share the code of your custom segment?

**Comment by zaneselvans** [comment]
Sure. It's pretty simple though.  Will probably only work on Linux with the `nordvpn` command line utility installed:
```sh
function nordvpn_prompt() {
    country_code=`nordvpn status | grep 'Current server:' | sed -e 's/^Current server: //g' | sed -e 's/\.nordvpn\.com$//g' | sed -e 's/[0-9]//g' | tr '[:lower:]' '[:upper:]'`
    if [[ -n $country_code ]]
    then
        # Padlock and country code
        vpn_prompt=$'\U1F512'$country_code
    else
        # Big red X
        vpn_prompt=$'\U274C'
    fi
    echo -n $vpn_prompt
}
# Custom nordvpn segment...
POWERLEVEL9K_CUSTOM_NVPN=nordvpn_prompt
POWERLEVEL9K_CUSTOM_NVPN_FOREGROUND='015' # white
POWERLEVEL9K_CUSTOM_NVPN_BACKGROUND='000' # black
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context custom_nvpn dir newline status)
```

**Comment by romkatv** [comment]
@zaneselvans Thanks, this looks useful. I've implemented it elsewhere.

**Comment by dritter** [comment]
@zaneselvans If you use your segment as regular one, instead of a custom one, this should work as well. Put this in your `~/.zshrc` before you source P9K:

```zsh
function prompt_nordvpn() {
    local country_code=$(nordvpn status | grep 'Current server:' | sed -e 's/^Current server: //g' | sed -e 's/\.nordvpn\.com$//g' | sed -e 's/[0-9]//g' | tr '[:lower:]' '[:upper:]')
    local segment_content state icon
    if [[ -n $country_code ]]
    then
        # Padlock and country code
        segment_content=$country_code
        state="CONNECTED"
        icon="NORDVPN_CONNECTED_ICON"
    else
        # Big red X
        state="DISCONNECTED"
        icon="NORDVPN_DISCONNECTED_ICON"
    fi
    "$1_prompt_segment" "${0}_${state}" "$2" $DEFAULT_COLOR_INVERTED $DEFAULT_COLOR "$segment_content" "$icon"
}
```

To use your segment, you need to put `nordvpn` in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` (or `RIGHT`). You can now style the segment as any other:
```zsh
POWERLEVEL9K_NORDVPN_CONNECTED_BACKGROUND="green"
POWERLEVEL9K_NORDVPN_CONNECTED_ICON=$'\U1F512'
POWERLEVEL9K_NORDVPN_DISCONNECTED_BACKGROUND="blue"
POWERLEVEL9K_NORDVPN_DISCONNECTED_ICON=$'\U274C'
```

**Comment by romkatv** [comment]
> `"$1_prompt_segment" "${0}_${state}" "$2" $DEFAULT_COLOR_INVERTED $DEFAULT_COLOR "$segment_content" "$icon"
}`

By the way, do you consider this public API? I keep telling users to stay away from it because it's not guaranteed to work across releases.

**Comment by dritter** [comment]
> By the way, do you consider this public API? I keep telling users to stay away from it because it's not guaranteed to work across releases.

At least in `next` we have defined it as part of the public API (see [Styleguide.md](https://github.com/Powerlevel9k/powerlevel9k/blob/651ab5f10de6bf50baf06ad90da8b676f0dd1dd1/STYLEGUIDE.md#variable-and-function-names) ). But there is no such decision in the current master, so it's undefined there and will break with `v7.0.0`. @bhilburn This is the main point to start with SemVer > 1.0.0..

**Comment by romkatv** [comment]
To clarify, this will only work in `master` and not in `next`? (It doesn't work in the fork either, but there is a public API; it's not the same as in `next` though.)

**Comment by dritter** [comment]
Ha! I've to correct myself. `__p9k_left_prompt_segment` (in `next`) is part of the _private_ API! So it is likely to break between updates.

**Comment by romkatv** [comment]
> Ha! I've to correct myself. `__p9k_left_prompt_segment` (in `next`) is part of the _private_ API! So it is likely to break between updates.

This matches my prior understanding of the state of this API. Users who rely on `$1_prompt_segment` have to be careful when they upgrade their theme because their code is not guaranteed to work in the future. Is this accurate?
