### ISSUE TITLE
[svn] No svn powerline in svn repository

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#311]
Hello seems like something gone wrong in the next branch. I have checked out c4fdc8f70804fea6f543e6bbf3964301e2537e36 

I can't see any svn powerline.

![svn repo test](https://paste.archlinux.de/4JLJ/)

**Comment by bhilburn** [comment]
@shibumi - After you checked out the `next` branch, did you restart your terminal program? You must completely reload your terminal emulator for it to take effect.

**Comment by shibumi** [comment]
@bhilburn 
Yes I did. I restarted zsh via `zsh` and just now I have restared my whole terminal.
I have still the same behaviour.

Here is my current zshrc:

```
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_SHOW_CHANGESET=true
#source  /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
source  /home/chris/export/github/powerlevel9k/powerlevel9k.zsh-theme
function pkgcleanup {
    random=$RANDOM
    mkdir /tmp/cleanup-$random
    mv PKGBUILD /tmp/cleanup-$random
    mv *.install /tmp/cleanup-$random
    mv .SRCINFO /tmp/cleanup-$random
    rm -rI *
    mv /tmp/cleanup-$random/*.install .
    mv /tmp/cleanup-$random/PKGBUILD .
    mv /tmp/cleanup-$random/.SRCINFO .
    rmdir /tmp/cleanup-$random
}
zstyle ':completion:*:hosts' hosts 
```

`/home/chris/export/github/powerlevel9k/powerlevel9k.zsh-theme`

goes to the current next branch.

**Comment by bhilburn** [comment]
@shibumi - I'm not sure what could be happening, here. Here it is on my machine:

![svn](https://cloud.githubusercontent.com/assets/569571/18146859/efad1aec-6f9f-11e6-8dde-5d07632c58f4.png)

Can you go into your `/home/chris/export/github/powerlevel9k/powerlevel9k.zsh-theme` directory and do a `git log | head` and confirm it prints the same thing as what you see in my screenshot?

And you have no other directories with powerlevel9k checked out on your system? It's not installed any other way?

**Comment by bhilburn** [comment]
(didn't mean to close this bug)

**Comment by shibumi** [comment]
Ok Sorry, It was definitly my fault. I just checked out my repo without pulling your latest changes.. So of course the head in the next branch was wrong..
