### ISSUE TITLE
[svn] Change color of icons

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#312]
Hello,
Is there any chance to change the color of the icons in the svn powerline?
Here is a screenshot: 

![yellow...](https://paste.archlinux.de/iWz/)

As you can see I can't see the icons because the icons and the latest svn number is yellow.
Any chance to change this or do I need to change my terminal color theme?

I don't have this issue with the git powerline there is everything and the icons are black on yellow.

**Comment by bhilburn** [comment]
Ah, okay, I now see what you were talking about in your original PR. Not being a user of the Awesome font series myself, I didn't see this.

I'll play with it. I'm sure we can fix it.

**Comment by shibumi** [comment]
@bhilburn  Yes thats what I've meant. I had no idea how to fix it myself.. I tried injecting some colorcodes into the line but it has always just broke my powerline.

**Comment by shibumi** [comment]
Hey can you explain me how I can the color? I would do it my self. Would also be awesome if you could merge the newest changes with svn in the git master branch.

**Comment by bhilburn** [comment]
@shibumi - I just spent a bit of time looking at this, and I honestly have no idea what's happening. I created a branch where I made some changes (just simplified something), but I honestly am not sure how this could be happening.

If anyone else has insight, here, that would be helpful.
https://github.com/bhilburn/powerlevel9k/tree/debug-svn-icon-color

**Comment by shibumi** [comment]
@bhilburn 
I will have a look over weekend.. hope I can help.

**Comment by bhilburn** [comment]
@shibumi - I'm assuming this is still an issue, yes?

**Comment by shibumi** [comment]
@bhilburn yep. It's still an issue. Hadn't time yet to look over it. Hopefully sunday or Monday

**Comment by bhilburn** [comment]
Fixed by #484!
