### ISSUE TITLE
vi_mode customization

### ISSUE THREAD

**Issue by miguelcarax** [bhilburn/powerlevel9k#315]
I notice that the steps to change vi_mode colors in wiki are wrong.

This doesn't work:
`POWERLEVEL9K_VI_INSERT_MODE_<whatever>` 

This works:
`POWERLEVEL9K_VI_MODE_INSERT_<whatever>`

Also "normal" mode is wrong,  this is the way it works:
`POWERLEVEL9K_VI_MODE_NORMAL_<whatever>`

Regards and thanks for awesome theme!

**Comment by bhilburn** [comment]
Updated the wiki! Thanks, @miguelcarax!
