### ISSUE TITLE
Battery Module Verbose setting has no effect

### ISSUE THREAD

**Issue by IQubic** [bhilburn/powerlevel9k#322]
Whether I have POWERLEVEL9K_BATTERY_VERBOSE set to true or false in my .zshrc file the Battery Module still shows the same output. 85% ὐB is the output I get. The Readme states that this flag should change whether or not I have the time remaining shown, but It doesn't work.

**Comment by dritter** [comment]
Hi! Sorry for the late response.

There may be some circumstances where the remaining time could not be displayed. So it may be, that you use a Linux distro on a machine without acpi (or no acpi daemon installed in `/usr/bin/acpi`)..

So which OS do you use? If it is indeed linux. what does `ls -l /usr/bin/acpi` give you?

**Comment by IQubic** [comment]
I am running Gentoo Linux. And At the time I had neither ACPI, nor the ACPI Daemon installed on my machine. Now that I do have them both installed I'm going to try the battery module again.

`ls -l /usr/bin/acpi` tells me that /usr/bin/acpi is a script. The full readout is this:
`-rwxr-xr-x 1 root root 19808 Oct 29 00:37 /usr/bin/acpi`

**Comment by IQubic** [comment]
Alright, haveing ACPI and the ACPI Daemon made this segment work. Now is there a way to change what Unicode glyphs are shown in the battery segment?

**Comment by dritter** [comment]
Yep. The battery segment is a rather complex one. You can read about how to change the icons in the [wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).

**Comment by IQubic** [comment]
So setting `POWERLEVEL9K_BATTERY_ICON`to something else will fix this issue?
http://imgur.com/a/oPrkk
Look at the battery segment in the upper right corner.

**Comment by IQubic** [comment]
It appears it does.
ISSUE CLOSED.
