### ISSUE TITLE
Show current tag

### ISSUE THREAD

**Issue by jwhitmarsh** [bhilburn/powerlevel9k#329]
Is there any way to show the current vcs tag alongside the branch name? For example, my current HEAD is `c4bb843 - (HEAD -> master, tag: v0.47.1, origin/master) v0.47.1` and i'd like to see

` master   v0.47.1`

**Comment by bhilburn** [comment]
Yup! We actually have this feature already. Unfortunately, it was broken right before the v0.5.0 release. The fix is in the `next` branch, and will be in v0.5.1.

If you want to use it immediately, just check out the `next` branch for now =)

https://github.com/bhilburn/powerlevel9k/tree/next
