### ISSUE TITLE
Conditional hostname visibility?

### ISSUE THREAD

**Issue by spicypixel-** [bhilburn/powerlevel9k#335]
Is it possible to only show the user@hostname when the session is inside ssh and just user when it's local?

**Comment by bhilburn** [comment]
@spicypixel - I see, so you want it just to `user` when you're local, and `user@hostname` when you are SSH'd. Yeah, that's fairly simple, and a good idea for an enhancement.

Thanks!

**Comment by shibumi** [comment]
I just run powerlevel9k on my server also.. that way it will also change the user and hostname.. Do you really see a need here for an enhancement?

I also don't think thats  so simple. because when you login in to a server via SSH you are on a different system. You will have no powerlevel9k there (except you install it).

**Comment by spicypixel-** [comment]
Well yeah but I tend to install it via my dotfiles repo. Just nice if at
all possible.

**Comment by shibumi** [comment]
@spicypixel- 
Wouldn't it be easier to configure the powerline on your host that your host will just display the user?

**Comment by spicypixel-** [comment]
Yeah though means host specific config to override the local dotfiles. It
would just be merely nice if zsh was aware if was in an SSH session and
report accordingly.

I'm currently doing that though with my local machine having a different
configuration. Just becomes less attractive if I'm locally at the remote
machine and SSHing back into the original local machine.

**Comment by shibumi** [comment]
@spicypixel- 
Ah ok. Now I understand. You want that powerlevel9k is aware of it that it runs in a SSH session. Ok that makes sense. I thought you want to take your powerlevel9k configuration with you on the server. This would be nearly impossible..

**Comment by spicypixel-** [comment]
Correct merely if it detects it's running in SSH to show user@hostname, and
if it's not merely user. Obviously as you said it's going to be limited to
wherever I install the .zshrc but if I'm not going through the trouble of
setting up the host changes are I won't be connecting regularly enough to
worry.

**Comment by shibumi** [comment]
@spicypixel- 
I wrote a first ssh-detection prototype and virtualization prototype for powerlevel9k. You can checkout: https://github.com/bhilburn/powerlevel9k/issues/336

**Comment by bhilburn** [comment]
I think the feature that @spicypixel- is asking for in this issue could easily be integrated into the work that @shibumi started over in #336.

**Comment by bhilburn** [comment]
So I'm trying to dad this enhancement in [the bug-335](https://github.com/bhilburn/powerlevel9k/tree/bug-335) branch, and for whatever reason, I absolutely cannot make it work. It should be really simple, but the `elif` conditional isn't yielding `true` and I can't figure out why.

I'm pretty sure I'm just too tired and can't think straight. Can someone take a look at my latest commit, there, and tell me what I'm doing that's stupid? Hah =)

**Comment by rjorgenson** [comment]
Should it be `"$POWERLEVEL9K_ALWAYS_SHOW_USER"` instead of `"POWERLEVEL9K_ALWAYS_SHOW_USER"`? And the same with `POWERLEVEL9K_ALWAYS_SHOW_CONTEXT` above it.

**Comment by bhilburn** [comment]
Almost certainly. Going to sleep now, and hopefully I'll wake up with less
of a fried brain, hah :)

**Comment by bhilburn** [comment]
Thanks, @rjorgenson!

@spicypixel - This feature is now merged into `next` =)

**Comment by giogziro95** [comment]
Hi, everyone. I'm entering `POWERLEVEL9K_HIDE_HOST=true` into my _.zshrc_, and it doesn't seem to work. Am I missing something?

**Comment by shibumi** [comment]
Hello @giogziro95 which version do you have?

**Comment by giogziro95** [comment]
@shibumi It's the latest one from the _master_ branch.

**Comment by giogziro95** [comment]
Just checked on the _next_ branch. Doesn't seem work there either...
