### ISSUE TITLE
prototype for ssh and virtualization detection

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#336]
Hello,
#335 brought me on some ideas so I've written some custom functions.
You can find the code at the end. It would be nice if this would find a way into the next release :) I just wanted to type down a rapid prototype for it. Maybe I will implement it if I find some time.

![..](https://paste.archlinux.de/zrn/)

**Functions**

`zsh_detect_virtualization` will detect the type of virtualization. In case of no virtualization nothing will displayed. It uses the `systemd-detect-virt`-feature. So it should work on most of the Linux distributions (Debian, Ubuntu, Arch Linux, CentOS, Fedora..). 

`zsh_detect_ssh` will detect if the current session is in SSH. It just scans if `SSH_TTY` or `SSH_CLIENT` exist.

**Known Problems**

- due to the reason we use systemd for the virtualization detection it will not work on systems without systemd. For example Devuan, Gentoo (if run with openRC), Voidlinux and many more. We could write a fallback function for it but i doubt that our fallback function would be such precisely as `systemd-detect-virt`. We would also need a fallback function for BSD or Mac OS X systems.
- the ssh detection does only work with the first user in the ssh session. If you change the user inside of the ssh host you will lose it, because sshd exports `SSH_TTY` and `SSH_CLIENT` only for the first user. A workaround would be to set one of the environment variables manually... but this way somebody could also just tag `ssh` in the powerline manually...

**TODO**

- include it in the project
- Find some nice icons for it

```
zsh_detect_virtualization(){
    local virt=$(systemd-detect-virt)
    local color='%F{yellow}'
    if [[ "$virt" == "none" ]]; then
        if [[ "$(ls -di / | grep -o 2)" != "2" ]]; then
            virt="chroot"
            echo -n "%{$color%} $virt"
        else
            ;
        fi
    else
        echo -n "%{$color%} $virt"
    fi
}

zsh_detect_ssh(){
    local color='%F{yellow}'
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        echo -n "%{$color%} ssh"
    fi
}

POWERLEVEL9K_CUSTOM_DETECT_VIRT="zsh_detect_virtualization"
POWERLEVEL9K_CUSTOM_DETECT_SSH="zsh_detect_ssh"
POWERLEVEL9K_CUSTOM_DETECT_VIRT_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_DETECT_SSH_BACKGROUND="black"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time custom_detect_virt custom_detect_ssh)
```

**Comment by bhilburn** [comment]
Thanks so much for putting this together, @shibumi! 

I like the idea of detecting virtualization a lot. The primary issue here is that we have a lot of OSX users, so we'll need something in there that works for them, as well.

SSH detection is currently built into the `context` segment (see [here](https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L436)), but it probably makes sense to break it out into its own function.

You raise an interesting point about things not working if the $USER changes within the SSH session... it's interesting that there isn't some sort of environmental awareness of this carried forward. I wonder if there is and we are just unaware of it.

This is a great idea to get into the next major release. Let's iterate and get it merged. I do recommend we move this to a PR =)

**Comment by shibumi** [comment]
@bhilburn 

> I like the idea of detecting virtualization a lot. The primary issue here is that we have a lot of OSX users, > so we'll need something in there that works for them, as well.

Maybe I am wrong. But do we really need this? I mean most of the OSX doesn't virtualize OSX. They just run powerlevel9k on their Macbook without virtualization. Therefore they would just see 'none' virtualization in their powerline.. More important would be a solution for BSD. Although if we solve BSD, I think we will solve OSX, too.

> SSH detection is currently built into the context segment (see here), but it probably makes sense to break > it out into its own function.

Are you sure checking for `SSH_CLIENT` is enough? I would also check for `SSH_TTY`. Some `SSH_CLIENTS` may not set `SSH_CLIENTS`.

> You raise an interesting point about things not working if the $USER changes within the SSH session... >it's interesting that there isn't some sort of environmental awareness of this carried forward. I wonder if >there is and we are just unaware of it.

Well, I thought about this for a while.. I solved this on my Server with using `su -p` and `sudo -E` this way the environment will be preserved. But this is really unclean and nobody should do this.. I  thought about writing a temporary file somewhere so that powerlevel9k would know about an SSH Session. But how to make sure to delete it after the SSH Session was closed? I really doubt that there is a better way to detect SSH than our current way.. For most of the people it will be enough they just log in on their server with root access and work in a root shell..

For BSD I found several solutions. Solution 1 is to use `dmidecode -s system-product-name`. Solution 2 would be to convert this into a shellscript: https://github.com/chef/ohai/blob/master/lib/ohai/plugins/bsd/virtualization.rb

**Comment by bhilburn** [comment]
> Maybe I am wrong. But do we really need this? I mean most of the OSX doesn't virtualize OSX. They just run powerlevel9k on their Macbook without virtualization. Therefore they would just see 'none' virtualization in their powerline.. More important would be a solution for BSD. Although if we solve BSD, I think we will solve OSX, too.

Oh, I see your point. Yes, I agree, nobody is virtualizing OSX. If someone using OSX, though, has a local Vagrant Linux virtualization, that is something we would want to work. That would still work with the above, though, as this code works with Linux. 👍 

> Are you sure checking for SSH_CLIENT is enough? I would also check for SSH_TTY. Some SSH_CLIENTS may not set SSH_CLIENTS.

You're right. That's an important improvement.

> Well, I thought about this for a while.. I solved this on my Server with using su -p and sudo -E this way the environment will be preserved. But this is really unclean and nobody should do this.. I thought about writing a temporary file somewhere so that powerlevel9k would know about an SSH Session. But how to make sure to delete it after the SSH Session was closed? I really doubt that there is a better way to detect SSH than our current way.. For most of the people it will be enough they just log in on their server with root access and work in a root shell..

Agreed. I think we are just going to have to accept this limitation.

> For BSD I found several solutions. Solution 1 is to use dmidecode -s system-product-name. Solution 2 would be to convert this into a shellscript: https://github.com/chef/ohai/blob/master/lib/ohai/plugins/bsd/virtualization.rb

I don't know anything about BSD, but it looks like `dmidecode` is standard on BSD OSes. Let's roll with that.

Can you put all of this together and submit a PR against `next`? Excited to get these improvements merged.

**Comment by bhilburn** [comment]
And, actually, let's try to get #335 integrated into this, as well.

**Comment by bhilburn** [comment]
Merged!

**Comment by bhilburn** [comment]
Wait, no - only partially. We can now detect SSH, but not other types of virtualization. @shibumi still has some great ideas, here, that could be added to P9k.

**Comment by shibumi** [comment]
@bhilburn mh? I have added detection for virtualization via systemd long ago. Or what are you talking about? ^^

**Comment by bhilburn** [comment]
@shibumi - No, you're right, I was confused, hah.
