### ISSUE TITLE
Improve Go segments

### ISSUE THREAD

**Issue by mingrammer** [bhilburn/powerlevel9k#337]
The gvm is Golang version management package like virtualenv of python.

How about support gvm for Go like rvm for ruby, nvm for javascript and virtualenv for python?

**Comment by dritter** [comment]
@mingrammer That would be a great improvement! 👍 

Feel free to submit a pull request and do not hesitate to ask if you need help ;)

**Comment by bhilburn** [comment]
I would still love to see this happen, if there are any Go programmers that are up to the task! =)

**Comment by zikes** [comment]
I think the Go segment is fairly robust now, anything else on your Go wishlist?

**Comment by bhilburn** [comment]
Agreed! Thanks for your contributions, @zikes =)
