### ISSUE TITLE
Laptop power weirdness

### ISSUE THREAD

**Issue by IQubic** [bhilburn/powerlevel9k#339]
I am experiencing something odd when using Powerlevel9K on a Gentoo Laptop. Whenever I have my laptop plugged into a power source AND my laptop is fully charged and I run a command I get the command's output, and then on a new line I get the following printed: 
`date: invalid date 'discharging'`

The included image shows that when the laptop is plugged in and fully charged, I get the extra line. Then, the second time I run `acpi` and `echo test` my laptop is unplugged and I don't get the extra line.

I have verified that my issue does not occur when the laptop is plugged in BUT NOT fully charged. It does not occur when I have Powerlevel9K disabled, even if my laptop is plugged in and fully charged

![2016-11-15-194612_1920x1080_scrot](https://cloud.githubusercontent.com/assets/22628816/20334133/9b17a35e-ab6c-11e6-80fc-68ffed1d5b57.png)
PS: Ignore the missing glyphs. I've temporarily uninstalled Font-Awesome.
Also, ignore the fact the prompt is in the middle of the screen. That happens after I change the of my terminal

**Comment by IQubic** [comment]
Since it might be relevant my Powerlevel9k config is as follows:
`ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time battery)
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S} \uf017"
POWERLEVEL9K_BATTERY_ICON="\uf240"
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3`

**Comment by rjorgenson** [comment]
I believe that's the output from the acpi command, this is the relevant bit from the battery function

```
    if [[ -f /usr/bin/acpi ]]; then
      local time_remaining=$(acpi | awk '{ print $5 }')
      if [[ $time_remaining =~ rate ]]; then
        local tstring="..."
      elif [[ $time_remaining =~ "[:digit:]+" ]]; then
        local tstring=${(f)$(date -u -d "$(echo $time_remaining)" +%k:%M)}
      fi
    fi
    [[ -n $tstring ]] && local remain=" ($tstring)"
```

If you run acpi from your command line does it return the same thing? It shouldn't be outputting anything =/

**Comment by IQubic** [comment]
@rjorgenson Yeah, removing the battery module fixes my issue. Running acpi  from my terminal only produces this weird output if I have Powerlevel9k active. If I have Powerlevel loaded, then I see that line of output after EVERY SINGLE COMMAND, including acpi.

**Comment by rjorgenson** [comment]
@IQubic what is the output of your acpi command when the battery is fully
charged and plugged in? Also what version are you on? Are you on master? Is
that bit of code in the powerlevel9k.zsh-theme file the same? It should be
lines 408-416.

--
Robert Jorgenson

**Comment by IQubic** [comment]
@rjorgenson I think that I'm using the latest version on the master branch, but I'm not sure how to tell.

**Comment by IQubic** [comment]
@rjorgenson Here's a weird thought I had: perhaps awk is not able to find a fifth column when my laptop is plugged in and fully charged since that's a different output from plugged in and charging, as well as discharging. I. E. it's the only instance where acpi doesn't give a time output.

acpi usually gives a time to full, or a time to empty depending on whether or not the laptop is plugged in. When fully charged and plugged in, a time estimate is useless.

**Comment by bhilburn** [comment]
We've dealt with previous problems regarding the output of `acpi` in the past (see #206, for example).

That said, this one is different, and I think @IQubic might have just identified the issue in his above comment. Need to play with the code a bit (currently on a Windows machine at work and can't mess with it).

**Comment by IQubic** [comment]
@bhilburn Yeah, so the 5 column of `acpi` (as gotten with awk) in this case is the word "discharging" That can't be parsed to a valid date, and therefore the date command throws a fit. Not sure how to fix that though.

**Comment by rjorgenson** [comment]
Hmm, it still shouldn't be running the date command with 'discharging' as the value. Maybe there's some reason I don't understand that "discharging" is matching a regex of "[:digit:]+" - I'm not the greatest at regular expressions =/

**Comment by IQubic** [comment]
@rjorgenson That regex will match anything that has one or more of the characters inside the brackets.
Since "discharging" one or more of the letters in the inside the bracket (d and i), then it passes.

What I suggest is the following regex:
` (:0-9:)+ `
I think that's what you were trying to go for.

Feel free to test out that, or other possible regexes here:
https://regex101.com/

**Comment by rjorgenson** [comment]
@IQubic Did some testing on this as I remember looking into this specifically when I wrote it. ZSH uses POSIX compatible regex by default which uses the [:digit:] special place holder rather than \d which is what I was used to. It looks like I left out a set of brackets to make that actually work though. See example screenshot below. I've made the fix in next branch on my fork, could you test this version and if it works I can submit a PR for the change. Thanks for helping us track this down. I don't actually have access to a linux machine with a battery. Most of the linux portion of the battery segment was written blind.

https://github.com/rjorgenson/powerlevel9k/tree/next

![screen shot 2016-11-21 at 9 45 33 am](https://cloud.githubusercontent.com/assets/44096/20491828/df99a07e-afcf-11e6-9bf5-451f9cd1f0c1.png)

**Comment by IQubic** [comment]
@rjorgenson Yeah, I was not aware that the [:digit:] was a valid POSIX regex expression. When I get access to my Linux machine I'll test out you're fork. It seems to work from those diagrams.

**Comment by IQubic** [comment]
@rjorgenson Your fix works for me. I'd say you should submit a pull request now.
