### ISSUE TITLE
Path Directory Separators?

### ISSUE THREAD

**Issue by PoLoMoTo** [bhilburn/powerlevel9k#340]
Would it be possible to add an option to use symbols for the separation between directories in the current path? I attached a screen shot that I found, I'm not sure how the look was achieved in the screen shot.

![687474703a2f2f7777772e67657870657274732e636f6d2f696d672f7465726d696e69782f7465726d696e697831312e706e67](https://cloud.githubusercontent.com/assets/5509894/20370840/dd5f0e10-ac2e-11e6-8ed7-fb3c3d22f080.png)

(I apologize if this is already possible. I couldn't seem to find anything documenting this, although I didn't really know what to search.)

**Comment by bhilburn** [comment]
Hm, that does look nice, hah.

@dritter - Do you have any thoughts on how the above might have been achieved?

**Comment by dritter** [comment]
@bhilburn yep. We could replace all slashes in the path with the desired sign. Should not be too hard. I'll send a PR in the next days.

**Comment by PoLoMoTo** [comment]
Any update on this?

**Comment by dritter** [comment]
@PoLoMoTo Sorry for the delay and thanks for the reminder. ;)
#346 is my pull request for that. Check it out!

**Comment by PoLoMoTo** [comment]
Cool thanks, I just wanted to check in.  Looks good!

**Comment by dritter** [comment]
@PoLoMoTo Glad you like it. :)

How did you install the theme? It may take a while until it is merged in `master`, but I am sure it will be soon in `next` branch.

**Comment by PoLoMoTo** [comment]
@dritter For this I downloaded the zip for the last commit in your pull request but that didn't seem to work, I probably did something wrong as I don't quite understand git fully.  I'll just be patient and wait for it to be merged with next or master, thats probably the best to avoid wasting my time and yours.

**Comment by dritter** [comment]
Allright. 👍

**Comment by bhilburn** [comment]
This is now in the `next` branch! Thanks, @dritter!

**Comment by PoLoMoTo** [comment]
I've just cloned the next branch and this does not work.  I cloned the branch and put `POWERLEVEL9K_DIR_PATH_SEPARATOR="%f "$'\uE0B1'" %F"` in my zshrc and nothing happened.  I don't know what I could possibly have done wrong, but then again I say that a lot.....

**Comment by Hebgbs** [comment]
@PoLoMoTo You need to be on the `next` branch. In Terminal, do `git checkout next` then your code should work.

`%F{XXX}` for the first argument in your code is what I did to make it change colour, `XXX` being whatever your ANSI colour value is from 0 to 255.

**Comment by PoLoMoTo** [comment]
@Hebgbs Thank you.  That works now.  Git is all black magic and witch craft as far as I can tell.  I apologize for my stupidity, my brain seems to be shrinking by the day.

**Comment by tonylambiris** [comment]
@PoLoMoTo any chance of sharing that great color scheme? :)

**Comment by PoLoMoTo** [comment]
@tonylambiris the color scheme in the screenshot in the op? With the purple and gray? I found that on the Terminix (now Tilix) website so I don't actually have it. Sorry.
