### ISSUE TITLE
Icons are replaced with text or whitespaces

### ISSUE THREAD

**Issue by Virkkunen** [bhilburn/powerlevel9k#358]
I've recently installed the powerlevel9k theme, and I am using [dritter's configuration](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#dritters-configuration). The issue I am facing is that some icons are replaced with text or a whitespace (eg. the tux icon is shown as Lx, Apple is OSX). I checked the icons.zsh file on functions, are the icons there are shown correctly, and I am using the same font on my terminal and text editor (Roboto Mono for Powerline, but the issue happens with any powerline/awesome/nerd font).

Here's screenshots from Terminator and Mousepad.
http://i.imgur.com/rPiSOfz.png
http://i.imgur.com/kkDzivV.png

**Comment by dritter** [comment]
Did you:
- Choose the right POWERLEVEL9K_MODE according to your setup?
- Set the awesome font as font in your terminal emulator?
- Set `POWERLEVEL9K_MODE='awesome-patched'` before you source/configure the theme?

These are the main causes for this problem..

**Comment by Virkkunen** [comment]
> Choose the right POWERLEVEL9K_MODE according to your setup?
Yes. I've tried all modes and they all display text instead of icons. Double checking the icons.zsh, it displays the proper icons there.

>Set the awesome font as font in your terminal emulator?
Also did that. I've tried patched powerline, awesome and nerd fonts, tried patching them myself, won't display icons only on the terminal (terminator, xfce terminal, urxvt). The icons are displayed correctly on any other program or text field.

>Set POWERLEVEL9K_MODE='awesome-patched' before you source/configure the theme?
I've purged the theme and installed again, setting all the different modes, but the issue still persists.

**Comment by dritter** [comment]
> I've purged the theme and installed again, setting all the different modes, but the issue still persists.
Just to be sure, you have somewhere in your `~/.zshrc` something like:
```zsh
POWERLEVEL9K_MODE="awesome-fontconfig"
source ~/my/path/to/p9k/powerlevel9k.zsh-theme
# or, if you use oh-my-zsh:
ZSH_THEME="powerlevel9k/powerlevel9k"
```
right?

And if you do `print -P $'\uF201'`, you see a flash icon, right?

But if you do `print_icon 'ROOT_ICON'`, you don't see the flash icon?

**Comment by Virkkunen** [comment]
I've double checked my .zshrc, the ZSH_THEME is set to powerlevel9k/powerlevel9k.

For the prints, this is what gives
![image](https://cloud.githubusercontent.com/assets/9111925/21121946/6a0b11e2-c0b6-11e6-9c9b-6c6a8829b973.png)

The ROOT_ICON though is set on the get_icon_names command. The LINUX_ICON, for exemple, isn't and only shows as Lx, but on the icons.zsh file, it is the penguin, displayed correctly.

**Comment by dritter** [comment]
Could you post your `~/.zshrc` here? That would be a great help.

**Comment by Virkkunen** [comment]
Here it is
http://hastebin.com/hokusuhedu.bash

**Comment by dritter** [comment]
Could you move the `source $ZSH/oh-my-zsh.sh` line at the bottom and try again?

**Comment by Virkkunen** [comment]
Hah, that works! Icons are all correctly displayed now.
Thank you for the help!

**Comment by bhilburn** [comment]
Looks like we are all set! Happy you're up and running @Virkkunen!
