### ISSUE TITLE
Improve CVS icons

### ISSUE THREAD

**Issue by davidmpaz** [bhilburn/powerlevel9k#359]
When using `POWERLEVEL9K_MODE='awesome-fontconfig'`, I think that having Github icon as VCS_GIT_ICON is not as good as it could be.

Would not be nice to show icon from respective service depending of the repo? For example I in my theme setup I have this:
```
get_icon_by_repo() {
  local remote=`git ls-remote --get-url`
  if [[ "$remote" =~ "github" ]] then
    POWERLEVEL9K_VCS_GIT_ICON='\uf113 '
  elif [[ "$remote" =~ "bitbucket" ]] then
    POWERLEVEL9K_VCS_GIT_ICON='\uf171 '
  elif [[ "$remote" =~ "gitlab" ]] then
    POWERLEVEL9K_VCS_GIT_ICON='\uf296'
  else
    POWERLEVEL9K_VCS_GIT_ICON='\uf1d3 '
  fi
}
```
this allow me to have Github where origin point to gibhub, or bitbucket icon when origin point to bitbucket. But has the drawback that it doesn't change dynamically as we change to another repo unless we open a new terminal to refresh icon value.

Could we have this included in a better way in the main stream?

Thanks in advance for such a good project

**Comment by dritter** [comment]
@davidmpaz Cool Idea! 👍 

I think the best place would be in `functions/vcs.zsh` in `+vi-vcs-detect-changes()`. There we determine the right icon:
```zsh
  if [[ "${hook_com[vcs]}" == "git" ]]; then
    vcs_visual_identifier='VCS_GIT_ICON'
  elif [[ "${hook_com[vcs]}" == "hg" ]]; then
    vcs_visual_identifier='VCS_HG_ICON'
  elif [[ "${hook_com[vcs]}" == "svn" ]]; then
    vcs_visual_identifier='VCS_SVN_ICON'
  fi
```
The icon definitions should go into `functions/icons.zsh`.

Would you mind creating a pull request againt `next` branch for that? That would be awesome!

**Comment by bhilburn** [comment]
Agreed with @dritter! This sounds great.

Please submit a PR against `next`! Remember that you'll need to create font points even for non-awesome configurations - make sure to leave them as `VCS_GIT_ICON` so that current configurations aren't broken.

**Comment by davidmpaz** [comment]
Hi @dritter for sure!

Thanks for checking this out. I will update referenced files and add new icons definitions as explained, as soon as possible.

Cheers

**Comment by davidmpaz** [comment]
Hi,

i think I can close this now. Thanks again!
Cheers
