### ISSUE TITLE
Character duplicate when press tab

### ISSUE THREAD

**Issue by zhengnanlee** [bhilburn/powerlevel9k#364]
When I press tab, the first character in current command line will duplicate, and will not disappear till I press <Enter>.  I am using iTerm, and please tell me if you want any further detailed configuration.

**Comment by zhengnanlee** [comment]
<img width="1009" alt="screen shot 2016-12-18 at 15 45 59" src="https://cloud.githubusercontent.com/assets/3368306/21296417/1dd7ddfa-c539-11e6-8d7e-36167249b093.png">

**Comment by dritter** [comment]
Seems like the calculation of columns is not right somehow. Before we go in detail with your configuration, could you try to disable the prompt "mark" in your iTerm settings (should be under Profiles/Terminal/Shell Integration/Show mark indicators), and see if that helps?

**Comment by zhengnanlee** [comment]
Hi dritter, it doesn't work....

**Comment by dritter** [comment]
Too bad. Could you post your `~/.zshrc`?

**Comment by zhengnanlee** [comment]
Hi, please check http://paste.ubuntu.com/23650204/

**Comment by dritter** [comment]
Okay. Could you comment the following line `ZLE_RPROMPT_INDENT=0`. This always causes such errors. ;)

**Comment by dritter** [comment]
Btw. This will cause a gap at the right border. The common "fix" for that is setting the right indent to zero (as you did), but this has some side effects (like the one you observed). Unfortunately there is no good fix around for that. At least not that I know besides calculating the columns manually (which is a bigger issue)..

**Comment by zhengnanlee** [comment]
Hi dritter, thanks so much for your advice. Now it is normal, thanks again.

**Comment by bhilburn** [comment]
Nice work, @dritter! Happy you are up and running, @zhengnanlee!
