### ISSUE TITLE
Improve `battery` segment

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#373]
@rjorgenson I found in #344 some inconsistencies (harsh word, this is a mere suggestion) in the `battery` segment. These come from mixing up capacity-values ("low") and status information ("charging", "charged", "disconnected"). 

My suggestion is to clear that up by changing the color only at certain capacity thresholds, like the "low" one now. And to add some more thresholds for "medium" and "high".
The status information could be indicated by an icon (similar to the "incoming" and "outgoing" feature of the `vcs` segment.

This suggestion could be pivoted, so that capacity values could be indicated by icons and status information control the colors..

I came up with this idea while writing [tests](https://github.com/dritter/powerlevel9k/blob/63d48e726046640613e71be6b55476c110cfc4ba/test/segments/battery.spec) for that segment..

What do you think? Is this a bad idea?

**Comment by rjorgenson** [comment]
Hmm, I guess I never really thought of the 'low' warning as a strict capacity value, and as more of a status warning. More-so since it's a configurable threshold. I don't particularly like the idea of indicating charge levels at various capacities because such things are generally vague and mostly without meaning. Especially when it says exactly what the charge capacity is right next to that. Though I could see that being useful if all someone didn't want the text output(percentage and time remaining). I think multiple icons might start to get confusing though, what icons did you have in mind?

**Comment by dritter** [comment]
My thoughts were just that we have two classes of values, and one (the more important one) of them should be responsible for changing the background color. For me that is the capacity. I agree these values are vague, but still valuable ;)

For 'charging' and 'discharging' I had in mind an up and a down arrow, or maybe plus and minus (maybe doubled).
 
![bildschirmfoto 2017-01-10 um 20 49 50](https://cloud.githubusercontent.com/assets/1544760/21822173/775fd05e-d776-11e6-9396-548f5f11a9f2.png)
![bildschirmfoto 2017-01-10 um 20 50 11](https://cloud.githubusercontent.com/assets/1544760/21822179/7b0fdc94-d776-11e6-950b-033d540f73c7.png)

**Comment by rjorgenson** [comment]
I'm probably the wrong person to have input on that behavior as I'm not a big fan of different background colors on segments lol - If we did move that behavior over and have the capacity control the color I'd still like to maintain a 'critical low' status independent of the capacity behavior. As it's written now I don't really see it as changing colors on capacity, but on battery states. The states are charging, charged, discharging, and critical low - all of which I feel are important independent of the actual current capacity of the battery. Anyone else have any thoughts on this?

**Comment by bhilburn** [comment]
@rjorgenson @dritter - I saw this discussion when it took place 10 days ago, and I've mulled over a bit since then. To me, I would prefer that any color changes are dependent upon the status (charging / discharging / etc.,) rather than charge level alone. If I'm at a low battery level, but am plugged in & charging, a "battery warning color" state would annoy me. What I care about is:

1) Am I at a low charge level and discharging
2) Am I discharging (battery level okay)
3) Am I charging
4) Am I charged

It looks like the existing code covers these scenarios. I do like @dritter's suggestions of icon changes, though, as that would also limit the color changes of the segment. I prefer the double `++` and `--` suggestions.

Something like:

state|icon|color
------|-----|--------
low level & discharging | {battery icon} {warning icon} | red
discharging | {battery icon} `--` | blue
charging | {battery icon} `++` | blue
charged | {battery full icon} | green

But, this could also make it _way_ too busy. Probably can't say definitively without mocking it up, honestly.

**Comment by dritter** [comment]
Interesting. I started this discussion coming from the other direction. While writing the tests for this segment, I found it strange that connecting/disconnecting power supply changes the color.
Consider the following tests:
```zsh

function testBatterySegmentIfBatteryIsAlmostFullWhileDischargingOnOSX() {
  OS='OSX'
  makeBatterySay "Now drawing from 'Battery Power'
 -InternalBattery-0 (id=1234567)	98%; discharging; 3:57 remaining present: true"

  prompt_battery "left" "1" "false" "${FOLDER}"
  p9k_build_prompt_from_cache 0

  assertEquals "%K{black} %F{white%}🔋%f %F{white}98%% (3:57) %k%F{black}%f " "${PROMPT}"
}

function testBatterySegmentIfBatteryIsAlmostFullWhileChargingOnOSX() {
  OS='OSX'
  makeBatterySay "Now drawing from 'Battery Power'
 -InternalBattery-0 (id=1234567)	98%; charging; 3:57 remaining present: true"

  prompt_battery "left" "1" "false" "${FOLDER}"
  p9k_build_prompt_from_cache 0

  assertEquals "%K{black} %F{yellow%}🔋%f %F{yellow}98%% (3:57) %k%F{black}%f " "${PROMPT}"
}
```
The only different is mocking power supply/disconnecting.
What is odd to me, that yellow always has a "warning" connotation. But on 98% there isn't IMHO anything to warn about. Connected or not..

**Comment by rjorgenson** [comment]
When I originally chose the colors to indicate each state, I tried replicating what showed up on my power adapter(green = charged, orange = charging, and no light when unplugged). The LED glows orange when charging, and yellow was the closest color in the 16 default colors so I went with that. I can understand how that might be confusing for someone not used to an Apple power connector. If we were to stick with having the color indicate state, what colors would you suggest? As with @bhilburn I don't really care about the capacity of my battery at a quick glance unless it's critical. Maybe we could change the name of the low state to critical or something along those lines to be more clear about it's purpose?

**Comment by dritter** [comment]
@rjorgenson Well, that explains a lot. 😄  I have a mac, but never associated the battery segment with the power plug. And thinking about it, the power plug tells a different story than the battery segment. The power plug can differentiate between the loading states, but the battery segment tells me something about the capacity..

**Comment by rjorgenson** [comment]
Yeah, it wasn't meant to replicate the power adapter, but to replicate the battery menu item in OS X. It can do much fancier things with it's icon than I was able to in text without ramping up font size ridiculously high, and I wanted to keep it nice and compact so I decided to use colors to indicate state, and the colors that seemed most appropriate were the colors already used to indicate state on the power adapter =]

This idea is much older than the segment, I initially wrote a 'geeklet' in 2008 when I got an  11" MacBook Air and wanted to remove as much from the menu bar as possible but still keep things compact. Perhaps the use case for my reasonings is no longer that valid =]

**Comment by bhilburn** [comment]
@dritter @rjorgenson - Great discussion! Thanks for sharing your opinions!

So, setting aside what the battery segment *currently* does, what are your ideal scenarios in terms of state / icons / color? Can you put together a table to lay it out? I think I'm having trouble following the suggestions, at this point.

**Comment by dritter** [comment]
For me it would be:

|               | cable plugged | cable unplugged |
|---------|---------------|------------------|
| empty   | background red, icons "++" | background red, icons "--" |
| half full | background yellow, icons "++" | background yellow, icons "--" |
| full        | background green | background green, icons "--" |

Maybe with a critical level (but then the colors above should be foreground colors, and the critical level changes it to background color red).

Thresholds and icons are to be discussed.

**Comment by rjorgenson** [comment]
Personally I still don't like the idea of indicating capacity with colors, but I wouldn't want to block changes based on my bias if that's the way people want to go with it. If that is the way people want it done I think @dritter's table makes sense. I also suggest a state-based foreground and background color so the user can customize the colors in case green/yellow/red doesn't really fit with their prompt colors. As far as icons go I don't initially see anything better than the + and - inside a circle, though I'm not sure having more than one icon in a segment is ideal. In every other state there is one icon and it indicates what data is displayed in the segment and not any particular data within the segment(with the exception of the recent changes to the dir segment). All that said I prefer how it is now, but again I am definitely biased in that regard =]

**Comment by dritter** [comment]
>  I wouldn't want to block changes based on my bias if that's the way people want to go with it.

Same applies to me and changing something just for the changes sake. Nobody except me seems to be confused by how the battery segment works now. At least I didn't hear any complaints.. So, maybe we should leave it like it is and wait for some other folks to raise their voices..

Btw. + / - in a circle is an excellent idea!
Hmm. I might be blind, but I just find the full icons (not the open ones) `$'\uE168'` / `$'\uE169'`:
![bildschirmfoto 2017-03-07 um 23 58 08](https://cloud.githubusercontent.com/assets/1544760/23682058/286dd4bc-0392-11e7-9435-4077998de5e0.png)


Just stumbled upon:
`$'\uE86B'` / `$'\uE86C'` (patched mode)
![bildschirmfoto 2017-03-07 um 23 54 22](https://cloud.githubusercontent.com/assets/1544760/23681962/96c1fffc-0391-11e7-97c0-343e91bb0569.png)

**Comment by rjorgenson** [comment]
Yeah those were the icons I was referring to, I don't have the open circle ones in my patched font either. The square ones are better, I didn't catch those ones =]

**Comment by bhilburn** [comment]
I wonder if the best solution, here, might be to provide something that's heavily customizable using our usual state structure, but have the default be really, really simple. Example:

Default:
|               | cable plugged | cable unplugged |
|---------|---------------|------------------|
| critical   | no color, icon "+" | background red, icon "-" |
| half full | no color, icon "+" | no color, icon "-" |
| full        | no color | no color, icons"-" |

As long as the levels for what constitutes `critical`, `half-full`, and `full` were customizable, and we enabled our usual modification of FG / BG color and icons, this is a fairly non-obnoxious default as it only really blares at you if you are critical and aren't charging.

With this structure, folks that want more information, like @dritter, could easily configure something more complex, like this:

|               | cable plugged | cable unplugged |
|---------|---------------|------------------|
| critical   | background red, icons "++" | background red, icons "--" |
| half full | background yellow, icons "++" | background yellow, icons "--" |
| full        | background green | background green, icons "--" |

Thoughts?

**Comment by dritter** [comment]
For me it looks good :)
Only thing I would consider is using a more colorful version by default. IMHO the battery segment is a quite important one and more people would want to have it more colorful and the other way is still possible (to configure the segment more grayscale).

**Comment by onaforeignshore** [comment]
While on the topic, Nerd fonts support 5 icons for battery, from full to empty.

Nerd Icons: \uF240  \uF241  \uF242  \uF243  \uF244

Would it be possible to make the icon change to reflect the charge level?

**Comment by dritter** [comment]
Finally a different voice. 😄 
Well, it would be, if we make this change. And you need to convince @bhilburn to add five states. 😆

**Comment by bhilburn** [comment]
Thanks for hopping in, @onaforeignshore! We definitely appreciate another viewpoint =)

Okay, so the one issue there is that in non-nerdfont configurations, which are the majority of our users, how would we deal with the extra state? I suppose we could just set the same icon for all of them, which would actually be pretty easy.

I can't actually see the icons you used, @onaforeignshore, since Github / Chrome won't render them. Can you screenshot them? What might make sense? States with steps of 25% charge levels (e.g., 0%, 25%, 50%, 75%, 100%)?

**Comment by bhilburn** [comment]
@onaforeignshore is working on this in #476.

**Comment by onaforeignshore** [comment]
Filed PR #498 for this

**Comment by bhilburn** [comment]
#498 has been merged! Thanks, @onaforeignshore, for all of your work, and thanks to @dritter and @rjorgenson for the great discussion in this thread =)
