### ISSUE TITLE
Simplify `disk_usage` conditionals

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#380]
@dritter - Moving the conversation here since I merged the PR.

> Hmm. I was too tired yesterday as well.. Now I am too late, but this control structure should work:
> ```zsh
> local level="${$(df -k . | sed -n '2p' | awk '{ print $5 }')%%\%}"
> 
> # Default state is "normal" unless POWERLEVEL9K_HDD_USAGE_ONLY_WARNING
> # is set to true, then it is "unknown"
> if [[ "$POWERLEVEL9K_HDD_USAGE_ONLY_WARNING" != true ]]; then
>   current_state='normal'
> fi
> 
> if [ "$level" -ge "$POWERLEVEL9K_HDD_USAGE_CRITICAL_LEVEL" ]; then
>   current_state='critical'
> elif [ "$level" -ge "$POWERLEVEL9K_HDD_USAGE_WARNING_LEVEL" ]; then
>   current_state='warning'
> fi
> ```

Not too late! I should have waited for this topic to close out before merging, anyway. My apologies.

Okay, so here is our existing code:
```zsh
  local disk_usage="${$(\df -P . | sed -n '2p' | awk '{ print $5 }')%%\%}"

  if [ "$disk_usage" -ge "$POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL" ]; then
    current_state='warning'
    if [ "$disk_usage" -ge "$POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL" ]; then
        current_state='critical'
    fi
  else
    if [[ "$POWERLEVEL9K_DISK_USAGE_ONLY_WARNING" == true ]]; then
        current_state=''
        return
    fi
    current_state='normal'
  fi
```

My goal is to minimize evaluations for the most frequent code paths (gotta keep things speedy!). Here is how the two options compare as I read them:

code path|# evals current|# evals new|
-------------|--------------------|---------------|
below warning|2|3|
above warning|2|3|
above critical|2|2|

Thoughts, @dritter? I don't care for the current code because it's difficult to follow, but I'm having trouble figuring out how to simplify it while also keeping the comparison count low.

**Comment by dritter** [comment]
Well, we are talking here about a difference of one check in memory, no disk/network IO involved. I did a quick performance measurement. The following script runs in `0,81s` on my machine:
```zsh
#!/usr/bin/env zsh

local threshold=50000

for i in $(seq 1 100000); do
  if [ $i -ge $threshold ]; then
    # Do nothing; we just want to measure the condition.
  fi
done
```

So, I would go totally for readability in this case..

**Comment by bhilburn** [comment]
Agreed with you, @dritter. I'll make the changes and merge =)

**Comment by dritter** [comment]
Is this change already on next? Can't spot it anywhere...
