### ISSUE TITLE
Segment outer arrow miscoloring in Terminal.app

### ISSUE THREAD

**Issue by akrueger** [bhilburn/powerlevel9k#381]
I'm on **macOS 10.12.2** using **Terminal.app** and the arrow portion of the segment is coloring differently than the rest of it. I do not have the same problem in **iTerm2** however. It only seems to happen on the outermost arrow of both the left and right prompt. The inner arrow seems to behave as expected.

Any insights into why this may be happening?

(Terminal.app on top, iTerm2 on bottom)

<img width="634" alt="screen shot 2017-01-22 at 23 19 13" src="https://cloud.githubusercontent.com/assets/1644520/22192407/810c409c-e0f9-11e6-9eae-2a3cefb9588d.png">

**Comment by bhilburn** [comment]
Hey @akrueger - 

Yeah, this has been a problem in `Terminal.app` for as long as we know. Check out this bit in the Troubleshooting guide written 2 years ago on it: https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#segment-separators-are-wrong-color

I don't think anyone knows of a solution for making `Terminal.app` work properly, unfortunately. I'll let some of the OSX users I know comment, though, in case something has changed?

@dritter @rjorgenson

**Comment by rjorgenson** [comment]
I can't remember the last time I used Terminal.app on one of my personal machines, but I just tried it out and I have the same problem.

**Comment by dritter** [comment]
Unfortunately, `Terminal.app` improves the contrast for you. [Here](http://apple.stackexchange.com/a/216159) is a longer explanation.
I played with the settings, and sometimes it looked like it worked.

**Comment by akrueger** [comment]
Interesting. Well I had gone back to `Terminal.app` from `iTerm2` because after they improved it, it was meeting all my needs and I like to simplify my tooling as much as possible. They are mostly interchangeable for me at this point, so I'll probably just start using iTerm again.

Really interesting read though and I feel more satisfied knowing it isn't a simple setting that I boofed that's keeping me from having the colors uniform. 

Thanks for the help!

**Comment by rjorgenson** [comment]
Just tested that out and after changing the background color away from one of the preset defaults the contrast adjustment went away and the colors rendered as expected.

**Comment by akrueger** [comment]
@rjorgenson Would you mind exporting that profile so I could look at it? I just tried changing the background and had no luck.

**Comment by rjorgenson** [comment]
Sure, here's a screenshot.

![screen shot 2017-01-23 at 2 15 12 pm](https://cloud.githubusercontent.com/assets/44096/22222997/6a56dcb8-e176-11e6-8949-2e9a1f7f0196.png)

and here's the export.

[Pro 1.terminal.zip](https://github.com/bhilburn/powerlevel9k/files/724972/Pro.1.terminal.zip)

**Comment by rjorgenson** [comment]
For what it's worth, I am on Sierra 10.12.2 - The link above mentioned it was changed on newer versions of Terminal, but it was also posted November 2015. So unless you're on a really old version of OS X it should be the same for you.

**Comment by akrueger** [comment]
Hrrmmm. I'm on the same OS version. I just imported it and the only thing I changed was adding a powerline font (Roboto), but still no dice for me.

<img width="1280" alt="screen shot 2017-01-23 at 15 25 12" src="https://cloud.githubusercontent.com/assets/1644520/22223376/53ac68a2-e180-11e6-8dc7-dd98b700884c.png">

**Comment by rjorgenson** [comment]
Hmm, I tried changing the color of one of my segments and I did get the same behavior as you =/ My default must just be dark enough that I can't really see a difference between them.

**Comment by bhilburn** [comment]
@akrueger - I agree that it's a bummer the default macOS `Terminal.app` can't handle the segment boundaries properly. I'm also a fan of simplified toolflows, and requiring the use of iTerm2 isn't ideal.

Is there anything else you'd like to address in this bug report? Otherwise I'd like to close it out.

**Comment by akrueger** [comment]
@bhilburn No, I think we've got good documentation of the issue even if we don't have a solution. I'm happy using iTerm2. If it ends up working in future macOS versions I may revisit. Feel free to close.

Thanks

**Comment by bhilburn** [comment]
👍
