### ISSUE TITLE
Hiding the branch icon does not seem to work

### ISSUE THREAD

**Issue by fikovnik** [bhilburn/powerlevel9k#383]
Despite setting `POWERLEVEL9K_HIDE_BRANCH_ICON=true` in my `.zshrc` I still see the icon. The other options such as `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` work just fine.
I'm using prezto.

**Comment by dritter** [comment]
Hmm. Did you set that variable before initializing prezto? So, before:
```zsh
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
```
Or (as prezto suggests) directly in `.zpreztorc` (that should work)?

**Comment by fikovnik** [comment]
Thanks! Putting it to `.zpreztorc` worked!

**Comment by dritter** [comment]
Cool! And sorry for the inconvenience. There are some variables that need to be set before the theme is sourced. `POWERLEVEL9K_HIDE_BRANCH_ICON` is one of them..

**Comment by fikovnik** [comment]
I though that might be it! Thanks for quick help (and awesome powerline!)
