### ISSUE TITLE
Replace IP address with icon if none is found

### ISSUE THREAD

**Issue by akrueger** [bhilburn/powerlevel9k#384]
I like to have the IP address showing when I'm connected, but it's also valuable for me to see when I've lost a connection.

I don't find the default`NETWORK_ICON` especially helpful except if it were distinguishing wi-fi from ethernet for example (I thought this was the case, but it didn't seem to switch when I went to ethernet).

I was wondering if there was an easy way for me to customize displaying the `POWERLEVEL9K_FAIL_ICON` when no IP is found and simply displaying the IP when it is.

I have found that I can disable the `NETWORK_ICON` by setting it to `''`, but then I just get a blank segment for my IP when I'm not connected.

I saw the `prompt_ip` function in `powerlevel9k.zsh-theme`, but didn't think it was wise to edit that directly in the case of updates, etc.

Thanks

**Comment by rjorgenson** [comment]
I have this functionality in the recent public_ip segment that I wrote by allowing you to set a POWERLEVEL9K_PUBLIC_IP_NONE variable to display when there is no IP, perhaps that logic can be implemented in the internal IP segment as well?

**Comment by akrueger** [comment]
@rjorgenson I didn't find any of those in the repo, or in yours. Where can I find that implementation for the public ip? Thanks

**Comment by rjorgenson** [comment]
@akrueger it's in the next branch here.

**Comment by akrueger** [comment]
@rjorgenson ah, I see it now, thanks!

I can't say I follow the implementation perfectly (not much of a shell scripter), but the documentation is quite clear. Is `POWERLEVEL9K_PUBLIC_IP_NONE` able to be set to `FAIL_ICON` or does it dynamically change? 

It would be great if I had both internal and public IPs and when either or none were resolving it would go to `FAIL_ICON`

**Comment by rjorgenson** [comment]
@akrueger That variable can be set to anything, but you'd need to reference fail icon with it's actual code point, rather than `FAIL_ICON` as that's just what p9k uses to reference that icon in the icons array =]

**Comment by akrueger** [comment]
Ok, do you have any notion of when the next release might be? I'm actually more interested in the public IP for VPN purposes. I may end up doing both, but screen real estate is valuable, so perhaps I'll just wait for your inclusion in the next release.

**Comment by rjorgenson** [comment]
I do not =/ But you can follow the progress here - https://github.com/bhilburn/powerlevel9k/projects/1

**Comment by akrueger** [comment]
Thanks! I'll keep my eye on it

**Comment by bhilburn** [comment]
@akrueger - I'm trying to get the release out as soon as I can. Just a matter of working through the last few items. If you want to help, we are always looking for more devs! ;) #371
