### ISSUE TITLE
Installation of fonts.

### ISSUE THREAD

**Issue by bweston92** [bhilburn/powerlevel9k#39]
I've installed the fonts but my terminal looks like this. (I'm using `compatible` but it is not very compatible)

![image](https://cloud.githubusercontent.com/assets/1764057/8249495/adb47320-1662-11e5-8dff-bb3a4f34ff06.png)

**Comment by bhilburn** [comment]
Thanks for the bug report, @bweston92! 

Few questions:
1. Do you see the Powerline fonts in your OS's font manager?
2. Now that you have installed the Powerline Patched fonts, have you set your terminal's default font to one of those?

**Comment by dritter** [comment]
Unfortunately `compatible` mode still needs a compatible font.. So it should be capable of displaying glyphs like \uE0B0 to display the segment separators. Some fonts have them, others don't.. See issue #32 for more infos.

**Comment by bweston92** [comment]
@dritter How do you tell the terminal which fonts to use?

**Comment by dritter** [comment]
@bweston92 I have no Computer ATM, but it should be somewhere in the preferences of your terminal app. Maybe this link helps you:http://askubuntu.com/questions/384551/mac-os-x-terminal-clone-for-ubuntu

**Comment by bhilburn** [comment]
Hey @bweston92 - Any luck? This bug doesn't seem like an issue with the theme, so I'm going to go ahead and close it. 

I am somewhat confused by your initial question - if you have installed the patched fonts, you shouldn't need to use the `compatible` mode. You just need to select one of the Powerline-patched fonts in your terminal.

You can continue commenting after this bug has been closed, and we will try to help you as best we can!

**Comment by bweston92** [comment]
Yes I've managed to do it, thanks.

**Comment by bhilburn** [comment]
@bweston92 - Good to hear! Thanks for following-up!
