### ISSUE TITLE
Custom context colours?

### ISSUE THREAD

**Issue by Hebgbs** [bhilburn/powerlevel9k#392]
I don't know how to modify the colour of the context. I've managed to do everything else using external and internal information but the context colour eludes me.

Fill in the blank and gimme a hand; 
`POWERLEVEL9K_`___________________`_FOREGROUND`

**Comment by Hebgbs** [comment]
I'm still keeping this issue opened in the hopes a more elegant solution comes about, but I just copied the bit from 438-447 of `powerlevel9k.zsh-theme`. Until then putting this in my `.zshrc` worked (default values kept for example);
`prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    if [[ $(print -P "%#") == '#' ]]; then
      # Shell runs as root
      "$1_prompt_segment" "$0_ROOT" "$2" "$DEFAULT_COLOR" "yellow" "$USER@%m"
    else
      "$1_prompt_segment" "$0_DEFAULT" "$2" "$DEFAULT_COLOR" "011" "$USER@%m"
    fi
  fi
}`

Change yellow and 011 to whatever colour codes you wish and changes will be applied upon reload.

**Comment by rjorgenson** [comment]
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND

**Comment by Hebgbs** [comment]
I had the right words, but the wrong order I think. Almost had it with shots in the dark. Thanks for the solution.

**Comment by rjorgenson** [comment]
No problem =]

**Comment by dritter** [comment]
Btw. this is a stateful segment, you can learn more about these segments [here](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).
