### ISSUE TITLE
Show off the icons

### ISSUE THREAD

**Issue by allanbarbosa** [bhilburn/powerlevel9k#396]
Hello everyone, i'm with a little problem.

I install the PowerLevel9k mode for Oh My Zsh and the icons on prompt don't show off.

In below a send a screenshoot

![screen shot 2017-02-01 at 11 15 54](https://cloud.githubusercontent.com/assets/3648093/22510240/fb1d351c-e86f-11e6-99f5-863d79c76e9b.png)

And here are my .zshrc configuration.

![screen shot 2017-02-01 at 11 17 53](https://cloud.githubusercontent.com/assets/3648093/22510262/18074262-e870-11e6-9425-5e87f4e50a2c.png)

I would like to know what's going on?

Thank you so much.

**Comment by dritter** [comment]
It seems like you have set a powerline font in your Terminal Emulator, but not an awesome-patched one. Could you double-check that?

**Comment by allanbarbosa** [comment]
You say that the preferences on iTerm on Profiles is incorrect?

**Comment by dritter** [comment]
Yes. Could you post a screenshot of your selected fonts there?

**Comment by allanbarbosa** [comment]
![screen shot 2017-02-01 at 15 28 21](https://cloud.githubusercontent.com/assets/3648093/22520460/1ee8fb98-e893-11e6-90be-c37101ac3fb8.png)

there.

**Comment by dritter** [comment]
Yep. That's the wrong font. For `awesome-patched` mode you'll need one of [these](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched).

**Comment by allanbarbosa** [comment]
It's work, thanks a lot.

**Comment by dritter** [comment]
Cool! Have fun with the theme :)
