### ISSUE TITLE
Custom glyphs not appearing

### ISSUE THREAD

**Issue by ixodie** [bhilburn/powerlevel9k#397]
Hi,

I ran the instructions on OSX and installed the Adobe Source Code TTFs.

I see that the virtualenv glyph is working properly but the other glyphs are showing up as ?.

Anyone have an idea what I might be doing wrong?

<img width="316" alt="screen shot 2017-02-01 at 7 46 20 pm" src="https://cloud.githubusercontent.com/assets/2715976/22532755/39da52f2-e8b7-11e6-9584-1a1dd412a22c.png">

**Comment by dritter** [comment]
Hi @ixodie !

Which `POWERLEVEL9K_MODE` do you use? You may have configured the wrong font in your terminal emulator..

**Comment by ixodie** [comment]
I have:

POWERLEVEL9K_MODE='awesome-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"

And I use iterm2 in OSX with default font for the profile being Source Code Pro 12pt

Any ideas what I am doing wrong?

**Comment by dritter** [comment]
@ixodie I don't know much about fontconfig, but I think it should work if you installed [awesome-terminal-fonts correctly](https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X). Could you double-check that? I am not sure about which font you need to configure as non-Ascii-Font in iTerm2 (if that matters at all).

**Comment by ixodie** [comment]
I did install those fonts, as well as a lot of other ones suggested.

<img width="784" alt="screen shot 2017-02-05 at 2 42 57 pm" src="https://cloud.githubusercontent.com/assets/2715976/22629313/9a785832-ebb1-11e6-80dc-caafab55ab95.png">

**Comment by dritter** [comment]
Maybe you need to update your font cache: `fc-cache -f -r -v`.
From the help:
```
  -f, --force              scan directories with apparently valid caches
  -r, --really-force       erase all existing caches, then rescan
  -v, --verbose            display status information while busy
```

**Comment by ixodie** [comment]
I'm doing this on OSX and I cleared the font cache and it still doesn't work.

**Comment by dritter** [comment]
Hmm. Maybe someone with more experience with fontconfig than me can help.

**Comment by ixodie** [comment]
Thanks.

To be clear, the virtualenv python icon works, as do the side arrows and the status green check, but nothing else is working.

This is what I have now:
POWERLEVEL9K_MODE="awesome-patched" (have changed this back and forth with no effect)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history)
POWERLEVEL9K_DIR_FOREGROUND="white"
POWERLEVEL9K_RBENV_FOREGROUND="white"

ZSH_THEME="powerlevel9k/powerlevel9k"

And the DIR_FOREGROUND doesn't work either.

**Comment by dritter** [comment]
So, what you are saying is, that changing the colors for the `dir` and `rbenv` segment does not work, right?
The `dir` segment is a stateful one. The color overriding works differently there. You could read more about that in the [wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors).
Changing the color for the `rbenv` segment does not work, because you have not configured the segment at all.

**Comment by ixodie** [comment]
OK, that helped resolve that issue.  I am now able to get the colors working on the DIR segment.

But still no icons, except the python one.

Also, it seems that the dir_default doesn't work properly:

POWERLEVEL9K_MODE="awesome-patched"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history)
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"

![screen shot 2017-02-07 at 3 05 33 pm](https://cloud.githubusercontent.com/assets/2715976/22709207/008b9968-ed47-11e6-8485-49c8de673ba5.png)

**Comment by dritter** [comment]
Great! Now we are getting somewhere! :)
Okay. For `awesome-patched` mode you need to install and configure one of [these](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched) pre-patched fonts.

**Comment by ixodie** [comment]
Yes I downloaded that font, and double clicked on it, and some window flashes quickly and then disappears and the font book says the font is already installed.

So in iterm2 I have this:
![screen shot 2017-02-07 at 3 22 29 pm](https://cloud.githubusercontent.com/assets/2715976/22710244/92ceb14a-ed4a-11e6-918c-f5d7fd6542e3.png)

**Comment by dritter** [comment]
That font you selected just includes Powerline symbols, but not the `awesome-terminal-font` symbols.
This is my configuration:
![bildschirmfoto 2017-02-07 um 21 50 23](https://cloud.githubusercontent.com/assets/1544760/22710920/79d718a0-ed7f-11e6-9c51-13be6ecf14bd.png)

**Comment by ixodie** [comment]
So I assume that that is a single font, which for some reason I do not have.

![screen shot 2017-02-07 at 3 52 40 pm](https://cloud.githubusercontent.com/assets/2715976/22711013/95ef8d60-ed4d-11e6-954b-182763747ab6.png)

**Comment by dritter** [comment]
Could you uninstall that font, and double-click the awesome one again? I think it is not properly installed..

**Comment by ixodie** [comment]
Aha!  That was the problem.  I am seeing the proper font in the list now.

I still can't get the non-home dir foreground to white.

**Comment by rjorgenson** [comment]
@ixodie you'll need to set POWERLEVEL9K_HOME_SUBFOLDER_FOREGROUND to have a color while in a subdirectory of your home directory. DEFAULT handles everything outside of your home directory.

**Comment by ixodie** [comment]
Are you sure?  I tried POWERLEVEL9K_HOME_SUBFOLDER_FOREGROUND and it didn't do anything.

**Comment by dritter** [comment]
The `dir` segment has three states:
1. Directly inside home folder (HOME)
2. Somewhere inside a subfolder of home (HOME_SUBFOLDER)
3. Anywhere else (DEFAULT)

**Comment by ixodie** [comment]
Ahh, got it, need POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND

**Comment by bhilburn** [comment]
Thanks, @dritter and @rjorgenson for providing excellent support to @ixodie! Glad you're all up and running :)
