### ISSUE TITLE
Gitter is being stupid for me

### ISSUE THREAD

**Issue by Hebgbs** [bhilburn/powerlevel9k#399]
Just making this issue to see if anybody else is having a problem with using the service, and to open discussion for chat relocation.

**Comment by dritter** [comment]
Could you go more into detail what does not work for you? If that is a bug in Gitter, consider to file an issue there: https://github.com/gitterHQ/gitter

For me the Gitter works well.

**Comment by bhilburn** [comment]
@Hebgbs - Are you still having issues? It looks like you were able to get support from @dritter on Gitter a couple of days ago, and I just responded to your PMs, there.

**Comment by shibumi** [comment]
I am not a big fan of gitter. I would prefer an IRC channel, but I have no problem with gitter when everybody relies on it :)

**Comment by dritter** [comment]
I'm not attached to gitter. I just like that it is webbased. No need to install additional software is a big plus, IMHO.

**Comment by bhilburn** [comment]
I also use IRC regularly. The primary issue with it is that it is not easily accessible if you aren't already familiar with it / involved in the open-source world. As one of the goals for P9k is to be approachable by new users (for example, OSX users just discovering open source projects), I don't want to shut them out.

@shibumi - Have you given this a shot? I wonder how well it works: https://irc.gitter.im/

**Comment by bhilburn** [comment]
The other option that I might consider is Slack (which has an IRC gateway). The issue with Slack, though, is that you have to be "invited" to join the team - I don't think there is a way to just say "anyone can join", which is a huge advantage of Gitter.
