### ISSUE TITLE
Symbols only appear when after theme is reloaded

### ISSUE THREAD

**Issue by bobbybroadcast** [bhilburn/powerlevel9k#401]
Symbols only show up after reloading. 
ex:
<img width="1018" alt="screen shot 2017-02-10 at 12 13 51 am" src="https://cloud.githubusercontent.com/assets/13399612/22819192/d864e206-ef25-11e6-85c9-b60cdc12c054.png">

This was the case with OMZ, same with zgen and everything else I've tried.

**Comment by bobbybroadcast** [comment]
Note that you should define any customizations at the top of your `.zshrc` (i.e. setting the `POWERLEVEL9K_*` variables) in your `.zshrc`

**Comment by dritter** [comment]
Hi @bobbybroadcast !

Yes, you are right. Some configurations must be set before the theme is actually called. We did this mostly because of performance reasons. But as this is a constant point of misunderstanding, we changed this in #344 . But it will take some time until this is in master.
