### ISSUE TITLE
patched font not loading for os_icon

### ISSUE THREAD

**Issue by Steven-Harris** [bhilburn/powerlevel9k#405]
Sorry, if this is a duplicate issue. I have looked all over for a solution to this issue. 

For some reason the os_icon is not loading in my shell. Instead it just  shows "Lx". I have tested that all my patched fonts are installed correctly. Running, `echo "\uE271"` results in the the icon I am looking for so I don't know why it is not loading in my shell 
![screenshot from 2017-02-15 23-30-28](https://cloud.githubusercontent.com/assets/7720242/23008668/c6810b4a-f3d6-11e6-872e-b606744ff69e.png)

**Comment by dritter** [comment]
Hi @Steven-Harris 

Please make sure, that you set `POWERLEVEL9K_MODE="awesome-patched"` at the **top** of your `~/.zshrc`.

**Comment by Steven-Harris** [comment]
Ok, does order matter? I have my powerlevel configs at the bottom.

**Comment by Steven-Harris** [comment]
Thanks, @dritter. I see now that order does matter!
