### ISSUE TITLE
Hide Branch Icon Doesn't Work

### ISSUE THREAD

**Issue by alock** [bhilburn/powerlevel9k#406]
I have `POWERLEVEL9K_HIDE_BRANCH_ICON=true` set in my .zshrc and it doesn't seem to work.

**Comment by bhilburn** [comment]
@alock - Thanks for the bug report! I'll have a look at that flag.

In the meantime, you should be able to achieve the same result by customizing the branch icon to make it empty. 

Wiki instructions here: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#icon-customization

```
POWERLEVEL9K_VCS_BRANCH_ICON=''
```

**Comment by bhilburn** [comment]
I haven't been able to reproduce this one. @alock - Can you grab the latest release and test again?

**Comment by alock** [comment]
I can still replicate, but I am fine with the work-around you provided.

<img width="600" alt="screen shot 2017-03-09 at 5 38 06 pm" src="https://cloud.githubusercontent.com/assets/6048048/23778491/5c292f78-04ef-11e7-9634-c29fb54374a7.png">

**Comment by bhilburn** [comment]
@dritter - can you test this? I was unable to reproduce

**Comment by dritter** [comment]
Looking at the code, it seems that `POWERLEVEL9K_HIDE_BRANCH_ICON` is a top-level variable like `POWERLEVEL9K_MODE`..

@alock Could you try to move that variable to the top of your `~/.zshrc` and see if that works?

**Comment by alock** [comment]
```#THEME
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
#POWERLEVEL9K_VCS_BRANCH_ICON=''
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
 ```
Ordering didn't change anything (below is what is set) but it might have something to do with my zgen configuration.  Creating a new shell brings the icon back, but when I source `~/.zshrc` it works.

<img width="594" alt="screen shot 2017-03-14 at 4 49 53 pm" src="https://cloud.githubusercontent.com/assets/6048048/23927351/6dacccb0-08d6-11e7-93b3-a2bb9d8f38ed.png">

**Comment by dritter** [comment]
Could you make sure, that your P9K configuration stands before that line: `source "${HOME}/.zgen/zgen.zsh"`?

**Comment by alock** [comment]
Thanks that worked I did not realize it had to be above the `"${HOME}/.zgen/zgen.zsh"`
