### ISSUE TITLE
[dir] Change colors of directory prompt

### ISSUE THREAD

**Issue by samupl** [bhilburn/powerlevel9k#407]
Hi, is it possible to change the directory prompt color font? I'm trying to do it according to the documentation, but without success:

![Dir colors](http://i.imgur.com/nZwMTe4.png)

**Comment by samupl** [comment]
Ok, now I see I didn't read the documentation on states. My mistake.

**Comment by bhilburn** [comment]
No problem! Glad you got it sorted =)

**Comment by drorata** [comment]
I have `POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'` in my `.zshrc`, but the color of the `dir` segment won't change... Why is that?

**Comment by 0brew1** [comment]
@drorata I do not know if this question is still relevant. 
Just a workaround - In order to change the color of the entire 'dir' segment, all values related to 'dir' needs to be set.
POWERLEVEL9K_DIR_HOME_BACKGROUND='123'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='123'
POWERLEVEL9K_DIR_ETC_BACKGROUND='123'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='123'

**Comment by Diaphteiros** [comment]
> @drorata I do not know if this question is still relevant.
> Just a workaround - In order to change the color of the entire 'dir' segment, all values related to 'dir' needs to be set.
> POWERLEVEL9K_DIR_HOME_BACKGROUND='123'
> POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='123'
> POWERLEVEL9K_DIR_ETC_BACKGROUND='123'
> POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='123'

I did this and it resolved my problem of the "dir" segment not changing color. Now it works fine, until I go to `/etc` - then it defaults the color back to blue, although `POWERLEVEL9K_DIR_ETC_BACKGROUND` is set to another color. 

Any idea why this is happening?

**Comment by Diaphteiros** [comment]
@dritter Nevermind, after I booted the mac today, it worked. ;-)
