### ISSUE TITLE
iTerm2: segment arrow incorrectly coloured

### ISSUE THREAD

**Issue by creynders** [bhilburn/powerlevel9k#409]
I seem to have a problem similar to #381, but in iTerm2: the segment separators are all white, except for the outer ones.
Also, the arrows seem to be slightly larger than the segments.

The relevant part of my `.zshrc` file:

```
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time ram dir status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs node_version)
POWERLEVEL9K_STATUS_OK_BACKGROUND="green"
POWERLEVEL9K_STATUS_OK_FOREGROUND="white"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="red"
POWERLEVEL9K_STATUS_OK_FOREGROUND="white"

export DEFAULT_USER="creynder"
ZSH_THEME="powerlevel9k/powerlevel9k"
```

And this is how it looks:

![screen shot 2017-02-20 at 17 33 12](https://cloud.githubusercontent.com/assets/436347/23133804/b48a8c76-f792-11e6-8a22-b3cef051a46a.png)

Using the  iTerm2 Build 3.0.14, with 12pt SourceCodePro+Powerline+Awesome. Same font for non-ASCII characters.
Mac OS X v10.12.3 (Sierra)

**Comment by dritter** [comment]
Hi @creynders !

Could you make sure, that you disable the minimum contrast in the iTerm2 settings? If set it at max (as shown in the screenshot) I get similar results like you.
![bildschirmfoto 2017-02-20 um 23 00 37](https://cloud.githubusercontent.com/assets/1544760/23143271/cb622a16-f7c0-11e6-8dd6-9b67729108fe.png)

**Comment by creynders** [comment]
@dritter thanks, that did the trick! Any idea why the arrows are larger than the segments?

**Comment by dritter** [comment]
@creynders awesome!
Yes, this is usually a problem of a bad patched font. But there is a trick in iTerm2, that you can try. In iTerm2 you can set different fonts for normal text and non-ascii font. The trick is now to select the same font. In the dialog you can tweak the font size for the non-ascii font..
![bildschirmfoto 2017-02-21 um 20 18 16](https://cloud.githubusercontent.com/assets/1544760/23180888/3c8782e2-f873-11e6-8976-82e360e43099.png)

**Comment by dritter** [comment]
Closing this issue for now.
@creynders If this workaround is not sufficient, feel free to reopen the issue.
