### ISSUE TITLE
How to remove yellow coloring when off-host

### ISSUE THREAD

**Issue by colemickens** [bhilburn/powerlevel9k#41]
https://github.com/bhilburn/powerlevel9k/blob/f84a14419400854f84ed70676fe0296de86480f7/powerlevel9k.zsh-theme#L430

I know that that line is relevant. Is there a mechanism to override the yellow color of the foreground text on the left prompt? Or do I have to edit the theme directly?

**Comment by bhilburn** [comment]
Nope, you're right - that one is hard-coded. I'll add an option that lets you override, similar to the configurability of the VCS colors.

Thanks for the request!
