### ISSUE TITLE
iTerm2: segments appearance

### ISSUE THREAD

**Issue by czerwonkabartosz** [bhilburn/powerlevel9k#414]
I have problem with segments padding. It's looks like this
![screen shot 2017-02-24 at 10 34 59](https://cloud.githubusercontent.com/assets/1795926/23298180/ee3fefd2-fa7c-11e6-89c7-ecd7a1922d59.png)

My config:
```
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs node_version)
  POWERLEVEL9K_STATUS_VERBOSE=false
  POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
  POWERLEVEL9K_NODE_VERSION_BACKGROUND='022'
  
  ZSH_THEME="powerlevel9k/powerlevel9k"
```

iTerm version: 3.0.14 

![screen shot 2017-02-24 at 10 36 34](https://cloud.githubusercontent.com/assets/1795926/23298232/23e05460-fa7d-11e6-860c-b4646c8b2eb4.png)

![screen shot 2017-02-24 at 10 44 35](https://cloud.githubusercontent.com/assets/1795926/23298521/4cdf3f7e-fa7e-11e6-9044-5b6200c08897.png)

**Comment by dritter** [comment]
Hi @czerwonkabartosz !

Could you uncheck the box that says "Treat ambiguous-width characters as double width"? That should fix your problem.

**Comment by czerwonkabartosz** [comment]
@dritter Thanks ! Your tip solved this problem
