### ISSUE TITLE
Use memory available instead of free

### ISSUE THREAD

**Issue by Darkheir** [bhilburn/powerlevel9k#415]
Currently the prompt_ram function is getting the free ram. Wouldn't it be better to compute the value using the available value ?

In many unix system the free memory will be close to zero but in fact a lot of ram is still usable by other applications.

See: http://www.linuxatemyram.com/ (The part "How do I see how much free ram I really have?")

**Comment by dritter** [comment]
Hey @Darkheir !

Thanks for that suggestion. Indeed, that would improve the segment greatly! Could you do a PR for that? This would be awesome.

**Comment by Darkheir** [comment]
Okay I will create a pull request. I just have to check how to get this value in :

* Mac OSX (I have one)
* BSD (Don't have one)
* Others Linux distribution (I have one)

**Comment by dritter** [comment]
👍 
Btw. our development branch is `next` (just wanted to let you know, before you need to rebase ;) ).

**Comment by alilotfi** [comment]
@Darkheir 
This is a piece of code I wrote for my (Arch) linux.
```bash
prompt_ram() {
  local ramfree=0
  local ramtotal=0
  ramfree=$(grep -o -E "MemAvailable:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")
  ramtotal=$(grep -o -E "MemTotal:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")
  local rampercent=$(( ramfree * 100 / ramtotal ))

  "$1_prompt_segment" "$0" "$2" "yellow" "$DEFAULT_COLOR" "$rampercent%%" 'RAM_ICON'
}
```

**Comment by Darkheir** [comment]
Thanks, it will help me.

Right now the thing that I can't do is the BSD part:

```bash
 if [[ "$OS" == "OSX" ]]; then
    ramfree=$(vm_stat | grep "Pages free" | grep -o -E '[0-9]+')
    # Convert pages into Bytes
    ramfree=$(( ramfree * 4096 ))
  else
    if [[ "$OS" == "BSD" ]]; then
      ramfree=$(vmstat | grep -E '([0-9]+\w+)+' | awk '{print $5}')
      base='M'
    else
      ramfree=$(grep -o -E "MemFree:\s+[0-9]+" /proc/meminfo | grep -o "[0-9]*")
      base='K'
    fi
fi
```
I will check the documentation for `vmstat` this week-end

**Comment by rjorgenson** [comment]
FWIW here is the output of vmstat on a FreeBSD box I have access to.
```
 procs      memory      page                    disks     faults         cpu
 r b w     avm    fre   flt  re  pi  po    fr  sr da0 da1   in   sy   cs us sy id
 2 0 334  48246M    14G   689   2   0   0   680 511   0   0  287  669  788  0  1 99
```
Here is the output of vmstat | grep -E '([0-9]+\w+)+'
` 0 0 334 49348572  15655920   689   2   0   0   680 511   0   0  287  670  789  0  1 99`

I'm not sure why it's dropping the human readable values when piped through grep. It's output appears to be in kB.

**Comment by Darkheir** [comment]
Hum may be using `vmstat -a`,  I obtain the following:

```
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free  inact active   si   so    bi    bo   in   cs us sy id wa st
 1  0 939840 883000 4259932 9669764    1    2    19   176   23    2 26  7 65  2  0
```

And the total available memory would be: `free + inact`

**Comment by rjorgenson** [comment]
I seem to get the same output wether I use -a or not. The only FreeBSD box I have access to is FreeBSD 8.2 which is quite old. The behavior of vmstat may have changed.
```
#: \vmstat -a
 procs      memory      page                    disks     faults         cpu
 r b w     avm    fre   flt  re  pi  po    fr  sr da0 da1   in   sy   cs us sy id
 0 0 334  48156M    14G   691   2   0   0   684 511   0   0  289  677  792  0  1 99

#: \vmstat
 procs      memory      page                    disks     faults         cpu
 r b w     avm    fre   flt  re  pi  po    fr  sr da0 da1   in   sy   cs us sy id
 0 0 334  48170M    14G   691   2   0   0   684 511   0   0  289  677  792  0  1 99

#: \vmstat -a | grep -E '([0-9]+\w+)+'
 0 0 334 49335776  15070176   691   2   0   0   684 511   0   0  289  677  792  0  1 99

#: \vmstat | grep -E '([0-9]+\w+)+'
 0 0 334 49335776  15070184   691   2   0   0   684 511   0   0  289  677  792  0  1 99
```

**Comment by rjorgenson** [comment]
You could use the top output. I'm not sure how well this would translate to other systems, both linux and OS X seem to have different tops.

```
top -b | grep -E '^Mem:'
Mem: 3116M Active, 25G Inact, 4249M Wired, 470M Cache, 4923M Buf, 14G Free
```

**Comment by Darkheir** [comment]
Yes, that is an alternative. Or do you have the `free` command ?

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15964        8602         781         654        6580        6109
Swap:         16299         917       15382
```

**Comment by rjorgenson** [comment]
No free command on the BSD system I have access to, I can't say wether it's typically available or not though.

**Comment by Darkheir** [comment]
And could you try` dmesg | grep -i mem` ?

In the following page they are giving this alternative: https://www.cyberciti.biz/faq/openbsd-checking-for-ram-memory-size/

**Comment by rjorgenson** [comment]
@Darkheir Sorry I don't have access to an OpenBSD box, the FreeBSD box I have access to also has some locked down permissions, so dmesg doesn't show me very much at all. No memory information.

**Comment by bhilburn** [comment]
@dritter jumped in and made an awesome FreeBSD VM that you can use for testing (see #424), which I just merged into `next`.

Is that the last piece of this you are hammering out before submitting the PR, @Darkheir?

**Comment by bhilburn** [comment]
Merged!
