### ISSUE TITLE
When switching conda environments, the name does not show up

### ISSUE THREAD

**Issue by shangxor** [bhilburn/powerlevel9k#418]
There seems to be an issue with conda environments. From what I have seen in the powerlevel9k.zsh-theme file, there is a  function defined for anaconda.

I have modified the prompt_anaconda() and changed the path as follows:
```
_path=$CONDA_ENV_PATH$CONDA_PREFIX
_path=$CONDA_DEFAULT_ENV
```

The $CONDA_DEFAULT_ENV is empty when using root environment, but after executing ```source activate env-name``` it will contain the the value 'env-name'. This value is prepended to the PROMPT in the following manner: (env-name).

Also the reason I wouldn't use $CONDA_PREFIX is because it returns the full path of the env, not just the basename. This would make the PROMPT 'too long'.

This does not seem to work with powerlevel9k, and the conda env name does not get displayed at the beginning of the PROMPT.

**Comment by dritter** [comment]
Hi @shangxor !

Thanks for the bug report.
Just to get you right, you changed `_path=$CONDA_ENV_PATH$CONDA_PREFIX` to `_path=$CONDA_DEFAULT_ENV` which is an improvement, and should work, but doesn't, right?

The segment does not very much, if `$CONDA_DEFAULT_ENV` gets populated by conda, it should be present at the time the segment is drawn..

Looking at the segment, I think @krischer is the best to answer that question..

**Comment by krischer** [comment]
I'm not sure - it should work. Settings the segment a couple lines later uses `basename $_path` to only select the last portion of the path.

The reason I used `_path=$CONDA_ENV_PATH$CONDA_PREFIX` is that this works across a couple of different conda versions. I'm not sure if the `$CONDA_DEFAULT_ENV` var is set for old conda versions.

Anyway - I see no reason the current code should not work for you. What does `basename $CONDA_PREFIX` return for you? And are you sure your powerlevel settings are correct?

**Comment by shangxor** [comment]
Indeed `basename $CONDA_PREFIX` returns the correct env name. I agree with your rationale on using `_path=$CONDA_ENV_PATH$CONDA_PREFIX`.
The problem is it didn't work out of the box for me. What do you mean by powerlevel settings ? 
The only thing I changed is the default user, to avoid having the full path displayed in the PROMPT. 

<img width="829" alt="screen shot 2017-03-02 at 11 02 21" src="https://cloud.githubusercontent.com/assets/10943905/23502375/f0327908-ff37-11e6-8390-edf01aea524b.png">

**Comment by krischer** [comment]
> What do you mean by powerlevel settings ?

You have to add `anaconda` to the left or right prompt elements: https://github.com/bhilburn/powerlevel9k#customizing-prompt-segments

**Comment by shangxor** [comment]
Oh, sorry for wasting your time with this ticket... 
It works, only problem with it is that it adds a trailing space at beginning of left-hand prompt. And I have just noticed now the trailing space after right-hand prompt, can't stop noticing it now hehehe.

<img width="719" alt="screen shot 2017-03-02 at 15 26 39" src="https://cloud.githubusercontent.com/assets/10943905/23511252/c725040c-ff5c-11e6-96cc-4e78a4732f81.png">

**Comment by dritter** [comment]
Thanks @krischer 

@shangxor Glad that fixed your problem. To provide a little more background information: Some themes show all segments by default. We did not want that, as it will slow down the prompt and provide unwanted information (and every user wants to have his individual prompt). So we decided to go another way and let every user configure his individual prompt. Trade off is that, if you do not want the default configuration, you have to invest some time and set it up like you want..

Regarding the spaces: The first one is odd.. The second one is the same problem as in #420 (I'll answer that shortly).

**Comment by dritter** [comment]
@shangxor regarding the left whitespace: Could you temporarily set `POWERLEVEL9K_PYTHON_ICON="X"` and post a screenshot of that?

**Comment by shangxor** [comment]
Sorry for not replying. I ended up changing fontconfig mode to `awesome-fontconfig` because I noticed that in normal power line-font the `PYTHON_ICON` was just set to ''.
Feel free to close this ticket. Thanks again for the help.

**Comment by dritter** [comment]
Yes, there is no appropriate icon in normal mode. That's why we disable the Python icon..

Glad you got it working.

**Comment by zc-alexfan** [comment]
Hi, 

Sorry for reopening the issue. I tried to add `anaconda` into the prompt elements, but it results in 

~~~
[1]    5067 segmentation fault (core dumped)  zsh      
~~~

Is there any fix of this?

**Comment by romkatv** [comment]
@zc-alexfan What's the output of "echo $ZSH_VERSION"? If it's below 5.7, see if upgrading helps.

**Comment by zc-alexfan** [comment]
Thanks for the info. My Ubuntu is 16.04. It seems that 5.1 is the latest version of zsh I can get. Is there any workaround with this?

**Comment by romkatv** [comment]
@zc-alexfan First check that a newer version of ZSH would solve your problem. You can use Docker for such tests to ensure you make no destructive changes to your local system. For example, you can check whether Ubuntu 18.04 (comes with zsh 5.4) suffers from the same defect:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  cd
  apt update && apt install -y zsh git
  git clone https://github.com/bhilburn/powerlevel9k.git
  echo "
    # Add relevant POWERLEVEL9k options here.
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(anaconda)
    source ~/powerlevel9k/powerlevel9k.zsh-theme" >~/.zshrc
  exec zsh'
```

Note: The `--rm` option instructs docker to remove the image once you close the shell. This makes this whole command a no-op regardless of what you do in the shell that pops up.

If you establish that upgrading ZSH is indeed the right solution, you can install a newer version of zsh to your system. The simple way to build a specific version of ZSH (say, 5.4) is this:

```zsh
sudo apt update -y
sudo apt install -y git build-essential libncurses-dev gcc autoconf man
git clone -b zsh-5.4 https://github.com/zsh-users/zsh.git /tmp/zsh
cd /tmp/zsh
./Util/preconfig
./configure
make -j 20 install.bin install.modules install.fns
```

This will install ZSH 5.4 alongside 5.1 you already have. You'll need to change your default shell to switch.

The problem with this approach is that it doesn't build ZSH exactly the same way it's done in Ubuntu, so your new ZSH won't pick up global config files as it'll look for them in the wrong place. To fix this, you need to build ZSH just like Ubuntu does. For that you can read https://git.launchpad.net/ubuntu/+source/zsh/tree/debian/rules and copy over the relevant flags and config files.

Sounds crazy, huh? The truth is that that only sane way to update software on Ubuntu is upgrade the whole distribution. If you cannot upgrade to 18.04, then you are stuck with the software you have.

**Comment by zc-alexfan** [comment]
Thanks for the detailed instructions. Really appreciated!

**Comment by nWacher** [comment]
Sorry to reopen the thread, if need be I'll create a new one. Is there a way to remove the python version from the anaconda section? I checked that both my Mac and Ubuntu 18 configs are the same, and it only shows on Ubuntu.
![powerlevel_screenshot](https://user-images.githubusercontent.com/10953535/60761699-83594800-a013-11e9-979c-164374b328ad.png)

**Comment by romkatv** [comment]
Powerlevel9k doesn't show Python version in the anaconda section.

Perhaps you are using [Powerlevel10k](https://github.com/romkatv/powerlevel10k/)? If yes, you can disable the display of Python version with `POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true`.

**Comment by nWacher** [comment]
Thank you, that worked like a charm (changing true to false). You are right, I was using Powerlevel10k.
