### ISSUE TITLE
Tab completion in PROMPT_ON_NEWLINE draws invalid characters

### ISSUE THREAD

**Issue by martinpelikan** [bhilburn/powerlevel9k#42]
Bad example, but let's say I want to run 'cat test.py', in my current directory I have: temp, test.py, test.sh...

I type:
cat\<tab\>\<tab\> -- this should select 'cat', the first command of the completion list, but I now see 'ccat' completed for me
te\<tab\> -- shows me [temp, test.py, test.sh], I want test.py, so I type 's' to narrow down the results and \<tab\> again. I now I have 'ccat ts t.'
p\<tab\>  -- what I would see at this point is 'cat test.py', but instead I see 'ccat ts t.py'

The command runs as if it were actually 'cat test.py' when executed.

The [comments](https://github.com/bhilburn/powerlevel9k/blob/558d137bfaf3b64c5e1b6b1091b0c066cb5f5cce/powerlevel9k.zsh-theme#L601-605) suggest that the implementation of the PROMPT_ON_NEWLINE is ugly, so maybe this is a consequence of the implementation used?

**Comment by bhilburn** [comment]
@martinpelikan - Thanks for the bug report!

And, just to be sure, if you use the single-lined prompt, it behaves as you expect?

**Comment by martinpelikan** [comment]
@bhilburn Correct, sorry for missing that.

If the behaviour isn't reproducible by default, perhaps something in my [config](https://github.com/martinpelikan/dotfiles/blob/master/zshrc) is to blame?

**Comment by bhilburn** [comment]
@martinpelikan - Hm, I'm not sure. I just tried to reproduce the bug based on your description, and it's working just fine for me. Will take some additional investigation using your config.

**Comment by martinpelikan** [comment]
@bhilburn - Just tested on a second machine and I can't reproduce it. Same config, both using urxvt. The difference is the distro they are running... 

The one with the issue is [Arch's rxvt-unicode](https://www.archlinux.org/packages/?name=rxvt-unicode)
The one without the issue is [Ubuntu's rxvt-unicode-256color](http://packages.ubuntu.com/precise/rxvt-unicode-256color)

**Comment by bhilburn** [comment]
Ah. Can you try adding `export TERM='xterm-256color'` to your zshrc and see if that has an effect?

**Comment by martinpelikan** [comment]
@bhilburn Nice! That seems to have fixed it. Both the Arch and Ubuntu distributions of urxvt seem to identify as 'rxvt-unicode-256color' in the TERM environment variable, and I have no idea what would cause this behaviour... Regardless, thank you.

**Comment by bhilburn** [comment]
@martinpelikan - Glad you're all set!
