### ISSUE TITLE
Trailing space after right-hand prompt.

### ISSUE THREAD

**Issue by edwardsmit** [bhilburn/powerlevel9k#420]
As can be seen in the screenshot in https://github.com/bhilburn/powerlevel9k/issues/418#issuecomment-283610740 there is a trailing space after the right segment.
At my machine it is even more apparent, as I use `tmux` with a right colored segment and then you really see the difference.
Is this something which can be fixed by a setting, or is this a bug?

**Comment by dritter** [comment]
Hi @edwardsmit !

I got good news and bad news for you. Good: yes, that is a bug (so its fixable) and a workaround exists. Bad news: it is a bug/feature of ZSH. See #110 

In short: the bottom right corner seems to be special in Terminal Emulators. This goes way back to the early years of ZSH (I found a conversation from 2007). So you can set `ZLE_RPROMPT_INDENT=0`, BUT that has some trade offs (at least one): #364

**Comment by edwardsmit** [comment]
What a complete answer. Thanks for taking the time to write this. Other OSS supporters/creators/community runners can take an example from that. It's complete, to the point and light of tone. Too bad this issue looks impossible to fix...
Thanks Dominik,@dritter

**Comment by bhilburn** [comment]
Yeah, @dritter is a rock star.
