### ISSUE TITLE
right statusbar should apply terminal colorscheme

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#421]
Hello,
I have changed my colorscheme in my terminal to something more softy.
The left statusbar applied this change. But the right statusbar seems not to apply it.
Here is a picture of it:

![](https://paste.archlinux.de/dOWiK/)

Or is it just in my mind? the right statusbar looks a lot brighter than the left one.

**Comment by dritter** [comment]
Hi @shibumi !

Hmm. Hard to tell. But if the colors are not what you expected, you can change them easily.. All that powerlevel9k does is to output a ZSH color code to print text or background in a color. The terminal emulator picks this color codes up and modifies the color according to your color scheme. So nothing we can do here..

**Comment by shibumi** [comment]
Hi @dritter k, then it's the fault of my colorscheme. Let me close this issue :)
