### ISSUE TITLE
prompt_context:2: command not found: prompt_segment

### ISSUE THREAD

**Issue by NikKovIos** [bhilburn/powerlevel9k#423]
After each command i got this error
`prompt_context:2: command not found: prompt_segment`  

![2017-03-06 10 27 48](https://cloud.githubusercontent.com/assets/16647690/23600428/95e22868-0257-11e7-94f6-a01bcae5ddce.png)

Why it can be?

**Comment by NikKovIos** [comment]
It was because when in .zshrc i added for agnoster theme lines to escape user title. 
```
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)"
  fi
}
DEFAULT_USER=
```

**Comment by dritter** [comment]
So it works, and the issue can be closed? Or did I miss a question?

**Comment by NikKovIos** [comment]
Yes, it can be closed.

**Comment by dritter** [comment]
@hck94829 there is no `prompt_segment` function in P9K. So, please make sure you don't have such code in your `~/.zshrc`.

**Comment by silkyland** [comment]
just type 
```bash 
   sudo nano ~/.zshrc 
```
and remove 
```
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)"
  fi
}
```
just insert this : 
```
prompt_context() {}
```
save it! done.

**Comment by romkatv** [comment]
@silkyland That's not the right solution. The correct fix is to remove `prompt_context` function from `~/.zshrc`. If you keep `prompt_context() {}` in there, then `context` prompt segment won't work.
