### ISSUE TITLE
Improve compatibility on iOS client

### ISSUE THREAD

**Issue by debiansid** [bhilburn/powerlevel9k#428]
I need to ssh into my Linux from iOS client such as iPad/iPhone via Prompt2, but I cannot install any fonts onto them. So how can get those fancy themes working on iOS clients?
Thanks

**Comment by debiansid** [comment]
![img_5620](https://cloud.githubusercontent.com/assets/9624961/23780232/a6f99772-0580-11e7-8574-6efdd135a12c.PNG)

**Comment by debiansid** [comment]
there is a %

**Comment by debiansid** [comment]
I am think how to switch theme or profile based on client like iOS/MacOS/Linux/Windows you ssh from.

**Comment by bhilburn** [comment]
I honestly have no idea how to do this, but that said, it actually looks like the prompt is rendering correctly in your screenshot? There's a little bit of a color issue in the segment transitions, but you may not be able to fix that in an iOS client.

**Comment by bhilburn** [comment]
Closing this one out for now. Feel free to re-open, @debiansid, if you want to discuss things further, but I'm not sure there is much we can do, here.
