### ISSUE TITLE
Truncate VCS Branch

### ISSUE THREAD

**Issue by rawkode** [bhilburn/powerlevel9k#431]
Sometimes branch names can get a little out of control and take up the entire terminal (Especially if you're using BitBucket/GitLab/GitHub and the branch names can be inferred from a task)

Would it be possible to allow this to be truncated, like directories?

**Comment by dritter** [comment]
Awesome idea! 👍  
I want to refactor the dir segment anyway. And this is a perfect addition. I'll do a PR for that in the next weeks..

**Comment by bhilburn** [comment]
I agree, this is a really great idea, @rawkode 

@dritter - We could perhaps include some of the ideas from @ikelner's commit in [his fork on Gitlab](https://gitlab.com/lokiexinferis/powerlevel9k/commit/935a0942cae55bb2c092903739c9296754af2dde) into the `dir` segment refactor.

**Comment by bhilburn** [comment]
@dritter - Are you still hacking on this one?

**Comment by dritter** [comment]
Yep, I am still on it. But refactoring the `dir` segment is harder than I thought. I'll turn to truncating VCS branches after dir segment is refactored. You can track my progress [here](https://github.com/dritter/powerlevel9k/tree/rework_dir_truncation). ;)

**Comment by bhilburn** [comment]
How are things going on this one?

I just don't want things to bitrot if you have useful work done =)

**Comment by dritter** [comment]
This is bigger than I expected.. 😲  But I have a working draft. Still needs some polish. And maybe a rethinking of the truncation strategy. I changed it to accept an array of methods, but I think this is still not sufficient. One would want to execute some truncations more than once with different settings. E.g. first split a string by X and then by Y..

**Comment by bhilburn** [comment]
Leaving this one open until @dritter says otherwise `=)`

**Comment by ionsquare** [comment]
Any update on this? It would be really useful to have.

**Comment by dritter** [comment]
This is already in `master` now (See #798 ). Thanks to @floor114 .
