### ISSUE TITLE
PuTTY does not render nerdfonts correctly

### ISSUE THREAD

**Issue by debiansid** [bhilburn/powerlevel9k#436]
I am trying to ssh into Ubuntu linux with powerlevel9k installed from Windows 10 with Putty and Nerd-fonts installed. but the icons does not show correctly. even after I change the code in icon.zsh
```
POWERLEVEL9K_VCS_BRANCH_ICON='\ue725'
POWERLEVEL9K_VCS_TAG_ICON='\UF02B'
POWERLEVEL9K_HOME_ICON='\uf015'
POWERLEVEL9K_LINUX_ICON='\ue712'
```
vcs_tag and home icon are wrong.
but linux and branch icon working.

**Comment by canna002** [comment]
I have the same exact issue. I tried a variety of patched fonts, awesome fonts and nerd fonts. I use the method mentioned in the website below to install the fonts:

https://www.groovypost.com/howto/install-fonts-windows-10/

Some of the fonts can be selected in Putty whereas others are hidden:

https://www.asia-home.com/images/vimutf8putty5appearance.jpg

When I SSH using Putty the icons from the fonts are not displayed correctly. In some fonts the icons are tool small or narrow in width. In other fonts the icons do not appear, a question mark of some sort is displayed. I have enabled UTF-8 and everything should work. I have noticed that if I use nerd fonts without specifying the extra icons then everything is fine but I want to get the extra icons included with the fonts to display. For instance the Linux penguin.

**Comment by bhilburn** [comment]
@debiansid @canna002 - Interesting. I've never tried to do anything special in PuTTY, so unfortunately I'm not sure that I have any advice to offer. I imagine that it is not uncommon to try and do this, though, so if we can get it figured out it would be good to put in the wiki.

So, just to be clear, you see problems even if you use something other than nerdfonts?

**Comment by debiansid** [comment]
@bhilburn Yes.
but when I use SecureCRT, it can render nerd-fonts correctly.

**Comment by debiansid** [comment]
Here is my thoughts.Is there a way to determin ssh clients' type, ex. Prompt 2 on iOS; putty/securecrt on windows. Then set different shell or powerlevel9k-mode?

**Comment by bhilburn** [comment]
@debiansid - Ah, so, just to be clear, if there was a p9k mode that worked in PuTTY, that would do what you want it to - it doesn't have to be Nerd Fonts?

**Comment by debiansid** [comment]
@bhilburn 
Nerd Fonts are the best on Win10+PuTTY(my thoughts), so if there is a way to get it work on PuTTY, that would be perfect.

**Comment by bhilburn** [comment]
Okay, this doesn't look like something we'll really be able to do on our end. It's really entirely up to PuTTY. This is one you'll need to file against PuTTY, I'm afraid, and it's likely not going to be something they'll really be able to tackle since I think they piggy-back on the Windows Console, which is very limited in what it can render.

This might be your best show, for now: http://mikelindegarde.com/post/2016/03/10/feeling-like-a-real-developer

**Comment by chrisl8** [comment]
Doing some testing I found that even with the Windows Nerd Fonts TTF installed, for some reason many glyphs don't translate properly or at all across puTTY for some reason.

So I used the Nerd Font cheat sheet on their home page, tested out glyphs until I found ones that *did work* and replaced the current ones with working glyphs that were similar enough to the proper ones.

This is what I have so far:
```
POWERLEVEL9K_VCS_UNSTAGED_ICON='\uf704'                                                                                                                                                       
POWERLEVEL9K_VCS_STASH_ICON='\uf48d'                                                                                                                                                          
POWERLEVEL9K_VCS_STAGED_ICON='\uf916'                                                                                                                                                         
POWERLEVEL9K_HOME_ICON='\uf46d'                                                                                                                                                               
POWERLEVEL9K_CARRIAGE_RETURN_ICON='\uf810'                                                                                                                                                    
POWERLEVEL9K_OK_ICON='\uf62b'
```
Again, no idea why this is the case.

Also, FYI, to get the list of currently in use icons run `get_icon_names` while running powerlevel9k.

It would be cool to have  "puTTY" mode, but obviously somebody would have to work out all the weirdness and build it.

**Comment by dritter** [comment]
Hey @chrisl8 ,
IMHO it is not the right thing to exchange all icons. Instead I think this is a configuration issue. Could you try to configure your putty as described in [this comment](https://github.com/ryanoasis/nerd-fonts/issues/269#issuecomment-447621210) and see if that helps?

Thanks

**Comment by chrisl8** [comment]
@dritter If I enable 'Allow selection of variable-pitch fonts' and pick a variable pitch version of Nerd Fonts it does seem to display more, but not all, of the glyphs, however:
1. They look terrible as they are wider than their given spaces, thus being clipped.
2. It makes puTTY very slow. Text is slow to display and regularly the entire screen repaints from top to bottom.

I can do more testing to give better details and screen shots if you want more information, but going down the variable-pitch fonts road produced such bad results, that I decided that must be why that option is disabled by default in puTTY.
