### ISSUE TITLE
Unable to hide the VCS icon

### ISSUE THREAD

**Issue by natemccurdy** [bhilburn/powerlevel9k#440]
I just updated to the master branch, and now I can't hide the git VCS icon (VCS_GIT_ICON).

Previously, adding `POWERLEVEL9K_VCS_GIT_ICON=''` to my .zshrc did the trick. That seems to no longer work though.

![screen shot 2017-03-16 at 1 36 59 pm](https://cloud.githubusercontent.com/assets/10200384/24017525/a4d1f9cc-0a4d-11e7-82a6-18e6e15b1bcf.png)

So, what's the new way to hide the VCS icon?

**Comment by rjorgenson** [comment]
It should be `POWERLEVEL9K_VCS_GIT_ICON`- Just tested this on my copy of master and it worked.

**Comment by natemccurdy** [comment]
@rjorgenson Saw that typo right as you posted your response.

However, I just changed it from `10K` -> `9K` (super confused how I had that in there), reloaded my shell and I'm still seeing the icon.

![screen shot 2017-03-16 at 1 47 49 pm](https://cloud.githubusercontent.com/assets/10200384/24017987/5f8e1920-0a4f-11e7-9ad8-eb60c085100f.png)

**Comment by bhilburn** [comment]
@natemccurdy - Is there any chance you are using `zgen` or a similar framework?

Thinking about another issue like this, #406, that we just resolved.

**Comment by dritter** [comment]
I would say it is because the detection is now aware of the remote. Try setting `POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''`. 
See https://github.com/bhilburn/powerlevel9k/commit/f2cac2273a662127cf9dc25471047cdd0c116701

**Comment by natemccurdy** [comment]
@dritter `POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''` did the trick! Thanks everyone 👍 

I ended up blanking all the icons like this:
```
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
```
