### ISSUE TITLE
One char gap between terminal edge and right prompt

### ISSUE THREAD

**Issue by Cpt0r** [bhilburn/powerlevel9k#441]
See below.  Bottom line is tmux filling full width of terminal, the line above is zsh right prompt.

Tried different setups, always the same.

<img width="314" alt="screen shot 2017-03-17 at 14 46 57" src="https://cloud.githubusercontent.com/assets/8690075/24028137/e1f0ceae-0b20-11e7-8fec-984f47fc47ff.png">

iTerm2, OSX Sierra.

**Comment by dritter** [comment]
Hi @Cpt0r ! 

Have a look at #420 

In short: You could set `ZLE_RPROMPT_INDENT=0` but that raises issues with completion. ;)

**Comment by Cpt0r** [comment]
Ah nuts, I tried searching for it too, figured I wasn't the first to notice/report.

Short and sweet - well, bitter sweet.  Cheers!

**Comment by bhilburn** [comment]
I just added an answer on the Troubleshooting page of the wiki for this. Thanks, @Cpt0r and @dritter!
