### ISSUE TITLE
nerd-fonts not working on macOS 

### ISSUE THREAD

**Issue by debiansid** [bhilburn/powerlevel9k#442]
https://github.com/ryanoasis/nerd-fonts/issues/143

**Comment by dritter** [comment]
This seems to be more a powerlevel9k issue than nerd fonts.
What is your locale?
And do you have any special P9K setup?

**Comment by debiansid** [comment]
```
POWERLEVEL9K_MODE='nerdfont-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"

#POWERLEVEL9K_MODE='awesome-patched'
#POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm node_version)

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
```
```
locale                                                          
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by debiansid** [comment]
ok, I added `export LANG=en_US.UTF-8` into .zshrc
it works now.
thanks

**Comment by zayajf** [comment]
Where would the locale be located. Im having this same issue. I added `export LANG=en_US.UTF-8` into .zshrc and its still not working for me.

`POWERLEVEL9K_MODE='nerdfont-complete'
#source ~/powerlevel9k/powerlevel9k.zsh-theme

#Theme
ZSH_THEME="powerlevel9k/powerlevel9k"
#ZSH_THEME="spaceship"
#ZSH_THEME="agnoster"
`

this is all i have really for P9k settings.
