### ISSUE TITLE
 Triangles are not in their places

### ISSUE THREAD

**Issue by flomaster9** [bhilburn/powerlevel9k#443]
![qlbpz_croper_ru](https://cloud.githubusercontent.com/assets/20969848/24066926/aaf0f5fc-0b87-11e7-95f0-b21273f840af.png)
How can I fix this?

**Comment by dritter** [comment]
Hi @flomaster9 !

Please have a look at our [troubleshooting](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#gaps-between-segments) wiki page. If that does not help you, I am afraid this is a font issue then..

**Comment by bhilburn** [comment]
Yeah, this looks to me like you are using Apple's `Term.app`, which has known issues rendering things properly.

Were you able to get this fixed, perhaps by using iTerm2?

**Comment by ryanoasis** [comment]
@flomaster9 Can you tell which font you are using? Is it a nerd font? If so we are working on some fixes for the positioning

**Comment by xasx** [comment]
I have this issue with a nerd-font, in particular 'DroidSansMonoForPowerline Nerd Font Book', the non-Mono variant. With the Mono variant, the gaps are collapsed; however, then the glyphs are way too small as per #430

**Comment by xasx** [comment]
Found another reference ryanoasis/nerd-fonts#26
