### ISSUE TITLE
Awesome Powerline icons cut off

### ISSUE THREAD

**Issue by binxycraft** [bhilburn/powerlevel9k#453]
This is probably not a powerlevel9k issue but I figured this would be the best place to start since someone may have an answer. I have recently installed powerlevel9k on 3 different computers. I am using Kayant's config as a starting point and like it so far. I am using SourceCodePro+Powerline+Awesome+Regular since it seemed popular. The problem is with the Awesome powerline icons. This happens on all 3 computers exactly the same. I am running Manjaro/KDE on all three and using Konsole as my primary terminal emulator. I have tried playing with every appearance setting I could find within Konsole but could not get this behavior to stop. I decided to try another terminal emulator (Terminator) and the font seemed fine there. I thought maybe it only affected Qt emulators so I downloaded QTerminal and I had the exact same issue as with Konsole. Weirdly enough the folder icon (outside of home folder) is fine but the other two are cut off. I know as a workaround I could disable these icons but I kind of like them so would rather get it fixed if anyone has any ideas.

![powerlevel9k](https://cloud.githubusercontent.com/assets/8657284/24179146/b80bea5e-0e83-11e7-8aa8-7341bb7df76e.jpeg)

**Comment by D4v2z** [comment]
Hey man, the solutions : https://github.com/bhilburn/powerlevel9k/issues/231

**Comment by dritter** [comment]
Ha! Thanks @D4v2z for finding that solution. I completely forgot about it.

Btw. I did a quick research this morning and found out that `Konsole` has some issues regarding double-width glyphs. Hard to say what other terminal emulators do different. The information that a glyph needs to be printed as double-width is coded somewhere in the font I guess..

**Comment by binxycraft** [comment]
Perfect! Thank you. This is exactly the kind of workaround I was looking for. I must have been searching the wrong key words. Following the example I also added another entry for my other cut-off icon:
`POWERLEVEL9K_HOME_SUB_ICON=$'\UE18D '`
Using this page as reference:
https://github.com/bhilburn/powerlevel9k/blob/master/functions/icons.zsh

**Comment by dritter** [comment]
Btw. , Just for completeness, easier than looking into `functions/icons. zsh` would have been to call `get_icon_names`. ;)

**Comment by millsoft** [comment]
Hi, I did this but no home icon is being displayed, just a square. :(

![screenshot](https://user-images.githubusercontent.com/964209/32226936-2d398248-be4a-11e7-97a8-132581d98218.png)

**Comment by dritter** [comment]
@millsoft It seems that your font does not support all Icons. Which font do you use?
Btw. sorry for the late response.

**Comment by vanushwashere** [comment]
Same issue on latest KDE neon
