### ISSUE TITLE
Best way to update MULTILINE_SECOND_PROMPT_PREFIX??

### ISSUE THREAD

**Issue by querentCode** [bhilburn/powerlevel9k#455]
I'm trying to do what seems to be simple, but I also seem to be having a simple bug that I'm having a had time addressing.  This may just be a zsh question, but I'm asking it here because of the expertise regarding all of the components involved (zsh, oh-my-zsh, powerlevel9k, iterm2).

I'm trying to create a simple function to dynamically update the content of MULTILINE_SECOND_PROMPT_PREFIX.  Everything works as expected, except after I reload the zsh config I can type in the termial, but the moment I press the spacebar or the enter key the shell crashes.  I've added a gif to show what I'm talking about, as well as the what I believe to be the relevant configuration items.

I may not be approaching the problem in the right way, or I may be missing something simple, eitherway, any help would be appreciated!  Thanks!

```
quote () {
    export QUOTE=$1 &&
    source ~/.zshrc &&
    echo "termal quote set to " $1
}

POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{white}%F{black}\n `echo $QUOTE`.%f%k%F{white}%f $ "
```

![quotefunc](https://cloud.githubusercontent.com/assets/1161295/24219214/03290f7c-0f14-11e7-82c0-353152905c79.gif)
1. Call quote function with string arg
2. .zshrc is reloaded
3. terminal accepts keyboard input
4. spacebar or enter crashes terminal

**Comment by dritter** [comment]
Interesting problem. I didn't try to reproduce your error, but I think re-sourcing the `zshrc` all the time is quite some overhead.

I would have written that function like this:
```zsh
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
quote () {
  POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{white}%F{black}\n ${1}.%f%k%F{white}<U+E0B0>%f $ "
  echo "termal quote set to " $1
}
# Initial state
quote "."
```
And that way it works for me. Could you try this version?

**Comment by querentCode** [comment]
![powerleveltada](https://cloud.githubusercontent.com/assets/1161295/24224734/d96329e0-0f2a-11e7-9d7d-abc2acdce532.gif)

WORKS GREAT!  Thanks!

**Comment by dritter** [comment]
Awesome! :)

**Comment by querentCode** [comment]
I hope to turn this concept into a 'next up' todo list that reads/modifies lines from a file

```
$quote done <line1>
$quote new <newline>
$quote hold <line1>
$quote list
-active- "Todo2"
-hold- "Todo3"
-hold- "Todo1"
```

**Comment by dritter** [comment]
Ah. Cool. So similar to [todo.txt](http://todotxt.com/)?

**Comment by querentCode** [comment]
orgmode files are what I had in mind, but yeah! I now see there's a powerlevel9k element for todo.txt, ;)  I'll look at that code to see if anything fun can happen! Thanks!

**Comment by querentCode** [comment]
![quote-for-tw](https://cloud.githubusercontent.com/assets/1161295/24236482/ea9c2bea-0f6f-11e7-8586-4e981e563257.gif)
I went with taskwarrior instead as the interface was cleaner to work with

```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
setNewlinePrompt () {
    POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{white}%F{black}\n $1 %f%k%F{white}%f $ "
}

quote () {
    if [ -z "$1" ]; then
        export QUOTE=`task _get 1.description`
        if [ -z "$QUOTE" ]; then
            echo "no tasks in queue, go do something else"
            echo "Setting quote to '.' "
            setNewlinePrompt "."
        else
            echo "Setting quote to first task from taskwarrior:" $QUOTE
            setNewlinePrompt $QUOTE
        fi
    elif [[ $1 = "help" || $1 = "h" ]]; then
        echo "\n quote is a lightweight facade to taskwarrior for use with Powerlevel9k's Second Prompt Prefix\n"
        echo   Options:
        echo -----------------------------------------------------------------------------
        echo   "  No args           ---   Calls first available task from taskwarrior."
        echo   "  help              ---   h - This help dialog."
        echo   "  list              ---   ls - A Wrapper for \'task next\'."
        echo   "  set  <taskID>     ---   s - Sets the quote prompt to description of specified task id."
        echo   "  done              ---   d - Completes the current task and sets quote to next task."
        echo   "  \"string\"          ---       \"string\" with no additional arguments, sets the quote prompt but no new task."
        echo   "  \"string\" add      ---   a - \"string\" followed by 'add' will set the quote and add a new task to taskwarrior.\n\n"
        echo   Examples:
        echo "-----------------------------------------------------------------------------\n"
        echo "   Create a task:"
        echo "      $ quote \"Edit Super Cool Project\" add"
        echo "      $ quote \"Write Blog Post\" a"
    elif [[ $1 = "list" || $1 = "ls" ]]; then
        task next
    elif [[ $1 = "set" || $1 = "s" ]]; then
        export QUOTE=`task _get $2.description`
        if [ -z "$QUOTE" ]; then
            export QUOTE=`task _get 1.description`
            if [ -z "$QUOTE" ]; then
                quote
            else
                echo "no task with id $2 in queue"
                echo "Setting quote to first available task: " $QUOTE
                setNewlinePrompt $QUOTE
            fi
        else
            echo "Setting quote to first task from taskwarrior:" $QUOTE
            setNewlinePrompt $QUOTE
        fi
    elif [[ $1 = "done" || $1 = "d" ]]; then
        task /$QUOTE/ done
        task
        export QUOTE=`task _get 1.description`
        if [ -z "$QUOTE" ]; then
                quote
        else
            echo "Setting quote to next task: "$QUOTE
            setNewlinePrompt $QUOTE
        fi
    elif [ -z "$2" ]; then
        setNewlinePrompt $1
        echo "terminal quote set to " $1 "But no task has been created"
    elif [[ $2 = "add" || $2 = "a" ]]; then
        export QUOTE="$1"
        task "$1" add
        task
        setNewlinePrompt $1
    fi
}
# Initial state
quote "."
```

**Comment by bhilburn** [comment]
Nice work, @dritter and @querentCode!

@querentCode - I added this to the [User Segments](https://github.com/bhilburn/powerlevel9k/wiki/User-Segments) wiki. This is really cool!

**Comment by bhilburn** [comment]
Hah! I just saw that you added it to 'Show off your config'. I copy / pasted the extra content you had there (including the link to your gist) to the User Segment page.

**Comment by juanrgon** [comment]
Just saw this today. To get this to work, I had to change MULTILINE_SECOND_PROMPT_PREFIX to MULTILINE_LAST_PROMPT_PREFIX

**Comment by querentCode** [comment]
@juanrgon good catch!  I also found the associated issue.  bhilburn expalins it in #635.
