### ISSUE TITLE
Terminal does not take the accents in Zsh

### ISSUE THREAD

**Issue by D4v2z** [bhilburn/powerlevel9k#456]
As you see in this image below, when I put the theme powerlever9k in zsh with oh-my-zsh the terminal is put in English and the accents do not catch them, any ideas?
SO: Arch linux, gnome-terminal and Tilix (terminix)

PS: only happens to me with this subject , the others themes of oh-my-zsh does not happen.
![captura de pantalla de 2017-03-22 23-47-17](https://cloud.githubusercontent.com/assets/26611092/24224250/77228be2-0f5a-11e7-94c7-c783e0f144b5.png)

**Comment by dritter** [comment]
Thanks for the report @D4v2z . Interesting.
The only place we set locales is in `functions/icons.zsh`, because if the user did not set a `locale`, the icons would break with a nasty error message ("character out or range").

Have you set a locale?

**Comment by D4v2z** [comment]
@dritter Thanks for replying, my set in locale with powerlevel and Zsh
![captura de pantalla de 2017-03-23 01-03-05](https://cloud.githubusercontent.com/assets/26611092/24226055/8761bb7c-0f64-11e7-9a1b-479b22b53aa2.png)

Theme "Agnoster" (for example) and Zsh
![captura de pantalla de 2017-03-23 00-39-52](https://cloud.githubusercontent.com/assets/26611092/24226115/df8e3334-0f64-11e7-9437-04fdc24f0bd7.png)

Theme powerlever9k and Zsh
![captura de pantalla de 2017-03-23 01-12-27](https://cloud.githubusercontent.com/assets/26611092/24226294/eeff8394-0f65-11e7-8e08-b42f6211e03e.png)

Theme "Agnoster" (for example) and Zsh
![captura de pantalla de 2017-03-23 01-14-59](https://cloud.githubusercontent.com/assets/26611092/24226352/432ae062-0f66-11e7-958c-0e53becb9647.png)

Hope this can help you!

**Comment by dritter** [comment]
Could you install the locale for `en_US.utf8` and see if that helps?

Background is that we had to pick a default locale for the utf8 code points in `functions/icons.zsh` to avoid further errors. For lowest impact, we chose en_US, as this is the most widespread locale around.

**Comment by D4v2z** [comment]
Good afternoon, he got to know that it is, in /etc/locale.gen I have enabled the "en_US.UTF-8" apart from the three of my language and it works, thanks for the help.

**Comment by dritter** [comment]
Awesome! Thanks for the report. I added it to the troubleshooting wiki page. And sorry for the inconvenience.

**Comment by D4v2z** [comment]
One thing, when you put '/etc/locale.gen' and to enable "LANG=en_US.UTF-8" you  have to generate locale with 'sudo pacman (in case of arch) locale-gen', otherwise it will not work.

https://wiki.archlinux.org/index.php/Locale

**Comment by dritter** [comment]
That is an addition to the troubleshooting paragraph I wrote, right? Yeah, I had thought about adding some words on how to regenerate the locale. At last I skipped it, because it differs on the various OSes...

Btw. Your profile pic is perfect for this theme! :)

**Comment by bhilburn** [comment]
Thanks for that extra bit in the troubleshooting guide, @dritter, and I'm glad you're up and running, @D4v2z!
