### ISSUE TITLE
Name of nerd-font icon set is confusing

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#458]
The name of the nerd-font icon array is called "nerdfont-fontconfig". This is a bit misleading, because the complete versions of nerd-font (the ones we support) are already pre patched fonts, right? We could use them in a fontconfig setup, but that is not necessary.

If I understood @ryanoasis correctly, the code points are stable in the complete fonts. So there should be no difference in using nerdfont in a fontconfig setup and as directly installed.

I suggest the name "nerdfont-complete". For BC reasons, I would keep the old name (but only as a fallback in `functions/icons.zsh`. Everywhere else the new name should be referenced.

What do you think?

Documentation:
In #351 the nerdfont support was merged.

**Comment by onaforeignshore** [comment]
Shouldn't this be "nerdfont-patched" to match "awesome-patched"?

**Comment by dritter** [comment]
@onaforeignshore I thought about "nerdfont-patched" too, but came to the conclusion that "nerdfont-complete" reflects the situation better. The NerdFont project is a set of patched fonts. On the opposite, `awesome-terminal-fonts` offer explicitly a fontconfig strategy and a patched strategy. Even in the fontconfig variant the codepoints get shifted, so they are different from the ones in the source font. That is something that does not exist in NerdFonts. Of course, you could use the source fonts in a fontconfig setup as well, but would get collisions eventually.

**Comment by ryanoasis** [comment]
@dritter Yes they should be stable (at the very least for any major version). I am all for using 'complete' as an identifier that makes sense to me given the conversation here

**Comment by bhilburn** [comment]
Excellent point, @dritter. @onaforeignshore raises a fair concern, though, in that as the number of different configuration keywords grows we risk even further confusing users over an already confusing topic, hah. I'm in favor of staying technically accurate, though, and it sounds like `-fontconfig` isn't the best option. Since the nerdfont maintainer, @ryanoasis, agrees with `-complete`, let's roll with that.

Have a look at #466!

**Comment by bhilburn** [comment]
Merged in #466!
