### ISSUE TITLE
Add priority levels to each segment

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#460]
I know this is a big one, but priority levels would allow certain segments of the path to be dropped when the prompt gets very long. Yes, I know it is a powerline feature, but it can be very useful for limited displays or very long prompts. That way, the right prompt doesn't have to disappear when the left one gets too long.

**Comment by dritter** [comment]
Hmm. Interesting idea @onaforeignshore !
I agree, this is quite a big change. It would be interesting to know how the powerline achieved that. I guess they render everything in python, which makes it much easier to calculate the available/needed space.. In pure ZSH this is much harder and especially in an async setup (that is the future).

**Comment by bhilburn** [comment]
@onaforeignshore - Wow, cool idea! And yeah, you're right, that's a big one! Hah :)

@dritter has a good point in that the Powerline project has the advantage of being able to write everything in Python, which makes that sort of overhead management significantly easier. I'm trying to think about how we go about doing that, and honestly I don't think we have the right levers to pull.

So, the right prompt going away, for example, is something that ZSH does, not P9k. In order for us to catch that, we would need to detect the length of the line relative to the window size and drop segments before ZSH did it for us.

Does anyone know if ZSH has any features / functions that might help, here? This would be a useful feature for P9k, but my bet is that it may be infeasible for us to implement in P9k.

**Comment by bhilburn** [comment]
I'm going to close this one out - doesn't seem feasible, at the moment. Feel free to re-open if you have ideas!
