### ISSUE TITLE
Icons disappear on tmux

### ISSUE THREAD

**Issue by agungsetiawan** [bhilburn/powerlevel9k#464]
I'm not sure if here is the right place to ask
The icon are fine

<img width="830" alt="screen shot 2017-04-02 at 17 45 59" src="https://cloud.githubusercontent.com/assets/5874815/24586484/4d085f10-17cc-11e7-8324-937b15272f5d.png">

but when I use tmux, those icons disappear

<img width="830" alt="screen shot 2017-04-02 at 17 46 09" src="https://cloud.githubusercontent.com/assets/5874815/24586483/4cfff05a-17cc-11e7-8828-f21cb666c09a.png">

My font is SourceCodePro+Powerline+Awesome
Any body knows the solution?

**Comment by dritter** [comment]
Hi @agungsetiawan !

Is the line where you define the mode (`POWERLEVEL9K_MODE`) on the top of your `~/.zshrc`?

**Comment by agungsetiawan** [comment]
No, I have this line on third line from bottom
`POWERLEVEL9K_MODE='awesome-patched'`

Should I place it on the very first line?

**Comment by dritter** [comment]
Yes, try that! ;)

**Comment by agungsetiawan** [comment]
Ah yes, after move it to the up, now it's working
thank you @dritter what a wonderful clue 🤝

**Comment by dritter** [comment]
Awesome! And apologies for that confusion. We are working on that, so that the position where you place that line gets irrelevant..

**Comment by agungsetiawan** [comment]
It's okay :)
Cool!
I'm looking forward for the update
