### ISSUE TITLE
signed releases

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#465]
Hello,
What do you guys think about signing the releases? This would increase security a lot. You can find a tutorial for it here:  https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by bhilburn** [comment]
Great idea, @shibumi! I'll do this for our latest release, and start doing it for all future releases, as well :)

Leaving this open to remind me to take care of this ASAP.

**Comment by shibumi** [comment]
@bhilburn Don't forget to insert a link to your pubkey into the README. So the people will know who will sign the release and with which key. I will adjust the Arch Linux zsh-powerlevel9k package when it's done.

**Comment by bhilburn** [comment]
Okay, v0.6.2 has a signature uploaded!

Thanks for sharing this, @shibumi, and I'll do this for all future releases :)

**Comment by shibumi** [comment]
@bhilburn AWESOME! \o/ Now I can secure the PKGBUILD on aur.archlinux.org and make it even more secure :)

**Comment by shibumi** [comment]
Ahhh @bhilburn by the way.. you can also sign git commits and tags :) 
Just add this to your `~/.gitconfig` file:
```
[commit]
    gpgsign = true
[tag]
    forceSignAnnotated = true
```

this will automatically sign your commits and tags when you use git

**Comment by Tritlo** [comment]
Woo! I've been signin all my commits by default as well, nice to have it here :)
