### ISSUE TITLE
GH Pages with easy installation instructions

### ISSUE THREAD

**Issue by alex285** [bhilburn/powerlevel9k#469]
hello, 
first thanks for your great work! 
i use your theme in my YouTube channel and what happens is to have literally more than 100 comments asking how to setup such prompt, even if i do give a link to this repository ..and i really got tired to help in comments :)

so, i want to ask you if you are fine to let me add step by step easy documentation how to install powerlevel9k in `gh-pages` in this repository ..just 5 html pages, which it will be easy maintain if i quit updating when necessary in future!

**Comment by bhilburn** [comment]
Yes! Please do. I actually just bought some domains for this project, and
this sounds like a great way to get something up.

Go ahead and submit the PR. I'm eager to get this live :)

**Comment by alex285** [comment]
awesome thanks! i will PR probably this weekend!

**Comment by alex285** [comment]
@bhilburn hey are you okay to use Gatsby for that?
https://github.com/gatsbyjs/gatsby

it is a static site generator in React, but it is straight simple, you can render .md, you can easily override things, you can deploy directly in Github, it has active development, and it takes no time to maintain it! 

Plus you can create more content than what i was initially asked for, just in case you want to! Basically you could move all the docs you have in README.md in that!

**Comment by bhilburn** [comment]
@alex285 - I'm not much of a web developer myself, but I do like static site generators, and while I'm not familiar with Gatsby it does look quite useful. @dritter's input would be useful, here, as I think he actually knows a thing or two about web development.

I am on-board with using something that will allow us to create a nicer site, though, and unless @dritter chimes in with some reason for why Gatsby is a poor choice I say go for it :)

**Comment by dritter** [comment]
I don't know Gatsby, but it looks like a reasonable choice. 👍

**Comment by alex285** [comment]
okay i start with Gatsby then, and add a demo here to check on!

**Comment by bhilburn** [comment]
Awesome, @alex285! Looking forward to seeing the results!

**Comment by bhilburn** [comment]
Hey @alex285! Were you still looking into putting this together! Now that I own p9k.org (and a few others) I'd like to get a site up for the project, and am thinking your work could be an excellent way to get going.

**Comment by bhilburn** [comment]
Hey @alex285! It would be really great if this came together. I'm going to close this issue for now, but please re-open if you get a chance to hack on this =)

**Comment by alex285** [comment]
@bhilburn  hey sorry! i have already done the initial sections design a week ago, i just need 4-5hrs to actually write the docs and i had a very busy week! i will have it this weekend! sorry for the delay again!

**Comment by bhilburn** [comment]
@alex285 - Not a problem at all - we are really appreciative of any time you have to spend on this to begin with! It sounds like you are already making progress, which is awesome, and I can't wait to see what the first pass looks like =)

I'll re-open this for discussion.

**Comment by bhilburn** [comment]
Hey @alex285! How are things coming along?

If you're too busy to address this, no worries, just let us know. I am really excited about this idea, though, and would like to find someone to tackle it if you aren't able `=)`

**Comment by bhilburn** [comment]
Closing this out, for now. I would still really like to see this happen, but until we have an ongoing effort I don't want to clutter the tracker.
