### ISSUE TITLE
README: Symbol table wrong about branch icon

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#47]
Our readme currently shows this in the symbol table:

| `@`         | ![icon_branch_powerline](https://cloud.githubusercontent.com/assets/1544760/8000852/e7e8d8a0-0b5f-11e5-9834-de9b25c92284.gif) | ![](https://cloud.githubusercontent.com/assets/1544760/7976087/b58bbe3e-0a76-11e5-8d0d-7a5c1bc7f730.gif) | Branch Icon
| None         |  None               | ![icon_commit](https://cloud.githubusercontent.com/assets/1544760/7976088/b58f4e50-0a76-11e5-9e70-86450d937030.gif)2c3705 | The current commit hash. Here "2c3705"
| None         |  None               | ![icon_git](https://cloud.githubusercontent.com/assets/1544760/7976092/b5909f80-0a76-11e5-9950-1438b9d72465.gif) | Repository is a git repository
| None         |  None               | ![icon_mercurial](https://cloud.githubusercontent.com/assets/1544760/7976090/b5908da6-0a76-11e5-8c91-452b6e73f631.gif) | Repository is a Mercurial repository

And the `branch icon` is supposed to be configurable. I don't think this is quite right, though. What is currently shown there as the `branch icon` is actually used as the Git and Hg icons, and is *always* present. The branch icon is different, and not always present.

@dritter

**Comment by bhilburn** [comment]
@dritter - I think I've got it right, now, in the `fixing_symbol_table` branch. Have a look and let me know if it looks right: https://github.com/bhilburn/powerlevel9k/tree/fixing_symbol_table#symbols

**Comment by dritter** [comment]
@bhilburn 
I think it should be the branch icon and we should show it by default. The only thing is, that it could be ugly, if the users wants to display the commit hash. Then it would look like this: `772c9a![icon_branch_powerline](https://cloud.githubusercontent.com/assets/1544760/8000852/e7e8d8a0-0b5f-11e5-9834-de9b25c92284.gif)master`

IMHO this is better than displaying the icon at a unusual position in the readme..

**Comment by bhilburn** [comment]
@dritter - Hm, I'm not sure I understand your comment. Are you saying that the README is correct, as is, and the branch icon should just be turned on by default?

**Comment by dritter** [comment]
@bhilburn Yep. :)

The icon ![](https://cloud.githubusercontent.com/assets/1544760/8000852/e7e8d8a0-0b5f-11e5-9834-de9b25c92284.gif) shows a branch icon. So we should use it as such. It would be confusing, if we use it for other purposes..

Turning on the branch icon by default would like the previous layout (showing branch icon, than the branch name), with the exception when the commit hash is on..

I hope that explanation made it clearer.

**Comment by bhilburn** [comment]
@dritter - Maybe we keep current README, set branch icon to default to on, and add a space to the commit hash to make it readable?

**Comment by dritter** [comment]
Yeah, maybe.. Just tried a little bit. Seems not to be done by just adding a space to the commit hash..

Here is what it looks like with just a space added to the icon:
![bildschirmfoto 2015-07-09 um 22 06 49](https://cloud.githubusercontent.com/assets/1544760/8605640/f153bef4-2686-11e5-9037-e07b4a0ecba1.png)

Here with space after the icon and hash:
![bildschirmfoto 2015-07-09 um 22 07 20](https://cloud.githubusercontent.com/assets/1544760/8605641/f1563134-2686-11e5-9f22-206d3887c2e6.png)

But with `awesome-patched` it looks best without a space between the icon and hash.
![bildschirmfoto 2015-07-09 um 22 02 49](https://cloud.githubusercontent.com/assets/1544760/8605704/53e1a090-2687-11e5-93e6-c4120dbec8d5.png)

**Comment by dritter** [comment]
@bhilburn I'll try to clean that up.. ;)

**Comment by dritter** [comment]
@bhilburn I think I got it!

![bildschirmfoto 2015-07-10 um 00 28 28](https://cloud.githubusercontent.com/assets/1544760/8608401/e055b652-269a-11e5-94b2-e2dc0c11aff9.png)
![bildschirmfoto 2015-07-10 um 00 28 51](https://cloud.githubusercontent.com/assets/1544760/8608399/e054df48-269a-11e5-9bd3-4e7387fbd37c.png)
![bildschirmfoto 2015-07-10 um 00 29 09](https://cloud.githubusercontent.com/assets/1544760/8608400/e055a004-269a-11e5-9661-76c916eadf24.png)
![bildschirmfoto 2015-07-10 um 00 29 19](https://cloud.githubusercontent.com/assets/1544760/8608403/e05855a6-269a-11e5-88cb-ff72f08af836.png)
![bildschirmfoto 2015-07-10 um 00 29 28](https://cloud.githubusercontent.com/assets/1544760/8608402/e0581708-269a-11e5-89c8-f4bbe8adf492.png)
![bildschirmfoto 2015-07-10 um 00 29 49](https://cloud.githubusercontent.com/assets/1544760/8608404/e05aa162-269a-11e5-8e25-4f3c3631c17e.png)

**Comment by bhilburn** [comment]
@dritter - Awesome! Where is the branch? `=)`

**Comment by dritter** [comment]
Almost there, just some last tests. ;)

Here are the screenshots, if the branch icon is disabled:
![bildschirmfoto 2015-07-10 um 00 39 05](https://cloud.githubusercontent.com/assets/1544760/8608565/51fd9b7a-269c-11e5-97b7-b42ea0562e2e.png)
![bildschirmfoto 2015-07-10 um 00 39 16](https://cloud.githubusercontent.com/assets/1544760/8608566/51fe7d1a-269c-11e5-912f-f827776a73d8.png)
![bildschirmfoto 2015-07-10 um 00 39 28](https://cloud.githubusercontent.com/assets/1544760/8608567/51feab78-269c-11e5-864d-ebf42d0b29fc.png)
![bildschirmfoto 2015-07-10 um 00 39 35](https://cloud.githubusercontent.com/assets/1544760/8608569/526197e2-269c-11e5-8fbe-71941d16d30c.png)
![bildschirmfoto 2015-07-10 um 00 39 43](https://cloud.githubusercontent.com/assets/1544760/8608570/526da5dc-269c-11e5-8af7-ad7a9146e365.png)
![bildschirmfoto 2015-07-10 um 00 39 51](https://cloud.githubusercontent.com/assets/1544760/8608571/526eb300-269c-11e5-908a-aa6d896ffd5f.png)

**Comment by bhilburn** [comment]
Resolved by PR #49.
