### ISSUE TITLE
Unable to disable git icon in 'awesome-fontconfig' mode

### ISSUE THREAD

**Issue by chhschou** [bhilburn/powerlevel9k#475]
Unable to disable the git icon via `POWERLEVEL9K_VCS_GIT_ICON=''`, the octocat is shown.
It worked correctly in `POWERLEVEL9K_MODE` which I left out of the config completely.

Fresh install of Powerlevel9k via zgen and using Source Code Pro for Powerline font.  
Here is a screenshot of the prompt:
![image](https://cloud.githubusercontent.com/assets/429067/24801353/f7970df8-1bf7-11e7-8285-8deb99a49ad2.png)

**Comment by bhilburn** [comment]
I think this is the same as #440. This comment will probably solve your problem:
https://github.com/bhilburn/powerlevel9k/issues/440#issuecomment-287199151

We probably need to update the docs to reflect this change since this is the second time we've gotten this question. Leaving this issue open as a TODO.

**Comment by dritter** [comment]
That would be a good first-timer contribution. ;)
@chhschou Do you want to file a PR against the `next` branch? That would be awesome!

**Comment by chhschou** [comment]
I'll try this out and update doc later today thanks.

**Comment by onaforeignshore** [comment]
If you are using git, the icon is chosen as follows:
For Github: `VCS_GIT_GITHUB_ICON`
For BitBucket: `VCS_GIT_BITBUCKET_ICON`
For GitLab: `VCS_GIT_GITLAB_ICON`
For everything else: `VCS_GIT_ICON`

**Comment by onaforeignshore** [comment]
I've updated the `Stylizing your prompt` to include this list

**Comment by bhilburn** [comment]
Thank you, @onaforeignshore! Very helpful =)
