### ISSUE TITLE
Help in changing font to Monaco!

### ISSUE THREAD

**Issue by svaderia** [bhilburn/powerlevel9k#477]
Hello there,  
I really loved this theme and the support you're providing.
While I was watching the section "Show Off Your Config" on wiki page I came across [Miguelcarax's config](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#miguelcaraxs-configuration), I loved the Monaco font and went to the [gist](https://gist.github.com/epegzz/1634235) that he has provided. I have downloaded `file-monaco_linux-powerline-ttf`, put it to `~/.fonts` folder and run `fc-cache -vf`, I don't  know what to do next in order to change the fonts of the terminal.  
Sorry for asking a very basic question. 
Thanks.

**Comment by onaforeignshore** [comment]
Changing fonts in the terminal depends on the emulator you use, but most have a section where you can edit the profile and set the fonts there.

**Comment by bhilburn** [comment]
@svaderia - Your terminal application's preferences should let you select a font to use in the emulator. What terminal emulator are you using?

**Comment by svaderia** [comment]
I'm using default `gnome-terminal-server` emulator for Ubuntu 16.04.
When I change my font in preference, Look the efects below:
![selection_001](https://cloud.githubusercontent.com/assets/26005890/25004223/d31156f0-2070-11e7-961e-ea3df9ecc216.png)
![selection_002](https://cloud.githubusercontent.com/assets/26005890/25004228/df115a72-2070-11e7-94ea-91784e47f814.png)

It will be very helpful if you can tell me how to fix this Or suggest some other good emulator since I'm a new learner of `*nix` systems.

Thanks :smile:

**Comment by bhilburn** [comment]
@svaderia - And, just to be sure, if you right-click in your terminal and select that `new` profile, you don't see a font change take effect?

Those settings look correct (I use the same emulator), so if it's not working I'm honestly not sure what to say :-/

**Comment by svaderia** [comment]
@bhilburn Thanks for the reply. It chaged the font but as shown in the second screen shot of my previous comment the triangular shape is not showing correctly.

**Comment by bhilburn** [comment]
@svaderia - I'm really not sure what to say, unfortunately. This seems to be something specific with the font. I followed the threads on Github discussing that Gist, and people's success with it seems to be pretty hit-or-miss: https://gist.github.com/baopham/1838072

I know you're on Linux, but you could give this one a go?
https://gist.github.com/kevinis/c788f85a654b2d7581d8

Otherwise not really sure what to tell you, I'm afraid.

**Comment by svaderia** [comment]
Thank you so much @bhilburn. The second link worked. 
Appreciate the support you are providing! 
Keep up the good work! :smile:

**Comment by bhilburn** [comment]
Glad you're all set, and I'm happy you're a P9k user! =)
