### ISSUE TITLE
Virtual environment Icon

### ISSUE THREAD

**Issue by ralpheeee88** [bhilburn/powerlevel9k#485]
is it possible to get an icon for virtual environment?

https://i.imgur.com/4ujSneD.png

**Comment by bhilburn** [comment]
@ralpheeee88 - Sure! So, that segment, by default, uses the `PYTHON_ICON`:
https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L1193

You should be able to change that icon directly using the methods here:
https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#icon-customization

**Comment by ralpheeee88** [comment]
@bhilburn super... Thxs chief
