### ISSUE TITLE
Powerlevel 9K does not work in the PyCharm terminal

### ISSUE THREAD

**Issue by dheerajchand** [bhilburn/powerlevel9k#510]
When I try to use the terminal in PyCharm, I get the following errors:

```/Users/dheerajchand/.oh-my-zsh/custom/themes/powerlevel9k/functions/icons.zsh:134: character not in range
/Users/dheerajchand/.oh-my-zsh/custom/themes/powerlevel9k/functions/utilities.zsh:86: command not found: print_icon
powerlevel9k_vcs_init:32: command not found: print_icon
powerlevel9k_vcs_init:33: command not found: print_icon
powerlevel9k_vcs_init:43: command not found: print_icon
powerlevel9k_prepare_prompts:4: command not found: print_icon                                                                                                                         
left_prompt_segment:24: command not found: print_icon
left_prompt_segment:44: command not found: print_icon
prompt_dir:4: character not in range
powerlevel9k_prepare_prompts:4: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
   3.16                                                                                                                                                            23:34  01.05.17 
```

In my normal terminal, oh-my-zsh works fine. Here are the relevant settings.

```# Powerlevel 9k things

#POWERLEVEL9K_MODE='awesome-patched'
DEFAULT_USER="$(whoami)"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon load context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv time)
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

#POWERLEVEL9K_CUSTOM_TIME_FORMAT="%D{\uf017 %H:%M:%S}"
POWERLEVEL9K_TIME_FORMAT="%D{\uf017 %H:%M \uf073 %d.%m.%y}"

POWERLEVEL9K_STATUS_VERBOSE=false

POWERLEVEL9K_PROMPT_ON_NEWLINE=true```

Any advice?

**Comment by onaforeignshore** [comment]
`print_icon` lives in `functions/icons.zsh`. It might be that there is an issue sourcing that file?

**Comment by iScrE4m** [comment]
On my 2 laptops and 1 pc powerlevel9k works just fine in PyCharm (well except for cutting awesomefonts in half, but that's not powerlevel's issue).  

Do you have correct Shell path in Settings (Tools->Terminal) - it should have '/bin/zsh'. In the options below I have everything checked.

**Comment by bhilburn** [comment]
Hey @dheerajchand - any thoughts on the comments, above?

**Comment by dheerajchand** [comment]
Oh my goodness, GitHub alerts did not tell me you guys had responded!

Pycharm has the right shell set, I did check that. I reinstalled Power
level 9k as well before posting, but I will check the install again!

On May 9, 2017 8:17 PM, "Ben Hilburn" <notifications@github.com> wrote:

Hey @dheerajchand <https://github.com/dheerajchand> - any thoughts on the
comments, above?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bhilburn/powerlevel9k/issues/510#issuecomment-300346239>,
or mute the thread

**Comment by dritter** [comment]
@iScrE4m Awesome! We had some complaints about P9K not working in the builtin JetBrains-Shell. Could you try [this fix](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#icons-are-cut-off) for the cut-off icons (well it's for Konsole, but it might work on the PyCharm shell as well)?

**Comment by iScrE4m** [comment]
It's not ZSH specific, even editing in VIM - space doesn't help. http://i.imgur.com/9IeyVCL.png

**Comment by dritter** [comment]
What a pity. But thanks for testing @iScrE4m

**Comment by bhilburn** [comment]
Closing this one due to inactivity. Feel free to re-open if there is something further to discuss!
