### ISSUE TITLE
2 lines,icon

### ISSUE THREAD

**Issue by GuanAllen** [bhilburn/powerlevel9k#512]
There are spaces before entering the text
macOS
<img width="1059" alt="screenshot 2017-05-03 at 03 41 18 pm" src="https://cloud.githubusercontent.com/assets/14134195/25651697/fdb1301e-3016-11e7-806d-e5b2fb5314c5.png">

**Comment by bhilburn** [comment]
Does this bit from the troubleshooting guide apply?

https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#strange-character--segment-spacing

**Comment by GuanAllen** [comment]
Yes,Thanks.
I have some icon not work.
POWERLEVEL9K_MODE='awesome-fontconfig'
<img width="380" alt="screenshot 2017-05-04 at 05 09 40 pm" src="https://cloud.githubusercontent.com/assets/14134195/25697181/8d45ad6a-30ec-11e7-98c1-41a077544224.png">

**Comment by bhilburn** [comment]
What font are you using and how did you install it?

**Comment by GuanAllen** [comment]
follow [this](https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X)

**Comment by GuanAllen** [comment]
I use [this](https://github.com/ryanoasis/nerd-fonts), that works.
<img width="452" alt="screenshot 2017-05-05 at 08 25 56 pm" src="https://cloud.githubusercontent.com/assets/14134195/25745355/1a994c32-31d1-11e7-9adb-601ccd35908c.png">

**Comment by onaforeignshore** [comment]
To fix the sizing issue, tick "Use a different font for non-ASCII text" and set the font to 13pt DejaVu Sans Mono Oblique for Powerline.

**Comment by GuanAllen** [comment]
not fix
<img width="544" alt="screen shot 2017-05-11 at 09 10 29 pm" src="https://cloud.githubusercontent.com/assets/14134195/25950684/4ca96628-368e-11e7-8c55-04dd63554ece.png">
<img width="298" alt="screen shot 2017-05-11 at 09 09 37 pm" src="https://cloud.githubusercontent.com/assets/14134195/25950655/3c72c600-368e-11e7-88ce-6c70fd00baea.png">

**Comment by onaforeignshore** [comment]
You can set the Font to DejaVu Sans Mono for Powerline and the Non-ASCII Font to the nerd font to solve the issues or you can use the nerd font for both. The Powerline font does not contain the code points (icons) for the missing icons.

**Comment by GuanAllen** [comment]
Thanks.
