### ISSUE TITLE
Exclude specific vcs directory

### ISSUE THREAD

**Issue by hackel** [bhilburn/powerlevel9k#522]
Please provide a way to support excluding a specific directory from VCS display.  oh-my-zsh does this by setting `oh-my-zsh.hide-status=1` in a repo's git config.  It would be nice to support this, though I think it would be even better if this could be done in a standardized way.

**Comment by bhilburn** [comment]
This functionality is provided  by ZSH`s `VCS_INFO` module, which is what P9k uses. The VCS_INFO module actually provides a pretty straight-forward way of doing this with the `disable-patterns` flag:
http://zsh.sourceforge.net/Doc/Release/User-Contributions.html

We can probably make a new P9K flag, which you can define as a list of directories, that gets fed to `disable-patterns` at VCS_INFO's init.

Thanks for the suggestion!

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
