### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by dakky** [bhilburn/powerlevel9k#527]
Hello ;)

I'm also having trouble with the icons. Here is my setup:

- OS X
- Iterm2

Config: Copied from here: https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#semartins-configuration

```
POWERLEVEL9K_MODE='awesome-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"
```

This results in:
![image](https://cloud.githubusercontent.com/assets/579584/26025365/2d32af62-37e6-11e7-8c35-4ce9b029dd4d.png)

From reading around here, I understand that i have a problem with my fonts. But I don't know why. 
Obviously I installed the wrong ones ;)

Any idea howto fix that?

**Comment by dritter** [comment]
Hi @dakky 😉 
Is your `POWERLEVEL9K_MODE` variable at the top of your `~/.zshrc` file? It should be at least before you source your ZSH framework (which seems to be oh-my-zsh)..

If that does not solve the issue:
Is your fontconfig [set up correctly](https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X)?

**Comment by dakky** [comment]
hmm medium improvements:
![image](https://cloud.githubusercontent.com/assets/579584/26025860/ef7aa43a-37f0-11e7-9ddb-c2cc14f38b8b.png)
 When using font-awesone.ttf **some** of the icons appear, but the font is **really** ugly. :(

**Comment by dritter** [comment]
That is the trick of `fontconfig`. You configure a font cascade, in which order fontconfig looks if the icon exists, and if not tests the next font. By using font-awesome.ttf directly, you get the icons from this font only, which is why not all are displayed. You should select the main font in the iTerm settings.

Did you follow all steps from the wiki page I posted successfully?

**Comment by dakky** [comment]
Ha! must have doen something wring the first try. Now it worked fine! I have to chose another font in iTerm (SourceCodePro+Powerline+Awesome Regular 14, found it via google)

Just for educational purpose:

What was I doing there? Did i understand it correctly:
1. I modified the way, OSX is looking for font icons by modifying the order of how is looked for missing icons, if not in the present font
2. by using SourceCodePro+Powerline+Awesome Regular as font in iTerm i get the "default" icons via search order an the special icons via selecting the "patched" font?

**Comment by dritter** [comment]
So you switched to a pre-patched font. ;)

To answer your questions:

1. Partially, yes. AFAIK the program you use has to support fontconfig. If it does, then yes, the behaviour has changed. But I am not sure about this.. 

2. Not sure if I understand correctly. iTerm has two settings for fonts: One for "normal" characters (ASCII alphabet, numbers etc) and one for the non-ascii characters. At least you need to set the latter one to the patched font. That way you'll get the special icons. The first one you could set to whatever you want. There is a little caveat in there: Font sizes might differ, so the icons (especially the segment separators - a.k.a. the powerline glyphs) might not match the background color.
So the safest is to set both settings to the patched font.
