### ISSUE TITLE
Idea: Support for other (arbitrary?) prompts

### ISSUE THREAD

**Issue by docwhat** [bhilburn/powerlevel9k#528]
There are a bunch of other prompts that would be cool to be able to style:

- `PS2` – Secondary prompt. AKA `PROMPT2`
    > The secondary prompt, printed when the shell needs more information to complete a command. Recognizes the same escape sequences as `$PS1`. The default is `%_> `.
- `RPS2` –Secondary prompt on right-hand side.
    > This prompt is displayed on the right-hand side of the screen when the primary prompt is being displayed on the left. This does not work if the `SINGLE_LINE_ZLE` option is set. Recognizes the same escape sequences as `PROMPT`.
- `PS3` – Selection prompt. AKA `PROMPT3`
    > Selection prompt used within a select loop. Recognizes the same escape sequences as PS1. The default is `?# `.
- `PS3` – xtrace (`set -x`) prompt. AKA `PROMPT4`
    > The execution trace prompt. Default is `+ `.

If powerlevel9k was turned into a generic method, it could be used in other places.  Example (hypothetical) of usage:

``` sh
my_left_prompt=(
os_icon
context
dir
dir_writable
rbenv
root_indicator
background_jobs
status
)
PROMPT="$(powerlevel9k left my_left_prompt)"
```

Then this could be expanded to work with arbitrary left and right prompts, include `zle` prompts, etc.

**Comment by bhilburn** [comment]
This is a really interesting idea, @docwhat. 

It strikes me that if we provided a way to call into P9k as a function, it could be used in non-prompt applications, as well. An example is a `tmux` statusline, for example. Thoughts, here? Too crazy?

**Comment by docwhat** [comment]
It would then be a hybrid function/command.

You create a zsh `function` file to be added to the user's `fpath` and a wrapper shell command that pull in that function and uses it.

The problem I see with a "command" version is that local environment variables (ones that haven't been exported) won't be available.  That may or may not be a problem, but it would be an iteresting experiment.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
