### ISSUE TITLE
Date command in multiline second prefix is not executed each time

### ISSUE THREAD

**Issue by Shini31** [bhilburn/powerlevel9k#532]
Hello,

My date command in my multiline second prefix isn't executed each time:
![bug_date_command](https://cloud.githubusercontent.com/assets/333820/26287150/5bd6fdec-3e75-11e7-98c8-12c2b55d64ac.png)

Here is my configuration:
```
POWERLEVEL9K_MODE="awesome-fontconfig"
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{0252}%F{black} \Uf017 `date +%T` %f%k%F{0252}%f "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(background_jobs status_joined context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(ip)
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_IP_BACKGROUND="252"
POWERLEVEL9K_IP_FOREGROUND="black"
POWERLEVEL9K_TIME_BACKGROUND="cyan"
POWERLEVEL9K_TIME_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="black"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="red"
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="black"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="red"
```

Any ideas ?
Regards

**Comment by dritter** [comment]
> isn't executed each time

Is it ever? I mean, to me it looks like your `POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX` is executed once when your `~/.zshrc` is sourced. So it will never be updated.
It should work if you set it in single quotes, as your subshell-call to `date` will be evaluated every time.
`POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX='%K{0252}%F{black} \Uf017 `date +%T` %f%k%F{0252}%f '`

**Comment by Shini31** [comment]
Yes it is. There is no explanation in the wiki on that.

With you suggestion, i got there.
Here is the good line:

```POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX='%K{0252}%F{black} \Uf017 %D{%H:%M:%S} %f%k%F{0252}%f '```

Thank you for your help.
