### ISSUE TITLE
Icons not showing even with right font

### ISSUE THREAD

**Issue by Drakota** [bhilburn/powerlevel9k#534]
Hi, I was trying to get the theme working on my shell and I got this : 
![screenshot from 2017-05-23 13-35-00](https://cloud.githubusercontent.com/assets/22665836/26367815/dfa8e9ca-3fbd-11e7-87f3-0832eb0510f6.png)
Lx should be a Linux Icon and Dur a clock, but it doesn't work.  If I try to resize my terminal I get this:
![screenshot from 2017-05-23 13-35-28](https://cloud.githubusercontent.com/assets/22665836/26367854/035dc4da-3fbe-11e7-91b7-90a5d513a081.png)
I have the right font selected in the preferences: 
![screenshot from 2017-05-23 13-36-17](https://cloud.githubusercontent.com/assets/22665836/26367929/286aa586-3fbe-11e7-946d-9d01008021a9.png)
And my .zshrc looks like this:
```
export PATH=$PATH:~/.composer/vendor/bin
export ZSH=/home/drakota/.oh-my-zsh
source  ~/.oh-my-zsh/themes/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k.zsh-theme
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=245
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(root_indicator background_jobs command_execution_time time)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_MODE='nerdfont-complete'
source /usr/share/zsh/antigen.zsh
antigen use oh-my-zsh
antigen theme bhilburn/powerlevel9k powerlevel9k
antigen apply
```
Thanks for helping.

**Comment by dritter** [comment]
Yep. That is because you need to set the config before you source the theme. That seems to be an accident, as you source the theme directly and via antigen..

It should work if you remove this line:
```zsh
source  ~/.oh-my-zsh/themes/powerlevel9k/powerlevel9k.zsh-theme
```

**Comment by Drakota** [comment]
You are right I didn't remove it.
Now my shell looks like this though.
![image](https://cloud.githubusercontent.com/assets/22665836/26375106/aa1d6ee4-3fd5-11e7-82df-d3136c270ee6.png)

**Comment by dritter** [comment]
Problem solved.. 😆 

Hmm. So it looks like your antigen does not apply the theme correctly. We had recently some issues (see #457) with antigen..
One way to fix this is to replace `antigen theme bhilburn/powerlevel9k powerlevel9k` with the `source` line..
I hope that helps.

**Comment by Drakota** [comment]
Never mind fixed it! 

.zshrc
```
export ZSH=/home/drakota/.oh-my-zsh
POWERLEVEL9K_INSTALLATION_PATH="${HOME}/.antigen/bundles/bhilburn/powerlevel9k"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=245
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(root_indicator background_jobs command_execution_time time)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_MODE='nerdfont-complete'

source /usr/share/zsh/antigen.zsh
antigen use oh-my-zsh

antigen bundle robbyrussell/oh-my-zsh plugins/gitfast
antigen theme bhilburn/powerlevel9k powerlevel9k
antigen apply
```
Forgot `POWERLEVEL9K_MODE`

**Comment by dritter** [comment]
Awesome!

Btw. that `ZLE_RPROMPT_INDENT=0` line will give you some trouble while tabbing.. We saw some issues with that. I recommend to remove it (and accept that whitespace at the right)..

**Comment by Drakota** [comment]
Yes, I saw that. Is there an ETA on when is this gonna be fixed? And minor detail, but I still get weird symbols if I resize is it normal?

**Comment by bhilburn** [comment]
@Drakota - Unfortunately, that's an issue in ZSH, not P9k.

See this comment for more: https://github.com/bhilburn/powerlevel9k/issues/420#issuecomment-283753317

**Comment by Drakota** [comment]
Oh alright, thanks for the heads-up.
