### ISSUE TITLE
`vpn` Segment Needs macOS Support

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#540]
Per @onaforeignshore's comment in #539: https://github.com/bhilburn/powerlevel9k/pull/539#issuecomment-305855991

The `vpn` segment currently does not support macOS. @onaforeignshore offered a way to implement this in #538:

>On macOS, VPN IP address can be found using: 
`ifconfig ppp0 | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}'`. If VPN is inactive the result is ifconfig: interface ppp0 does not exist

This simply needs to be conditionalized into the `vpn` segment code. If someone with a Mac is interested in taking this on and testing it, that would be great.

Stretch goal: unit tests for this segment =)

**Comment by guidoilbaldo** [comment]
Hi @bhilburn,

just sharing my thoughts on this. The solution proposed by @onaforeignshore will work only with PPTP VPNs, while using other common tools (for a Mac OS user), for example OpenVPN or Tunnelblick, will result in having net ifaces with different names - respectively tun0 and utun0.
I would think of something more generic, then I'll be glad to help with the troubleshooting :)
Thanks again for the great work everyone's doing here!

**Comment by bhilburn** [comment]
@guidoilbaldo - That's good to know, @guidoilbaldo! Thanks so much for the input! It's much appreciated.

**Comment by golgoth31** [comment]
Hi, I made a test on tunnelbrick and it works; the default value is "tun" but it can be overridden in zshrc.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
