### ISSUE TITLE
Syntax error: "elif" unexpected line 29

### ISSUE THREAD

**Issue by max223** [bhilburn/powerlevel9k#542]
Hi ! Just installed the theme with antigen, everything look to run well, but anytime i open the terminal, it will find an error in the theme  : 

> /home/rogiss_m/.antigen/bundles/bhilburn/powerlevel9k/powerlevel9k.zsh-theme: 29: /home/rogiss_m/.antigen/bundles/bhilburn/powerlevel9k/powerlevel9k.zsh-theme: Syntax error: "elif" unexpected

Can somebody help me with this one ? find it very ugly and disturbing :/ 

`

**Comment by zikes** [comment]
Could you share your `.zshrc` file?

**Comment by bhilburn** [comment]
Closing this one due to inactivity.

Feel free to re-open, @max223, if you still need help!
