### ISSUE TITLE
load and ram classes

### ISSUE THREAD

**Issue by guidoilbaldo** [bhilburn/powerlevel9k#544]
Hi guys,

I had no luck in finding thresholds to tweak for these 2 classes. I mean, my load becomes yellow as soon as CPU utilization goes above 2% and red as soon as it goes above 3%. In the same way, with a browser open and during common usage, I have 2GBs of RAM always used but the color prompted is, again, yellow.

I would like to set these thresholds based on my effective usage of the laptop. Is this possible?
Best,
Stefano

**Comment by dritter** [comment]
Hi @guidoilbaldo !

So, you suggest that the `ram` segment should change color like the `load` segment, right? That is not possible right now, which makes this issue a feature request ;)

**Comment by guidoilbaldo** [comment]
well, in fact the `ram` segment would be a feature request, yes. But currently my main problem is that the `load` one is not behaving like expected. I mean, it's colored green when CPU is under 2% of usage, it's yellow when it stays between 2% and 3% and it becomes red after 3% up to 100%.

How does that suppose to behave? I guess red segment should be over 70%-80% of CPU utilization, yellow up to 50% and green otherwise, right?

**Comment by zikes** [comment]
The `load` segment doesn't necessarily measure CPU utilization percentage. It uses the `/proc/loadavg` (or your OS's equivalent) command, which returns "the number of jobs in the run queue (state R) or waiting for disk I/O (state D) averaged over 1, 5, and 15 minutes". The `load` segment then divides this by the number of cores in the machine to determine core utilization and sets the segment color state accordingly. In your case, if you have 4 cores then 2.0 or over would be 50% or more utilization, and `load` would be in the orange "warning" state.

I think this could be clarified in the p9k documentation, as it assumes some familiarity with the `/proc/loadavg` format.

**Comment by guidoilbaldo** [comment]
thank you @zikes for the explanation. I'll close this as it's not an issue :) and I'll go study /proc/loadavg better!

**Comment by guidoilbaldo** [comment]
Just some more information about this: Mac OS does not have /proc/loadavg command.
We rely on `sysctl -n vm.loadavg` that only shows the number of jobs in the last 1,5 and 15 minutes. No more information is provided with this command, so probably `load` segment in powerlevel9k for Mac OS is not complete.

**Comment by bhilburn** [comment]
Hm, it sounds like we need to make this segment a bit more intuitive overall.

That said, I'm not sure I understand @guidoilbaldo's latest comment about macOS. To me, it sounds like `sysctl -n vm.loadavg` provides the exact same information as `/proc/loadavg`? I don't have a mac, so can't test - perhaps I'm misunderstanding?

**Comment by guidoilbaldo** [comment]
Here's an example:

- /proc/loadavg on CentOS
`[root@centos ~]# cat /proc/loadavg
0.23 0.24 0.23 1/267 9894`
- sysctl -n vm.loadavg on Mac OS
` ❯ sysctl -n vm.loadavg
{ 1.57 1.94 1.97 }`

hope this helps :)

**Comment by tadeoos** [comment]
Yes, they provide the same information. 
By the way, I've made a PR #605 that adds ability to choose which load average you want to see ;)

**Comment by dritter** [comment]
#605 is already merged. I close this issue for now. @guidoilbaldo If you think the problem still persists, feel free to reopen.

Thanks for helping @zikes and the PR @tadeoos .

**Comment by bhilburn** [comment]
Thanks for the house-keeping, @dritter  =)
