### ISSUE TITLE
The GPG Signing-Key for the releases has expired

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#545]
Hello @bhilburn,
your GPG key is expired. You can adjust the expiration date in the key via GPG. Just want to mention this :)

**Comment by bhilburn** [comment]
Hah! You're right - it expired yesterday. I'll take care of that...

**Comment by bhilburn** [comment]
Done! =)

http://pgp.mit.edu/pks/lookup?op=vindex&search=0xECD0D0410C149675
