### ISSUE TITLE
Question about zsh_highlight_styles

### ISSUE THREAD

**Issue by zer09** [bhilburn/powerlevel9k#550]
Hello I need help, I just copied the config V1gur's config, and change and change the default_user and zsh export location. but i am getting this error.

```/.zshrc:45: ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range```

I dont have any idea has to fix this.

Please help me, thanks.

P.S. new linux user here.

**Comment by zer09** [comment]
I did manage to fix the issue above but I  am facing this now.
I will attach a screenshoot.
![screenshot from 2017-06-15 09-57-36](https://user-images.githubusercontent.com/780780/27162323-34be3d6e-51b3-11e7-92b5-ac910b8649a3.png)

I am seeing the ```print_icon``` command and on the git part the icon show is the ```female symbol```.
any suggestion how to fix this?

thanks.

**Comment by V1rgul** [comment]
The fontconfig configuration is invalid since the update of awesome-terminal-fonts.
You need to checkout the pull request #472 :)

**Comment by zer09** [comment]
Thank you so much, finally made it. But one more last thing. How I can fix the vertical lines on my left elements?
![screenshot from 2017-06-15 22-33-58](https://user-images.githubusercontent.com/780780/27186648-92dde990-521b-11e7-9217-b3b5583004b7.png)
sorry to bother you to much.

thanks :)

**Comment by V1rgul** [comment]
The Powerline font from fontconfig isn't perfectly aligned with DejaVu Mono, so I found a prepatched one :
You need to use this one https://github.com/powerline/fonts/tree/master/DejaVuSansMono and follow this : https://github.com/bhilburn/powerlevel9k/issues/370#issuecomment-290494529

**Comment by mavam** [comment]
For the record: I'm encountering [the same symptom](https://github.com/ryanoasis/nerd-fonts/issues/26#issuecomment-305974861) due to a bug in the patched nerd fonts (which is supposed to be fixed in the next release).

**Comment by bhilburn** [comment]
Thanks, @mavam.

We usually see that problem with this: https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#gaps-between-segments

Thanks for the heads-up on the nerd-fonts issue!

**Comment by zer09** [comment]
@V1rgul I tried it but with no luck, I am unable to build the awesome-terminal-fonts because of fontforge-python bindings. I already tried installing fontforge using dnf but still i failed to build it, also tried to find fontforge on pip but got no luck.

If you don't mind can I ask your patched  awesome-terminal-fonts, if it just ok? :)

@bhilburn is there a plan that this would be fix in the future? :)

Thanks

**Comment by V1rgul** [comment]
They are available here : https://github.com/V1rgul/dotfiles/tree/master/files/.fonts :)

**Comment by zer09** [comment]
Thank you so much. :+1:

**Comment by pejkosz94** [comment]
@zer09 how did you manage to solve problem with `ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range`? I tried moving `source` above/under `HIGHLIGHT` but nothing changed.

**Comment by zer09** [comment]
@pejkosz94  if I remember it correctly, it was just pointing to invalid file.
Try to give it an absolute path.

This is a part of my config.
```
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
# /!\ do not use with zsh-autosuggestions

plugins=(k tig gitfast colored-man colorize command-not-found cp dirhistory autojump sudo zsh-syntax-highlighting)
# /!\ zsh-syntax-highlighting and then zsh-autosuggestions must be at the end

source /home/user/git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/oh-my-zsh.sh
# source ~/.fonts/*.sh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[cursor]='bold'

ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=green,bold'


rule () {
    print -Pn '%F{blue}'
    local columns=$(tput cols)
    for ((i=1; i<=columns; i++)); do
        printf "\u2588"
    done
```

**Comment by tliss** [comment]
Thanks for that @zer09! I was able to resolve my highlighting error by doing the following:

`sudo apt-get install zsh-syntax-highlighting`

Then locating the zsh-syntax-highlighting.zsh file with:

`find / -mount -name "zsh-syntax-highlighting.zsh"

And adding the path it gave me to my .zshrc file like you did!

`source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`
