### ISSUE TITLE
Can't find configuration to show only last dir name

### ISSUE THREAD

**Issue by FreddieOliveira** [bhilburn/powerlevel9k#552]
With all fancy complexity directory naming configuration
POWERLEVEL9K_SHORTEN_DIR_LENGTH
POWERLEVEL9K_SHORTEN_DELIMITER
POWERLEVEL9K_SHORTEN_STRATEGY
etc, I couldn't find any combination to show only the last dir name offered by the simple %1~
Eg.
~/Documents/I_symply_want_to_show_the_last_name/movies/last_name
would become
last_name

**Comment by dritter** [comment]
Well. More or less:
```zsh
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_folders
```
And, if you want to get rid of the abbreviation:
```zsh
POWERLEVEL9K_SHORTEN_DELIMITER=""
```

To pick up your example:
`~/Documents/I_symply_want_to_show_the_last_name/movies/last_name` would become `…/last_name`, and if you set the delimiter to blank, you'll get `/last_name`.

**Comment by FreddieOliveira** [comment]
Hmm, nice. If I add `POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true` I get exactly what I want. But if the direcotry contains only one char, as in the case when I'm at home dir, the omit char option will disappear with the ~

**Comment by bhilburn** [comment]
As in you want to also remove the leading `/` from the filename?

Hm, don't think we actually have an option to do that, honestly. It would be fairly easy to modify the code for this, if you were so inclined, but I don't think we have a way to only show the parent dirname.

Am I correct on that, @dritter? If so, this option would be a fairly easy feature to add since there isn't much logic to it.

**Comment by FreddieOliveira** [comment]
I want an exactly behaviour as in `%1~`. I had indded modified `powerlevel9k.zsh-theme` line `623` from  `local current_path="$(print -P "%~")"` to
`local current_path="$(print -P "%1~")"`
since it was the only way I found to achieve this. Maybe you guys could add an option to this :)

**Comment by dritter** [comment]
As said, there is no easy way to achieve exactly the same as `%1~`..

But I found a hacky way, without changing the code in the theme..

![bildschirmfoto 2017-06-23 um 23 23 33](https://user-images.githubusercontent.com/1544760/27500998-1d7a8068-586b-11e7-8003-e14409977bfd.png)

The Idea is to override the `prompt_dir` function, and set `POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER` dynamically.
```zsh
# Backup original prompt_dir function to _prompt_dir
eval "`declare -f prompt_dir | sed '1s/.*/_&/'`"
prompt_dir() {
  # Never omit first character
  POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false
  # Except if current directory is longer than one character
  local currentDirectory=$(print -P "%~")
  [[ ${#currentDirectory} -gt 1 ]] && POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

  # Call original prompt_dir function
  _prompt_dir "${1}" "${2}"
}
```
That code must be after you source P9K. I put it in my `~/.zshrc` at the very end.

@bhilburn I agree, we should put such an option into the theme. Maybe we could give `POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER` more logic. ;)

**Comment by bhilburn** [comment]
@dritter - Nice hack! Very clever :)

@FreddieOliveira - Does @dritter's hack work for you?

I'm going to leave this issue open as a tracking item for the enhancement. I agree with @dritter - this would be a good thing to add to the `OMIT_FIRST_CHARACTER` logic.

**Comment by FreddieOliveira** [comment]
Thanks for the attention guys. Now I've got exactly what I wanted :+1: The hack works perfectly and is an ugly but functional replacement for the `%1~`
: P

**Comment by faewin** [comment]
@dritter With the hack above, what would be the best way to change the color of the foreground?

After using the workaround, the foreground went into the default black text despite having the code below in my .zshrc

`POWERLEVEL9K_DIR_HOME_FOREGROUND="white"`
`POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"`
`POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"`

**Comment by dritter** [comment]
@faewin Sorry, just stumbled upon your comment.

The answer lies in how we generate that color overwrite variable names. In our very basic `*_prompt_segment` functions we take the name of the actual segment and substitute `prompt_` (this is how we name the segments internally `prompt_dir`, `prompt_vcs`, etc) from the name and check if a back or foreground variable exists. So, now that we redeclared our `prompt_dir` function to `_prompt_dir` (note the underscore in the beginning), this mechanism does not work any more. The same applies to other variable names as well (like `*_VISUAL_IDENTIFIER`).
Disclaimer for both solutions: The `prompt_dir` function checks internally for some variables. Here the name is hardcoded. So, if you use these variables, they do not get renamed.

### Solution 1

Short, but ugly: Rename your variables as if the segment name was never stripped. Rename your variables to `POWERLEVEL9K__PROMPT_DIR_HOME_FOREGROUND="white"` (double underscore here).

Btw. if you want to set all segments to white foreground color, you might try setting `POWERLEVEL9K_COLOR_SCHEME='light'`. That might not set foreground always to white, but probably in a lot of cases.

### Solution 2

Change the redeclared name to something else:
```zsh
# Backup original prompt_dir function to prompt_my_dear
eval "`declare -f prompt_dir | sed '1s/.*/prompt_my_dear() {/'`"
prompt_dir() {
  # Never omit first character
  POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false
  # Except if current directory is longer than one character
  local currentDirectory=$(print -P "%~")
  [[ ${#currentDirectory} -gt 1 ]] && POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

  # Call original prompt_dir function
  # no pun intended
  prompt_my_dear "${1}" "${2}"
}
```

The tricky part is how the `declare` statement works. `declare -f prompt_dir` outputs the source of `prompt_dir`, and we pipe that output through `sed` to replace the function name with something else. This whole expression gets evaluated and is by that a real function in your shell.

With this approach your color variables should be renamed to `POWERLEVEL9K_MY_DEAR_FOREGROUND="white"`..

**Comment by bhilburn** [comment]
Going to close this one out due to staleness, and the fact that this should be a bit easier in our new codebase, so this discussion isn't totally relevant anymore.

**Comment by nathanielevan** [comment]
A year late to the party, but:
> this should be a bit easier in our new codebase
Is there now an easier, more straightforward solution to the issue above? This is pretty much my only niggling issue with powerlevel9k; overall, it's an awesome little thing, keep up the good work. :)

**Comment by romkatv** [comment]
@nathanielevan You are in luck. There is indeed a straightforward solution: `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last`.

**Comment by nathanielevan** [comment]
It works, thank you!

**Comment by romkatv** [comment]
You are very welcome.
