### ISSUE TITLE
Prompt hangs when using Kubecontext and minikube

### ISSUE THREAD

**Issue by derekbassett** [bhilburn/powerlevel9k#553]
When using the functionality on the `next` branch kubecontext.  If someone has minikube installed locally and is currently pointing to minikube for kubernetes context.  Zsh will hang for several seconds for each prompt and ^C does not terminate, on the `kubectl version` command.  As the `kubectl version` command is designed to just test to see if you have kubernetes installed a `kubectl version --client` will suffice.

**Comment by bhilburn** [comment]
Fixed by merge of #554
