### ISSUE TITLE
Change Foreground of VirtualEnv

### ISSUE THREAD

**Issue by svaderia** [bhilburn/powerlevel9k#564]
I want to change the foreground of virtualenv element.
I tried to search in Readme and wiki but I couldn't find it, 
I tried to use,
```
POWERLEVEL9K_VIRTUALENV_BACKGROUND="blue"
POWERLEVEL9K_VIRTUALENV_FOREGROUUND="white"
```
but it didn't work.
Can anyone please guide me to the correct place.
Thanks.

**Comment by dritter** [comment]
Well. That should work, if:
1. you choose another background than the default blue.
2. you fix your typo in the foreground variable name.

This works:
```zsh
POWERLEVEL9K_VIRTUALENV_FOREGROUND="white"
POWERLEVEL9K_VIRTUALENV_BACKGROUND="red"
```
![bildschirmfoto 2017-07-09 um 00 00 19](https://user-images.githubusercontent.com/1544760/27989473-cef2d726-6439-11e7-894e-3813479cdb33.png)

**Comment by bhilburn** [comment]
@svaderia - I'm assuming you're up and running, now? If not, please re-open and let us know what's going on! `=)`

**Comment by svaderia** [comment]
@bhilburn Yeah it's up and running, sorry for late reply.
@dritter Thanks for quick response!
