### ISSUE TITLE
Home folder shows as …/~ rather than ~ initially

### ISSUE THREAD

**Issue by unikitty37** [bhilburn/powerlevel9k#565]
When I start a new shell, the home directory shows in the prompt as "…/\~" rather than just "\~". If I cd to another directory and then back to home, it shows correctly as "~".

![screen shot 2017-07-09 at 14 02 35](https://user-images.githubusercontent.com/139183/27994151-954c125a-64af-11e7-9597-33b6dd460184.png)

Relevant sections of my .zshrc:
```zsh
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_folders"
```

Interestingly, this is happening on macOS 10.12.5 with zsh 5.2, but not on Linux with zsh 5.3.1 or zsh 5.1.1. Apart from differing colours, I have the same options in the .zshrc on all three systems.

**Comment by unikitty37** [comment]
When I start a new shell, the home directory shows in the prompt as "…/~" rather than just "~". If I cd to another directory and then back to home, it shows correctly as "~".

![screen shot 2017-07-09 at 14 02 35](https://user-images.githubusercontent.com/139183/27994151-954c125a-64af-11e7-9597-33b6dd460184.png)

Relevant sections of my .zshrc:
```zsh
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_folders"
```

Interestingly, this is happening on macOS 10.12.5 with zsh 5.2, but not on Linux with zsh 5.3.1 or zsh 5.1.1. Apart from differing colours, I have the same options in the .zshrc on all three systems.

**Comment by bhilburn** [comment]
@unikitty37 - Hah, yup, that's bizarre. I'm using ZSH 5.2 on Linux and don't see this.

It's likely that I'll be a macOS user in a couple of weeks, but right now I don't have a mac available to me. It's really obnoxious that we can't easily set up test VMS (e.g., Vagrant, Docker) for macOS...

@dritter - Would you mind replicating @unikitty37's settings and testing to see if you can reproduce this?

**Comment by unikitty37** [comment]
I'll leave all the oh-my-zsh stuff here in case it helps:

```zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME='powerlevel9k/powerlevel9k'

export POWERLEVEL9K_MODE='nerdfont-complete'
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv history)
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{195}\u250c\u2574%F{252}'
export POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX='%F{195}\u2514\u25b8%F{252} '
export POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# colours for Mac
export POWERLEVEL9K_OS_ICON_BACKGROUND="247"
export POWERLEVEL9K_OS_ICON_FOREGROUND="255"

# colours for desktop
export POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="196"
export POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="255"
export POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="090"
export POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="253"

export DEFAULT_USER="slacker"
export POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
export POWERLEVEL9K_ALWAYS_SHOW_USER=false

export POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="136"
export POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="233"
export POWERLEVEL9K_DIR_HOME_BACKGROUND="178"
export POWERLEVEL9K_DIR_HOME_FOREGROUND="233"
export POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="178"
export POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="233"
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_folders"

export POWERLEVEL9K_STATUS_VERBOSE=false
export POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
export POWERLEVEL9K_FAIL_ICON="\uf165"
export POWERLEVEL9K_OK_ICON="\uf164"

plugins=(git git-flow rbenv bundler brew gem cap zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
```

**Comment by bhilburn** [comment]
So, based on our discussion in #568, a change to our setup function that is coming in @dritter's `async` branch may actually fix this.

In the meantime, a quick hack might be to manually `cd` back to your home directory at the very end of your `zshrc`. Would you mind putting something like this at the bottom of your `zshrc`?

```
if [[ "$PWD" == "$HOME" ]]; then
  cd ~
fi
```

**Comment by unikitty37** [comment]
Not at all — but I've just tried it and it doesn't seem to make much difference. It's not a major problem — I'll wait and see if the `async` branch fixes it. Thanks!

**Comment by docwhat** [comment]
Is there a reason why the code doesn't use the ZSH builtin `%~` for the path?

**Comment by bhilburn** [comment]
@unikitty37 - I'm glad it solved your issue, and thanks for understanding!

@docwhat - Hah, nope. I just forgot to use it :-p
