### ISSUE TITLE
Custom prompt messed up cursor starting position

### ISSUE THREAD

**Issue by AnthonyWC** [bhilburn/powerlevel9k#572]
After I define a custom function and use it as part of POWERLEVEL9K_LEFT_PROMPT_ELEMENTS (or right), it messed up my prompt starting position:

Before:
![image](https://user-images.githubusercontent.com/6215805/28228454-9e9bfd4c-68ac-11e7-9f4f-4d4b95fd2d82.png)

After:
![image](https://user-images.githubusercontent.com/6215805/28228473-b1ff71ac-68ac-11e7-8d88-e55f1b0da458.png)

The custom function in this case uses echo -n to script out newline.

**Comment by dritter** [comment]
Hi!

Do you have `ZLE_RPROMPT_INDENT` set?
And what does your custom segment do?

**Comment by AnthonyWC** [comment]
I initially had `ZLE_RPROMPT_INDENT` set to 0; also tried to comment it out

I tried a few functions, for example a variation of the wifi example:

```
wifi_signal () {
    SSID=$(iwgetid -r)
    local signal=$(nmcli device wifi | grep "$SSID" | awk '{print $10}')
    local red='\033[0;31m'
    echo -n "${red}$signal%{%f%}"
} 
```

I also tried without %{%f%} (what does that exactly do?) which gave me the same apparent result.

**Comment by dritter** [comment]
Setting `ZLE_RPROMPT_INDENT=0` is known to have such an effect. Could you double check that this variable is commented out or set to 1?

**Comment by AnthonyWC** [comment]
Yes I tried both commenting it out and setting it to 1; same result.

**Comment by bhilburn** [comment]
@AnthonyWC - I wonder if another plugin might be setting it or changing the ZLE functions?

Can you share your `zshrc`, and also the output of `echo $ZLE_PROMPT_INNDENT`?

**Comment by bhilburn** [comment]
Hey @AnthonyWC, just a ping on this! =)

**Comment by AnthonyWC** [comment]
My .zshrc is ~1000 lines, here's a stripped down version that I think is most relevant below.  
I have tried setting ZLE_RPROMPT_INDENT to 0 or 1 or not set; didn't see to make any difference.

```
export COLORTERM=gnome-terminal
export TERM=xterm-256color
export ZSH=/home/antho/.oh-my-zsh
export HISTFILE=~/.zsh_history
export EDITOR=vi

fpath=(~/.zsh/completion $fpath)

POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="zsh_wifi_signal"
POWERLEVEL9K_MODE='flat'
POWERLEVEL9K_MODE='octicons-fontconfig'
POWERLEVEL9K_CUSTOM_WIFI="wifi_signal"
POWERLEVEL9K_CUSTOM_GCP="gcloud_profile"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv anaconda nvm rbenv rvm go_version vcs root_indicator docker_machine aws_eb_env aws load ram)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

ZSH_THEME="powerlevel9k/powerlevel9k"
autoload -Uz compinit && compinit -i

source $ZSH/oh-my-zsh.sh

eval `dircolors /home/antho/.dircolors`

source ~/.zplug/init.zsh

# http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/

setopt prompt_subst # enable command substition in prompt
PROMPT='$(PCMD)' # single quotes to prevent immediate execution
RPROMPT='' # set asynchronously and dynamically

# Right-hand prompt
RCMD() {
    if [[ "${PROMPT_MODE}" == 0 ]]; then
        echo "$(RPR_INFO)$(git_prompt_string)"
    elif [[ "${PROMPT_MODE}" == 1 ]]; then
        echo "$(git_prompt_string)"
    else
        echo ""
    fi
}

ASYNC_PROC=0

precmd () {
    async() {
        # save to temp file
        # printf "%s" "$(RCMD)" > "${HOME}/.zsh_tmp_prompt"

        # signal parent
        kill -s USR1 $$
    }

    # do not clear RPROMPT, let it persist

    # kill child if necessary
    if [[ "${ASYNC_PROC}" != 0 ]]; then
        kill -s HUP $ASYNC_PROC >/dev/null 2>&1 || :
    fi

    # start background computation
    async &! 
    ASYNC_PROC=$!
}

TRAPUSR1 () {
    # read from temp file
    RPROMPT="$(cat ${HOME}/.zsh_tmp_prompt)"

    # reset proc number
    ASYNC_PROC=0

    # redisplay
    zle && zle reset-prompt
}

plugins=(git sublime)
ENABLE_CORRECTION="true"                  # enable command auto-correction.
COMPLETION_WAITING_DOTS="true"            # display red dots @ waiting for completion
```

**Comment by bhilburn** [comment]
Hm, you seem to have a lot of custom stuff for `PROMPT` and `RPROMPT`. Can you describe what you are trying to do with those? I'm wondering if there is some incompatibility with that code and P9k, since P9k obviously sets all of those things, as well.

**Comment by AnthonyWC** [comment]
They are for meant for async prompt (see http://www.anishathalye.com/2015/02/07/an-asynchronous-shell-prompt/) but actually I commented it out and it didn't seem to make any difference. But actually I got it to work with the 2nd method:

`POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="echo signal: \$(nmcli device wifi | grep yes | awk '{print \$8}')"`
