### ISSUE TITLE
Misalignment at some font sizes

### ISSUE THREAD

**Issue by pikeas** [bhilburn/powerlevel9k#574]
iTerm2 with `POWERLEVEL9K_MODE='nerdfont-complete'` and the font set as the default as well as for non-ASCII.

Changing the font size with +/- results in some sizes which display perfectly, others which add a 1 pixel gap between the arrow and the segment, and others with no gap but vertical misalignment.

**Comment by bhilburn** [comment]
Hey @pikeas  -

Thanks for the bug report! Unfortunately, there isn't anything we can do about this one. The size of the particular font is actually different from nerdfont to nerdfont, and if you try a different one you'll likely see different behavior. There isn't a good way for us to mitigate this from within P9k, unfortunately.

If you're interested in more detail, check out [bug #430](https://github.com/bhilburn/powerlevel9k/issues/430) where we had a long discussion about this with input from nerdfonts creator & maintainer, @ryanoasis =)

**Comment by pikeas** [comment]
I'll check out the bug report! Please consider adding a note to the Nerd Font section of your README? Also, are any of the other patching or pre-patched fonts known to align correctly at multiple font sizes?

**Comment by bhilburn** [comment]
Adding a note to the README is a good idea.

Unfortunately, every font is different. I personally use Adobe SourceCode Pro, which has worked well a lot of different font sizes, but I haven't tested the nerd-font version.

**Comment by pikeas** [comment]
Sure, I guess my point is that a note along the lines of "Nerd Fonts often don't align at common sizes", or "most fonts tend to misalign at some sizes", or whatever is most accurate would be helpful.

Basically, I was very surprised to find that I can't freely choose a font and font size in the standard range (10-14pt) and have it work. It looks like a lot of fonts will tick-tock, aligning at say 12 pt, being off at 11, and good again at 10. It's not a deal breaker per se, but documenting this as a known limitation may save you a few open issues and spurious bug reports.

**Comment by pikeas** [comment]
Also, the linked issue is about double-width icons and icons appearing small, which doesn't seem related to this.

**Comment by bhilburn** [comment]
The specific symptom is different, but the cause is the same - everything comes down to what the specific font supports when it's patched for nerd-font distribution.

And yeah, a quick note clarifying the situation is a good call.

**Comment by ryanoasis** [comment]
@pikeas So 2 problems here if I am understanding correctly? One of horizontal gaps and the other of vertical offsets.

Can you tell me which Nerd Font you are using?

These issues should hopefully be mostly fixed when the fonts are all repatched for v1.1.0 release. You can see the progress of the separator characters in this issue and comment: https://github.com/ryanoasis/nerd-fonts/issues/26#issuecomment-309296604

I have just gotten back into working on v1.1.0 if you see the commits... so possibly could be ready by as soon as this weekend but no promises 😉 

Hope this is of some help or light at the end of the issue tunnel

**Comment by pikeas** [comment]
Hi @ryanoasis I'll try a few v1.1.0 fonts when the release lands and report back! Also, I'm not sure if this is useful, but there's some interesting back and forth on the same sort of issue at https://github.com/chrissimpkins/Hack/pull/234.

**Comment by ryanoasis** [comment]
@pikeas Thanks for the link! Also thanks for the willingness to report back and your understanding.

Interesting discussion and screenshots 😄 

I take it you use Hack then? 😏

**Comment by pikeas** [comment]
I've been using M+ 1mn with a tweaked version of Prezto's sorin theme for a few years. Fell down the font and theme rabbit hole this week when the Nerd Fonts patcher failed to produce aligned glyphs at all sizes in the range of 9-14 pt.

I'm currently using Iosevka while waiting to see what happens with the upcoming versions of Hack and NF. :-)

**Comment by ryanoasis** [comment]
Ah okay gotcha. Hah I totally get the rabbit hole. I started by creating a Vim plugin and it spun off into it's own project. Aren't fonts fun? 😏
