### ISSUE TITLE
Status icons use inconsistent font bolding

### ISSUE THREAD

**Issue by giogziro95** [bhilburn/powerlevel9k#576]
I have following the following setup:

```
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
```

When the exit status is OK, it returns a normal check mark (✓); when there's an error, it returns a heavy ballot X (✘). It'd be better if both were normal weight ones (✓, ✗) or heavy ones (✔, ✘).

**Comment by bhilburn** [comment]
Ah, nice catch, @giogziro95! This should be an easy fix to the code-points used for those icons in `functions/icons.zsh`.

Would you like to file a PR for this against `master`? If not, I can take it up - but I want to give you the opportunity if you're interested `=)`

**Comment by giogziro95** [comment]
@bhilburn Thanks! Done. I chose to go with heavy because I think it's more visible. (I use Noto Mono and the normal one is a bit thinner than what I'd like it to be.) If that's not a problem, feel free to merge. 🙂
