### ISSUE TITLE
Incorrect font size for left facing arrows

### ISSUE THREAD

**Issue by carlca** [bhilburn/powerlevel9k#579]
Hello, I'm running PowerLevel9K in iTerm2 with the Monaco with Powerline and awesome-terminal-icons Regular font and my left facing arrows seem to be too small. Am I right in thinking this is an issue with the font itself or is it something which can be fixed within pl9k?

![screen shot 2017-07-25 at 00 45 05](https://user-images.githubusercontent.com/260612/28549503-6008eb52-70d2-11e7-9105-211db1bec7fb.png)

**Comment by carlca** [comment]
My right facing arrows are properly sized so it isn't to do with the selected font size, I don't think.

![screen shot 2017-07-25 at 00 54 17](https://user-images.githubusercontent.com/260612/28549676-a01ae942-70d3-11e7-963a-9662c1a1ddf8.png)

**Comment by bhilburn** [comment]
Hm, that is indeed fairly strange. So, just to double-check, you are using https://github.com/gabrielelana/awesome-terminal-fonts with `fontawesome-regular`?

Can you share the P9k configuration options you are setting? @gabrielelana - Is this a familiar problem, by chance?

**Comment by carlca** [comment]
No, I actually got the font from https://gist.github.com/steakknife/c74538a1e7fb8d1e1e639f4d26723051.
I'll check out the site you mentioned and see if the problem goes away. I suspect I will end up having to use Monaco for the text font and one of the @gabrielelana fonts as the symbol font.

**Comment by carlca** [comment]
I installed the @gabrielelana fonts as the symbol font, but in the end, I selected Monaco Powerline as my Ascii font and my non-Ascii font and everything looks good!
