### ISSUE TITLE
Text kerning problems

### ISSUE THREAD

**Issue by PizzicatoWolf** [bhilburn/powerlevel9k#585]
Using the powerline font does not kern correctly. Thus looking like this.

![image](https://user-images.githubusercontent.com/22819862/28706024-803b45a0-73b1-11e7-9d3b-2a7eab12eae9.png)

I tried troubleshooting this but to no avail.

**Comment by dritter** [comment]
Hi @PizzicatoWolf !
Sorry for the late response. We had similar reports in the past. Unfortunately this cannot be fixed from inside the theme. You need to use another font (or patch your own).

Which Font do you use, btw?

**Comment by bhilburn** [comment]
Hey @PizzicatoWolf! Just a ping on @dritter's question!

Also, is that the macOS default Term.app?

**Comment by bhilburn** [comment]
Closing this one due to inactivity. Please feel free to re-open if you are still having issues!
