### ISSUE TITLE
 command not found

### ISSUE THREAD

**Issue by Whisht** [bhilburn/powerlevel9k#586]
Hey!Guys,thanks a lot for your contribution,I love this theme so much.Unfortunately ,I meet a problem when I set the "POWERLEVEL9K_FOLDER_ICON".The Terminal told me that "command not found: ".
I have followed #543,but I still encounter this problem . I am confused about this problem ,could you guys help me figure this out ? 
Here is my `.zshrc `,and my environment  is win10 with Cygwin .
```
POWERLEVEL9K_FOLDER_ICON= "$(print $'\uF07C')"
POWERLEVEL9K_HOME_SUB_ICON="$(print $'\uF015')"
POWERLEVEL9K_DIR_PATH_SEPARATOR="$(print $'\uE0B1')"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='176'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"

POWERLEVEL9K_TIME_BACKGROUND='255'
#POWERLEVEL9K_COMMAND_TIME_FOREGROUND='gray'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_SHOW_CHANGESET=true

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
```

**Comment by dritter** [comment]
Hi @Whisht !

It seems like this line is the cause of all evil:
```
POWERLEVEL9K_FOLDER_ICON= "$(print $'\uF07C')"
```
You have a whitespace that is too much. If you want a whitespace in front of the icon, then you need to include it in the quotes:
```
POWERLEVEL9K_FOLDER_ICON=" $(print $'\uF07C')"
```
But I think you just want to remove it.
Btw. do you know that you could write that lines like this?
```
POWERLEVEL9K_FOLDER_ICON=$'\uF07C'
```

**Comment by Whisht** [comment]
@dritter Thanks so much~,It has solved!

**Comment by bhilburn** [comment]
@Whisht - So glad you're up and running! Thanks, @dritter, for providing support :)
