### ISSUE TITLE
Truncate path elements to a unique minimum

### ISSUE THREAD

**Issue by eumiro** [bhilburn/powerlevel9k#589]
While P9K offers different ways how to truncate the path elements, it doesn't check whether the resulting collapsed path is unique (copy&paste it to another terminal and TAB it to a unique directory). I didn't find a solution to this problem until [I asked at SO](https://stackoverflow.com/questions/45263799/collapse-directories-in-zsh-prompt-in-a-unique-way) and received an answer I consider a good one.

I put it already into my `.zshrc` (credits for the `spwd` function go to Vartan Christopher Simonian at SO):

    spwd() {
      paths=(${(s:/:)PWD})

      cur_path='/'
      cur_short_path='/'
      for directory in ${paths[@]}
      do
        cur_dir=''
        for (( i=0; i<${#directory}; i++ )); do
          cur_dir+="${directory:$i:1}"
          matching=("$cur_path"/"$cur_dir"*/)
          if [[ ${#matching[@]} -eq 1 ]]; then
            break
          fi
        done
        cur_short_path+="$cur_dir/"
        cur_path+="$directory/"
      done

      printf %q "${cur_short_path: : -1}"
      echo
    }

    POWERLEVEL9K_CUSTOM_SDIR="spwd"
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status context custom_sdir dir_writable)`

Maybe this is an idea for another `POWERLEVEL9K_SHORTEN_STRATEGY`? It doesn't substitute the $HOME directory, but that shouldn't be a problem to implement.

**Comment by bhilburn** [comment]
Hey @eumiro!

Wow, that is really elegant, and works really well. I would love to see this added to P9k as a shortening strategy - it's excellent.

Would you like to become a contributor by filing a PR with this yourself? It's a great opportunity to get something into the P9k tree if you're up for it :)

**Comment by eumiro** [comment]
Thank you, @bhilburn . I gave it a try in #596.

**Comment by bhilburn** [comment]
This work was implemented by @eumiro, merged, and is now part of the v0.6.4 release! Nice work =)
