### ISSUE TITLE
How can i change the icon displayed by os_icon

### ISSUE THREAD

**Issue by yurividal** [bhilburn/powerlevel9k#590]
I want to show the arch logo, instead of Penguin logo. What do i have to change?

**Comment by watschi** [comment]
If you have Nerd Fonts installed put this in your .zshrc.

`POWERLEVEL9K_LINUX_ICON='\uf300'`

**Comment by yurividal** [comment]
I have Nerd Font Installed, and my terminal is using UbuntuMonoDerrivativePowerline Nerd Font Regular, amd i set 

POWERLEVEL9K_LINUX_ICON='\uf300'

but, still shows the pengiun icon.

**Comment by bhilburn** [comment]
Hey @yurividal -

If you type:
```sh
$ echo $'\uf300'
```
Into your command line, do you see the Arch logo?

**Comment by yurividal** [comment]
yes 
![screenshot from 2017-08-06 14-02-42](https://user-images.githubusercontent.com/8555749/29005356-fbc10516-7aaf-11e7-9a3c-5f16f7b06e88.png)

**Comment by yurividal** [comment]
@bhilburn it worked! i had tomove the following lines to the begginig of the .zshrc file.
`
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LINUX_ICON='\uf300'`

so now my config starts with these 2 lines. before, they were further down bellow, together with the other config lines
