### ISSUE TITLE
rust_version & kubecontext together cause right prompt to not appear

### ISSUE THREAD

**Issue by neverfox** [bhilburn/powerlevel9k#593]
Running next branch with antigen. The entire right prompt doesn't show. Each one works without the other.
```
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs pyenv
rust_version kubecontext time)
antigen theme bhilburn/powerlevel9k powerlevel9k
```

**Comment by bhilburn** [comment]
Ooof. That's not great.

Okay, we need to figure out when it broke. Are you familiar with `git bisect` at all, @neverfox?

**Comment by bhilburn** [comment]
Hey @neverfox - I just wanted to raise this one again. Are you still seeing the issue? Can you pull the latest `master` and let me know if the problem still exists?

**Comment by bhilburn** [comment]
Closing this one due to inactivity. Feel free to re-open if you are still having issues!

**Comment by dritter** [comment]
@neverfox ZSH automatically hides the right prompt if the prompt line gets too long. Maybe this is the case here. Could you post a screenshot of your prompt?

**Comment by neverfox** [comment]
@dritter Unfortunately, I no longer user powerlevel9k, so I couldn't recreate the issue now without modifying my setup. I apologize for not following up sooner at the time.
