### ISSUE TITLE
A useful custom_command for nodejs user

### ISSUE THREAD

**Issue by KSXGitHub** [bhilburn/powerlevel9k#600]
I share this file because I think this might be useful for Node.js devs

### Features

Show node's version (`node --version`), npm's version (`npm --version`), and package version (in file package.json) *only when* package.json is present. (always showing them is quite annoying)

### Screenshot

![image](https://user-images.githubusercontent.com/11488886/29248964-9338e518-804f-11e7-89c7-b5d8c17edda5.png)

### Command

```zsh
function zsh_package_json () {
  local pkgjson=$(pwd)/package.json
  if [[ -f $pkgjson ]]; then
    local nodever npmver pkgver

    if [[ $POWERLEVEL9K_CUSTOM_PACKAGE_JSON_NODEVER != 'false' ]]; then
      nodever=$POWERLEVEL9K_NODE_ICON' '$(node --version)
    fi

    if [[ $POWERLEVEL9K_CUSTOM_PACKAGE_JSON_NPMVER != 'false' ]]; then
      npmver=$POWERLEVEL9K_NPM_ICON' '$(npm --version)
    fi

    if [[ $POWERLEVEL9K_CUSTOM_PACKAGE_JSON_PKGVER != 'false' ]]; then
      local actualpkgver=$(node -p "require('$pkgjson').version || ''")
      [[ -z $actualpkgver ]] || pkgver=$POWERLEVEL9K_PACKAGE_ICON' '$actualpkgver
    fi

    env echo -n $nodever $npmver $pkgver
  fi
}

export POWERLEVEL9K_CUSTOM_PACKAGE_JSON=zsh_package_json
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=custom_package_json
```

https://github.com/KSXGitHub/khai-powerlevel9k-config/blob/e6d113657a046d36d9709450fef5deefc5e74136/.powerlevel9k.zsh#L63-L83

**P.S.** Suggestions for improvement are welcome

**Comment by bhilburn** [comment]
@KSXGitHub - I think this would be worth upstreaming into P9k as a new segment, if you're up for it! Be sure to file it against the `next` branch.

There are a couple of things we'll want to handle before merging, like setting default values for the new flags you created (e.g., `POWERLEVEL9K_CUSTOM_PACKAGE_JSON_NODEVER`), and adding it to the README, and using the P9k `_prompt_segment` functions instead of `echo`, but otherwise the code is already pretty close to a mergeable state.

Up for it? I would love to get this into the mainline `=)`

**Comment by KSXGitHub** [comment]
@bhilburn I didn't know `_prompt_segment` existed, where is the list of p9k functions?

**Comment by KSXGitHub** [comment]
Talking about creating a pull request, my implementation here is pretty slow, [this implementation](https://github.com/KSXGitHub/khai-powerlevel9k-config/blob/master/lib/zsh-package-json.js) is a bit faster but it requires a seperate JavaScript file.

**Comment by bhilburn** [comment]
There isn't a *list* of functions, really, other than in the theme code itself. 

We work really hard not to make calls out to external programs / files, as much as possible. Let's do this, for now: why don't you put your segment on the wiki, here: https://github.com/bhilburn/powerlevel9k/wiki/User-Segments

Then others can find it, and if you find a way to speed it up, we can work on getting it merged.

**Comment by KSXGitHub** [comment]
> if you find a way to speed it up

It's slow not because of node, but because of npm, one way to speed it up is to skip calling `npm --version` by overriding its version, which I already did [here](https://github.com/KSXGitHub/khai-powerlevel9k-config).

> why don't you put your segment on the wiki

I want [this repo](https://github.com/KSXGitHub/khai-powerlevel9k-config) be on wiki but since it's a repo, can I just put a link there?

**Comment by bhilburn** [comment]
Ah, I see.

Okay, here is how I think this is best handled, then: add a screenshot of your configuration and a link to your repo on this page: https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config

Let me know if you have any questions =)

**Comment by bhilburn** [comment]
Closing this one out!
