### ISSUE TITLE
Separate the two controls bundled into this one variable: POWERLEVEL9K_SHORTEN_DIR_LENGTH

### ISSUE THREAD

**Issue by maxwellmckinnon** [bhilburn/powerlevel9k#601]
POWERLEVEL9K_SHORTEN_DIR_LENGTH currently controls both the number of dirs and the number of characters. Can we have one control for each?

I would like to have one char until the last two folders, not one char until the last folder.

Example path usr/max/test/run1
Desire: u/m/a/test/run1/

**Comment by bhilburn** [comment]
@maxwellmckinnon - Interesting suggestion, and I agree, that does seem like it would be quite useful. I actually don't use shortening strategies right now, but I might personally use this one.

Any chance you're up for having a go at implementing it? We would be happy to provide guidance & code review, obviously =)

**Comment by maxwellmckinnon** [comment]
@bhilburn Sure I'd love to. I took a look around - looks like I should start with editing here
`grep -rnw . -e 'POWERLEVEL9K_SHORTEN_DIR_LENGTH'`

./powerlevel9k.zsh-theme:700:
> case "$POWERLEVEL9K_SHORTEN_STRATEGY" in
>       truncate_middle)
>         current_path=$(pwd | sed -e "s,^$HOME,~," | sed $SED_EXTENDED_REGEX_PARAMETER "s/([^/]{$POWERLEVEL9K_SHORTEN_DIR_LENGTH})[^/]+([^/]{$POWERLEVEL9K_SHORTEN_DIR_LENGTH})\//\1$POWERLEVEL9K_SHORTEN_DELIMITER\2\//g")

**Comment by maxwellmckinnon** [comment]
What is the recommended procedure? Do I make a branch or a fork to do my changes in?

**Comment by dualscyther** [comment]
Yes, make a fork and then submit your PR against the `next` branch.
https://github.com/bhilburn/powerlevel9k/wiki/Developer's-Guide

**Comment by onaforeignshore** [comment]
Created PR #744 to work on this. It already has @dritter 's optimizations from #344 merged into it.

**Comment by onaforeignshore** [comment]
How does `POWERLEVEL9K_SHORTEN_DIR_LENGTH` for the number of characters in the shortened directory and `POWERLEVEL9K_SHORTEN_DIR_COUNT` for the number of directories that should/should not be shortened sound?

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
