### ISSUE TITLE
Add little space or fix horizontal shift

### ISSUE THREAD

**Issue by Hacksaurus** [bhilburn/powerlevel9k#612]
Hello!
I just wanted to know how to fix horizontal misalignment in powerlevel9k. Here I am using font awesome, and as you can see my linux icon has a weird shift on the left... Is there a way to fix this?
Or it might be some sort of unrelated space, separate from the module...
![screenshot_2017-08-31_19-03-15](https://user-images.githubusercontent.com/24832107/29952611-5c5841a4-8e7f-11e7-8e7d-0fc163c63a09.png)

Thanks for any help!

**Comment by Hacksaurus** [comment]
Adding the the unicode `/u200F` sort of helped the problem but does not satisfy my needs, any suggestions?
![screenshot_2017-08-31_21-57-36](https://user-images.githubusercontent.com/24832107/29955830-6a638bf6-8e97-11e7-894b-aba98bce6025.png)

**Comment by Hacksaurus** [comment]
Actually after reviewing the actual space, the "unicode" space that I have given isn't actually a smaller space, but instead just a normal space... Is there any way to enable unicode spaces in a terminal? Or is that not possible?

**Comment by tippl** [comment]
What terminal emulator are you using? It may not support wider characters. Then the character overlaps into the space, that is the next character. That's why the space may seem smaller, because the character before it is overlapping into it.

**Comment by Hacksaurus** [comment]
I am using termite.

I'm not entirely sure what you mean by "wider characters", could you please explain further?

**Comment by tippl** [comment]
Some of the characters from the extended fonts use double width glyphs, which might not be handled well by the terminal emulator. [Here](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#icons-are-cut-off) it is mentioned in the wiki troubleshooting.

Icons are wider than the monospace character the terminal expects so it fills part of the space for the next character. For example showing up as a cut off icon if the character to the right is solid, or smaller space when the space is to the right.

![screenshot_20170905_022652](https://user-images.githubusercontent.com/2827500/30040591-b11678e0-91e1-11e7-8bea-e15abf38639e.png)
The two white squares being 2 character spaces, and the orange being double width, but only takes up one slot, so the second character being space with the rest of the character over the top. So it seems smaller despite being full size space. At least that is what i think is happening.

Not sure how termite handles it though.

**Comment by Hacksaurus** [comment]
I attempted to use the fix that you have provided, but it doesn't seem to work...
![screenshot_2017-09-04_18-08-58](https://user-images.githubusercontent.com/24832107/30041163-c273bf2a-919c-11e7-899d-7e202a7e0162.png)
I also tried using some different icon, and I still get the same weird result
![screenshot_2017-09-04_10-41-08](https://user-images.githubusercontent.com/24832107/30041176-d9b63e7e-919c-11e7-8d48-3064167c7bec.png)
I think what you have been saying is true, there is a cutoff in my icon itself, which is caused by the terminal.
So I think the only way that I could fix this issue, is by adding some sort of whitespace... But what whitespaces could I use? That's my question

**Comment by tippl** [comment]
The problem is that you want to use a smaller whitespace, but since terminal uses monospace fonts, you can't go smaller than normal space. So you will have to make do with normal space and have the spacing uneven. I haven't come up with a better solution. Maybe use different terminal emulator that supports double width glyphs. Not sure if that works better than using a space though.

**Comment by Hacksaurus** [comment]
If that seems to be the case, I might as well deal with using only a normal space...
Thank you for helping though!

Closing this thread because terminal is the issue, not icon/powerlevel9k

**Comment by tagliala** [comment]
Just to confirm that Font Awesome uses variable width icons by design. We use a css class, `fa-fw`, to simulate fixed width.

For a terminal emulator, I would consider a fixed-width icon font
