### ISSUE TITLE
Powerlevel9k broke after zsh update

### ISSUE THREAD

**Issue by martmists** [bhilburn/powerlevel9k#613]
All it outputs is this
```
build_left_prompt:8: failed to load module `zsh/regex': /usr/lib/zsh/5.4.1/zsh/regex.so: cannot open shared object file: No such file or directory
build_left_prompt:8: -regex-match not available for regex
build_right_prompt:8: failed to load module `zsh/regex': /usr/lib/zsh/5.4.1/zsh/regex.so: cannot open shared object file: No such file or directory
build_right_prompt:8: -regex-match not available for regex
```
after which nothing is displayed, leaving me with an empty, though usable shell.

EDIT:
This broke after doing `sudo pacman -Syu`

Fix: replace `5.4.1` with `5.4.2`

**Comment by bhilburn** [comment]
@martmists - Sorry it's taken me so long to respond to this! I've been AWOL for the last few weeks and am just catching up.

Okay, so it looks like there was a breakage in either ZSH or the Arch packaging for it that was resolved with an upgrade? Let me know if that's *not* the case and you are still seeing issues!

**Comment by martmists** [comment]
Found the issue. I was just being dumb and didn't restart my terminal. the 5.4.1 folder was renamed to 5.4.2 but zsh/ohmyzsh needs a restart before it works again :P
