### ISSUE TITLE
Why is my arrow color like this

### ISSUE THREAD

**Issue by Jesseszhang** [bhilburn/powerlevel9k#614]
<img width="1440" alt="2017-09-04 5 41 42" src="https://user-images.githubusercontent.com/10124205/30020981-68a1eaa2-9198-11e7-8b1f-e9aa4ac065ea.png">

**Comment by Jesseszhang** [comment]
who can help me？ thanks  a lot

**Comment by blackode** [comment]
what is the color you are expecting?

**Comment by Jesseszhang** [comment]
![image](https://user-images.githubusercontent.com/10124205/30021448-ff79fb8a-9199-11e7-9166-fc0895758dea.png)
The color of the arrow should be the same as the color on the left

**Comment by Jesseszhang** [comment]
my zshrc config

POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm node_version)
WERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
ZSH_THEME="powerlevel9k/powerlevel9k"

**Comment by Jesseszhang** [comment]
the system version is macOS Sierra  10.12.5

**Comment by Jesseszhang** [comment]
@blackode  The color of the arrow should be the same as the color on the left

**Comment by blackode** [comment]
Did you try this .... 
the color that terminal supports .... 
for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"

**Comment by blackode** [comment]
That might be a problem of terminal emulator You can find the solution in troubleshoot section 
https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#segment-colors-are-wrong

**Comment by Jesseszhang** [comment]
@blackode thanks
but I mean the color of the arrow
It should look like this
![default](https://user-images.githubusercontent.com/10124205/30022257-303636fa-919d-11e7-8a37-d6115d8db6a8.png)

Rather than
![image](https://user-images.githubusercontent.com/10124205/30022304-631af718-919d-11e7-8c2c-c634524f7bdf.png)

**Comment by Jesseszhang** [comment]
@blackode thanks!

**Comment by blackode** [comment]
@Jesseszhang You always welcome ...... did you find the solution in the troubleshoot section. If so then you can close the issue

**Comment by Jesseszhang** [comment]
https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#segment-colors-are-wrong
@blackode I've tried，the problem is still there

**Comment by Jesseszhang** [comment]
I'm using iterm2

**Comment by bhilburn** [comment]
@Jesseszhang - Were you able to resolve your problem? What was the issue?
