### ISSUE TITLE
Github status icon and branch name missing space

### ISSUE THREAD

**Issue by runmad** [bhilburn/powerlevel9k#617]
<img width="233" alt="screen shot 2017-09-08 at 1 22 30 pm" src="https://user-images.githubusercontent.com/708741/30229950-ddbce65e-9498-11e7-87ef-0fb0e5f2f0f7.png">

See screenshot. I have the same setup on another Mac, using iTerm2, however the spacing between the arrow icon and the branch name isn't there on one computer. Looking through docs, I see how to add the different segments but not customize their appearance specifically.

**Comment by runmad** [comment]
Update: I just pulled the latest of this repo on the other machine. Before I pulled it looked like this:

<img width="285" alt="screen shot 2017-09-08 at 5 39 09 pm" src="https://user-images.githubusercontent.com/708741/30235340-e5046bc0-94bc-11e7-877c-1c0375d01645.png">

After I pulled:

<img width="289" alt="screen shot 2017-09-08 at 5 41 23 pm" src="https://user-images.githubusercontent.com/708741/30235341-f2472d68-94bc-11e7-8fe4-d87f3fbfa84b.png">

I kind of like that spacing in the previous version.

**Comment by SConaway** [comment]
Agreed.

**Comment by bhilburn** [comment]
Closing this so that we can focus the conversation in the thread over in #618 `=)`

**Comment by bhilburn** [comment]
@SConaway @runmad - So, for now, you can simply overwrite the VCS_BRANCH_ICON string to add a space. We're still discussing #618.

`POWERLEVEL9K_VCS_BRANCH_ICON=$'\uF126 '

Note the space at the end, there? That'll do exactly what you need with zero code changes.

**Comment by bhilburn** [comment]
@SConaway @runmad - Okay, I just reverted that change, actually, and added the space back. You should be good if you pull master.

**Comment by runmad** [comment]
Thanks, @bhilburn
