### ISSUE TITLE
can't change color for user prompt

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#621]
Hello,
I am currently testing the newest release and changing my prompt a bit.
While doing this I realized that it's impossible to set the color for the `user` prompt:

I tried the following:
```
POWERLEVEL9K_USER_FOREGROUND='black'
POWERLEVEL9K_USER_BACKGROUND='green'
```

This doesn't work.

**Comment by shibumi** [comment]
nevermind.. I should read the wiki more carefully.
It can be set via:
```
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='green'

**Comment by bhilburn** [comment]
No problem. Glad you're all set! =)
