### ISSUE TITLE
Why don't I have any ICONS? guys？

### ISSUE THREAD

**Issue by OATOMO** [bhilburn/powerlevel9k#622]
![icon](https://user-images.githubusercontent.com/27196560/30364295-28341cce-9896-11e7-82cc-d9ff798acedd.PNG)

**Comment by tippl** [comment]
What have you done in order to have icons? To have icons you need to:
- Install one of the fonts that provide the icons.
- Select the font in your terminal emulator.
- Set the `POWERLEVEL9K_MODE` variable to correspond with the font you installed.

**Comment by shibumi** [comment]
you use the standard configuration. You have at least one icon there. The ok ICON. So icon seems to work. Try out command: `get_icon_names` that will show you all icons. You can check the wiki for a short FAQ how to modify your prompt.

**Comment by OATOMO** [comment]
thanks,Problem solved.I didn't see that before

![p9](https://user-images.githubusercontent.com/27196560/30408431-60c2bd0c-9931-11e7-816e-361d4884ee3c.PNG)

**Comment by bhilburn** [comment]
Glad you're all set, @OATOMO! Closing this issue as it looks like your problem has been solved `=)`
