### ISSUE TITLE
POWERLEVEL9K_SHOW_CHANGESET does not work

### ISSUE THREAD

**Issue by jpdoria** [bhilburn/powerlevel9k#623]
I would like to see the commit hash in my terminal so added `POWERLEVEL9K_SHOW_CHANGESET` to my `~/.zshrc` but it does not seem to work. I'm using the latest version [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/commit/d848c94804918138375041a9f800f401bec12068) and [powerlevel9k](https://github.com/bhilburn/powerlevel9k/commit/688f6203b4a1e048ee45bb9493069ab22840fd54). Is there something wrong?

Here's the screenshot.

<img width="602" alt="powerlevel9k_show_changeset" src="https://user-images.githubusercontent.com/22461427/30384239-5be5e846-98d6-11e7-963e-5d1c4e61cace.png">

**Comment by shibumi** [comment]
mhh works for me. can you paste your whole .zshrc file?

**Comment by bhilburn** [comment]
@jpdoria - Sorry for the delayed response, here!

Okay, as a quick test, would you mind moving your `ZSH_THEME` line to *after* your P9k variable definitions? The ZSH `vcs_init` subroutine is called only once, and I'm betting that field must be sot before that code is executed.

**Comment by bhilburn** [comment]
Hey @jpdoria - I just wanted to check in on this!

**Comment by jpdoria** [comment]
Apologies. It's okay now. Thanks for the help guys!
