### ISSUE TITLE
Changing line seperator will not change the seperator between user and host

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#624]
Hello,
I am currently testing the new user and host segment. There is a bug for the user and host segment that makes changing the seperator between them impossible:

As you can see the seperator is changed but not between user and host
![](https://paste.archlinux.de/yt1L/)

I changed the LEFT_SEGMENT_SEPERATOR to:
```
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0CC'
```

**Comment by bhilburn** [comment]
@shibumi - In P9k, when segments are joined or they are the same color, we actually use a different separator between them. Try setting `POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR` and see if that changes anything for you?

**Comment by bhilburn** [comment]
Hey @shibumi - I just wanted to double-check that you're all set, here? `=)`

**Comment by bhilburn** [comment]
Hey @shibumi - I'm going to close this for now. Please re-open if this is still an issue!
