### ISSUE TITLE
Strange issues when pressing CTRL+C

### ISSUE THREAD

**Issue by NyxCode** [bhilburn/powerlevel9k#626]
When pressing `ctrl+c` for a few seconds, this happens:
![image](https://i.imgur.com/GlMuQtK.gif)

_note: I had the same issue with bash+powerline which could be solved by starting the powerline-daemon._

**Comment by NyxCode** [comment]
[this](https://github.com/bhilburn/powerlevel9k/issues/374#issuecomment-274521014) worked for me. There are still some glitches, but it's acceptable!
![image](https://i.imgur.com/uF12uwe.gif)

**Comment by NyxCode** [comment]
x

**Comment by bhilburn** [comment]
So glad you are all set, @NyxCode!

And @dritter will appreciate that you are using his async branch `=)`
