### ISSUE TITLE
user segment not working

### ISSUE THREAD

**Issue by NyxCode** [bhilburn/powerlevel9k#627]
My `.zshrc`-configuration:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator command_execution_time time)

source ~/Coding/powerlevel9k/powerlevel9k.zsh-theme
```
When I press `enter`, I get the following error: `build_left_prompt:16: command not found: prompt_user`.
The rest of the theme works fine.

**Comment by bhilburn** [comment]
@NyxCode - So the `user` prompt was actually added pretty recently. What version of P9k do you have installed? If you update to the latest release, do you still see the issue?

**Comment by NyxCode** [comment]
@bhilburn Yes, everything works fine now!

**Comment by bhilburn** [comment]
@NyxCode - Great! Happy to hear it =)
