### ISSUE TITLE
looks odd on cygwin.

### ISSUE THREAD

**Issue by AraHaan** [bhilburn/powerlevel9k#628]
After doing the configuration on cygwin it seems to not work well and looks like this.
```sh
Elsword@Elsword-PC ~
$ zsh
\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
```

**Comment by bhilburn** [comment]
@AraHaan - Hello! Can you provide some more details? What is your P9k configuration? How did you install Powerline prompts for Cygwin? How did you configure Cygwin?

**Comment by AraHaan** [comment]
I used curl on cygwin cygwin should have the default configurations except for the forlder being on my 2 TB USB. My p9k config should be the same as my friend Martmists's.

**Comment by bhilburn** [comment]
@AraHaan - Thanks for the response! Unfortunately, we really need more details. I don't know who Martimists is, for example, or what their config looks like. I also don't have any idea what your Cygwin configuration is or if you've configured your terminal for Powerline fonts.

Can you post configs, screenshots, etc., to help?

**Comment by AraHaan** [comment]
```
# Set mode and theme
POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

# Change defaults
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_SHOW_CHANGESET=true

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""

# Custom pylint script
zsh_pylint(){
  if [[ -w . ]] then
    if [[ -e ".git" ]] then
      VER=$(cat .git/$(cat .git/HEAD | grep -Eo 'refs/heads/.+'))
      if [[ -e ".temp.git" ]] then
        if [[ $(cat .temp.git) = $VER ]] then
          WARN=$(grep -Eo '^[CWR]' .temp.pylint | wc -l)
          ERR=$(grep -Eo '^[EF]' .temp.pylint | wc -l)
          echo "$WARN\u2757$ERR \u2717"
          return
        fi
      fi
      echo $VER > .temp.git
    fi

    # Since doing this in python is easier than doing this in bash
    CODE="import os, sys
files = []

def check_files(path):
    found = False
    for file in sorted(list(os.scandir(path)), key=lambda x: not x.is_file()):
        if file.name == '.temp.py':
            continue

        if file.is_file() and file.name.endswith('.py'):
            found = True
            files.append(f'{path}/{file.name}')
        elif not file.is_file():
            if found:
                check_files(f'{path}/{file.name}')

check_files('.')
x = ' '.join(files)
print(x)"
    FILES=$(python3 -c $CODE)
    if [[ -n $FILES ]] then
      # I disabled stuff I don't care about
      python3 -m pylint --disable=no-name-in-module,missing-docstring,too-few-public-methods,invalid-name,too-many-branches,too-many-return-statements,redefined-builtin,protected-access,relative-beyond-top-level,too-many-instance-attributes,attribute-defined-outside-init,too-many-arguments,unused-argument $(echo $FILES) > .temp.pylint
      WARN=$(grep -Eo '^[CWR]' .temp.pylint | wc -l)
      ERR=$(grep -Eo '^[EF]' .temp.pylint | wc -l)
      echo "$WARN\u2757$ERR \u2717"
    fi
  fi
}

POWERLEVEL9K_CUSTOM_PYLINT="zsh_pylint"

# Custom command to get pylint logs without re-running
alias pylog="if [[ -e ".temp.pylint" ]] then; cat .temp.pylint; fi"

# Colors
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="black"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="yellow"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"
POWERLEVEL9K_PYENV_FOREGROUND="blue"
POWERLEVEL9K_PYENV_BACKGROUND="black"
POWERLEVEL9K_STATUS_FOREGROUND="red"
POWERLEVEL9K_STATUS_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_PYLINT_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_PYLINT_FOREGROUND="red"

# Prompts
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'context' 'dir' 'vcs'
'dir_writable' 'newline' 'os_icon_joined')
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status' 'custom_pylint' 'pyenv')


# `Pyenv` is deprecated, use `python3 -v` instead
alias pyenv="echo $(python3 -V | grep -Eo '[0-9\.]+$')"
```
I wonder if it is because the Windows OS does not have the powerline fonts installed.

**Comment by bhilburn** [comment]
@AraHaan - Yes, you definitely need to have Powerline fonts installed in order for this to work.

It's worth noting that @bender-the-greatest (#314) and @Whisht (#586) have previously opened issues with Cygwin systems that seem to be nominally working, so there must be a way to install the font and use it?

**Comment by AraHaan** [comment]
Well on the looks if it the only way to do that is to probably use powershell https://github.com/powerline/fonts or cygwin's bash but I dont trsut that one fully.

**Comment by AraHaan** [comment]
Edit: it seems the solution is this ```PS1=$'%{\e]0;%d\a%}\n%F{green}%n@%m %F{yellow}%d%f\n%# '`` when I enter into zsh.

**Comment by bender-the-greatest** [comment]
It's been a long time since I've used Cygwin/Babun on Windows (I've been using Powershell with Unix utilities for the last few years). I believe Babun uses mintty.exe if memory serves (I could be wrong on the terminal executable, but Babun was what I was using at the time I ran into #314). After installing the Powerline fonts I was able to select them as a font for the terminal, albeit the performance was a little slow, though @bhilburn was able to improve it a bit (see #314).

If you use something like ConEmu as your terminal and integrate Cygwin/Babun into it, you should be able to set your font in the terminal application without issue.

**Comment by bhilburn** [comment]
@AraHaan - Based on your last comment, I think you're all set for now? I'm going to close this issue out, but please re-open if you're still having issues.

@bender-the-greatest - Thanks so much for weighing in! I appreciate your time & input `=)`
