### ISSUE TITLE
After updating to iTerm 3.1.1, the lines on the left are crooked

### ISSUE THREAD

**Issue by tomioueda** [bhilburn/powerlevel9k#629]
See screenshot:

https://i.imgur.com/aqjtkjP.png

Regressed in iTerm 3.1.1 on OS X, was working in the last version of iTerm

**Comment by jorgeOmurillo** [comment]
I recently upgraded to iTerm2 3.1.1 and also have the same issue.

**Comment by omolazabal** [comment]
Same issue here:

[https://imgur.com/sZu1dAk](https://imgur.com/sZu1dAk)

Using Meslo LG S for Powerline font.

**Comment by andrewkusuma** [comment]
me too. for solving this situation I change font size to 12 or decrease it based on your setting.

**Comment by omolazabal** [comment]
@andrewkusuma Which font are you using? I tried changing my font size but it remains crooked.

**Comment by andrewkusuma** [comment]
@omolazabal I am using 12 pt Menlo Regular and use different font for non-ASCII text for arrow.

**Comment by andrewkusuma** [comment]
I guess I need another solution for this because 12 pt seems small for me. I use 13 pt for daily activity

**Comment by rjorgenson** [comment]
Maybe this is a change in how iTerm renders fonts? I use Source Code Pro at 9pt in iTerm and it's been fine until I updated iTerm(I'm on 3.1.2.beta.2 currently) - I downgraded to 3.1.0 and the font rendering went back to normal.

**Comment by rjorgenson** [comment]
3.1.2.beta.1 seems to render the font properly(or at least as it used to) as well.

**Comment by andrewkusuma** [comment]
You can try my setting
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\e[1D"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="❯ "

Hope it will work for you too

**Comment by bhilburn** [comment]
Hm, I wonder if we can get @gnachman to comment on this?

**Comment by rjorgenson** [comment]
the latest 3.1.3.beta.1 has gone back to normal for me.

**Comment by gnachman** [comment]
There was fancy new line drawing code that fell back to the font for arcs. That's fixed in 3.1.3.beta.1, as @rjorgenson  notes.

**Comment by bhilburn** [comment]
@gnachman - Thanks so much for the guidance! It's much appreciated.

It looks like everything is set, here. Thanks, @tomioueda, for filing the issue and documenting it!
