### ISSUE TITLE
Broken prompt in putty/mobaxterm

### ISSUE THREAD

**Issue by seguri** [bhilburn/powerlevel9k#630]
The prompt does not display correctly in mobaxterm or putty:

![image](https://user-images.githubusercontent.com/2405157/30706424-8abfbd54-9ef8-11e7-8ee7-f9df46c96735.png)

Can you help me configuring it the right way?

**Comment by natemccurdy** [comment]
@seguri That's likely because you need to use PowerLine fonts:

https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font

**Comment by seguri** [comment]
Thanks @natemccurdy, it worked.

![image](https://user-images.githubusercontent.com/2405157/30820360-fea43f52-a221-11e7-9f2b-ea447b93df41.png)

1. Download latest [Source Code Pro release](https://github.com/adobe-fonts/source-code-pro/tree/2.030R-ro/1.050R-it) (no variants)
2. Install all `.otf` files as Administrator
3. Set `Source Code Pro` in Settings>Terminal>Font
4. It may be necessary to also edit font settings in each saved session.
