### ISSUE TITLE
Can "Rust" be removed from `rust_version` prompt?

### ISSUE THREAD

**Issue by chhschou** [bhilburn/powerlevel9k#632]
The `rust_version` prompt has a `Rust` at the front. Since it already has a rust icon at the back, the `Rust` word in the prompt is redundant and takes up valuable real estate. 

![image](https://user-images.githubusercontent.com/429067/30772491-7a9a2522-a0b0-11e7-8bd5-6e92f30b3f63.png)

Happy to contribute a PR.

**Comment by bhilburn** [comment]
@chhschou - Fair point! A PR would be great =)

I think it would be good to move the Rust icon to be before the version. That way, for folks who aren't using a font with an expanded icon set (and thus don't have the Rust icon), the 'icon' can be set to `Rust` and they will still get the same effect.

**Comment by chhschou** [comment]
Ahh, good call on supporting folks without the extended icons. I'll put something in for this.

**Comment by chhschou** [comment]
I just did it, but moving the icon to the front feels out of place wrt to other prompts that have icons at the back. 
![image](https://user-images.githubusercontent.com/429067/30996497-c5516e1a-a51d-11e7-962b-67e03eab3dbf.png)

I still think removing word `Rust` form the front is a good idea, it is then consistent with other prompts. Should it be `(rust)` or `Rust` if no icon? Both styles exist in code today.

**Comment by bhilburn** [comment]
Closing this to track in #641. I know that PR has been languishing a bit, but I haven't forgotten about it =)
