### ISSUE TITLE
How to get arch install working

### ISSUE THREAD

**Issue by ashic** [bhilburn/powerlevel9k#633]
I use oh-my-zsh, and have just run pacman -S zsh-them-powerlevel9k. Pacman installed powerlevel9k into /usr/share. I changed the zsh theme to powerlevel9k/powerlevel9k, but I get:

```
/home/ashic/.oh-my-zsh/oh-my-zsh.sh:source:110: no such file or directory: /home/ashic/.oh-my-zsh/themes/powerlevel9k/powerlevel9k.zsh-theme
```
I also tried setting it to /usr/share/powerlevel9k/powerlevel9k, but it tried to find it in /home/ashic/.oh-my-zsh/themes//usr/share/powerlevel9k/powerlevel9k. 

Is there a straightforward way to have oh-my-zsh pick up the theme from the arch install?

**Comment by bhilburn** [comment]
It's a good thing the Arch maintainer is active in the project! `=)`

Hey @shibumi - can you comment, here?

**Comment by ashic** [comment]
I added a symlink to the folder in /usr/share, and it worked.

**Comment by bhilburn** [comment]
@ashic - Glad you're all set! If you think this is a bug in the package, @shibumi can respond =)

**Comment by RafLeszczynski** [comment]
I had the same issue. Installed both `oh-my-zsh-git` and `zsh-theme-powerlevel9k` via yaourt and pacman. Finally I just added symlink for powerlevel9k to `/usr/share/oh-my-zsh/custom/themes` directory.

**Comment by shibumi** [comment]
Yes, this symlink is necessary. In Arch Linux we don't want to enable stuff for users after package install.
The user should be the one who decides which package he wants to enable.
