### ISSUE TITLE
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX No longer works 

### ISSUE THREAD

**Issue by worldofpeace** [bhilburn/powerlevel9k#635]
This used to control the icon in the prompt on newline

**Comment by StephenCoady** [comment]
I think it is called POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX now.

**Comment by worldofpeace** [comment]
Thanks @StephenCoady . Is that somewhere in the documentation?

**Comment by StephenCoady** [comment]
I don't think so. I had to search to find it when I hit this issue. I might open a PR with a small update to the docs.

**Comment by worldofpeace** [comment]
There's a segment now called newline. I think it works better than POWERLEVEL9K_PROMPT_ON_NEWLINE. I think the latter is undocumented for a reason.
Is there something silmilar to POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX that will control the apperance of the newline segment?

**Comment by bhilburn** [comment]
@worldofpeace - Thanks for filing an issue! You can find the documentation on all of the newline options here on the wiki: https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#double-lined-prompt 

@StephenCoady - Do you see anything that is missing from the Wiki docs? I do want to be sure it's up to date! =)

**Comment by bhilburn** [comment]
Closing this because it seems everything is all set, here. Let me know if that's not the case!
