### ISSUE TITLE
Can't be correct displayed right prompt

### ISSUE THREAD

**Issue by michikora** [bhilburn/powerlevel9k#637]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/17198196/31015922-1bc338e6-a555-11e7-98a6-1a9f218af65c.png">
like this screenshot, my powerlevel9k's right prompt arrow can't be displayed.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/17198196/31016039-adc52254-a555-11e7-8923-bdc05ca41620.png">
when i try to highlight this row, it's looks like the arrow have same forwardcolor and backgroundcolor, but i don't know how to fix this.

my OS is macOS Sierra and Terminal is iTerm2,
i use zplug to installed powerlevel9k,font is Ricty patched nerd-fonts.
(Sorry about my poor English.)

**Comment by bhilburn** [comment]
@michikora - Whoa... that is definitely strange. I'm not sure I've ever seen this issue, exactly. It's strange that the FG works for your separator on the left but not on the right.

Have you made any configuration changes for P9k? Can you share any relevant parts of your `zshrc`?

**Comment by michikora** [comment]
@bhilburn Thank you for you reply!
Here is my zshrc, about P9k i just change the mode to nerdfont.

> POWERLEVEL9K_MODE='nerdfont-complete'
> 
> autoload -Uz add-zsh-hook
> autoload -Uz compinit && compinit -u
> autoload -Uz url-quote-magic
> autoload -Uz vcs_info
> 
> zle -N self-insert url-quote-magic
> 
> 
> setopt auto_list
> setopt auto_menu
> setopt auto_pushd
> setopt extended_history
> setopt hist_ignore_all_dups
> setopt hist_ignore_dups
> setopt hist_reduce_blanks
> setopt hist_save_no_dups
> setopt ignore_eof
> setopt inc_append_history
> setopt interactive_comments
> setopt no_beep
> setopt no_hist_beep
> setopt no_list_beep
> setopt magic_equal_subst
> setopt notify
> setopt print_eight_bit
> setopt print_exit_value
> setopt prompt_subst
> setopt pushd_ignore_dups
> setopt rm_star_wait
> setopt share_history
> setopt transient_rprompt
> 
> 
> export CLICOLOR=true
> export LSCOLORS='exfxcxdxbxGxDxabagacad'
> export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:'
> export EDITOR=vim
> export HISTFILE=~/.zsh_history
> export HISTSIZE=10000
> export SAVEHIST=1000000
> export LANG=ja_JP.UTF-8
> 
> 
> bindkey -v
> bindkey -v '^?' backward-delete-char
> bindkey '^[[Z' reverse-menu-complete
> bindkey '^@' anyframe-widget-cd-ghq-repository
> bindkey '^r' anyframe-widget-put-history
> 
> 
> alias vi='vim'
> alias ll="ls -lh"
> alias la="ls -lah"
> 
> 
> zstyle ':completion:*' completer _complete _match _approximate
> zstyle ':completion:*' group-name ''
> zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
> zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
> zstyle ':completion:*' use-cache true
> zstyle ':completion:*' verbose yes
> zstyle ':completion:*:default' menu select=2
> zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
> zstyle ':completion:*:options' description 'yes'
> 
> 
> function cd() {
>   builtin cd $@ && ls;
> }
> 
> 
> source ~/.zplug/init.zsh
> 
> zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
> 
> zplug "junegunn/fzf-bin", as:command, from:gh-r, rename-to:fzf
> zplug "junegunn/fzf", as:command, use:bin/fzf-tmux
> zplug "b4b4r07/easy-oneliner", if:"which fzf", on:"junegunn/fzf-bin"
> zplug "zsh-users/zsh-autosuggestions"
> zplug "zsh-users/zsh-completions"
> zplug "zsh-users/zsh-history-substring-search"
> zplug "chrissicool/zsh-256color"
> zplug "zsh-users/zsh-syntax-highlighting", defer:2
> zplug "mollifier/anyframe"
> 
> if ! zplug check --verbose; then
>     printf "Install? [y/N]: "
>     if read -q; then
>         echo; zplug install
>     fi
> fi
> 
> zplug load --verbose

**Comment by bhilburn** [comment]
@michikora - Okay, I'm really not sure what might be going on here. As a wild shot in the dark, can you try using a different font? Does that change anything for you?

**Comment by michikora** [comment]
Thank you for continuing to follow this matter.
You are right, when i try to use some font downloaded from Nerd-font's patched fonts list,
the right separator can be correct displayed.
I think it might be something wrong when I patched font,
I will try some different arguments to patch font, and see what happens.

**Comment by bhilburn** [comment]
Yeah, if other fonts work correctly then your configuration is fine, and you may have just found a font that's patching didn't go quite right. If that's the case, remember to let @ryanoasis know by filing an Issue so he sees it! =)
