### ISSUE TITLE
icons.zsh:168: character not in range

### ISSUE THREAD

**Issue by martmists** [bhilburn/powerlevel9k#639]
```
/home/mart/.oh-my-zsh/custom/themes/powerlevel9k/functions/icons.zsh:168: character not in range
/home/mart/.oh-my-zsh/custom/themes/powerlevel9k/functions/utilities.zsh:106: command not found: print_icon
powerlevel9k_vcs_init:21: command not found: print_icon
powerlevel9k_vcs_init:32: command not found: print_icon
powerlevel9k_vcs_init:33: command not found: print_icon
powerlevel9k_vcs_init:43: command not found: print_icon
left_prompt_segment:35: command not found: print_icon                                                   
left_prompt_segment:35: command not found: print_icon
left_prompt_segment:44: command not found: print_icon
left_prompt_segment:24: command not found: print_icon
left_prompt_end:2: command not found: print_icon
left_prompt_end:6: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:38: command not found: print_icon
```
I get this whenever I launch my terminal, `termite`, or whenever I SSH into this device. The left and right prompt segments error every time I run a command.

I wanted to know if it was possible to get PL9K running on a Raspberry Pi 1 B+, meaning the architecture is ARMv6

If anyone knows how to fix this issue let me know.

What I've tried:

- Change locale to UTF-8
- Any other similar issues on this repo

**Comment by bhilburn** [comment]
@martmists - There shouldn't be any issue running P9k on an ARM system. If you were able to install ZSH, you should be able to use P9k. It even works on 32-bit Android systems (per #480).

Have you tried not just setting locale to UTF-8, but `LC_CTYPE=en_US.UTF-8`?

How did you install P9k? I wonder if this is an issue with symlinks not getting followed correctly.

**Comment by martmists** [comment]
I installed it using the Oh-My-Zsh method.
I have set `LC_*` to `en_US.UTF-8`.

**Comment by bluTaz** [comment]
If it does not work after setting locale in your zshrc, you probably didn't set up your locale during installation.
[https://wiki.archlinux.org/index.php/locale](url)

**Comment by martmists** [comment]
I did, that's why I'm confused.

**Comment by nightscape** [comment]
Same problem here on an Arch installation on a ordinary x86 laptop.
It popped up only today after having worked correctly for the past ~2 months.

**Comment by bhilburn** [comment]
Hm, so @nightscape's comment concerns me even more.

@nightscape - Did you update P9k and then see the issue? Can you revert to the previous version and let me know if you still see the problem?

**Comment by nightscape** [comment]
Hi @bhilburn,

I figured out that somehow an Arch upgrade actually messed up the locales. I didn't notice that because it only happened in newly spawned shells and I was checking the locale stuff in shells that had already been spawned before the upgrade.

So, after doing some `locale-gen` foo the issue is solved for me now.

**Comment by bhilburn** [comment]
@nightscape - I'm happy to hear it! Thanks so much for updating us, and thanks for being a P9k user! =)

**Comment by existme** [comment]
I had the same problem, the only way that I could fix it was through installing language-pack-en:
`sudo apt install language-pack-en`

**Comment by toloveru** [comment]
@nightscape I've been trying for a really long time to figure out why one of my hosts wouldn't properly run Powerlevel9k (also Arch, in LXC) and your suggestion (uncommenting en_US.UTF-8 in /etc/locale.gen, then running locale-gen and also writing the locale to /etc/locale.conf) solved the issue. Thank you so much!! 🤗

**Comment by bhilburn** [comment]
@toloveru - That's great news! Would you mind adding that to the Troubleshooting Wikipage, by chance? =)

**Comment by toloveru** [comment]
@bhilburn That's a great idea actually, considering that I've mostly commented here to keep a note because it was missing in the troubleshooting page. I'll file a PR with it shortly 😃
