### ISSUE TITLE
[vcs] Enhance Subversion support

### ISSUE THREAD

**Issue by ghost** [bhilburn/powerlevel9k#642]
This is how trunk looks like:
![screenshot_20171007_133514](https://user-images.githubusercontent.com/10786469/31307416-763c2426-ab64-11e7-9ed1-77fc22434e3b.png)

Instead, I'd like it to write `trunk` just like a branch in git. Same might apply for svn branches which I haven't tested.

Also, readme section on `vcs` should be updated to say about basic svn support.

**Comment by shibumi** [comment]
Hello light2yellow,
I was the one who worked on SVN Support. I am not sure if I remember correctly, but I have disabled the 'branch' name on purpose for SVN because of 'reasons'. If you like to help out your welcome.

**Comment by bhilburn** [comment]
Thanks for the comment, @shibumi! It actually looks like that last commit specifically calls out why you removed the `%b` indicator, for color encoding reasons. If I remember correctly, the `VCS_INFO` module from ZSH was seriously struggling to render `fg`/`bg` properly in the branch encodings.

I wonder if anything has changed recently? If either of you, @shibumi or @light2yellow want to take a shot at it, that would be fantastic.

**Comment by bhilburn** [comment]
@shibumi - Do you have any recollection of why you disabled this in that last commit, by chance? You must have encountered some issue with it?

**Comment by dritter** [comment]
A bit late: I just merged #1084 , so that should be better now. If anybody is still interested in having SVN support..
