### ISSUE TITLE
how to disable this count right prompt

### ISSUE THREAD

**Issue by HaxorGaruda** [bhilburn/powerlevel9k#644]
like a title .. how to disable it ? 
![github-issue](https://user-images.githubusercontent.com/5996055/31312699-82a4c034-abf4-11e7-939d-ced739cc6f25.png)

**Comment by shibumi** [comment]
Thats the ID of your last command. You can disable it by building your own right prompt without `history` segment.

**Comment by HaxorGaruda** [comment]
thanks .... all done .... 
![nice](https://user-images.githubusercontent.com/5996055/31314221-767c954e-ac25-11e7-9cfa-295fcbde8c63.png)
