### ISSUE TITLE
README.md missing glyphs

### ISSUE THREAD

**Issue by ylluminate** [bhilburn/powerlevel9k#646]
I'm getting some missing glyphs on the main `README.md`:
![image](https://cl.ly/3i3R162s020v/Image%202017-10-11%20at%209.27.09%20PM.png)

Any idea of what might be causing this? I've seen it on a couple different systems so far (both macOS, but one is 10.13.1ß2 and the other is 10.12.6).

**Comment by bhilburn** [comment]
@ylluminate - Yup, you're right. Those glyph comments should be removed. Would you like to submit a PR to remove them? It's an easy fix, but since you spotted it I figured I'd give you the opportunity to make the fix and get into the commit log `=)`

**Comment by ylluminarious** [comment]
@ylluminate @bhilburn [Here you go :)](https://github.com/bhilburn/powerlevel9k/pull/656)

**Comment by bhilburn** [comment]
Merged!
