### ISSUE TITLE
not issue but how to remove this..

### ISSUE THREAD

**Issue by HaxorGaruda** [bhilburn/powerlevel9k#648]
it's not issue, but how to remove this space on right prompt ? thanks ... 
![space-right](https://user-images.githubusercontent.com/5996055/31582587-3b8b5a78-b1b2-11e7-83c5-d451c992dc5a.png)

**Comment by bhilburn** [comment]
@HaxorGaruda - Per #557, this is actually an issue with ZSH (or used to be, anyway). They somewhat recently added the ability to get rid of that space with a new setting, per this: 
https://superuser.com/questions/655607/removing-the-useless-space-at-the-end-of-the-right-prompt-of-zsh-rprompt

**Comment by HaxorGaruda** [comment]
thanks .. sorry for late answer ...  👍 👍
