### ISSUE TITLE
Interest in P9k Keycap?

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#652]
This is the best way I have of getting word out to the community, so this is just a quick interest check:

I plan to place an order for a custom PBT dye-subbed DSA Cherry MX-stem keycap with the P9k logo printed on it as a colored legend. I was thinking probably as a 1x1.5, so I could use it as a TAB key, but I'm open to other options if people feel strongly about it.

Anyway, let me know if you have any interest in this! If only a couple of other people are interested, the price would be like $10 per cap, but if more come in it would obviously go down.

**Comment by DanielGGordon** [comment]
I'll get one! Got a render of it?

**Comment by bhilburn** [comment]
@DanielGGordon - I don't have a render, yet, but I'll see if I can get one! I might just order a bunch and hope that a few other people decide they want one later to bring down the cost per cap a bit.

**Comment by dritter** [comment]
I don't have an external keyboard, but I am still interested :)
