### ISSUE TITLE
Segments in Double-Lined Prompt ?

### ISSUE THREAD

**Issue by sovetnik** [bhilburn/powerlevel9k#658]
How we can add segments for nether line in double-lined mode?
```
 POWERLEVEL9K_PROMPT_ON_NEWLINE=true
```
Now we can set prefix for both lines

```
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ "
```

But I didn't find any option for set segments for nether line.
Maybe exist something like that?
```
POWERLEVEL9K_LEFT_PROMPT_UPPER_ELEMENTS=(dir_writable dir rvm vcs)
POWERLEVEL9K_LEFT_PROMPT_LOWER_ELEMENTS=(context vi_mode)
```

**Comment by bhilburn** [comment]
I think what you are looking for is the `newline` segment, which already exists. If you do:

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir_writable dir rvm vcs newline context vi_mode)
```

I think you should get what you want?

**Comment by sovetnik** [comment]
Thanks! This is exactly what I was looking for.

**Comment by bhilburn** [comment]
Great! Glad that you're all set =)
