### ISSUE TITLE
Missing fonts somewhere

### ISSUE THREAD

**Issue by Coding-Doctors** [bhilburn/powerlevel9k#665]
![](http://i.imgur.com/4XKbXEG.png)
get_icon_names output
![](http://i.imgur.com/bjPIIYe.png)
![](http://i.imgur.com/C4uMAO6.png)

**Comment by bhilburn** [comment]
So, correct me if I'm wrong, but it looks like it's actually rendering your prompt just fine, but you then see UTF garbage when you execute your command, maybe? Can you show a bigger screenshot where you are seeing the bad codepoints?

**Comment by Coding-Doctors** [comment]
![](http://i.imgur.com/Px1sZKD.png)

**Comment by bhilburn** [comment]
So does the text appear after you execute a command? While you're typing? Can you describe what's happening?

**Comment by Coding-Doctors** [comment]
Sorry, it appears after command execution.

**Comment by bhilburn** [comment]
So you execute a command, which works fine, and then it echos the name of the program you ran surrounded by UTF garbage?

Can you share your ~/.zshrc?

**Comment by Coding-Doctors** [comment]
Sure. https://gist.github.com/Coding-Doctors/267fdbce6649ec5008eeec407c57aecf

**Comment by bhilburn** [comment]
Hm, two things to try: Can you try commenting out your  `setopt CORRECT` and let me know if that does anything? Can you also try removing your custom wifi segment from your prompt and let me know if that does anything?

**Comment by Coding-Doctors** [comment]
Seems neither do anything besides remove my wifi signal segment. I've updated my config with the changes you suggested https://git.io/vFCnG

**Comment by Coding-Doctors** [comment]
Small update, part of the issue seems to be in relation to me using xfce-terminal, (forgot how broken it is) After switching back to gnome-terminal the UTF garbage doesn't stay all the time, and usually disappears in a couple of seconds.

**Comment by bhilburn** [comment]
@Coding-Doctors - I'm really quite flummoxed, to be honest. I don't think I've seen anything like this before. What version of ZSH are you using? What version of gnome-terminal? Out of pure curiosity, what Linux distro?

**Comment by Coding-Doctors** [comment]
ZSH version is ``zsh 5.4.2``
gnome-terminal version is ``GNOME Terminal 3.26.2 Using VTE version 0.50.2 +GNUTLS``
I'm using the [Void Linux](http://voidlinux.eu) distro

**Comment by bhilburn** [comment]
@Coding-Doctors - I'm honestly not sure what's going on :(

The fact that the behavior changes between terminals makes me think that it's not necessarily a P9k issue, but I'm really not sure. If anyone else has thoughts, here, that would be super helpful! @dritter @shibumi

**Comment by Coding-Doctors** [comment]
So I've narrowed it down to this variable ``export TERM="screen-256color"`` when this is active the utf garbage is thrown after every command, with it disabled/commented out the garbage disappears and is no longer a problem.

**Comment by bhilburn** [comment]
@Coding-Doctors - That's really strange, because that's exactly what I have my `$TERM` env variable set to when I use `tmux` (which I do everyday). I'm not sure why it would work for me and not for you. And, just to be sure, you now don't see the garbage in xfce-terminal, too, with that env variable unset?

Really confused about this one.

Are you using the `master` or `next` branch of P9k?

**Comment by Coding-Doctors** [comment]
I see garbage in both gnome-terminal and xfce-terminal with it set, when unset neither of those have garbage in them. This occurs on both master and next (my git install for both powerlevel and ohmyzsh were broken for some reason, though after reinstalling those nothing but the git repo changed) it does not seem to be effected by which branch I'm using nor terminal.

I will not I'm not using tmux at the moment (need to remake a new config for it, managed to delete it) if that means anything to you.

**Comment by bhilburn** [comment]
@Coding-Doctors - Well, I apologize, but I really don't have any idea what's going on here or how to fix it. It sounds like you have a `$TERM` setting that works outside of screen/tmux, so hopefully it's not a problem for you to just use that? Sorry - I'm just not sure what else to do on this one. I'm going to close this for now, but feel free to re-open if you find more clues.
