### ISSUE TITLE
How do I change docker-machine segment color?

### ISSUE THREAD

**Issue by miguelcarax** [bhilburn/powerlevel9k#670]
I have tried to change docker-machine segment color, both foreground and background and i couldn't.

What is the specific syntax?

I have tried 

```
POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND
POWERLEVEL9K_DOCKER_FOREGROUND
POWERLEVEL9K_SERVER_FOREGROUND
```

Thanks in advance.

**Comment by bhilburn** [comment]
So, you should be able to do it with:
```
POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND=`black`
```
Can you show us the exact color setting you are trying?

**Comment by miguelcarax** [comment]
![image](https://user-images.githubusercontent.com/9194709/32676066-7e1e3da4-c659-11e7-9e49-89177c1f42cf.png)
It's not working that way.

Config:

```
 53 POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND='21'
 54 POWERLEVEL9K_DOCKER_MACHINE_BACKGROUND="254"
 55 POWERLEVEL9K_KUBECONTEXT_BACKGROUND="21"
 56 POWERLEVEL9K_KUBECONTEXT_FOREGROUND="254"
```

**Comment by miguelcarax** [comment]
wow, it's about the double quotes

```
 53 POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND='21'
 54 POWERLEVEL9K_DOCKER_MACHINE_BACKGROUND='254'
```
It's weird because I have all the other configuration with double quotes and it's working properly.

**Comment by bhilburn** [comment]
@miguelcarax - Yeah, the single quotes are important. It has to do with how the strings are "expanded" in the ZSH code. Glad you got it working!
