### ISSUE TITLE
Problem with folders using white spaces

### ISSUE THREAD

**Issue by jesus87hlm** [bhilburn/powerlevel9k#674]
Hello there,
I'm having some troubles when navigating inside folders whose parent directory name has white spaces in it. It only happens when powerlevel9k is enabled (it works correctly when I disable powerlevel9k)
![image](https://user-images.githubusercontent.com/17073736/32704098-f9a94fde-c7b4-11e7-877e-39dbc8f32288.png)

I got a very basic powerlevel9k settings, I don't have anything else in my .zshrc file

![image](https://user-images.githubusercontent.com/17073736/32704095-f173bc5a-c7b4-11e7-80c9-e9886daa0bd4.png)

I haven't been able to find a solution for this problem yet and I don't know if it is a bug with the theme and my settings or there is something else.
I would appreciate some help. Thank you!

**Comment by pucicu** [comment]
I have the same problem. Would be nice to have a fix soon.

**Comment by Nuntis** [comment]
I have the same problem. Don't know where to look to solve this problem.
Someone has a tip for this ?
Thank you :)

**Comment by Corwynt** [comment]
I just added an Pull-Request with a fix for this behavior. #686

**Comment by bhilburn** [comment]
This has been fixed by @Corwynt's PR #686, and is now in both `master` and `next`. Update your P9k installation and you should be all set!

Thanks so much for the bug report, @jesus87hlm, for confirming @pucicu and @Nuntis, and for the fix, @Corwynt!
