### ISSUE TITLE
powerlevel is not rendering

### ISSUE THREAD

**Issue by lehoff** [bhilburn/powerlevel9k#678]
I am regularly loosing my powerlevel line.

It seems to be related to having made an error in tab completion and then executing a command.

I don't really know how to debug this any further - all suggestions on what I can do to help this along are most welcome.

Sourcing my .zshrc does not solve the problem.

Environment:

- mac os 10.12.6
- iterm2 v3.1.5
- zsh 5.4.2 with oh-my-zsh
- powerline9k v0.6.4-27-g948e7f5
- using a two-line command prompt where the top line is for powerline

Let me know if I should provide more information.

**Comment by bhilburn** [comment]
Hey @lehoff - Thanks for the bug report, and I apologize for the long delay in getting back to you!

I'm not sure I understand the problem after reading your write-up, unfortunately. Can you take a screenshot, or even better, make a quick gif of the issue in-action?

I have almost the exact same set-up as you (macOS, iTerm2, ZSH), and can't reproduce, so I'll need to see a pic of it to start looking =)

**Comment by bhilburn** [comment]
Hey @lehoff - I'm going to close this one since we haven't heard back from you. Feel free to re-open if you still need help!
