### ISSUE TITLE
Active virtualenv name is not correct for pyenv 

### ISSUE THREAD

**Issue by dinhnv** [bhilburn/powerlevel9k#679]
When I activate multiple versions by `pyenv global devtools2 devtools3 3.2 2.7`, the promt segment shows that I've activated the first (`devtools`).
I think it should not show any thing here because they are global environment.
The issue can be fixed by using `PYENV_VERSION` environment variable. Check the document [here](https://github.com/pyenv/pyenv#choosing-the-python-version).
And I'm willing to fix that in a pull request.

**Comment by bhilburn** [comment]
Fixed by merge of #680
