### ISSUE TITLE
Test `next` branch - from stable v0.1.0

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#68]
The theme has reached a point where most of the core infrastructure is solid, we have a growing user-base, and everything appears stable. As our contributions grow more complex, I think it is time we implement a more refined software flow.

Going forward, the `master` branch will be for stable code, only. With the exception of small bugfixes, all new feature development should be branched from `next`. We will occasionally freeze `next` and take time to make sure that it is, in fact, stable, and ready to merged into `master`, at which point the process will restart.

Since this is a new workflow, this bug will serve as a tracker for testing the current `next` branch. As the team grows more familiar with the process, this bug should no longer become necessary.

It would be great if those of you making contributions to the project that don't mind testing out the latest code would continually run `next`, and file bugs on any issues you find.

Please start basing new development off of `next`, and let me know if you have any questions!

@dritter, @natemccurdy

**Comment by natemccurdy** [comment]
Sounds like a plan. I'll start using the next branch and checking for bugs.

**Comment by bhilburn** [comment]
Thanks so much, @natemccurdy! I really appreciate it `=)`

**Comment by dritter** [comment]
@bhilburn I'm in! :)

**Comment by bhilburn** [comment]
@dritter - Great! Are you talking about the branching model? 

https://datasift.github.io/gitflow/IntroducingGitFlow.html

**Comment by dritter** [comment]
@bhilburn Right. What you described sounded much like it.. So maybe switching directly to it may benefit us..

**Comment by bhilburn** [comment]
@dritter - Yup, I'm familiar with it. The `master` + `maint` + `next` model is effectively the same thing, but was around before `git flow`, and so has different names. It's used by a number of other FOSS projects I'm involved in, and so I just naturally started using it here. The only real difference is that the `release branch` for the latest release is called `maint`, and `develop` is called `next`.

Otherwise, we are already basically doing it. Once we tag our next release and I merge & re-set the `next` branch, I'll rename them to adhere to this model. You're right, it's more widely known that the naming scheme I used above =)

I'm not sure we need 'release branches', just yet. I don't know that our current level of complexity warrants it. If we decide we need it, I'll create it at the next tag.

Great idea, @dritter!
