### ISSUE TITLE
There should be tests for prompt_dir()

### ISSUE THREAD

**Issue by Artistan** [bhilburn/powerlevel9k#683]
https://github.com/bhilburn/powerlevel9k/pull/682/commits/f19b0a54db16c4ec06c2f42fec2f4f292d3754f2

no tests for actually building the directory structure based on options....

**Comment by bhilburn** [comment]
You are quite right! There are actually quite a few segments that we do not have real unit testing for, unfortunately =(

If anyone is up for helping us close our test coverage gap, that would be a tremendous contribution to the project.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
