### ISSUE TITLE
POWERLEVEL9K_MULTILINE_FIRST(and LAST)_PROMPT_PREFIX being ignored

### ISSUE THREAD

**Issue by Neutrollized** [bhilburn/powerlevel9k#687]
I'm on Mac OSX Sierra 10.12.6 and have been using oh-my-zsh for a while now, and today I decided to try the powerlevel9k theme and so far I do enjoy it, but I can't seem to get the multiline prompts working.

I installed nerdfonts via brew and as far as I can tell it's working properly and I'm getting the icons for LoadAvg, Subfolders, GitHub, etc fine and the debug script doesn't report any issues:

<img width="1030" alt="screen shot 2017-11-29 at 17 08 40" src="https://user-images.githubusercontent.com/17765481/33402346-464e91e6-d52a-11e7-803a-5b0f8d5f700b.png">

However, the prompt is still the ">" and not what I'm telling it to use (as per some of the examples from your users' "Show Off Your Config")

Here is my .zshrc, is there something obvious I'm missing here?

```shell
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ON_NEW_LINE=true
POWERLEVEL9K_RPROMPT_ON_NEW_LINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\u250f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\u2517"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(load dir vcs newline)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time)
ZSH_THEME="powerlevel9k/powerlevel9k"
````

And it doesn't matter what I set for FIRST and LAST, it doesn't get registered -- I've tried something simpler like "\n " and "-->", but it has no effect on the prompt at all.

Thanks for reading,
GY

**Comment by Neutrollized** [comment]
Nevermind I see it now.  I have it as NEW_LINE instead of NEWLINE -__-  of course I see it *after* I open an issue.

**Comment by bhilburn** [comment]
Glad you got it sorted out, @Neutrollized  =)
