### ISSUE TITLE
wired line-break on windows10(ssh to ubuntu)

### ISSUE THREAD

**Issue by yoyoys** [bhilburn/powerlevel9k#689]
I tried 4 shell client(cmd, mintty, powershell, cmder(conemu))
and adjust many font(monaco, pmingliu, consolas ...etc)
this problem still happened.
(my mac use iTerm is ok)

here is screenshot, please ignore font error(because that i only use cmder for shell client)
cmd:
![image](https://user-images.githubusercontent.com/22124891/33466670-735d1624-d68a-11e7-9161-bf9b3fcf30f9.png)

powershell:
![image](https://user-images.githubusercontent.com/22124891/33466772-186fb810-d68b-11e7-8fce-638ce2ab29e3.png)

cmder:
![image](https://user-images.githubusercontent.com/22124891/33466674-7b6696ec-d68a-11e7-8874-8721e012fb70.png)

mintty(git bash)
![image](https://user-images.githubusercontent.com/22124891/33466791-30a3253e-d68b-11e7-9ccc-d332693d77fe.png)

thanks!

**Comment by bhilburn** [comment]
Hi @yoyoys! Sorry you're having issues!

I don't have a Windows machine, so I can't easily debug this. That said, there are a number of people who are running P9k in WSL without issues.

Check out this blog post and see if it helps:
http://jessicadeen.com/tech/microsoft/badass-terminal-fcu-wsl-edition-oh-my-zsh-powerlevel9k-tmux-and-more/

**Comment by bhilburn** [comment]
Hey @yoyoys  - I'm going to close this one since we haven't heard back from you. Please feel free to re-open if you are still having issues!

**Comment by HappyHackingNinja** [comment]
@yoyoys  I got the same problem, you should try [wsl-terminal](https://github.com/goreliu/wsl-terminal) which based on [mintty](http://mintty.github.io/) and [wslbridge](https://github.com/rprichard/wslbridge)
