### ISSUE TITLE
Re-visit P9k's use of `add-zsh-hook`

### ISSUE THREAD

**Issue by RafalLukawiecki** [bhilburn/powerlevel9k#690]
iTerm2 _Shell Integration_ has a useful feature of automatically setting a "mark" at each prompt, which makes scrolling up through long sessions faster (Cmd-Shift-Up). Setting these marks manually (Cmd-Shift-M) still works, but they do not set automatically anymore. This is what they are supposed to look like (little blue triangle on the left):

<img width="161" alt="screen shot 2017-12-03 at 14 32 22" src="https://user-images.githubusercontent.com/22912705/33526302-d102b524-d836-11e7-9ab0-e51bf61c9dc4.png">

This feature does not work with powerlevel9k (installed via oh-my-zsh). All I get is:

<img width="163" alt="screen shot 2017-12-03 at 14 31 45" src="https://user-images.githubusercontent.com/22912705/33526297-bd75756e-d836-11e7-80d4-4202ce1f8fd4.png"> 

It is not just a matter of not seeing the blue triangle. The "Previous Mark" command does not work either, so they do not seem to be "set" when powerlevel9k is active.

Is there a solution or a workaround? Many thanks.

PS. I have also reported this issue on iTerm2 GitLab pages: https://gitlab.com/gnachman/iterm2/issues/6367

**Comment by bhilburn** [comment]
So iTerm2 marks do work for me with P9k, using iTerm2 `﻿3.0.15`. What version of iTerm2 are you running?

**Comment by RafalLukawiecki** [comment]
Thanks for picking this issue up. I am using iTerm 2 Build 3.1.5, and they work if I set them manually, Cmd-Shit-M, but they do not set automatically anymore.

**Comment by gnachman** [comment]
It depends on the order of source commands in .zshrc. This works:

```
source  ~/powerlevel9k/powerlevel9k.zsh-theme
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```

iTerm2 needs to after powerlevel9k.

I see that powerlevel9k uses `precmd_functions`. Shell integration modify the prompt from `precmd_functions`. Shell integration can tell when you've modified PS1 (or PROMPT, they're the same in zsh) and will decorate it with its escape sequences, preserving the previously set value. powerlevel9k does not—it just sets `PROMPT` to what it thinks it ought to be, which removes shell integration's escape codes. I think that's intentional, but as a consequence it must not be the last precmd function. I see it uses add-zsh-hook to install itself; perhaps, given its intended purpose, it would make more sense to do `precmd_functions=(powerlevel9k_prepare_prompts $precmd_functions)`

**Comment by RafalLukawiecki** [comment]
Thank you, @gnachman. In my case, I use oh-my-zsh, which, in turn, uses the powerlevel9k theme. Following your suggestion I swapped the order to this one:
```
source $ZSH/oh-my-zsh.sh
. ~/.iterm2_shell_integration.zsh
```
The automatic marks started appearing. Visually, they are in a slightly wrong place, appearing above the prompts:

<img width="126" alt="screen shot 2017-12-17 at 22 13 34" src="https://user-images.githubusercontent.com/22912705/34084420-eb438368-e377-11e7-9210-d2fa45e117ba.png">

However, they are still not working in a tmux session. Many thanks for any further suggestions how to get them everywhere, if it is possible. It is a great feature of iTerm2.

**Comment by gnachman** [comment]
You can edit PS1 to correct the mark's location. Place this in your PS1 at the location the mark should appear:

```
%{$(iterm2_prompt_mark)%}
```

**Comment by bhilburn** [comment]
@RafalLukawiecki - Did @gnachman's comments resolve your issue?

@gnachman - Thanks so much for participating in this issue! Your guidance has been really helpful, and I really appreciate you taking the time to comment & provide feedback.

We actually had originally used the `precmd` functions, but were forced to migrate away from it for reasons that I can now no longer remember. It may have actually had something to do with ZSH's `vim-mode`, actually. Based on your comments, though, it's probably worth looking back into moving away from `add-zsh-hook`.

@dritter @rjorgenson @docwhat - Do any of you remember why we moved away from `precmd` by chance? I can look through the git history, but I'm fairly sure we didn't document it, unfortunately.

**Comment by RafalLukawiecki** [comment]
@bhilburn Thanks for looking after this issue. I will retest @gnachman suggestion and I will report back.

**Comment by onaforeignshore** [comment]
A more "elegant" solution is:

At the end of `powerlevel9k_prepare_prompts`, insert the following code:

```zsh
  [[ $POWERLEVEL9K_PROMPT_ADD_NEWLINE == true ]] && PROMPT="$NEWLINE$PROMPT"

  # Allow iTerm integration to work
  [[ $ITERM_SHELL_INTEGRATION_INSTALLED == "Yes" ]] && PROMPT="%{$(iterm2_prompt_mark)%}$PROMPT"

}
```

**Comment by onaforeignshore** [comment]
Added a PR against `next`

**Comment by docwhat** [comment]
Note that the iTerm Shell Integration is known not to work in TMUX. See "Limitations" in [the iTerm docs for shell integration](https://www.iterm2.com/documentation-shell-integration.html).

**Comment by gnachman** [comment]
@docwhat  Shell integration refuses to load when you're using screen or tmux by checking that the `$TERM` doesn't look like `screen`. If you use tmux integration it's safe to remove the check.

**Comment by bhilburn** [comment]
I believe this has actually been fixed in the `next` branch by @onaforeignshore's PR last year. @onaforeignshore @dritter - am I correct, here? If so, this issue can be closed out.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!

**Comment by stefan-niemeyer** [comment]
> You can edit PS1 to correct the mark's location. Place this in your PS1 at the location the mark should appear:
> 
> ```
> %{$(iterm2_prompt_mark)%}
> ```

I use iTerm2 version 3.3.3 and had the same problem to position the mark before the second line of a  prompt with two lines.
The following works for me:
- uncomment the line where the [.iterm2_shell_integration.zsh](url) get's loaded
- expand the variable `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` with `'\033]1337;SetMark\007'` (s. **Set Mark** in the proprietary escape codes in the [iTerm2 documentation](https://www.iterm2.com/documentation-escape-codes.html))
