### ISSUE TITLE
gitfast rebase steps missing

### ISSUE THREAD

**Issue by cybercussion** [bhilburn/powerlevel9k#691]
I notice when using gitfast (which uses gitprompt.sh) during a rebase you'd get `[<BRANCHNAME> | REBASE -m 1/6]` letting you know you had a 6 step rebase.
Once applying PowerLevel9K it simply states `rebase -m` only, and I cannot locate anyway to rectify that.

Does any one have any tips on how to configure that?

Edit: I figured out with oh-my-zsh gitfast is actually the wrapper for git-prompt.  But seems like agnoster, and this theme adjust the original layout:
`➜   Project git:(Branchname|REBASE-m 1/1) ✗`

I've forked, and tacked in gitfast releated things to the vcs to get the result I was looking for.  Those alterations can be found here, but I'd treat them like a hack.
https://github.com/cybercussion/powerlevel9k/commit/a2cf1aaf3a13994bd48ca3b4ad40a81cccdfb404

**Comment by bhilburn** [comment]
@cybercussion - Thanks so much for opening this issue! I've actually never seen it display what step of the rebase you are on - that's super useful! It would be great to support that in P9k.

I took a look at the fork you mentioned, but it's not clear to me how we would integrate this with P9k. Am I correct in that you copied the source code from `git-fast` into P9k (and changed it a bit), effectively replacing the OMZ plugin?

Flat-out replacing OMZ plugins when users install P9k would be problematic, and honestly is outside the scope of P9k, anyway. I would really like to have that feature, though. Does the ZSH `VCS_INFO` module not provide the functionality in a way that we could specify from P9k?

**Comment by cybercussion** [comment]
@bhilburn  - this comes up specially if you've got a lot of devs iterating and its always handy to know you can skip vs. re-live merge conflict.  No one likes that :)

I essentially hacked in the gitfast which wraps git-prompt.sh (I believe this is the same one git bash uses).  I tried to figure out how gitfast was exposed in a generic oh-my-zsh theme, and then what would happen to it post powerlevel9k and I couldn't figure it out.  So I looked into the vcs portion and opted to just hot-drop it in, and then make some other tweaks so I could see the commit I was on and appropriate spacing.  
One thing that stuck though is it would say "| rebase -m" at the end and that seemed to come from a post process of the vcs and not anything within. So I removed the REBASE lines within gitfast/git-prompt.sh to match up to get a nice clean "branchname | 1 / 4* ea340829 | rebase -m"

I will spend some more time on it to see if this is something I can more elegantly add-on vs the brute force job I did last week.  I'll take a look at the VCS_INFO too.  Thanks.

**Comment by bhilburn** [comment]
@cybercussion - Keep me posted on how things are going! This really is a fantastic feature, with real utility, and I would really love to have it in P9k. If you need any help, please post here and let us know what you need help with! I'll tag some others who might be able to pitch in some know-how `=)`

**Comment by cybercussion** [comment]
I use babun on a win10 box and I noticed if I run the node_version on the right side it causes the cursor to go to the left of the prompt.  I thought it was something I did, but after removing node_version it goes back where it should.  It works fine on my Mac so now that I know I didn't goof that up.  I'll see if there is a way to interface git-fast vs what I did.  I did have to tweak it bit with whitespace and redundant stuff that the vcs was already doing too.

**Comment by bhilburn** [comment]
Hey @cybercussion - so sorry, I only just realized I lost track of this.

Okay, it sounds like you've triggered some strange bug. Would you mind posting a few screenshots?

**Comment by cybercussion** [comment]
![screen shot 2018-04-17 at 8 57 50 pm](https://user-images.githubusercontent.com/94954/38911135-090daefa-4282-11e8-97d6-e977c2d0d9a0.png)

My Mac looks like this.

**Comment by cybercussion** [comment]
The work I did (which I haven't come back to re-write like we were talking about) was mainly to get my need for rebase steps.  I still don't quite know why those disappeared in Agnoster or possibly in Powerlevel9K so I just jammed in git-fast and tweaked somethings to get it back.  This looks similar in babun on my Win10 laptop.

**Comment by bhilburn** [comment]
Functionality added by merge of #1040!

**Comment by cybercussion** [comment]
Thanks, I'll check it out.  Sorry haven't been doing choose your own destiny branching strategies as much after switching back to git flow last April.
