### ISSUE TITLE
OpenFOAM support

### ISSUE THREAD

**Issue by geniusupgrader** [bhilburn/powerlevel9k#696]
I propose a feature request for a prompt_openfoam powerlevel9k function, which shows the sourced  openfoam version in the prompt.
Guidance for "normal" prompt: <http://openfoamwiki.net/index.php/Tip/Foam_version_in_shell_prompt>.
I will make a pull request, now.

**Comment by geniusupgrader** [comment]
The second pull request is the correct one (in next branch). 
But I don't know why the Travis build is failing, maybe because of colors?

**Comment by iScrE4m** [comment]
The falling CI is likely not because of you, but because of a bug PR before yours fixes.

**Comment by bhilburn** [comment]
Failing unit tests have been fixed by @iScrE4m! Only thing needed for merge is an update to the README `=)`

**Comment by geniusupgrader** [comment]
I've updated the README.

**Comment by bhilburn** [comment]
Closed by merge of @geniusupgrader's PR!
