### ISSUE TITLE
SourceCodePro+Powerline+Awesome Icons not loading at startup

### ISSUE THREAD

**Issue by JonathanRufino** [bhilburn/powerlevel9k#699]
Hello everyone.
I'm kinda new to using zsh and powerlevel9k but after configuring it I encountered the following issue:

When i open my terminal (Tillix) the icons aren't loaded, as you can see below. But when I ````source ~/.zshrc```` all icons appear nicely. What I'm missing? I'm using the SourceCodePro+Powerline+Awesome font.

![captura de tela de 2017-12-12 12-11-49](https://user-images.githubusercontent.com/5273493/33889014-f89693d4-df35-11e7-8663-1f3680c7ae37.png)

This is my ````.zshrc````

````
export ZSH=/home/jonathan/.oh-my-zsh

ZSH_THEME="powerlevel9k/powerlevel9k"

plugins=(
    git
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
          source /etc/profile.d/vte.sh
fi

POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir_writable dir vcs)
````

**Comment by areinmeyer** [comment]
I'd try moving your last 4 lines of your `.zshrc` above the line `source $ZSH/oh-my-zsh.sh`.  That's how I have my `.zshrc` set up.

**Comment by JonathanRufino** [comment]
@areinmeyer 
Thank you so much. It worked perfectly.
