### ISSUE TITLE
vpn_ip module "grep" issue

### ISSUE THREAD

**Issue by swatalla** [bhilburn/powerlevel9k#701]
Whenever I attempt to add the vpn_ip module to the prompt elements line, restarting my shell results in the following output:

`grep: Desktop: Is a directory`
`grep: Downloads: Is a directory`
`grep: Pictures Is a directory`

This output continues for all of the directories in my home folder.

I am not sure what's causing it.

**Comment by bhilburn** [comment]
Well, that's annoying, hah.

@swatalla - What OS are you using? What version of `grep` do you have?

**Comment by swatalla** [comment]
I'm sorry, I should have included that in the original post haha.
I am using Arch Linux kernel 4.14.5-1, with grep 3.1.

**Comment by bhilburn** [comment]
Wow, I totally lost track of this one.

Okay, are you still having this problem? Looking at the code, I'm really not sure how this could be happening. The use of `grep` in that segment is pretty straight-forward:

https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L934

**Comment by bhilburn** [comment]
Closing this one due to inactivity. Feel free to re-open if you are still having issues!

**Comment by magicalraccoon** [comment]
I'm getting this same error on osx mojave.

**Comment by bhilburn** [comment]
Hi @magicalraccoon - Oh no! Would you mind opening a new issue on it and filling out the issue template? Let's take it from there =)
