### ISSUE TITLE
Using newline element returns 'build_left_prompt:11: command not found: prompt_newline'

### ISSUE THREAD

**Issue by jcoolrace** [bhilburn/powerlevel9k#705]
In my zshrc, adding `newline` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` between `dir` and `rbenv` does not work properly. Instead, upon opening zsh the message `build_left_prompt:11: command not found: prompt_newline` is returned. I've tried this with and without any preexisting settings involving multiple lines, but the same result is given.

For reference, these are all the powerline settings currently in my zshrc.

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context root_indicator dir rbenv vcs vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(history time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=" ↳ "

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='black'
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='yellow'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='112'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='022'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='white'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='027'
```

**Comment by bhilburn** [comment]
Hey @jcoolrace - I copied your settings, and am unfortunately not able to reproduce your problem. This is what I see:

<img width="1002" alt="screen shot 2017-12-30 at 17 39 50" src="https://user-images.githubusercontent.com/569571/34457745-8982d00a-ed88-11e7-91a7-3b1ed2a3b288.png">

Can you share your entire `.zshrc`?

**Comment by jcoolrace** [comment]
As soon as you said that, I realised my clone of the repo hasn't been updated for a very long time! Running `git pull` fixed all my problems. My apologies for any confusion you might've had.

**Comment by bhilburn** [comment]
@jcoolrace - Glad you got it running! =)
