### ISSUE TITLE
prompt_powerlevel9k_setup some bug

### ISSUE THREAD

**Issue by hepha** [bhilburn/powerlevel9k#707]
Hi, I am having some errors in executing prompt_powerlevel9k_setup

`env LANG=C ./prompt_powerlevel9k_setup                                      `
./prompt_powerlevel9k_setup: line 27: ${(%):-%N}: bad substitution
`export POWERLEVEL9K_INSTALLATION_DIR=/home/hepha/.zplug/repos/bhilburn/powerlevel9k`

/home/hepha/.zplug/repos/bhilburn/powerlevel9k/functions/icons.zsh: line 15: typeset: -H: invalid option
typeset: usage: typeset [-aAfFgilnrtux] [-p] name[=value] ...
/home/hepha/.zplug/repos/bhilburn/powerlevel9k/functions/icons.zsh: line 238: local: can only be used in a function
/home/hepha/.zplug/repos/bhilburn/powerlevel9k/functions/colors.zsh: line 13: unexpected argument `<' to conditional binary operator
/home/hepha/.zplug/repos/bhilburn/powerlevel9k/functions/colors.zsh: line 13: syntax error near `<-'
/home/hepha/.zplug/repos/bhilburn/powerlevel9k/functions/colors.zsh: line 13: `  if [[ "$1" = <-> ]]; then'

**Comment by bhilburn** [comment]
@hepha - Looks pretty strange, indeed. Can you share your `.zshrc`?

**Comment by bhilburn** [comment]
Hey @hepha! I'm going to close this one for now due to inactivity. If you are still having issues, please feel free to re-open!

**Comment by pshoultz** [comment]
im having a very similar issue but with a few more problems

bash: ${(%):-%N}: bad substitution
bash: /functions/icons.zsh: No such file or directory
bash: /functions/utilities.zsh: No such file or directory
bash: /functions/colors.zsh: No such file or directory
bash: /functions/vcs.zsh: No such file or directory
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: set_default: command not found
bash: /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme: line 862: syntax error near unexpected token `;'
bash: /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme: line 862: `      ;'

**Comment by dritter** [comment]
@pshoultz P9K is a ZSH theme. It won't work with bash.
