### ISSUE TITLE
Error ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range

### ISSUE THREAD

**Issue by pxc052** [bhilburn/powerlevel9k#708]
I just copy the whole configuration of V1rgul's. The customization displays beautifully but I keep getting this error "ZSH_HIGHLIGHT_STYLES: assignment to invalid subscript range" when i first open iterm2.

**Comment by bhilburn** [comment]
Hey @pxc052! What was the resolution of your issue? We like to have them documented for others that come along afterwards with the same problem =)
