### ISSUE TITLE
Change term_colors logic?

### ISSUE THREAD

**Issue by tonylambiris** [bhilburn/powerlevel9k#711]
Running into a weird issue on a FreeBSD 8.3 box I have a shell account on:
```
 export TERM=xterm-256color; echotc Co; tput colors
8
167
 ./colors.sh 
 export TERM=vt220; echotc Co; tput colors         
echotc: no such capability: Co
167
```
Not sure why zsh doesn't report a color capability when set to vt220 (the default if TERM isn't defined in the environment). Also not sure why it's reporting 167 colors for both termcaps. I don't have admin access so I can't do much in the way of digging much deeper into the system libraries and installed versions. As a fix would it make sense to use the following logic instead?

```
term_colors=0

if which tput &>/dev/null; then
	term_colors=$(tput colors)
else
	term_colors=$(echotc Co)
fi

if (( term_colors <= 16 )); then
    print -P "%F{red}WARNING!%f Your terminal isn't setup to use more than 16 colors!"
    print -P "You should put: %F{blue}export TERM=\"xterm-256color\"%f in your \~\/.zshrc"
    print -P "_before_ loading this theme in your \~\/.zshrc. In most terminal emulators, putting"
    print -P "%F{blue}export TERM=\"xterm-256color\"%f at the top of your \~\/.zshrc is sufficient."
fi
```

FWIW here is some version data and screenshots of running a local `colorgrid` function on both my local Linux box and the FreeBSD server:
```
 uname -a     
FreeBSD phalse.2600.COM 8.3-RELEASE-p3 FreeBSD 8.3-RELEASE-p3 #0: Mon Jun 11 23:52:38 UTC 2012     root@i386-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  i386
 zsh --version
zsh 4.3.17 (i386-portbld-freebsd8.3)
```

**Linux colorgrid**
![colorgrid-linux](https://user-images.githubusercontent.com/14058972/34413434-8d3159a2-ebb1-11e7-97d2-fc6f6d5366a7.png)

**FreeBSD colorgrid**
![colorgrid-freebsd](https://user-images.githubusercontent.com/14058972/34413438-915487a2-ebb1-11e7-8676-a1ba8a16fe7c.png)

**Comment by bhilburn** [comment]
Hey @tonylambiris! Congratulations on being our first FreeBSD user to report an issue! If I could award badges on Github, I totally would, hah `=)`

Okay, so we are actually in the middle of overhauling how P9k handles color definitions to make it more compatible with terminal color settings. The work is happening on the `next` branch, being done by @Artistan. It's broken at the moment, but I would be curious to know if giving a shot changes the way your terminal behaves in any way.

**Comment by Artistan** [comment]
updated my pull request which is the master branch here ...
https://github.com/Artistan/powerlevel9k
try it out and tell me what you think.

**Comment by bhilburn** [comment]
Fixed my merge of @Artistan's PR #703!

**Comment by tonylambiris** [comment]
Getting this now on login with the branch @Artistan referenced: 
```
 export TERM=xterm-256color; echotc Co; tput colors
8
80
```

I just updated both my Arch Linux workstation and laptop and they are both exhibiting this behavior. I'll dig into this a little more. Should I open a new issue if I come across anything or re-open this one?

**Comment by Artistan** [comment]
@tonylambiris - not sure what your terminal is doing. 

## Default Requirements
Colors minimum is still set to 256 as the required colors for term.
https://github.com/bhilburn/powerlevel9k/blob/next/functions/colors.zsh#L17

## TroubleShooting: Try 256
https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting
Please try adding `export TERM="xterm-256color"` at the very top of your .zshrc file.

## Debugging Powerlevel9k
getColorCode background
getColorCode foreground

## FYI: not powerlevel9k functions
`echotc Co;` AND `tput colors;` are not part of the theme. You may need to address this elsewhere.

**Comment by gregf** [comment]
I'm on FreeBSD 11.2 and seeing the following results.

```
export TERM=xterm-256color; echotc Co; tput colors                                                                                                                              
256
209
```

**Comment by mavam** [comment]
I'm also on FreeBSD 11.2 and am getting the following numbers for `echotc` and `tput`:
```
256
138
```
