### ISSUE TITLE
Segment Wiki

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#712]
We may want to start putting segment information on the wiki and indicate when they are available only for a certain OS. As far as I can see, the `dropbox-cli` is only available on Linux.

**Comment by Artistan** [comment]
This works on OSX...

```bash
mkdir -p ~/bin
wget -O ~/bin/dropbox.py "https://www.dropbox.com/download?dl=packages/dropbox.py"
chmod +x ~/bin/dropbox.py
# alias to the pyton script
printf "\nalias dropbox-cli='~/bin/dropbox.py'\n" | tee -a ~/.zshrc
```

**Comment by onaforeignshore** [comment]
Doesn't work for me... I get:

`# dropbox-cli status`
Dropbox isn't running!
`# dropbox-cli start`
Starting Dropbox...
The Dropbox daemon is not installed!
Run "dropbox start -i" to install the daemon
`# dropbox-cli start -i`
Starting Dropbox...Traceback (most recent call last):
  File "/Users/chris/bin/dropbox.py", line 1404, in start
    download()
  File "/Users/chris/bin/dropbox.py", line 280, in download
    import pygtk
ImportError: No module named pygtk
`#`

**Comment by Artistan** [comment]
@onaforeignshore That pertains to dropbox, not powerlevel9k....
make sure that the dependencies for dropbox-cli are installed...
 `brew install pygtk`

**Comment by bhilburn** [comment]
Right now, we actually don't have any OS-specific segments, that I'm aware of, and generally I refuse to merge segments unless they work cleanly on all supported OSes. If there are segments you find that don't work in some OS, be sure to file a bug!

It sounds like this Dropbox issue was settled, though? If not, feel free to re-open!

**Comment by onaforeignshore** [comment]
It doesn't work for me. `dropbox-cli start -i` opens a python download window to download the daemon, but it doesn't even progress from 0. When run in root, it halts with `Error: Platform not supported` so it's not supported on macOS High Sierra 10.13.3
