### ISSUE TITLE
Customize color of rebase steps

### ISSUE THREAD

**Issue by tgeng** [bhilburn/powerlevel9k#716]
First thank you for the awesome theme for zsh!

Is it possible to customize the color of the "rebase/merge" status displayed after the branch name? Currently it's always displayed as red which looks bad for my VCS segment background colors.

Thanks!

**Comment by bhilburn** [comment]
Thanks so much, @tgeng! I'm glad you like it! Sorry for the delayed response, here.

And yes! You can change that by setting this variable in your `zshrc`:
```
export POWERLEVEL9K_VCS_ACTIONFORMAT_FOREGROUND=blue
```

If this doesn't work for you, please re-open this issue and let us know!

**Comment by tgeng** [comment]
Thanks Ben! Works perfectly!
