### ISSUE TITLE
vcs change detection doesn't work for hg?

### ISSUE THREAD

**Issue by paulhybryant** [bhilburn/powerlevel9k#719]
I have files changed in a mercurial repo but the status of the prompt is still green.

**Comment by bhilburn** [comment]
@paulhybryant - Thanks for the bug report. Not being a mercurial user myself, this isn't something I would catch, and it's possible our unit tests aren't robust for Hg, either.

I do know that @dritter and @mfarrugi are Hg users - are you seeing any issues, here?

**Comment by bhilburn** [comment]
@paulhybryant - Just to double-check, it works for you in git repos, right? I want to be sure this isn't #764.

**Comment by dritter** [comment]
@paulhybryant Could you give some more hints? What exactly did you do? What is our output of `hg st`?
One of the differences between git and hg in the vcs segment is that creating a new file (without adding it), won't show the segment as `dirty`..

**Comment by paulhybryant** [comment]
Yeah it works for me in git repos.

**Comment by paulhybryant** [comment]
I just tried again and it works now (for both changed files and newly created files)

**Comment by bhilburn** [comment]
Glad you're all set, @paulhybryant! Thanks for updating.
