### ISSUE TITLE
git prompt not working correctly on macOS (vanilla ZSH)

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#720]
I am having issues with the git prompt. It shows the branch and tag names, but the rest of the segment doesn't show up.

For example, `echo $(git stash list 2>/dev/null | wc -l)` returns `2`, but the prompt doesn't show any stashes...

**Comment by bhilburn** [comment]
Hm, so I can't replicate this. Using `master` and `next`, git stashes are working fine and show up in the prompt for me.

What version of P9k are you using?

**Comment by onaforeignshore** [comment]
Six months later and I found the culprit by accident while cleaning up my configuration files. I had a file that set some formats from before I used P9k, and that interfered with the prompt. Now it is working correctly and this issue can finally be closed.

For future reference for people with this issue, search for and files outside P9k containing `zstyle ':vcs_info:*'` and comment those lines out with `#` to see if that is your issue.
