### ISSUE TITLE
weirdness in custom elements

### ISSUE THREAD

**Issue by vinnyt** [bhilburn/powerlevel9k#723]
I'm seeing weird extra spaces in customs segments.  Looking at the wifi on the left and the weather on the far right side. 

<img width="1770" alt="screen shot 2018-01-15 at 7 17 57 pm" src="https://user-images.githubusercontent.com/25773/34966398-56fa2e46-fa29-11e7-8116-ef24d73e6efd.png">

the weather segment ends with the line `echo "%{%K{blue}%} $symbol $temp°F"`
and wife ends with `echo -n "%{$color%} $symbol "`

**Comment by bhilburn** [comment]
@vinnyt - So, just to make sure, these are custom segments that you have written?

Can you share the custom segment code along with your definitions for `$symbol`s?

**Comment by bhilburn** [comment]
Hey @vinnyt! Closing this for now - once you're ready to continue the discussion, feel free to re-open!
