### ISSUE TITLE
Possible to make vi_mode work with ^X^V?

### ISSUE THREAD

**Issue by ionsquare** [bhilburn/powerlevel9k#725]
While using the regular emacs mode, you can temporarily enter vi mode by pressing ctrl+x ct+v.

This is really useful for moving the cursor around. It would be cool to be able to have the vi_mode indicator show up for NORMAL mode and maybe just hide it completely for INSERT mode.

Is that something that could be added?

**Comment by bhilburn** [comment]
Yeah, you should be able to do that pretty easily. As a quick fix, I think you just want to blow away the second case in the switch statement in the segment code, here:
https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L1363

Making this a feature should be pretty straight-forward, and I can see the utility of it. It would just be a matter of making a new configuration flag, like `POWERLEVEL9K_VI_MODE_HIDE_INSERT`, default it to `false`, and then conditionalize the segment. This would be a great first PR for someone that wanted to contribute!

**Comment by ionsquare** [comment]
Sorry, I don't think I understand.

Currently when using the normal emacs mode, if I add the vi_mode plugin, the indicator shows up as INSERT as it should, but if I press ^X^V to temporarily switch to vi normal mode, the indicator does not change. It just stays showing INSERT. I don't think the plugin can detect that the prompt is in vi:normal mode. Looking at the code I guess that maybe means using ^X^V does not set the keymap to vicmd.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
