### ISSUE TITLE
Font awesome not showing

### ISSUE THREAD

**Issue by mnameghi** [bhilburn/powerlevel9k#73]
I installed font awesome form this [repo](https://github.com/gabrielelana/awesome-terminal-fonts) but not showing correctly.
I think problem is for config file.

**Comment by bhilburn** [comment]
Hi @mnameghi - Can you provide additional details regarding your problem? What do you mean by "not showing correctly"? What config file are you referring to? How did you install the font, and what OS are you using? Do the fonts work in an editor but not in your terminal?

**Comment by mnameghi** [comment]
Hi
I am using ubuntu and installed oh_my_zsh.
I installed font from this(https://github.com/gabrielelana/awesome-terminal-fonts).
from this repo:
>customize the configuration file ./config/10-symbols.conf replacing PragmataPro with the name of the font you want to use in the terminal

I don't know what is the name and my terminal show some other character instead of git icon.

**Comment by dritter** [comment]
@mnameghi This is the wrong font.
Have a look in #71 how to install the right one. ;)

**Comment by mnameghi** [comment]
Thanks :)
