### ISSUE TITLE
Font Awesome 5 missing symbol git up arrow symbol

### ISSUE THREAD

**Issue by thevtm** [bhilburn/powerlevel9k#733]
First of all, this theme is awesome. 😄 
I've managed to find a little bug when using Font Awesome 5.

## Expected Behavior
![expected](https://user-images.githubusercontent.com/978715/35526408-677cb960-050e-11e8-9fcb-9e3cb1bb2b73.png)
(Font Awesome 4)

## Actual Behavior
![actual](https://user-images.githubusercontent.com/978715/35526406-6759cd9c-050e-11e8-80a0-f5c4bcbdca14.png)
(Font Awesome 5)

## Specifications
`POWERLEVEL9K_MODE='awesome-fontconfig'`
[ttf-font-awesome 5.0.2-1](https://www.archlinux.org/packages/community/any/ttf-font-awesome/)
zsh 5.4.2
Linux version 4.14.15-1-ARCH

**Comment by bhilburn** [comment]
@thevtm - Thanks so much for the kind remark! I'm glad you like it =)

Ah, interesting. So, just to be sure, the _only_ difference between those two screenshots is the Font Awesome version? It looks like they change a codepoint on us in the recent version. This is actually rather a pain for us, because we don't really have a way of changing the codepoint based on font version (which P9k doesn't know).

**Comment by thevtm** [comment]
I'm pretty sure the version is the issue.

Have you considered doing something like `POWERLEVEL9K_MODE='awesome5-fontconfig'`.
I could work on it.

**Comment by flohw** [comment]
Hello there !
I can confirm what @thevtm mention. I removed my font awesome 5 related files and add the font awesome 4 ones this fixed the problem.
FontAwesome 5 provides multiple formats for web (ttf, svg, eot, woff, woff2) and a version for desktop as the directory name suggest (use-on-desktop) I tried with the web format and desktop format, same problem : up arrow is incorrect.

Font awesome version 5.0.6

**Comment by weilbith** [comment]
@bhilburn 
As u mentioned, handle different font versions is not possible (isn't it?). I've also a huge interest into this, cause I run into similar issues with nerdfont. So far I often have to define my own segment, to get around these ugly literals.

So here just an approach how to handle this problem in general. Some segments support to define ur own icons. I was rly happy to use them, just to get around this problem.
If we just add the possibility to let the user overwrite each entry in the [icon function](https://github.com/bhilburn/powerlevel9k/blob/master/functions/icons.zsh), everyone can tackle this problem himself.
This approach should have a minimal effort, but provide high flexibility.<br>

If this approach should get attention here and is acceptable, I could do it on my own in a PR, if u like so.

**Comment by dritter** [comment]
@weilbith This is already possible!
If you type `get_icon_names` into your shell, you get a list of all icons and the according variable.

Looks like this:
![bildschirmfoto 2018-03-28 um 20 49 15](https://user-images.githubusercontent.com/1544760/38049837-878027a4-32c9-11e8-989b-c14f40e929cb.png)

Just declare the variable with your new icon.

**Comment by weilbith** [comment]
@dritter 
Wow, its actuallz rly simple. I missed that the function `print_icon` doesn't do much more then searching for such a variable. Sry for that asininity.

**Comment by dritter** [comment]
@weilbith Actually, giving the user the opportunity to overwrite icons is the main purpose of `print_icon`. ;) This is why we changed all simple outputs of icons to that function.
And no need for self-shaming. Making all icons overwritable is a great idea. Only drawback is that we made it quite cryptic (too much magic involved).

**Comment by bhilburn** [comment]
Sounds like everything is all set, here! If there are still issues, please let us know!

**Comment by ImtiazEpu** [comment]
Why php icon is missing??
