### ISSUE TITLE
symbols are not displayed properly 

### ISSUE THREAD

**Issue by yuceltoluyag** [bhilburn/powerlevel9k#737]
im using https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#kayants-configuration
- Terminal -> Tilix
- Font -> SourceCodePro+Powerline+Awesome+Regular 10pt 
- Color  Base 16 Google Dark

but not showing icon replace LX 
https://hizliresim.com/oOE6Vk
https://hizliresim.com/lOEbZb
https://hizliresim.com/VrE3Dr
https://hizliresim.com/VrE39n

**Comment by Jahhein** [comment]
You say you have *nerfont* patch when you want to say awesome. 

However some icons may be in nerdfont and not awesome.

This is a font problem either way.

**Comment by yuceltoluyag** [comment]
I  was installed but my problem persists 🔢

**Comment by bhilburn** [comment]
@yuceltoluyag - So sorry for the delayed response, here.

I can't see the images, unfortunately - I'm getting a 403 error. That said, if it's not displaying the icons, and you've installed the font, set P9k to the right font options, and set that font to be your terminal's font, then there isn't a whole lot we can do on our end, unfortunately - it's almost certainly a font issue.

Where did you get the font you installed?

**Comment by dritter** [comment]
I can't see the images either - just can guess here.

So, if I understand you correctly, you see the wrong icons. This can have different causes:
1. Please make sure you have the correct font installed - as @Jahhein suggests. Not all fonts contain all icons, and not all fonts use the same codepoints (codes for the icons) we use.
2. Double-check that you use a fitting [`POWERLEVEL9K_MODE`](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts#p9k-configurations) (needs to match the font)
3. `POWERLEVEL9K_MODE` variable needs to be defined before you source/apply the theme/ZSH-framework. To be sure, put it on the very top of your `~/.zshrc`. 

Btw. regarding the images: Did you know, that you could drag and drop the images here in github?

**Comment by yuceltoluyag** [comment]
ok solved, 
After installing powerline and powerline-fonts. Add the following to your ~/.zshrc:
```
powerline-daemon -q
. /usr/lib/python3.6/site-packages/powerline/bindings/zsh/powerline.zsh
```

https://wiki.archlinux.org/index.php/Powerline#Installation
