### ISSUE TITLE
Am I allowed to simply add a user segment?

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#739]
Hi!
I would like to add a segment to the [User Segments](https://github.com/bhilburn/powerlevel9k/wiki/User-Segments) page but I am not sure on how to do that.
Should I simply edit the page here on GitHub or should I fork the repo or something?

### iTunes "Now Playing" Segment
<img width="550" alt="bildschirmfoto 2018-02-07 um 23 58 12" src="https://user-images.githubusercontent.com/22161944/35946101-cb7f2e74-0c62-11e8-88c0-0acdb0933981.png">

_Only supported on OS X / macOS_

Create a `.nowplaying` file in your `$HOME` folder and make it executable with `chmod +x`
Add the following code to this file
```
#! /bin/bash
osascript -e 'tell application "iTunes" to if player state is playing then artist of current track & " - " & name of current track'
``` 

In your `.zshrc` add the following code
```
POWERLEVEL9K_CUSTOM_NOW_PLAYING='~/.nowplaying'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_BACKGROUND='blue'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_FOREGROUND='black'
```

Now you can add this segment as `custom_now_playing` to your prompt

**Comment by bhilburn** [comment]
Hey @sambadevi! Yes, please do! You should be able to edit the wiki and simply add your segment to the page!

That segment is great, by the way! Nice work, and thanks so much for being willing to share it! I'll leave this issue open for now, and let me know if you have any issues.

**Comment by sambadevi** [comment]
I added the new version of the segment (now with Linux support) to the page, I think I have explained everything, if not just tell me if there is something missing.

--> [User Segments](https://github.com/bhilburn/powerlevel9k/wiki/User-Segments#current-itunesosx--spotifyubuntu-track)

If everything is alright the issue can be closed

**Comment by bhilburn** [comment]
@sambadevi - looks great! Thanks so much for your contribution! `=)`

**Comment by beninato8** [comment]
I started using this segment, and I noticed that it will open iTunes in the background when you aren't playing a song. I found a way to fix the issue by changing the `~/.nowplaying` file to
```
#! /bin/bash
osascript ~/bin/currenttrack.scpt
```
In `~/bin/currenttrack.scpt` I have
```
if application "iTunes" is running then
	tell application "iTunes"
		if player state is playing then
			return name of current track
		end if
	end tell
end if
```
You could just keep the applescript directly inside the `~/.nowplaying` file but I wanted to have a separate file just to keep things more readable.

**Comment by sambadevi** [comment]
@beninato8 thank you, I didn’t notice that behaviour on OS X because I have iTunes running all the time, I will add the check whether iTunes is running to the segment, soon
