### ISSUE TITLE
Unknown Characters in VCS Segment

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#74]
We were discussing this previously in a separate bug, and I thought I had narrowed it down to simply a configuration issue, but now I'm not so sure.

I've been using Linux machines exclusively so far. I just now grabbed an MBP and set up OMZ and Powerline on it. It was looking great until I updated my remotes, and `git` reported that I was behind. I then saw a garbage character instead of the `behind commit` indicator. When I updated, it went away. See screenshots: 

<img width="626" alt="screen shot 2015-08-14 at 8 37 03 am" src="https://cloud.githubusercontent.com/assets/569571/9277716/da7be256-4260-11e5-9718-242a9af06a83.png">

<img width="543" alt="screen shot 2015-08-14 at 8 43 24 am" src="https://cloud.githubusercontent.com/assets/569571/9277719/dea886a4-4260-11e5-95fc-1b873795e3b5.png">

This is:
* OSX Yosemite
* iTerm2
* OMZ + Powerline `next` branch

**Comment by bhilburn** [comment]
I think it's actually interpreting the numeric characters as part of the UTF character - the displayed character changes depending on how many commits I am behind:

<img width="654" alt="screen shot 2015-08-14 at 10 00 11 am" src="https://cloud.githubusercontent.com/assets/569571/9279296/6c3eff02-426b-11e5-92eb-a1d342ae72ba.png">

**Comment by dritter** [comment]
@bhilburn are you sure that `POWERLEVEL9K_MODE` is not set to `awesome-patched`? I had this issue on my linux machine with mode set to `awesome-patched`, but no awesome-terminal-font installed..

**Comment by dritter** [comment]
I found it! It's the change to uppercase UTF-8 codepoints. In some cases, it seems to be necessary, but in others (like this one), it is mandatory to use lowercase `\u`..
What a mess. :cry:

**Comment by bhilburn** [comment]
@dritter - Ugh. Fonts are such a mess.

Do you already have a branch where you are sorting out which need to be `\U` and which need to be `\u`? If not, I'll start looking at it.

**Comment by bhilburn** [comment]
@dritter - Ignore my last comment (which I just deleted). I'm an idiot.

**Comment by bhilburn** [comment]
Confirmed that PR #74 fixes the problem! Thanks, @dritter!!
