### ISSUE TITLE
Multiline second prompt prefix broken?

### ISSUE THREAD

**Issue by jldeen** [bhilburn/powerlevel9k#745]
Hi there,

I recently updated to the latest version of P9k on MacOS and when I did, my second line prefix stopped working. As you can see in the below pic, the second line just has the standard line, but my Unicode rebel alliance symbol has disappeared. 

![image](https://user-images.githubusercontent.com/7676214/36117139-704e40ec-0fed-11e8-8f4b-7491cd46d354.png)

My .zshrc hasn't changed and the fonts work - I can run "echo \uf1d0" in the prompt and see the symbol fine. Screenshot of my .zshrc file below:

![image](https://user-images.githubusercontent.com/7676214/36117206-a102354a-0fed-11e8-905a-316db9c56377.png)

Finally, I tested by putting the prefix on the first line as a test and P9K handles that just fine:

![image](https://user-images.githubusercontent.com/7676214/36117254-c0d5828c-0fed-11e8-8298-818c1289fc58.png)

Any ideas on how to fix the multiline not accepting my defined prefix?

Thanks!

**Comment by bhilburn** [comment]
Hey @jldeen! Good to hear from you `=)`

So `MULTILINE_SECOND_PROMPT_PREFIX` was actually removed last year. It was a stupid mistake on my part, and we broke backwards compatibility (which we try to *never* do). The change was made, though, because we made it possible to split the prompt segments themselves over multiple lines, so `SECOND_PROMPT_PREFIX` became something of a misnomer.

Anyway, if you change it to `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX`, it should work. Give it a shot and let me know if it solves the problem?

https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#double-lined-prompt

**Comment by jldeen** [comment]
Yep! That was the problem! I ended up finding another closed issue from late last year right before you answered. Sorry for not digging into that more before opening an issue. 

I'll be sure to update my dotfiles and install script in my repo - perhaps even add in a check for that line and an output comment to the end user that `MULTILINE_SECOND_PROMPT_PREFIX` has been deprecated.

**Comment by bhilburn** [comment]
I'm actually going to push a fix to `master` for the next release that will recognize `MULTILINE_SECOND_PROMPT_PREFIX` and translate it to the new option. That should have been in the previous release, and hopefully most people that would be impacted will pass over the current release and not even notice, hah.

**Comment by dritter** [comment]
@bhilburn Maybe we should add a "deprecated variables" array, that we check at startup. Similar to `deprecated_segments`. That way we avoid cluttering the code with outdated variables.

**Comment by jldeen** [comment]
@dritter @bhilburn Depending on how many deprecated variables there are, I think that makes sense.

**Comment by bhilburn** [comment]
I'm actually going to push a fix to `master` for the next release that will recognize `MULTILINE_SECOND_PROMPT_PREFIX` and translate it to the new option. That should have been in the previous release, and hopefully most people that would be impacted will pass over the current release and not even notice, hah.

**Comment by jldeen** [comment]
Thank you so much, Ben! I appreciate your follow up on this!
