### ISSUE TITLE
Query about getColorCode

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#746]
Just a few questions / suggestions about getColorCode:

1. Why do most colors have a 3 digit number, but some have a name, e.g. `red - red`?

getColorCode output (first 10 lines):

```
059 - grey37
241 - grey39
067 - steelblue
red - red
057 - blueviolet
063 - royalblue1
green1 - green1
green3 - green3
194 - honeydew2
green4 - green4
```

2. The list is neither numerical or alphabetical, so difficult to use. Can we choose one option?
3. Is it possible to display them in columns? One color per line results in lots of lines to go through.

**Comment by bhilburn** [comment]
Hey @onaforeignshore - Good questions!

Our recent color work was done by @Artistan. Pinging him for some guidance `=)`

**Comment by bhilburn** [comment]
Pretty sure this one has been fixed! Closing this out.
