### ISSUE TITLE
Carrier return in promt line when Anaconda environment is active

### ISSUE THREAD

**Issue by sbmueller** [bhilburn/powerlevel9k#747]
When I activate a virtual Anaconda environment, it's name is displayed in my promt. It seems since a few days, there is a carrier return at the end of the virtual environment name, which yields all elements right of the VE name to be displayed at the beginning of the row. Any ideas how that could happen? I'm on Windows 10.
![image](https://user-images.githubusercontent.com/7465688/36195579-3ca6d614-116e-11e8-869e-669f9c2fe7cb.png)

**Comment by bhilburn** [comment]
Hey @sbmueller! Sorry for the delayed response, here.

And, uh, whoa. That's not great. Did this start happening after an update to P9k, or was it using an existing config / P9k version?

**Comment by bhilburn** [comment]
@sbmueller - Whoa, crap. Would you mind bisecting to nail down the commit?

**Comment by sbmueller** [comment]
Hmm I'm unlucky. When checking out a commit somewhere around early 2017, I even get a nasty conda error when using `source activate`:
```
 Traceback (most recent call last):
      File "C:\app\anaconda3\lib\site-packages\conda\cli\main.py", line 98, in main
        return activator_main()
      File "C:\app\anaconda3\lib\site-packages\conda\activate.py", line 581, in main
        print(activator.execute(), end='')
      File "C:\app\anaconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 16-17: character maps to <undefined>
```

**Comment by bhilburn** [comment]
Errrr no. Definitely not. @sbmueller - What commit triggers the error? And the one right before it works fine?

I believe @dritter is our dev most familiar with the conda work. Any thoughts, here?

**Comment by sbmueller** [comment]
Oh sorry, I wasn't precise. *All* the commits back to early 2017 have the carrier return problem. If I go back as far as early 2017 (052eba9c74b2153dbd70eb4ba829f258a596baf2 for instance) I even get the conda error message. So there is no commit that I can check out that works fine for me.
I think the problem is not within p9k, but if you @bhilburn or @dritter have any ideas what external impact can cause this, I'm happy to hear about it!

**Comment by dritter** [comment]
> If I go back [...] I even get the conda error message.

Does that mean your conda variables `$CONDA_ENV_PATH$CONDA_PREFIX` contain a stack trace? If not, do they contain a line break?
These two variables are the data input for the anaconda segment. For good data hygiene we should sanitize the input of our segments. It might be possible to do this in a central place (`*_prompt_segment`) before we print the actual `PROMPT` string; disclaimer: mind `newline` segment.

**Comment by sbmueller** [comment]
Sorry for the delayed response.
The error message also shows some conda information and allows me to report the error to the conda team, therefore I called it 'conda error message'.
The first variable seems to be empty:
```
echo $CONDA_ENV_PATH

```
The second has content, but is not escaped correctly. No linebreak though.
```
echo $CONDA_PREFIX
C:naconda3vs\proxy
```

**Comment by sbmueller** [comment]
Is the variable `PS1` used in any way? I've noticed after some digging that it is passed within some conda scripts. Here, the environment name comes before what seems to be the beginning of each promt line:

```
PS1='(proxy) ╭─%f%b%k%K{blue} %F{black}~ %k%F{blue}%f \n╰─ '
```

**Comment by dritter** [comment]
Sorry back for the delayed response. :D
`PS1` is the main left prompt variable (equivalent with `PROMPT`, which is filled by P9K). This contains all control elements for ZSH to build up the prompt. So, if you see `%F{black}` this means that from this point on the foreground color will be black and so on. So P9K builds up this string that is interpreted by ZSH.

Btw. your `PS1` looks a bit odd to me, as this contains your conda env (This should be somewhere in `RPS1` somewhere)..

Just to be sure, could you paste the output of `echo "x${CONDA_ENV_PATH}${CONDA_PREFIX}x"` here?

**Comment by sbmueller** [comment]
Hi @dritter 
the output of `echo "x${CONDA_ENV_PATH}${CONDA_PREFIX}x"` is
```
xC:naconda3vs\proxy
```

**Comment by bhilburn** [comment]
Closing this one due to inactivity. If something else breaks or anyone else experiences this, please re-open!
