### ISSUE TITLE
Issue with POWERLEVEL9K_DIR_PATH_SEPARATOR

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#748]
Setting `POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon 'POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR') "` gives `command not found: print_icon`.

Setting `POWERLEVEL9K_DIR_PATH_SEPARATOR=" \uE0B1 "` shows `E0B1` as the path separator.

The only workaround I found without setting the literal character is `POWERLEVEL9K_DIR_PATH_SEPARATOR=$(echo -n " \uE0B1 ")`

**Comment by weilbith** [comment]
I've same issue. Solved it so far, by sourcing the theme file on my own (again). So in my case by using `oh-my-zsh`, I just add `source ~/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme`. By this the function `print_icon` ist known, if it is sourced before usage of cause.<br>
Sure that is a pretty ugly solution, just want to add it to ur "only workaround I found". So I'm not aware how `zsh` or in fact `oh-my-zsh` is appling the theme file, when defining the `ZSH_THEME` variable.

**Comment by onaforeignshore** [comment]
I don't use any framework, just pure ZSH & p9k

**Comment by weilbith** [comment]
Just to make clear: This should not be the solution here to fix this outsite of the theme import (shouldn't it?). But how does ur minimal runtime configuration looks in this case? Cause if u don't use a theme, I can't see why the function is not defined for u.

@bhilburn r u aware about `zsh`'s theme import with `oh-my-zsh` and the usage of functions from that theme?

**Comment by weilbith** [comment]
Only for all which are interested in the case with `oh-my-zsh`:
I took a look into the `oh-my-zsh` implementation on my own. The implementation of the `theme` plugin rly simply source the theme file. But in case that the configurations for the theme takes place before the `oh-my-zsh` script is sourced, the function is not known. I think this could occur often, cause it is intuitive to place all the theme configurations right after defining the `oh-my-zsh` theme variable. So the correct approach here is to first define the `ZSH` variable, then define the theme, source `oh-my-zsh` and afterwards define everything belonging to the _powerlevel9k_ theme.

I registerted, that putting the _powerlevel9k_ variables after the `oh-my-zsh` source (so here also the theme get loaded as result), the `POWERLEVEL9K_MODE` variable do not get into effect. So after all I have to move this single line right after the theme definition, to get the correct mode working.

@bhilburn I think this is quite obvious, but maybe it should be mentioned in the _wiki_ of the installation instructions. Could simply avoid headache of newcomers or people don't thinking more in deep as I did not.


A minimal `.zshrc` using `oh-my-zsh` (following the structure of the `oh-my-zsh` instructions) :
```bash
export ZSH=~/.oh-my-zsh
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="<mode>"
source $ZSH/oh-my-zsh.sh

# All other POWERLEVEL9K_* variables here...
```

**Comment by weilbith** [comment]
@onaforeignshore could u fixed it in ur runtime configuration?
If so, anything left to discuss here?

**Comment by onaforeignshore** [comment]
Since I am not sourcing a framework, it isn't resolved for me.

**Comment by weilbith** [comment]
Sure, but as figured out, it depends on the relation between where the _powerline9k_ theme get sourced and the configuration using a function (here `print_icon`). In fact the configuration has to be defined after the sourcing.
Using a framwork just affect the point where the theme is getting sourced. Since u do it on ur own (what I do now as well), it should be much easier determine.

**Comment by onaforeignshore** [comment]
OK, so try this in your prompt:
`echo $(print_icon 'POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR')`
and
`echo $POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR`

What do you get?

**Comment by weilbith** [comment]
In both cases nothing, cause u have to use `LEFT_SUBSEGMENT_SEPARATOR`. The function is expanding the argument by `POWERLEVEL9K_`. So for ur case it would try to read `POWERLEVEL9K_POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR` which does not exist, obviously.

**Comment by onaforeignshore** [comment]
True, but does the end user know that? We tell them to use `POWERLEVEL9K_` everywhere, but this is an exception to the rule.

**Comment by weilbith** [comment]
The documentation for the [dir segment](https://github.com/bhilburn/powerlevel9k/blob/master/README.md#dir) do so yes.
In more general to use it in other places it could be mentioned somewhere in the wiki for the customization.
Open a PR for this?

**Comment by onaforeignshore** [comment]
Or update `print_icon` to remove the prefix automatically when it is included?

**Comment by weilbith** [comment]
@bhilburn what r ur thoughts for @onaforeignshore proposal?

**Comment by bhilburn** [comment]
@weilbith - Re: function loading - We've actually had a number of questions about this this exact problem. I was actually under the impression that we *had* added this to the wiki, but now that I'm looking for it, I can't find it. So, yes, let's definitely add it to the wiki. It would be a good addition to the `Troubleshooting` page.

Okay, going back to the issue that @onaforeignshore originally opened this bug about... I don't think I understand why calling `print_icon` is necessary. My preferred mode of fixing this would be to preclude the need for that entirely. This isn't something I need to do on my own machines, and I  don't think most of our users do it, either.

Can either of you try to explain why it's needed in your configurations in a bit more detail?

**Comment by weilbith** [comment]
Unfortunately it is not directly possible to accept both nations, cause it is possible (and sometimes recommended by the documentation) to define icon variables as empty.
A possibe approach would be to check if the first notation is defined, if not checke the alternative one and if both are empty (include not defined as well as unser icon) it return an empty String. 
But before open a PR to implement that why u want this? Cause the API is consistent. Also when using the custom prompt, u define a variable where the suffix is cutted of. :thinking_face . In my option a mark in the documentation should be enough.

**Comment by weilbith** [comment]
@bhilburn simple: U advice the usage of `print_icon` in the documentation of the already linked dir segment above. So users try to apply this and get into trouble.

**Comment by bhilburn** [comment]
@weilbith - Fair point. Okay, let's roll with just updating the docs for now, then. Are you up for making the addition?

**Comment by weilbith** [comment]
@bhilburn
Okay. Ur simply mean the documentation? Should I do this by an PR to the `next` branch or what r ur thoughts?

**Comment by bhilburn** [comment]
@weilbith - For now, let's just add it to this page of the Wiki. You should be able to edit it yourself:
https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting

**Comment by weilbith** [comment]
@bhilburn 
I just wanted to make that clear.

Okay I add a new section for this problem. I tried to explain the problem, why it occurs and how to fix it. Afterwards I give a short configuration example also. In the end I add a quick note for using the icon variable names.
Hopefully I don't miss any typo and ur statisfied.

**Comment by onaforeignshore** [comment]
Suggested solution is satisfactory
