### ISSUE TITLE
SSH session error: ~/powerlevel9k_cfg: 15: character not in range

### ISSUE THREAD

**Issue by drew-kun** [bhilburn/powerlevel9k#750]
Good day.
I have set up oh-my-zsh with powerlevel9k on both of my mac machines and it works fine without errors.

But when I ssh from one to another, I get the following warning/error:

    ~/powerlevel9k_cfg: 15: character not in range

Locales:

```
user@macbook% locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

Again, this message does not pop up on the machines - only when establishing SSH session.
**sshd_config**:

```
AuthorizedKeysFile ssh/authorized_keys
UsePAM yes
AcceptEnv LANG LC_*
Subsystem sftp /usr/libexec/sftp-server
```
What could be a reason of this error?

**Comment by drew-kun** [comment]
Ok, kinda figured this out.. for some reason my custom config variables looked like this:
```
...
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0B0'
...
```

Although, IT RENDERS PROPERLY, it must be set like:

```
...
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0B0"
...
```
Otherwise it returns the error above... Also, if it is set properly, but the error appears, then it is a locale problem which can be fixed as described [here](https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue)

**Comment by bhilburn** [comment]
@drew-kun - Oh wow, that's a subtle detail! I'm glad you got it figured out `=)`

Would you be up for adding a note about this to the Troubleshooting wiki?

**Comment by onaforeignshore** [comment]
IIRC, this was discussed quite a while ago on Gitter, but I can't remember why we need the `$` in front? All the UNICODE icons are declared this way in `icons.zsh`.

**Comment by drew-kun** [comment]
@bhilburn Sure I will modify the wiki and make a pull request later when I have time ;)

**Comment by bhilburn** [comment]
@drew-kun - Thanks so much! Feel free to edit the wiki without a PR - it's open-access.

**Comment by drew-kun** [comment]
where would I put screenshots?

**Comment by bhilburn** [comment]
Ah, yes, screenshots. Use the old "Issue Image" trick ;)

Basically, post your screenshots here. Then, use those image URLs in the wiki. Quick and easy!

**Comment by drew-kun** [comment]
Incorrect rendering with `POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0B0'`
![ssh_incorrect](https://user-images.githubusercontent.com/10493450/36450949-5594d916-1644-11e8-94c5-c3cbc71e7793.png)

Correct rendering with `POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0B0"` format
![correct](https://user-images.githubusercontent.com/10493450/36450951-55aa5d7c-1644-11e8-8091-43f29ee3520e.png)
