### ISSUE TITLE
remove git stash counter when it is 0

### ISSUE THREAD

**Issue by lpuglia** [bhilburn/powerlevel9k#753]
As the title already explains, is it possible to hide the git stash counter when there are none?

**Comment by sambadevi** [comment]
Are you sure you have no stashes saved in git? Could you please try `git stash list` and check if the output is actually empty?

**Comment by lpuglia** [comment]
you are right just noticed that the list was there but empty, solution:
git stash clear

**Comment by sambadevi** [comment]
Referenced by mistake, please ignore
