### ISSUE TITLE
extra space before and after user and host

### ISSUE THREAD

**Issue by lpuglia** [bhilburn/powerlevel9k#754]
I'm using `user` and `host` contexts but i have annoying space characters before and after:

`\ user @ host ` 

is it possible to overwrite this behaviour?

my config:

```
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}@%f"

POWERLEVEL9K_USER_TEMPLATE="%n"
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="green"
#POWERLEVEL9K_USER_DEFAULT_BACKGROUND="gray"

POWERLEVEL9K_HOST_LOCAL_FOREGROUND="red"
#POWERLEVEL9K_HOST_LOCAL_BACKGROUND="gray"
```

**Comment by sambadevi** [comment]
Take a look at [the context segment](https://github.com/bhilburn/powerlevel9k#context) and how to customise it.

The example you mentioned (`user@host`) would be 

```
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -s`"
```

**Comment by sambadevi** [comment]
@lpuglia if you don't really need to use the `user` and `host` but still want a different foreground colour you can also use escape sequences, I will add those to my suggestion with `context`

**Comment by lpuglia** [comment]
Thank you for the reply, your solution is a nice work around, here is the style i have now:

`POWERLEVEL9K_CONTEXT_TEMPLATE="%F{"green"}%n%F{"white"}@%F{"red"}%m"`

but i still have an annoying space character before the left prompt, how can i remove it?

**Comment by sambadevi** [comment]
Unfortunately I believe the space **between the segments** can't be removed with just configuration, maybe @bhilburn can answer this

Even with no segment separator like this
```
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
```
The segments are still divided with a whitespace

**Comment by weilbith** [comment]
This problem can be solved by setting these both variables:
- `POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS`
- `POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS`

Both are set per default to `" "`. Just define it to `""` and it should look like u want.
Just to mention: This will affect all segements on either the left or right side.

**Comment by lpuglia** [comment]
what version do you use? it says not found.

**Comment by weilbith** [comment]
Just working on the current master state. U can take a look into the [theme-file](https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme) in line `112` and `202`.  A short gaze to both lines in git blame shows, that both have been changed last time over 2 years ago.<br>

**Comment by weilbith** [comment]
For some reasons, I've relogin to my shell, to get the changes work. But that should not cause ur problem that u can't find it.

**Comment by weilbith** [comment]
@lpuglia still an issue or could it be closed?

**Comment by lpuglia** [comment]
ok, it sounds like a solution, i still have a problem in ssh session but maybe i will open another issue for that.
