### ISSUE TITLE
OS_ICON Support for more distros

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#756]
@ryanoasis mentioned the upcoming update of ryanoasis/nerd-fonts in #751 

With the new logos to be included in Nerd Fonts there are new distros to support for the `os_icon` segment

- NixOS
- ManjaroLinux
- Devuan
- Alpine Linux
- AOSC

When the next Nerd Fonts release is out I will prepare a new pr to include these icons as well and also fix the old icons since the code for those will change, too

**Comment by bhilburn** [comment]
@sambadevi - Thanks so much for spotting this coming down the pipeline and preparing for it. Much appreciated =)

**Comment by bhilburn** [comment]
Closed by merge of #780
