### ISSUE TITLE
Battery Segment showing '%' on desktop pc

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#757]
While I was running the `next` branch I encountered a bug with the battery segment on Ubuntu 17.10

Even though I don't have a battery on my pc the battery segment is showing with a single `%`, no percentage, no time remaining or a glyph for the battery symbol.

My guess is it's trying to look up a battery and finds an empty device or something but can't output any values since there are no values in the empty device

**Comment by weilbith** [comment]
That's interesting. For _Linux_ distros, the plugin look up here `/sys/class/power_supply` for a `BAT[0|1]`. If such not exist, it simply return without doing anything. So in ur case for some reason u seem to have such power supply. Maybe this is a version thing of _Ubuntu_? :thinking:

**Comment by sambadevi** [comment]
@weilbith output of `ll /sys/class/power_supply`

```
drwxr-xr-x     - root 19 Feb 17:50  ./
drwxr-xr-x     - root 19 Feb 17:50  ../
```
And I still have the battery segment like this

![Screenshot](https://i.imgur.com/o9lh7Y1.png)

**Comment by weilbith** [comment]
Okay so can u please check ur `$OS` variable? Cause then I don't get how it should be possible if u rly working on a _Linux_ distro.
Just to refer: check the lines `238` - `250` [here](https://github.com/bhilburn/powerlevel9k/blob/next/powerlevel9k.zsh-theme).

**Comment by sambadevi** [comment]
Alright, so my `$OS` variable is `Ubuntu`, which is my own doing because of my changes to the os detection for more distro icons on the `os_icon` segment, however how does the os variable interfere with the lines you mentioned? I don't see `$OS` being used there

**Comment by weilbith** [comment]
Damn, I should write the correct lines... Both are meant to be in the 400 range (`438` and `450`).
But yeah, that is the issue. There is no `else`, so ur "unkown" OS isn't handled, so no catch case for no battery is there. Therfore the empty message with a `%` is used, cause the variable of the capacity is not defined.

**Comment by sambadevi** [comment]
Ah, thanks! Seems like I need to edit those as well for my pr then.
