### ISSUE TITLE
Unreadable vcs format string in left prompt

### ISSUE THREAD

**Issue by alexzhuaz** [bhilburn/powerlevel9k#76]
Recently I updated the powerlevel9k to latest master branch and I find a small bug in left prompt.
If the vcs repository backend is git-svn, the left prompt will extend with a string 'git-svn' which is very hard to read because it's font color is same as default foreground color.
So I made a small fix to solve the problem, hope it can help others with the same problem.

diff --git a/powerlevel9k.zsh-theme b/powerlevel9k.zsh-theme
index 1b52d03..1fed0d9 100644
--- a/powerlevel9k.zsh-theme
+++ b/powerlevel9k.zsh-theme
@@ -217,7 +217,7 @@ zstyle ':vcs_info:*' enable git hg
 zstyle ':vcs_info:*' check-for-changes true

 VCS_DEFAULT_FORMAT="$VCS_CHANGESET_PREFIX%F{$VCS_FOREGROUND_COLOR}%b%c%u%m%f"
-zstyle ':vcs_info:git:*' formats "%F{$VCS_FOREGROUND_COLOR}$VCS_GIT_ICON%f$VCS_DEFAULT_FORMAT"
+zstyle ':vcs_info:(git|git-svn):*' formats "%F{$VCS_FOREGROUND_COLOR}$VCS_GIT_ICON%f$VCS_DEFAULT_FORMAT"
 zstyle ':vcs_info:hg:*' formats "%F{$VCS_FOREGROUND_COLOR}$VCS_HG_ICON%f$VCS_DEFAULT_FORMAT"

 zstyle ':vcs_info:*' actionformats " %b %F{red}| %a%f"
@@ -225,7 +225,7 @@ zstyle ':vcs_info:*' actionformats " %b %F{red}| %a%f"
 zstyle ':vcs_info:*' stagedstr " %F{$VCS_FOREGROUND_COLOR}$VCS_STAGED_ICON%f"
 zstyle ':vcs_info:*' unstagedstr " %F{$VCS_FOREGROUND_COLOR}$VCS_UNSTAGED_ICON%f"

-zstyle ':vcs_info:git*+set-message:*' hooks vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname
+zstyle ':vcs_info:(git|git-svn)*+set-message:*' hooks vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname
 zstyle ':vcs_info:hg*+set-message:*' hooks vcs-detect-changes

 # For Hg, only show the branch name

**Comment by dritter** [comment]
Hey @alexzhuaz !
Thanks for the patch. Looks good to me. Could you submit a proper pull request? I don't want to steal your credit. ;)

**Comment by bhilburn** [comment]
Hey @alexzhuaz - just here to echo what @dritter said. Thanks for the awesome patch! I'm happy to apply your patch as-is, but if you would like authorship can you submit it as a PR?

https://github.com/bhilburn/powerlevel9k/pulls

Alternatively, you could e-mail it to me with git format-patch.

**Comment by labianchin** [comment]
Ow, now I saw this. I guess PR #82 is related to this bug.

**Comment by bhilburn** [comment]
Fixed in PR #82.
