### ISSUE TITLE
Issue with custom segments foreground color

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#761]
When I try to use `P9K_CUSTOM..._FOREGROUND=` it does not change the foreground color.

However `CUSTOM...BACKGROUND` works as imagined

![Screenshot](https://i.imgur.com/1SJzIYk.png)

Tested on `master` and `next`

**Comment by sambadevi** [comment]
Nevermind, I found the culprit, `cat` seems to delete color formatting, if I just `echo` something it gets the supposed color

**Comment by bhilburn** [comment]
Glad you got it working!
