### ISSUE TITLE
(Windows) Female glyph displaying in place of git commit in nerdfont-complete pre-patch

### ISSUE THREAD

**Issue by ryandward** [bhilburn/powerlevel9k#763]
I am using an emulator on windows, (https://github.com/goreliu/wsl-terminal) so, I can't use the fontconfig to render glyphs on the fly, or whatever it does 😨 An additional problem is that very few of the "Windows" fonts are usable on this interface. 

As for now, the only thing that works is using the pre-patched nerd-complete fonts. For some reason none of font-awesome fonts can be detected by terminal emulator or command prompt on Windows.

Nevertheless, I am getting the female font instead of the Git commit among other incorrectly displayed glyphs. 

![image](https://user-images.githubusercontent.com/6970996/36852857-1c0682de-1d2a-11e8-91fd-508c6455f1dd.png)

EDIT: For any future travelers who have this issue, make sure your font matches what you declare in the .zsh file. I was using a nerdfont and I had awesome-fontconfig set in my profile.

**Comment by bhilburn** [comment]
Glad you got this sorted out! =)
