### ISSUE TITLE
Request Date segment

### ISSUE THREAD

**Issue by Gy0m** [bhilburn/powerlevel9k#766]
Is there a way to have actual date segment just like time segment .
Consider this as a development idea, this is not an issue ... or explain me how to purpose development ideas.
I will close or delete if possible this issue at the second i receive an answer

**Comment by weilbith** [comment]
When u mean with "like a time segment", that the last prompt line has a clock that update itself other time, this not possible, cause the whole prompt is build as a single string when zsh calls a new prompt.

**Comment by Gy0m** [comment]
ok, i'm not skilled as much needed to argue but i was hoping date and time close to this : https://github.com/zakaziko99/agnosterzak-ohmyzsh-theme#agnosterzak-for-oh-my-zsh-

**Comment by tippl** [comment]
There is already a date segment, however it is still in the `next` branch. Either wait for a new version or download the current development version.

https://github.com/bhilburn/powerlevel9k/tree/next#date

You can also use the time format variable to add date to time as described [here](https://github.com/bhilburn/powerlevel9k#time).

**Comment by Gy0m** [comment]
Thank you @tippl  that's a very good news, however i still have trouble to configure powerlevel9k with awesome-terminal-fonts but it's another issue so thanks for the answer and as that issue was already old, we could consider this issue as closed. Thanks again.
