### ISSUE TITLE
Can you change color of subsegment separator?

### ISSUE THREAD

**Issue by cviebrock** [bhilburn/powerlevel9k#767]
From the changelog:

> Same color segements get visual separator
This separator can be controlled by setting POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR or POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR. By default this separator is printed in the foreground color.

Is it possible to change that color?  As an example, I'd like to change the red `<` to something else in my right-hand prompt:

![screen shot 2018-03-08 at 5 25 58 pm](https://user-images.githubusercontent.com/166810/37182310-426f24d6-22f6-11e8-8530-ea466008d6d6.png)

**Comment by bhilburn** [comment]
@cviebrock - The color of that separator is set to be the same color as the foreground of the previous segment. If you [follow this guide for setting colors](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization) you should be able to change it.

Give it a go and let us know if it works for you!

**Comment by cviebrock** [comment]
Thanks @bhilburn.  I did follow the guide, but the issue is that the foreground color (in this case) changes based on the state, and just using `POWERLEVEL9K_STATUS_FOREGROUND` with no state doesn't seem to work.

I did, however, discover the `*_VISUAL_IDENTIFIER_COLOR` option, which gives me what I wanted.  FWIW, It's pretty verbose, but this is my config now, keeping the icons red/green, but changing the separator to be more subtle:

```
# Status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_STATUS_OK_BACKGROUND='black'
POWERLEVEL9K_STATUS_OK_FOREGROUND='236'
POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_COLOR='green'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='black'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='236'
POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_COLOR='red'
```

<img width="372" alt="screen shot 2018-03-25 at 10 01 45 pm" src="https://user-images.githubusercontent.com/166810/37884945-2fd38a30-3078-11e8-8fdc-3fb49987745b.png">

**Comment by bhilburn** [comment]
@cviebrock - Glad you're up and running!

And we're actually going to be introducing an improvement that shortens the variables in @onaforeignshore's work =)

**Comment by dritter** [comment]
To give a bit more context about the `_VISUAL_IDENTIFIER_COLOR` variables:
I wanted each segement to have an individual "logo" (but that name seemed too big for an icon of a segment), that could be styled individually (see [rjorgensons config](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#rjorgensons-configuration)). The name "icon" for it was not really feasible, as some segments (like vcs) have multiple icons in it. So "visual identifier" was the best I came up with.. History: https://github.com/bhilburn/powerlevel9k/pull/165
