### ISSUE TITLE
Context always detected as remote when running in tmux

### ISSUE THREAD

**Issue by ionsquare** [bhilburn/powerlevel9k#770]
The functionality added by @tippl in #709 is great, unfortunately tmux sets `$SSH_CLIENT` and `$SSH_TTY` even when running it locally though, which means the context is always detected as remote. I would love to have this functionality but I'm basically always using tmux.

It would be great if there were a reliable way to detect a shell over ssh that works with tmux, but I can't seem to find a way that would reliably detect that without adding something like a `DEFAULT_HOST` variable, similar to the `DEFAULT_USER` one.

What about adding an optional `$DEFAULT_HOST` var that is used if it is defined, otherwise check `$SSH_CLIENT` and `$SSH_TTY`? Is that adding too much complexity?

If you think that might be worth adding I can work on that.

**Comment by bhilburn** [comment]
@ionsquare - `tmux` is an important tool, and we need to do what we can to maintain compatibility with it.

I think your idea is a good one. Are you up for taking a crack at the PR?

**Comment by ionsquare** [comment]
I actually just upgraded tmux yesterday from the version the Ubuntu 16.04 repos have (2.1) to the latest stable version (2.6) and somewhere between those versions tmux stopped setting `$SSH_CLIENT` and `$SSH_TTY`, so I don't think this is an issue after all.

I have to use Ubuntu 16.04 for my work machine, but newer versions of Ubuntu obviously have newer versions of tmux. Ubuntu 17 has 2.5 and 18 has 2.6.

I think it probably isn't too important to support outdated software, if you agree I think this can be closed. If you think there's still value supporting this feature in tmux 2.1 please let me know and I'd be happy to implement the change.

**Comment by bhilburn** [comment]
Oh, yeah, v2.1 is ancient, and I don't mind not supporting that.

Let's go ahead and close, and thanks so much for the discussion, @ionsquare! =)

**Comment by dritter** [comment]
@bhilburn We should write an system requirements table in the wiki. From time to time bugs of this kind pop up (same as with old git versions).
