### ISSUE TITLE
Not showing icons (glyph) on POWERLEVEL9K

### ISSUE THREAD

**Issue by travelskid** [bhilburn/powerlevel9k#772]
Hello everyone, i've a problem with the icons, i know, this is n-issues with this problem, but i've read many other posts without solving mine.
So, i've ARCH with GNOME and i use TILIX (all upgraded). I've installed P9K from Arch Repository (`pacman -S zsh-theme-powerlevel9k`) and i've downloaded [Droid Sans Mono Nerd Font Complete ](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf), installed on `usr/share/fonts/OTF`
setted on gnome 
![schermata da 2018-03-10 19-00-05](https://user-images.githubusercontent.com/37248858/37245288-270a822a-2496-11e8-876c-3de7dee8dd93.jpg)
setted on tilix
![schermata da 2018-03-10 19-08-03](https://user-images.githubusercontent.com/37248858/37245365-2b81b6f6-2497-11e8-9c1f-5606723040bd.png)
setted the `.zshrc` 
![schermata da 2018-03-10 19-16-20](https://user-images.githubusercontent.com/37248858/37245413-ea603700-2497-11e8-86c4-644bc81a61ff.png)
refresh the font cache `fc-cache -vf /usr/share/fonts`
but still the result is this
![schermata da 2018-03-10 19-21-15](https://user-images.githubusercontent.com/37248858/37245452-5685f780-2498-11e8-823a-0e21e6bf91ed.png)

Why?
Can somebody help me?

PS: sorry for my bad english, hope i've give you all needed information (in case ask me) and thanks!

**Comment by onaforeignshore** [comment]
The `source` command **must** follow the customisation settings, otherwise, it reverts to default.

**Comment by travelskid** [comment]
thanks @onaforeignshore now it works!!!!
