### ISSUE TITLE
rbenv prompt option always displays

### ISSUE THREAD

**Issue by ryandav** [bhilburn/powerlevel9k#777]
In powerlevel9k.zsh-theme the rbenv_prompt is set to only show the ruby version if it is different from the global version set. 

For people like me who want to always see the ruby version segment in the prompt, could the conditional be removed or at least an option (eg via an environment variable) to keep it always showing?

===>
local rbenv_global="$(rbenv global)"

    #Don't show anything if the current Ruby is the same as the global Ruby.
    if [[ $rbenv_version_name == $rbenv_global ]]; then
       return
    fi
=== From the function ===>
# rbenv information
prompt_rbenv() {
  if which rbenv 2>/dev/null >&2; then
    local rbenv_version_name="$(rbenv version-name)"
     local rbenv_global="$(rbenv global)"

    # Don't show anything if the current Ruby is the same as the global Ruby.
     if [[ $rbenv_version_name == $rbenv_global ]]; then
       return
     fi

    "$1_prompt_segment" "$0" "$2" "red" "$DEFAULT_COLOR" "$rbenv_version_name" 'RUBY_ICON'
  fi
}

**Comment by bhilburn** [comment]
@ryandav - Yup, good idea. Let's add a flag that turns it on permanently.

Are you up for taking a crack at the PR?

**Comment by ryandav** [comment]
Yes, I'll give it a go this week

**Comment by ryandav** [comment]
@bhilburn Now submitted a PR for this change https://github.com/bhilburn/powerlevel9k/pull/795

**Comment by dritter** [comment]
Closing this Issue; PR is already merged. Thx @ryandav
