### ISSUE TITLE
context state 'remote' doesn't actually exist

### ISSUE THREAD

**Issue by towo** [bhilburn/powerlevel9k#779]
The [documentation states](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors) that the `context` segment has the states

-  `DEFAULT`
- `ROOT`
- `REMOTE`

[The code](https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L567), however, does not; you can't set `POWERLEVEL9K_CONTEXT_REMOTE_*` to affect anything.

**Comment by onaforeignshore** [comment]
`prompt_host` (just below context) deals with local and remote. `prompt_context` was split into `prompr_user` and `prompt_host`, to enable finer control over the context. It was left intact to avoid breaking any configurations that use it, but I don't think it has had any updates in a long time.

**Comment by bhilburn** [comment]
Good catch, @towo! This was a bug that was fixed by @tippl in #709. You can use it on the `next` branch, and it'll be in the next release =)

Closing this for now - let me know if you have any other questions. Sorry for the hassle, here!
