### ISSUE TITLE
Right prompt dir showing .../~ instead of ~

### ISSUE THREAD

**Issue by FreddieOliveira** [bhilburn/powerlevel9k#785]
When `POWERLEVEL9K_SHORTEN_DIR_LENGTH=1` is used and you cd back to your home dir using `cd ..` the right prompt displays `…/~` instead of only `~`

![zsh](https://user-images.githubusercontent.com/9597536/37884643-68f6f680-3087-11e8-9418-232d5bc5a57a.png)

This behaviour appears not to be reproducible when POWERLEVEL9K_SHORTEN_DIR_LENGTH is higher than 1

**Comment by bhilburn** [comment]
@FreddieOliveira - Thanks so much for the bug report! And argh... looks like a bug in the directory truncation stuff.

@onaforeignshore - Any chance you're already touching this?

**Comment by dritter** [comment]
This is addressed by #776

**Comment by bhilburn** [comment]
Yup, @dritter's right! We've got a fix in the pipe from @conradhaupt `=)`

**Comment by bhilburn** [comment]
Fixed by merge of #773!
