### ISSUE TITLE
status segment cross

### ISSUE THREAD

**Issue by hipstersmoothie** [bhilburn/powerlevel9k#787]
have set POWERLEVEL9K_STATUS_CROSS=true and still get error codes for the status segment

zsh 5.4.2 (x86_64-apple-darwin17.3.0)

**Comment by bhilburn** [comment]
@hipstersmoothie - Ah, okay, I see.

What is different between your home computer and work? Are they both macs? Do you use the same config on each?

**Comment by bhilburn** [comment]
@hipstersmoothie - Just a ping, here. Are you still seeing the issue on the new release?

**Comment by hipstersmoothie** [comment]
I cannot seem to reporduce! 👍

**Comment by bhilburn** [comment]
@hipstersmoothie - Great news! So glad it's resolved =)
