### ISSUE TITLE
VCS segment at root of version controlled dir (subdirectories after vcs_segment)

### ISSUE THREAD

**Issue by sbibauw** [bhilburn/powerlevel9k#790]
I do not see the possibility to do this in powerlevel9k, so this is more a suggestion: make it possible to show the VCS segment in-between the path to the version controlled dir and its subdirectories. I find this presentation to be helping a lot to perceive where I am in a project, especially if there are submodules.

The prompt would look like this:

> ~/dev/project > **[master +...ꜛ1]** > src/module >

rather than current:

> ~/dev/project/src/module > **[master +...ꜛ1]** > 

This would allow to distinguish immediately in which version controlled repository one is, avoiding any confusion for submodules:

> ~/dev/project/vendor/cloned_repo > **[master ✓]** > 

In terms of **segments**, I would see it as:

    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs subdir)

**Comment by dritter** [comment]
Hi @sbibauw 
Sorry for the delay. I think this is an interesting idea. For my part I wouldn't split it into several segment, but see it as a part of a (overloaded) shortening strategy. Although it does not "shorten" the dir path, but makes it longer..
There are still a few things to consider:
- Do we want to display the full `vcs` segment? Probably a strange question, but if you consider some of the "special" git scenarios (cherry-pick, rebase, detached HEAD).. Not sure if you want to clutter up your path with that infos. On the other hand, you'll need an extra `vcs` segment just to see these informations..
- What if the branch name is very long? Do we want some truncation on this?
- What about states? What if you are in a dirty repo? What background color does the `dir` segment have? Do the act as one segment? I know you suggested splitting these segments, but the `subdir` segment should have the same state as the `dir` segment, right? So we would have the same problem here..

Thanks for your suggestion. Hopefully somebody picks it up.

**Comment by bhilburn** [comment]
This is an interesting idea, but not super simple to implement. I'm happy to leave it open as an `enhancement` request, but unless someone in the community picks it up, we probably won't have the bandwidth to tackle it.

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
