### ISSUE TITLE
macOS AirPods battery prompt

### ISSUE THREAD

**Issue by Jahhein** [bhilburn/powerlevel9k#792]
I'd love to see a PL9k prompt for connected AirPods battery much like the macOS battery. 

I might be able to figure out how to implement this but if anyone else has a working hack already that would save a lot of time.

**Comment by bhilburn** [comment]
Wow, that's an interesting idea! I've never seen a segment that implements that feature. You should be able to leverage the existing battery segment, though, if you want, to give it some flair!

**Comment by AtomicCoding** [comment]
@Jahhein [This](https://apple.stackexchange.com/questions/215256/check-the-battery-level-of-connected-bluetooth-headphones-from-the-command-line) seems promising.

**Comment by Jahhein** [comment]
@AtomicCoding As of right now, without a consistent prompt, I found a shell script to output battery levels of Apple AirPods.

[AirPodsPower.sh](https://gist.github.com/Jahhein/45b8e8c9c36a0932189a5037f990bcdd)

**Comment by Jahhein** [comment]
I've updated my Airpods script to include a NerdFont glyph icon for output and output clarity. Perhaps this is a good step to integrate it into PL9k.

**Comment by bhilburn** [comment]
@Jahhein - Integrating this into P9k would be fantastic! Any chance you're up for it as part of Hacktoberfest? =)

**Comment by Jahhein** [comment]
@bhilburn I am participating in Hacktoberfest and would love to finish this for everyone however I no longer have working Airpods. One of them no longer work so testing to ensure outputs work properly are out of my reach. Replacing the one no longer working is out of question for me sadly. Might anyone interested in this be able to assist in the testing?

**Comment by bhilburn** [comment]
Just realized this is still open! @Jahhein - is this still something you want to work on and get merged? Any chance you got airpods over the holidays? hah!

**Comment by Jahhein** [comment]
I’m sorry, but I don’t intend on getting AirPods again (the right being broken) until the new ones come out if they do. 
It is up to maintainers to get it fulfilled right now. Leave it open or close it I won’t complain. :)
I do already have system script to read the info. I’m not familiar with the codebase to make it a prompt at the moment. I also work 10-12 hour shifts 6-7 days a week right now. 
    	
    	

    	
    
  




On Thu, Jan 3, 2019 at 9:08 AM -0500, "Ben Hilburn" <notifications@github.com> wrote:












Just realized this is still open! @Jahhein - is this still something you want to work on and get merged? Any chance you got airpods over the holidays? hah!

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
