### ISSUE TITLE
cropped icons

### ISSUE THREAD

**Issue by D1mon** [bhilburn/powerlevel9k#794]
get_icon_names:
![icon](https://user-images.githubusercontent.com/3872485/38208099-9c614110-36b8-11e8-8ad0-298a3e65a704.png)

in terminal:
![cropped_icons](https://user-images.githubusercontent.com/3872485/38208123-b1eb66be-36b8-11e8-82bb-915b85c6b535.png)

two icons cropped (home directory and subdirectories), others seem to work fine.

OS: Manjaro
font: Hack (ttf-hack package)
terminal: Konsole (kde)
POWERLEVEL9K_MODE='awesome-patched'

**Comment by dritter** [comment]
Hi @D1mon !

Yes, it seems like [Konsole does not handle double-width characters correctly](https://bugs.kde.org/show_bug.cgi?id=378124). We had reports about [this before](https://github.com/bhilburn/powerlevel9k/issues/453). The best workaround is to [add a whitespace to the icon](https://github.com/bhilburn/powerlevel9k/issues/231#issuecomment-194240147).
I hope that helps.

**Comment by D1mon** [comment]
Yes, it helped. Thank you.
