### ISSUE TITLE
Powerline symbols doesn't work in Manjaro KDE after latest update in all GTK based terminals

### ISSUE THREAD

**Issue by IevgenSobko** [bhilburn/powerlevel9k#801]
Powerline symbols doesn't work in Manjaro KDE after latest update in all GTK based terminals(tried Tilix and xfce4-terminal).
I'm using Nerd fonts(POWERLEVEL9K_MODE='nerdfont-complete')
Customly patched Larabie  font with command
./font-patcher --fontawesome --fontawesomeextension --fontlinux --octicons --powersymbols --pomicons --material --weather --powerlineextra larabiefont\ rg.ttf
and again customly patched Cousine font from this repo with the same configuration
In Konsole KDE terminal it is working correctly(but eating some symbols like in known issues).

![screenshot_20180416_140010](https://user-images.githubusercontent.com/14232100/38805573-f28c1742-417e-11e8-99a1-81f4fd8332a5.png)

**Comment by ryanoasis** [comment]
It looks like you are missing the `--powerline` flag. Also if you want everything you can just use the `--complete` flag

**Comment by IevgenSobko** [comment]
@ryanoasis --fontawesome already contains powerline symbols as far as I know. it was working great for a few weeks till I installed latest manjaro update. Plus, as I stated it still works in KDE native terminal Konsole. I'm doing this intentionally because --powerline symbols have some small 1 pixel separator that looks ugly to my  taste.

**Comment by dritter** [comment]
@IevgenSobko For me it looks like `Cousine` has some glyphs that look like proper powerline characters, but are not:
![](https://user-images.githubusercontent.com/1544760/38899876-a22fecee-4299-11e8-89fd-689cca22ddc5.png)

Compared to my (fairly old) Knack:
![](https://user-images.githubusercontent.com/1544760/38899903-b4b27b84-4299-11e8-8d36-d4fbfd6a53fd.png)

Note, that the code point used by P9K for the powerline left separator is `$'\uE0B0'`.

**Comment by dritter** [comment]
@IevgenSobko You could try to set `POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\u25B6'` to see that glyph in action. But I doubt it will look like you want..

**Comment by IevgenSobko** [comment]
@dritter thx for an hint but with \u25B6 prompt looks ugly
![screenshot_20180420_021847](https://user-images.githubusercontent.com/14232100/39023101-624b1992-4441-11e8-9011-15bd038477fe.png)
I've investigated little bit and apparently here some fontconfig replacement has place.
And it actually works in KDE based applications but not in GTK.
My custom fonts really missing standard powerline symbols(in comparison with complete nerd font) and it is taken from some other font(don't know how to determine that) in KDE applications.
But GTK application somehow after update stopped doing this replacement in Manjaro.
I have almost the same configuration in Antergos and it works ok.
I just tried to use one of extended powerline symbols from nerd font but as I said in that case there is some small 1 pixel separator between some powerline segment that I would like to avoid.
![screenshot_20180420_021808](https://user-images.githubusercontent.com/14232100/39023304-6c80ccf8-4442-11e8-8f45-6a39d9a7429b.png)
For instance on the latter screenshot you might see it is in between ping and blue segments.

**Comment by dritter** [comment]
Well, do you use a [fontconfig](https://en.wikipedia.org/wiki/Fontconfig) setup? If so, maybe your configs differ. That would at least explain the between Manjaro and Antergos, but not between KDE and GTK (which I assumed you tried both on the half-working machine).

Regarding the gap: There are some [reports](https://github.com/ryanoasis/nerd-fonts/issues/26) about that in the NerdFonts Issue tracker. Ryan is working really hard to get these issues sorted out, but that seems to be a Sisyphean task..

**Comment by IevgenSobko** [comment]
@dritter I'm not using it intentionally. It is part of the Manjaro system(when I try to remove it half of the system packages going to be removed as well by default). Antergos BTW also has it installed by I guess different configs.

**Comment by ryanoasis** [comment]
@IevgenSobko 

> fontawesome already contains powerline symbols as far as I know

It actually does not.

I know this is something you shouldn't have to do but you might get rid of the gap if you go up/down in font size slightly.. :man_shrugging:

Maybe someday we could have a config to adjust positions of glyphs slightly for the Nerd Fonts patcher but that might be a "nice to have". I could try perhaps tweaking the position as well but in most fonts and at most sizes it looks fairly spot on or it's just _slightly_ off. I am actually going to take a look for the next release/build and if it is easy to fix and looks good I will scooch (technical term right?) it over a bit.

If you were so inclined you could also try firing up FontForge or some other font editor and manually adjusting the glyph placement.

> Regarding the gap: There are some reports about that in the NerdFonts Issue tracker. Ryan is working really hard to get these issues sorted out, but that seems to be a Sisyphean task..

Yeah, so it's gotten better but there are scenarios where it isn't quite perfect. I'd like to get it perfect but that can be an enemy of good enough. Who knew that would be asking so much to get dang font characters to line up. Haha it really does feel like pushing a boulder for eternity sometimes. I have been focusing more on features than issues lately but that's likely to change for a next release.

**Comment by IevgenSobko** [comment]
@ryanoasis thx for your comments.
meantime I've found one powerline symbol from powerline-extra font that can live with my inner perfectionist :)
![screenshot_20180429_224527](https://user-images.githubusercontent.com/14232100/39410313-72499b00-4bff-11e8-9001-079d0997901d.png)
At least with this it is hard to notice some gaps :)

**Comment by ryanoasis** [comment]
@IevgenSobko No problem. I totally get that.

Looks good. Rock on! :smile:

**Comment by dritter** [comment]
Closing this one. Problem is solved (at least a workaround exists). Thx @ryanoasis for help.

**Comment by cata0309** [comment]
@IevgenSobko Can you share your terminal theme ? I would like to try it on my terminal, I am facing the same gap issue

**Comment by IevgenSobko** [comment]
@cata0309 you should install POWERLEVEL9K theme for your zsh shell and use following config options for it
https://gist.github.com/IevgenSobko/032aaf2b07d2861977664629f232ba75

**Comment by cata0309** [comment]
Thank you
