### ISSUE TITLE
rust_version doesn't display anything

### ISSUE THREAD

**Issue by TheDan64** [bhilburn/powerlevel9k#803]
I added `rust_version` to my `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` list but nothing appeared.

Looking at https://github.com/bhilburn/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L1107 I see the command used but this doesn't seem to do anything.

Similar commands:
```shell
$ rustc --version
rustc 1.24.0-nightly (b98fd524e 2018-01-05)
$ rustc --version 2>&1 | grep -oe "^rustc\s*[^ ]*"
rustc 1.24.0-nightly
$ rustc --version 2>&1 | grep -oe "^rustc\s*[^ ]*" | grep -o '[0-9.a-z\\\-]*$'

```

Seems like the regex is off in the final grep?

**Comment by dritter** [comment]
Ha! Good catch @TheDan64 . When I implemented this segment I had some noise at the end of the version string. That is why the last regex exists.
Would you mind creating a PR for that?

**Comment by TheDan64** [comment]
Sure; should the inital "rustc" be trimmed out as well? Isn't there a rust icon that should make that obvious?

**Comment by dritter** [comment]
On second thought, this is a bit odd, as on my machine it works as expected:
![bildschirmfoto 2018-04-21 um 01 52 14](https://user-images.githubusercontent.com/1544760/39078048-bf07f04a-4506-11e8-994d-853f201679ff.png)

There is also a [test](https://github.com/bhilburn/powerlevel9k/blob/13b0e383a066c9c37d5cf71d4af521f9b73a173e/test/segments/rust_version.spec) that ensures that the version string gets trimmed correctly.

Which version of `grep` do you use?

**Comment by TheDan64** [comment]
Oh. This is probably my fault. I'm not at my computer at the moment, but I bet I have grep aliased to ripgrep lol

I can verify later and close if that's the case

**Comment by TheDan64** [comment]
Ok, so it's *not* the case that my `grep` is aliased to `ripgrep`. It is, however, aliased to use `--color=always` like so: `alias grep="/bin/grep --color=always"`

It seems as though the additional coloring messes up the final grep (but not the first one) for some reason

**Comment by dritter** [comment]
I would avoid using ripgrep here, not everybody has it installed. And I wouldn't fix using the grep colors in that regex.
The way to go would be to get rid of grep completely, and use `command`:
```zsh
prompt_rust_version() {
  local rust_version
  rust_version=$(command rustc --version 2>&1)
  # Remove "rustc " (inclusive the whitespace) from the beginning
  # of the version string and remove everything after the next
  # whitespace. This way we'll end up with only the version.
  rust_version=${${rust_version/rustc /}%% *}

  if [[ -n "$rust_version" ]]; then
    serializeSegment "$0" "" $1 "$2" $3 "darkorange" "$DEFAULT_COLOR" "Rust $rust_version" 'RUST_ICON'
  fi
}
```

Example:
![](https://user-images.githubusercontent.com/1544760/39083266-8b9d87ae-4562-11e8-8a51-525b62ba43aa.png)

**Comment by dritter** [comment]
My Bad. The parameters for `serializeSegment` and `$1_prompt_segment` differ.

This should be correct:
```zsh
prompt_rust_version() {
  local rust_version
  rust_version=$(command rustc --version 2>&1)
  # Remove "rustc " (inclusive the whitespace) from the beginning
  # of the version string and remove everything after the next
  # whitespace. This way we'll end up with only the version.
  rust_version=${${rust_version/rustc /}%% *}

  if [[ -n "$rust_version" ]]; then
    "$1_prompt_segment" "$0" "$2" "darkorange" "$DEFAULT_COLOR" "$rust_version" 'RUST_ICON'
  fi
}
```

If this works, could you open a PR for that?

**Comment by dritter** [comment]
Meh. Need to apologize again. I wrote that piece of code based on the `next` branch. There we changed the colors to named ones:
```zsh
"$1_prompt_segment" "$0" "$2" "darkorange" "$DEFAULT_COLOR" "$rust_version" 'RUST_ICON'
```
On `master` that line should be:
```zsh
"$1_prompt_segment" "$0" "$2" "208" "$DEFAULT_COLOR" "Rust $rust_version" 'RUST_ICON'
```
