### ISSUE TITLE
SSH_ICON switches to HOST_ICON when running `sudo -s` on remote host (connected via ssh).

### ISSUE THREAD

**Issue by drew-kun** [bhilburn/powerlevel9k#807]
Good day!

Thank you very much for wonderful project. I love it.

I have noticed this kinda behaviour:
![untitled](https://user-images.githubusercontent.com/10493450/39107931-45bebfd2-467a-11e8-8bd3-975e99b2d701.png)

**Expected behaviour:** the SSH_ICON should not change as it's still remote remote ssh shell.

Any ideas?

**Comment by sambadevi** [comment]
I suppose this is intended since you are starting a new shell inside your ssh shell. Technically it’s a local shell now instead of a remote shell.

If you ssh directly into root you should see the SSH_ICON being displayed since you are actually in a remote shell as root now.

**Comment by sambadevi** [comment]
Small Addition:

There are two variables `SSH_CONNECTION` and `SSH_TTY` if those are set the current shell is a remote/ssh shell. Since your switched from the user you originally logged in with to root these variables aren’t set. You can check for yourself with the `env` command if the mentioned variables are set

**Comment by drew-kun** [comment]
I don't think this is intended.
As you can see here the `su` command changes user and starts the new shell but the SSH_ICON does not change in this case

![untitled1](https://user-images.githubusercontent.com/10493450/39148991-95cb2ff6-46f2-11e8-9d6f-1c7c2824cae1.png)

The issue only happens with `sudo -s`.
It is confusing and does not make sense as it is still remote ssh session.
Otherwise any ssh session shell can be called "technically local"

**Comment by sambadevi** [comment]
With `sudo -s` you are starting a completely new shell without using ssh to login into this shell. I guess `su` takes the current env into the root shell and that’s why SSH_ICON behaves correctly there.

I just tried `sudo su` and the SSH_ICON isn’t there just like `sudo -s`

If `env` doesn’t show the mentioned variables as set after using `sudo -s` then you probably have to set either one of them to get the SSH_ICON to work (or use `su` instead)

**Comment by tonylambiris** [comment]
@drew-kun sudo cleans your environmental variables by default. I have the following options set for my personal account:

```shell 
$ sudo cat /etc/sudoers.d/tlambiris
Defaults:tlambiris !requiretty
Defaults:tlambiris !env_reset
```

**Comment by drew-kun** [comment]
@tonylambiris, @sambadevi  Oh, I see. Thanks guys.
