### ISSUE TITLE
Getting [?] instead of icons :(

### ISSUE THREAD

**Issue by panosru** [bhilburn/powerlevel9k#813]
I tried anything I could find by searching issues both here and in awesome terminal fonts repo, but as you can see from bellow screenshots, I still get that [?] instead of an icon :(

![image](https://user-images.githubusercontent.com/400362/39395479-a49c070a-4ae7-11e8-84d0-01d5af1b1bed.png)

![image](https://user-images.githubusercontent.com/400362/39395601-057f21aa-4ae9-11e8-9b38-ad924d11ae32.png)

![image](https://user-images.githubusercontent.com/400362/39395611-18a025cc-4ae9-11e8-8449-07a7c95c9f88.png)

![image](https://user-images.githubusercontent.com/400362/39395585-da0db18a-4ae8-11e8-9dbb-d309198be008.png)

## Update:
I folllowed [these](https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X) instructions and used `POWERLEVEL9K_MODE='awesome-fontconfig'` instead of `POWERLEVEL9K_MODE='awesome-patched'` and now I have:

![image](https://user-images.githubusercontent.com/400362/39396170-fef5b2dc-4af1-11e8-85ea-51574cc0e975.png)

But I still wonder why `awesome-patched` is not working though... :/

**Comment by dritter** [comment]
The instructions you mentioned are to build up a fontconfig based configuration on OSX. This is not the same as using a [pre patched font](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched), because the code points differ.
We have a pretty extensive [documentation about fonts](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts), if you want to know more.

**Comment by dritter** [comment]
Btw. just revisited your issue, and I stumbled upon your initially selected font. "SauceCode Pro" is not the same as "SauceCodePro+Powerline+Awesome" from [pre-patched fonts of Awesome-Terminal-Fonts](https://github.com/gabrielelana/awesome-terminal-fonts/tree/patching-strategy/patched). That is why you had a lot of missing icons in the first place.

But I am closing this issue for now, as it seems you have a working setup.
