### ISSUE TITLE
How to remove hostname and user in powerlevel9k theme

### ISSUE THREAD

**Issue by BeastF5** [bhilburn/powerlevel9k#815]

**Comment by BeastF5** [comment]
Can u please write full command to edit it

**Comment by dritter** [comment]
Errm. Not sure at which step you are stuck.. Basically you could type in your Terminal: `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir time)` (change to your favourite segments), and you should see an effect. To make that permanent, you have to write that variable in `~/.zshrc`..

**Comment by BeastF5** [comment]
Thanks it works and please can u help me more i want to change local host
and username abd write the my name  please help me

**Comment by bhilburn** [comment]
@BeastF5 - You're making it very difficult to help you by not providing enough information about what you are trying to achieve. Much of this is also described in our documentation, which @dritter linked you to in his first response.

I'm going to close this issue for now. If you would like additional help, you can re-open the issue, but please do the following:
* Post a screenshot of what you currently see
* Explain in detail what you would like to achieve
* Link us to the documentation you have read where it looks like you *cannot* do what you want.

**Comment by BeastF5** [comment]
Ok i will send u screenshot

**Comment by BeastF5** [comment]
I want to change this local host and username to my name which i want to
write

**Comment by mrmeku** [comment]
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
