### ISSUE TITLE
FOREGROUND Color not working on custom segments

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#819]
Using `next`, I can't get the `POWERLEVEL9K_CUSTOM_FOREGROUND` Variable to work:

```
POWERLEVEL9K_CUSTOM_PYVER='~/.dotfiles/bin/pyver'
POWERLEVEL9K_CUSTOM_PYVER_BACKGROUND='107'
POWERLEVEL0K_CUSTOM_PYVER_FOREGROUND='white'
```

Output looks like this:
![Imgur](https://i.imgur.com/mSmYYCf.png)

Just to confirm, the code generating the `2.7.4` is not an aliased command adding color codes or something:

```bash
#!/usr/bin/env zsh
if [ -v 'VIRTUAL_ENV' ]; then
 echo "$(python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}.{2}".format(*version))')"
fi

```

**Comment by dritter** [comment]
You have a typo in your variable name: `POWERLEVEL0K_CUSTOM_PYVER_FOREGROUND`. There should be a `9`. ;)

**Comment by sambadevi** [comment]
Ah I missed that one, thanks @dritter !
