### ISSUE TITLE
Discussion: Coding style guideline

### ISSUE THREAD

**Issue by onaforeignshore** [bhilburn/powerlevel9k#824]
Since we are updating everything, maybe we should set a guideline for coding style.

This could include things like:
- case -> myFunction - my_function
- prefixes -> p9kSomeFunction vs someFunction
- an outline of what a segment should have (icon registration, etc.)

What do you think?

**Comment by dritter** [comment]
Thumbs up for bringing up this topic.

I'd like to add defining a proper public API to the discussion (and prefixing internal methods with underscore). This would help us a lot to define which function could be easily changed (= which one is considered internal) in terms of semantic versioning (@sambadevi created #822 for that).

And to answer that points from your list:
- I have a tendency towards camelCased function names, but I see that a lot of shell functions use snail_case.
- I like to prefix "our" functions with `p9k`. This would reduce the possibility of potential name clashes a lot (e.g. `print_icon` is quite a common name, and it might be that other shell scripts define a function with that name). Another advantage is IMHO autocompletion. Users could input `p9k`, press double tab, and get a list of all p9k functions. Maybe we want to distinguish between functions that are user facing (thinking of `get_icon_names`)  and developer facing functions (`print_icon`).
- Thinking of the outline for new segments: Probably we could leverage the latest [github issue templates](https://blog.github.com/2018-05-02-issue-template-improvements/) for that. We just need to create a template for new segments.

**Comment by onaforeignshore** [comment]
I quite like the way `spaceship prompt` did their [API](https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/API.md).

In short:
- internal functions would be `p9k::`
- all variables would be `P9K_`, and
- all segments would be `p9k_`

This seems a lot clearer to me.

**Comment by dritter** [comment]
Closing this in favour of #940. We should keep only one issue per topic.
