### ISSUE TITLE
Padding on right prompt

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#829]
There seems to be a small padding on the right prompt.

As a comparison see the tmux statusline below:

Left Prompt is aligned
![bildschirmfoto 2018-05-08 um 09 34 40](https://user-images.githubusercontent.com/22161944/39744075-4fa05e90-52a3-11e8-99da-0298178a8913.png)

Right Prompt is slightly off
![bildschirmfoto 2018-05-08 um 09 34 51](https://user-images.githubusercontent.com/22161944/39744103-5f64de82-52a3-11e8-95e9-1c1e947ae9ce.png)

I use the following config
```
# General config
POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator battery  time)

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=..
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\uF460 "

POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
```

**Comment by sambadevi** [comment]
Thanks @dritter, it works in my case

**Comment by bhilburn** [comment]
Thanks, @dritter =)
