### ISSUE TITLE
POWERLEVEL9K_VCS_GIT_HOOKS does not work until .zshrc is sourced

### ISSUE THREAD

**Issue by illegalnumbers** [bhilburn/powerlevel9k#834]
So unless I source my .zshrc file manually I don't see any change in my vcs cli. I'm using zsh installed via Brew (zsh 5.4.2 (x86_64-apple-darwin15.6.0)) on mac osx 10.11.6 with iTerm2 3.0.15. My environment variables are set to be 
`export POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-tagname)`

And I've tried with both the export and without the export but it still keeps showing the stash count when I open a new terminal. The only way it goes away is by sourcing the file. Is there something else I should try?

**Comment by dritter** [comment]
Just to get you right: You do not want to see stashes, right?

In that case your `POWERLEVEL9K_VCS_GIT_HOOKS` looks good, but it must be defined _before_ you source the theme or your ZSH framework.

**Comment by illegalnumbers** [comment]
Ah!! That is probably what it is. I will check.

**Comment by illegalnumbers** [comment]
It fixed it! Thanks!
