### ISSUE TITLE
Nixos install instructions not working

### ISSUE THREAD

**Issue by cbailey555** [bhilburn/powerlevel9k#836]
The nix package these instructions rely on 'zsh-powerlevel9k' does not seem to exist anymore, causing the installation instructions to fail. Searching through nix-env -qa | grep <terms> didn't turn anything up either.

- Behavior:

`programs.zsh.promptInit = "source ${pkgs.zsh-powerlevel9k}/share/zsh-powerlevel9k/powerlevel9k.zsh-theme";`

Produces 'error: attribute 'zsh-powerlevel9k' missing, at <nix config location> (use '--show-trace' to show detailed location information)

- Steps to reproduce:
add 
programs.zsh.promptInit = "source ${pkgs.zsh-powerlevel9k}/share/zsh-powerlevel9k/powerlevel9k.zsh-theme"; 
to configuration.nix, rebuild with 'nixos-rebuild switch'

**Comment by bhilburn** [comment]
Thanks so much for providing the solution, @cjpbirkbeck. It really is much appreciated!

@cbailey555 - I'm closing this one out. If you're still having issues, feel free to re-open and comment!

**Comment by LinArcX** [comment]
@cjpbirkbeck After follow your instructions, i'v got this error:
`/etc/zshrc:source:51: no such file or directory: /run/current-system/sw/share/zsh-powerlevel9k/powerlevel9k.zsh-theme`

**Comment by LinArcX** [comment]
Ok, i find the solution.
Put all lines that there is in `.zpreztrorc` inside `.zshrc`, restart the shell and everything will be fine :)
