### ISSUE TITLE
Pyenv version not read from application-specific .python-version file

### ISSUE THREAD

**Issue by deinidol** [bhilburn/powerlevel9k#839]
Hey there,

If `>pyenv version` would result in a non-system wide version set through an application specific .pyenv-version file (output: `my-version-name (set by /Folder/to/current/folder/.python-version)`), the pyenv prompt element does not show up.

This is because the script does not check for the outcome of `>pyenv version` but only for a `$PYTHON_VERSION` environment variable being set. Pyenv virtual environments that are not system wide can also be set through the .python-version file present in the root folder of a project as described in the following section: [pyenv#choosing-the-python-version](https://github.com/pyenv/pyenv#choosing-the-python-version)

```
# pyenv: current active python version (with restrictions)
# https://github.com/pyenv/pyenv#choosing-the-python-version
prompt_pyenv() {
  if [[ -n "$PYENV_VERSION" ]]; then
    "$1_prompt_segment" "$0" "$2" "blue" "$DEFAULT_COLOR" "$PYENV_VERSION" 'PYTHON_ICON'
  fi
}
```

**Comment by dritter** [comment]
Hi @deinidol ,

Thanks for the report. Yes, the segment is currently very basic. We are currently in a big restructuring of the code base (#771 ), so I'll have a look afterwards.

If somebody else wants to pick this one up: We already have an [`upsearch` functionality](https://github.com/bhilburn/powerlevel9k/blob/0e3c1924fe40835dfe189227b8a165de147e65a1/functions/utilities.zsh#L224-L238).
