### ISSUE TITLE
`dir` segment: Extra space in prefix on `next` branch

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#84]
On the `next` branch, there is an extra leading space on the `dir` segment. Check out the screenshot below, where I'm on the `next` branch, then checkout `master` and open a new terminal:

![dirsegment](https://cloud.githubusercontent.com/assets/569571/9669571/ef86c670-523c-11e5-87e5-71bd6472353d.png)

You can see the extra leading space in the first prompt.

**Comment by dritter** [comment]
Whoops. My fault. I've made a quickfix for that.

A better solution might be to always print a whitespace if there is an icon to print (default-whitespace in `print_icon`). Then the icon definition would be simpler, except for the icons that need more space (like the github-icon).

**Comment by bhilburn** [comment]
Fix has been merged.
