### ISSUE TITLE
right prompt displayed in two lines

### ISSUE THREAD

**Issue by felizdonny** [bhilburn/powerlevel9k#842]
Hi, I just started using Oh My Zsh and encountered a display problem.
Here is my configuration:
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs history)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ "
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

![xnip2018-05-18_08-12-50](https://user-images.githubusercontent.com/32689782/40236469-45cc34a2-5a73-11e8-8ae4-62bca67565f4.jpg)
I don't know why history segment is cut into two lines. It seems abnormal to me, so is there a way to fix it?

Thanks in advance!

**Comment by dritter** [comment]
This is most probably an issue with your iterm settings. Please have a look at our [troubleshooting page](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#strange-character--segment-spacing).

**Comment by felizdonny** [comment]
Thank you very much, it solves the problem!

**Comment by upupming** [comment]
Hi, @dinhnv I got this too, but I'm on Windows and VSCode, and there is no iterm `Double-Width Characters`.Could you please help?

![image](https://user-images.githubusercontent.com/24741764/56212726-2e014080-608d-11e9-9e72-676c65311a43.png)

**Comment by romkatv** [comment]
If your terminal cannot display double-width characters, you configure your theme to not use double-width. I use [Pure Power](https://github.com/romkatv/dotfiles-public/blob/master/.purepower) config, which makes my terminal look like this:

![Pure Power](https://raw.githubusercontent.com/romkatv/dotfiles-public/master/dotfiles/purepower.png)

It doesn't use any fancy characters and thus works everywhere out of the box (no patched fonts required).

**Comment by dinhnv** [comment]
@upupming It seems that you are using terminal inside vscode. I see `bash` instead of `zsh`. Please add to your vscode settings this line:
```
"terminal.integrated.shell.osx": "/bin/zsh"
```

**Comment by upupming** [comment]
Actually, bash is the same as zsh.
