### ISSUE TITLE
weird '?' symbol in my prompt

### ISSUE THREAD

**Issue by whoissqr** [bhilburn/powerlevel9k#845]
I am using Mac OS with oh-my-zsh,

my ~/.zshrc looks like this:

![image](https://user-images.githubusercontent.com/4846507/40350678-15683f28-5ddd-11e8-84e6-9ec4d0197660.png)

and, my prompt looks like the following:

![image](https://user-images.githubusercontent.com/4846507/40350630-f0af7f0c-5ddc-11e8-97fc-52465ad7400c.png)

what do i need to change to get rid of the '?'  symbol in between?

thanks!

**Comment by salmanulfarzy** [comment]
[Install and configure `powerline-fonts`](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font)

**Comment by whoissqr** [comment]
hi @salmanulfarzy 

thanks. I already installed using option 3.

https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#option-3-install-awesome-powerline-fonts

is there a way to tell whether my installation is successful?

**Comment by dritter** [comment]
Well. Did the questionmarks go away? Another easy way is to call `get_icon_names` to see if the icons show up..

**Comment by whoissqr** [comment]
ok. I tried just now, and i noticed that my POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR and POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR are showing question mark; is this intended or i should define them?

![image](https://user-images.githubusercontent.com/4846507/40400506-03746f1a-5e75-11e8-8cef-46d7661818ea.png)

**Comment by whoissqr** [comment]
okay, at least i can define it away.

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''

![image](https://user-images.githubusercontent.com/4846507/40400893-bb453f06-5e76-11e8-945f-07693d539af0.png)

**Comment by dritter** [comment]
Sorry for the delay. Yes, you could configure your segment separators away... But it seems like your font setup is still not right. Most of the icons show up, so I assume you use a fontconfig setup and set `POWERLEVEL9K_MODE="awesome-fontconfig"`, right?
If this is all right it is likely that your fontconfig setup is faulty. Then you should check the order of your fonts in your config..

**Comment by whoissqr** [comment]
hi @dritter , sorry for the very late reply, i was traveling without notebook during past 2 week.

i followed the link (https://github.com/gabrielelana/awesome-terminal-fonts/wiki/OS-X) , and my order of font is like the following:


![image](https://user-images.githubusercontent.com/4846507/41471014-f8beda56-70e4-11e8-8ae9-11e5be4a5ea3.png)

**Comment by sambadevi** [comment]
Might be a stupid question but, which Emulator are you using (Terminal, iTerm2, other)?
Also did you edit your theme in your Emulator to use the patched font?

**Comment by dritter** [comment]
So it looks like you are only missing the Segment Separators. This might be, because you did not include a font that has the powerline icons included. As far as I remember, the base for the `patching-strategy` branch of Awesome Terminal Fonts is such a font. But on the fallback strategy you have to include such a font yourself.

**Comment by whoissqr** [comment]
@sambadevi , i am using iTerm2 and zsh. I have the following in my ~/.zshrc; it is sufficient?

 11 POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"
 12 POWERLEVEL9K_MODE='awesome-fontconfig'
 13 POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
 14 POWERLEVEL9K_COLOR_SCHEME='light'
 15 POWERLEVEL9K_DISABLE_RPROMPT=true
 16 RPROMPT="%{%}"
 17 ZSH_THEME="powerlevel9k/powerlevel9k"

@dritter , thanks, I will look at the patching-strategy branch.

**Comment by dritter** [comment]
What I was trying to say is that the `patching strategy` branch uses a Powerline enabled font as base, and you need to use such a font as main font. No need to switch entirely.

**Comment by bhilburn** [comment]
Going to close this one out due to inactivity. Let us know if you're still having issues!
