### ISSUE TITLE
Meslo fonts not being listed on gnome-terminal

### ISSUE THREAD

**Issue by notrev** [bhilburn/powerlevel9k#846]
I use `Meslo LG M for Powerline` and want to use the Nerd Fonts patched version. I tried all `Meslo LG M` in the repository, but none of them appeared in the gnome-terminal's fonts list. they were listed in the system, thought (in the `fonts` application).

I also downloaded the original ones, without any patches, and they got listed.

Anyone has any clue about how to fix this?

**Comment by notrev** [comment]
Sorry, this is most likely an issue with Nerd Fonts.

An issue was opened there: https://github.com/ryanoasis/nerd-fonts/issues/270

**Comment by bhilburn** [comment]
Thanks for the update! @ryanoasis does sometimes pop in, here, btw! `=)`
