### ISSUE TITLE
OMZ + NerdFonts = missing icons ?

### ISSUE THREAD

**Issue by RaisonBlue** [bhilburn/powerlevel9k#849]
Am afraid this is another font-missing issue... I'm trying to get basic default powerlevel9k installed on oh-my-zsh. This is my zshrc in which `ZSH_THEME` and `POWERLEVEL9K_MODE` have been set.

```bash
export ZSH=/home/blue/.oh-my-zsh
ZSH_THEME="powerlevel9k/powerlevel9k"
CASE_SENSITIVE="true"

plugins=(
  git
  ssh-agent
)

source $ZSH/oh-my-zsh.sh
POWERLEVEL9K_MODE='nerdfont-complete'
```
> ~/.zshrc

 
As a terminal emulator, I'm using Rxvt which I configure to use Hack Nerd Font Mono :

```bash
URxvt*font:                         xft:Hack Nerd Font Mono:style=Regular
```
> ~/.config/Xresources.d/rxvt

 
Font as been properly installed (frorm nerd-font ./install.sh script) and can be displayed with `fc-list` :

```bash
/home/blue/.local/share/fonts/NerdFonts/Hack Regular Nerd Font Complete.ttf: Hack Nerd Font:style=Regular
/home/blue/.local/share/fonts/NerdFonts/Hack Bold Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold Italic
/home/blue/.local/share/fonts/NerdFonts/Hack Bold Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold
/home/blue/.local/share/fonts/NerdFonts/Hack Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Italic
/home/blue/.local/share/fonts/NerdFonts/Hack Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Italic
/home/blue/.local/share/fonts/NerdFonts/Hack Regular Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Regular
/home/blue/.local/share/fonts/NerdFonts/Hack Bold Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Bold Italic
/home/blue/.local/share/fonts/NerdFonts/Hack Bold Nerd Font Complete.ttf: Hack Nerd Font:style=Bold
```
> fc-list |grep Hack

 
Result of get_icon_names :

![2018-05-28-125430_488x1031_scrot](https://user-images.githubusercontent.com/15968815/40611339-35b0eb66-6276-11e8-8a72-d4c183dc8e9b.png)
> get_icon_names

 
My computer has been rebooted after the whole installation process (X has been reloaded). Did I miss anything in the doc ?

**Comment by dritter** [comment]
You need to switch the order of these two lines:
```zsh
source $ZSH/oh-my-zsh.sh
POWERLEVEL9K_MODE='nerdfont-complete'
```

**Comment by RaisonBlue** [comment]
@dritter Wow ! Ok ! Well thanks a lot  :+1:
