### ISSUE TITLE
Background Jobs Is Displayed Right After Killed Last Job

### ISSUE THREAD

**Issue by Griiid** [bhilburn/powerlevel9k#851]
Hi, powerlevel9k looks great and it is easily to customize ourselves, nice job. 😄 

What I have done is:
1. Execute some program.
2. Press ~~`Ctrl-C`~~ `Ctrl-Z` to make it become a background-job, and this is the only one background-job.
3. Kill the job.

After step 2, the background-job icon was displayed, this is correct.  
But, after step 3, the background-job icon was still there, this is wrong, the icon will disappear after I press enter or execute other command.

I have no idea how to fix this bug (or maybe it's not?), can someone helps?

**Comment by dritter** [comment]
Hmm. `Ctrl-C` usually kills the program, but `Ctrl-Z` moves it in the background.
After a quick check I did not see this issue.

My steps were:
1. `less powerlevel9k.zsh-theme`
2. Press `Ctrl-Z`
3. Run `htop` and kill the `less` process

Background-job icon was gone.

Just to be sure, you did this in the same shell, right? Or did you open a new shell, kill the program there, return back and not pressing `enter`?

**Comment by Griiid** [comment]
I'm sorry, I did `Ctrl-Z`, not `Ctrl-C`

I did them in the same shell and I use **zsh**.

I noticed that the origin configuration doesn't occur this problem, just like this [picture](https://imgur.com/a/ZXFeyMl)

But the problem occurred after I add these configuration in .zshrc

```
  POWERLEVEL9K_DISABLE_RPROMPT=true
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status background_jobs time dir vcs)
```

Here's what I saw: [picture](https://imgur.com/GHStGF9)

**Comment by dritter** [comment]
Okay. I see the problem if I use `kill %1`. This seems to be an issue how the signal is executed:
![bildschirmfoto 2018-06-02 um 01 19 07](https://user-images.githubusercontent.com/1544760/40867234-0eaa8f28-6603-11e8-850a-9fe67e3c93ba.png)
As you can see, the process terminated message always comes last.. I even get the same result, if I do a `kill -9 %1`.

Only thing that works is to `disown` the process:
![bildschirmfoto 2018-06-02 um 01 42 18](https://user-images.githubusercontent.com/1544760/40867642-4812a1c6-6606-11e8-8ac5-79b71e17a73a.png)
But we probably do not want to do this..

**Comment by dritter** [comment]
Yes, there seems to be a difference how ZSH handles right and left prompt. From our point of view, it is the exact same code that is run (at least for the segment itself).
![bildschirmfoto 2018-06-05 um 00 40 59](https://user-images.githubusercontent.com/1544760/40945497-635ebc26-6859-11e8-9358-b4c4aef377c6.png)

**Comment by bhilburn** [comment]
Okay, I'm really not sure what to do about this one, to be honest. If ZSH is fundamentally drawing the `PROMPT` and `RPROMPTS` differently with respect to proc timing, that's likely something we are just going to have to accept as a `wont fix`.

@dritter - do you agree / disagree?

**Comment by bhilburn** [comment]
Closing this one out as a wont fix - this seems like something we just can't do anything about. If someone disagrees or has other ideas, feel free to re-open!
