### ISSUE TITLE
Newline not working in the right prompt?

### ISSUE THREAD

**Issue by ivellios** [bhilburn/powerlevel9k#858]
Am I missing something or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` cannot use newline? I tried to put it together with time and custom echo command and it shows up in one line.

**Comment by dritter** [comment]
Unfortunately `newline`s are only supported for `left` segments. I started working on supporting right prompt as well (see #856 ), but this has quite a low prio right now.

**Comment by bhilburn** [comment]
Going to close this one out in favor of tracking the discussion in #856, which is where I've pointed several other issues about this same topic. Thanks so much for raising this as something you care about, @ivellios!
