### ISSUE TITLE
Can't change to color of the 'dir' segment

### ISSUE THREAD

**Issue by gdalex** [bhilburn/powerlevel9k#866]
Hi,

I've set POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white' in my .zshrc, but the color of the 'dir' segment is still black.

The only one that is working is POWERLEVEL9K_DIR_HOME_FOREGROUND='white', but it applies only the home dir.

What am I missing?

Thanks

**Comment by dritter** [comment]
Hi @gdalex !
In which folder did you try it? The `default` state does only affect folders outside of the home directory. For folders inside of your home directory, there is `home_subfolder` (`POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND`).. Any chance you tried in a subfolder of you home directory?
![bildschirmfoto 2018-06-11 um 22 29 01](https://user-images.githubusercontent.com/1544760/41255469-ece3bef2-6dc6-11e8-983a-4ab742d4fe07.png)

**Comment by gdalex** [comment]
Hi dritter,

you're right, I tried it inside my home subfolders.
It works perfectly with POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND.

Cheers
