### ISSUE TITLE
Making `dir_writable` a default segment

### ISSUE THREAD

**Issue by lucatrv** [bhilburn/powerlevel9k#869]
I would suggest the following two updates for the default `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`:

- Add `dir_writable`, which is in general very useful in particular in connection with `root_indicator`.
- Remove `rbenv`, which is useful only for rubyists, and therefore IMHO should not be enabled on a general basis but only by people using it (or otherwise all other language segments should be enabled by default...).

So I would suggest to update the default settings to:

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)
```

Of course I am aware that I can always set those defaults by myself, and this is wonderful, but I wanted to give my 2 cents contribution hopefully to make `powerlevel9k` even better. Thanks!

**Comment by dritter** [comment]
Hi @lucatrv !

Thanks for your suggestion. That is something that @bhilburn has to decide. IMHO you got a point to set the defaults to a small, common set of segments that most people find useful. I would even add `command_execution_time` to the defaults.

**Comment by lucatrv** [comment]
Yes I know of `POWERLEVEL9K_DIR_SHOW_WRITABLE=true` but it shows a dark lock on regular blue background, IMHO `dir_writable` (yellow lock on red background) is a better choice as it stands out.

**Comment by bhilburn** [comment]
@lucatrv - Thanks so much for filing this, and as you can tell, everyone agrees with you! We actually removed `rbenv` before the last release, and as @onaforeignshore, `dir_writeable` is now merged into the primary `dir` segment. We should be all set, here!

Let us know if you spot anything else `=)`

**Comment by lucatrv** [comment]
@bhilburn I tested the `next` branch. By default it shows only `dir`, so to show the write permission state I need to set `P9K_DIR_SHOW_WRITABLE=true` manually, and this shows a dark lock on regular blue background (which is difficult to notice). Just to avoid any misunderstandings, I point out that my suggestion was to set `P9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)` by default, which gives the following different outcomes:

- write permission state is shown by default,
- the lock is shown in yellow on red background (which stands out).

**Comment by bhilburn** [comment]
Hi @lucatrv - 

Ah, yes, I see - your suggestion was to make the `writeable` icon display by default, and change the default colors. I'm willing to entertain both ideas, actually, but would like input from others who work on OS maintenance and system administration.

@shibumi @rjorgenson @dritter @iScrE4m @docwhat - What do you guys think about turning on the writeable flag by default in the `dir` segment, so that if you enter a dir without write perms it pops up?

Separately, it sounds like there is a bug in the `dir` segment on the `next` branch, because what you tried should work, @lucatrv. The `dir_writable` segment actually still also exists, too. Can you try putting that segment back into your segment list and let us know if that one works? @onaforeignshore

**Comment by lucatrv** [comment]
I just tried with:
```
P9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)
```
and I do not get the lock.

Note: I'm on Debian Stable, zsh v5.3.1

**Comment by bhilburn** [comment]
@lucatrv - Just merged @dritter's fix for `dir_writable`, #1017. Can you pull next and give it a shot?

**Comment by onaforeignshore** [comment]
The variables are `P9K_DIR_NOT_WRITABLE_xxx`

**Comment by onaforeignshore** [comment]
@bhilburn To change the defaults of this segment in `next` just change the values of line 18 of `segments/dir.p9k`

**Comment by lucatrv** [comment]
@onaforeignshore thanks for your hint, I confirm that for instance with the following:

```
P9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
P9K_DIR_SHOW_WRITABLE=true
P9K_DIR_NOT_WRITABLE_FOREGROUND='black'
P9K_DIR_NOT_WRITABLE_BACKGROUND='yellow'
```

I can set all the prompt in black on yellow for not writable directories. I assume that in order to change only the lock colors (for instance yellow on red) we still need to show the separate `dir_writable` segment:

```
P9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)
```

**Comment by onaforeignshore** [comment]
You can set the icon foreground colour with `P9K_DIR_NOT_WRITABLE_ICON_COLOR`

**Comment by lucatrv** [comment]
Ok, so maybe one possible option with `dir_writable` integrated into `dir` would be to set:

```
P9K_DIR_SHOW_WRITABLE=true
P9K_DIR_NOT_WRITABLE_ICON_COLOR='red'
```

For myself, I prefer however to stick with the previous behavior and set by default:

```
P9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)
```

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
