### ISSUE TITLE
vi mode

### ISSUE THREAD

**Issue by lgjmac** [bhilburn/powerlevel9k#874]
Hi guys. Great work.
But.../
how do you get vi mode working on a vanilla zsh Arch installation? I have tried using both the pacman package and the github clone. Everything else works fine. Reading the issues, has there been some problem recently with the vi-mode indicator? Or is there something tiny I'm missing in my zshrc? I can get the prompt to display but it sticks in INSERT.
Thank you.

**Comment by softmoth** [comment]
You might give [vim-mode][] a try. It's a separate plugin but I've done quite a bit to make its mode indicator work well.

[vim-mode]: https://github.com/softmoth/zsh-vim-mode

**Comment by bhilburn** [comment]
Hey @lgjmac @softmoth - Are you still having issues with vi-mode? Does it work for you on the `next` branch?

**Comment by softmoth** [comment]
It's fine for me.

**Comment by bhilburn** [comment]
Really happy to hear that! Thanks so much for responding, @softmoth.

I'm going to close this issue out. If you're still having issues, @lgjmac, feel free to re-open.

**Comment by tkolleh** [comment]
Resolved my `vi_mode` switching issue by using @softmoth's [plugin](https://github.com/softmoth/zsh-vim-mode)
