### ISSUE TITLE
pyenv plugin ignore .python-version file

### ISSUE THREAD

**Issue by j9ac9k** [bhilburn/powerlevel9k#879]
the pyenv plugin does not appear to pick up the current python version.  Looking at the history, it appears that #680 removed the query to `pyenv version` and instead looked directly at the `PYENV_VERSION` environmental variable.

If we look at the pyenv documentation [here](https://github.com/pyenv/pyenv#choosing-the-python-version) we can see that having the environmental variable of `PYENV_VERSION` is only one of the methods to select the current python version.  If no variable is set, one can place a `python-version` file in a directory.  Furthermore, you can set a global python interpreter as well.

This issue was driven by #679, but I think #680 was not the correct fix, as @dinhnv wanted to remove the global environment variant; but that still leaves those of us that are dependent on local `.python-version` files as not being utilized.

Here is a screenshot that hopefully illustrates the issue.

![screen shot 2018-06-19 at 8 55 33 am 1](https://user-images.githubusercontent.com/646398/41608943-89404ca2-739e-11e8-9f02-a9f3c49a4a23.png)

Ideally the pyenv plugin would show that I'm using the `pytest-book` python version.

I would be happy to attempt a pull request to address this.

**Comment by bhilburn** [comment]
This issue was fixed by the merge of #900! Let us know if you are still seeing issues!
