### ISSUE TITLE
Is there a way to truncate directory name from left?

### ISSUE THREAD

**Issue by munjalpatel** [bhilburn/powerlevel9k#885]
I see there is a `truncate_from_right` strategy. However, I want to truncate names from left instead of right. Is there a similar `truncate_from_left` option?

**Comment by dritter** [comment]
Hi @munjalpatel !

@onaforeignshore was so kind to add this missing truncation option. Could you try that PR (#889) and see if that works for you? That would be awesome.

**Comment by bhilburn** [comment]
Thanks so much for opening this, @munjalpatel! Closing this in favor of tracking the discussion in #998, where the work is happening `=)`
