### ISSUE TITLE
Icon doesn't display AtomicCoding powerlevel9k

### ISSUE THREAD

**Issue by janskey** [bhilburn/powerlevel9k#892]
Hi, how can I show the apple and other icons? i'm following the powerlevel9k [AtomicCoding](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config#atomiccodings-configuration) config.

![screen shot 2018-07-05 at 8 25 02 am](https://user-images.githubusercontent.com/11430512/42296923-9cb3b6b6-802d-11e8-9ebd-bc760a13e4b1.png)

![screen shot 2018-07-05 at 8 31 26 am](https://user-images.githubusercontent.com/11430512/42296952-dff64e52-802d-11e8-985b-0f16327a4d94.png)

**Comment by dritter** [comment]
Hi @janskey !
You need to set `POWERLEVEL9K_MODE="nerdfont-complete"` before the theme gets sourced. In doubt, put it on the top of your `~/.zshrc`. [Link to wiki](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts#p9k-configurations).

**Comment by onaforeignshore** [comment]
`POWERLEVEL9K_MODE` tells the theme what font you have installed, so it is also required in addition to setting the font. Unfortunately, there is no way to detect what font the user is using, so this step is the only way for the theme to know what font set you want to use.

**Comment by janskey** [comment]
@dritter it worked.

> put it on the top of your ~/.zshrc
