### ISSUE TITLE
Cannot change background/foreground colors

### ISSUE THREAD

**Issue by izemmouri** [bhilburn/powerlevel9k#896]
It seems setting the POWERLEVEL9K_(ELEMENT)_FOREGROUND/BACKGROUND to either symbolic color names or 3 digits numeric color codes  and sourcing back powerlevel9k.zsh-theme doesn't update to the new colours.

I can't say if I'm missing something here. Can anyone reproduce the problem or help me troubleshoot it?

**Comment by dritter** [comment]
Hi @izemmouri !

Some of the Segments are quite complex and can have different states. To give a user the opportunity to configure the colors of these states, we use special variables. Please have a look at [the wiki](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#special-segment-colors) where a describe the different States for each segment.

Hope that helps!

**Comment by izemmouri** [comment]
I am actually just plain stupid. Changing POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND simply worked! I hadn't takent into account the (state) part. Sorry about the inconvenience. Thank you.
