### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by lazarvgd** [bhilburn/powerlevel9k#897]
Hi there, 

I have installed powerlevel9k and I am facing the problem with icons, instead icons in my iterm2 is displayed question mark character, how can I fix this?

Pls sorry if this is trivial question, I haven't found the answer so far.
Thanks :)

here is the screenshot 

![image](https://user-images.githubusercontent.com/11629801/42507939-29d42630-8447-11e8-8519-65269a12ef9e.png)

**Comment by dritter** [comment]
Hi @lazarvgd !

It looks like you have not installed and configured the correct fonts. Please have a look into the [installation instructions](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions#step-2-install-a-powerline-font) and the [about fonts page](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts).

**Comment by bhilburn** [comment]
Closing this issue as it seems resolved. Feel free to re-open if you are still having issues, @lazarvgd!
