### ISSUE TITLE
Context Segment Colors envvars not being used

### ISSUE THREAD

**Issue by robobenklein** [bhilburn/powerlevel9k#898]
#### Describe Your Issue
What is happening?

![image](https://user-images.githubusercontent.com/5423266/42534105-d386c414-8459-11e8-8195-2d1be00cdf70.png)
![image](https://user-images.githubusercontent.com/5423266/42534368-8f4d3598-845a-11e8-9c3e-1cdff4858474.png)
(Ubuntu 16.04)
![image](https://user-images.githubusercontent.com/5423266/42534570-ff46d444-845a-11e8-86f4-5ba08fc833d8.png)
(RHEL 7.5 - I realize zsh <5.1 isn't supported? https://github.com/bhilburn/powerlevel9k/issues/877 )

Note - does *not* occur on my local machine:

![image](https://user-images.githubusercontent.com/5423266/42534239-3725a224-845a-11e8-86c8-7c73cb8b9ec2.png)
(Ubuntu 18.04)

#### Have you tried to debug or fix it?

This occurred just today as of the 0.6.5 release. It was working this morning, before I ran the update. I couldn't find any reason this broke locally.

I haven't seen any change notes in the Github release that specified a greater ZSH requirement, but to me it looks like I would just prefer the previous / older release since I didn't have any problems there.

#### Environment Information

P9K is being managed by Zplugin, I've tried fresh reinstalls and on multiple systems.

Systems shown in screenshots use the same ZSHRC and variables to start.

**Comment by bhilburn** [comment]
Uh oh, looks like we might be tagging a v0.6.6? @dritter 

@robobenklein - Can you clarify what version of ZSH you are running? Is this < 5.1, based on your comment about RHEL 7.5?

@dritter - Might be good to roll back to our own function for legacy OS support.

**Comment by dritter** [comment]
Hi @robobenklein !

Thanks for that lightning-fast report. I looked a bit into this, and it looks like this is not a bug, but a feature ;)
The `context` segment is now aware of `sudo` powers. So if you recently did something with sudo, this state is in charge. You can test this behaviour with `sudo -n true && echo "true" || echo "false"`, so you are probably changing the color for the wrong state.

Old states:
`ROOT` - If you are root
`DEFAULT`

New states:
`ROOT` - If you are root
`SUDO` - If you got elevated rights via sudo
`DEFAULT`
`REMOTE` - If you are via SSH in the machine
`REMOTE_SUDO` - If you got elevated rights and SSHed in the machine

Proof that it works with 5.0.2:
![bildschirmfoto 2018-07-10 um 22 59 58](https://user-images.githubusercontent.com/1544760/42537758-1cc83928-8496-11e8-97ad-84830636f1e2.png)

@bhilburn We need the `defined` function only in one case in the `battery` segment..

**Comment by robobenklein** [comment]
@dritter Yep! It was `POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND` that I was missing!

Upon seeing the change, the first place I looked was the wiki and docs. ( https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt still shows the three states for context )

That's probably where my confusion came from.

**Comment by dritter** [comment]
Thanks for pointing at the wiki. I fixed that.

Note to self:
Look into the wiki for other cases that need to be updated.

**Comment by robobenklein** [comment]
Also got `SUDO` state on `user` but I don't see anything else right now.

**Comment by bhilburn** [comment]
Hah, I had actually left this open as a reminder to fix the Wiki. You beat me to it, @dritter! Thanks so much.

@robobenklein - Thanks again for reporting this and pointing us to the broken docs! We really appreciate it `=)`

**Comment by unikitty37** [comment]
The text in the Stylizing Your Prompt page of the wiki is still considerably less helpful than it could be, as it just lists the context names without the explanations.

Also, is there a way to simply print the name of the context type that the prompt is using? I've spent an age trying to debug a .zshrc, only to find that it wasn't using the _REMOTE_ form despite my having ssh'ed in. It would be helpful if the docs could mention how this detection worked.

**Comment by dritter** [comment]
@unikitty37 Could you have a look at the [documentation for the `context` segment](https://github.com/bhilburn/powerlevel9k/blob/next/segments/context/README.md) in the upcoming  Release? Hopefully that is more helpful. :)

**Comment by unikitty37** [comment]
Thanks — that _is_ lot more helpful :)
