### ISSUE TITLE
missing signature for release 0.6.5

### ISSUE THREAD

**Issue by shibumi** [bhilburn/powerlevel9k#899]
Hello,
The signature for release 0.6.5 is missing. Please sign the tarballs so that we can be sure that the code didn't get compromised. Thanks

**Comment by bhilburn** [comment]
Thanks for the reminder! When I made the release, I didn't have access to my PGP keys. Working on getting it signed and uploaded now `=)`

**Comment by bhilburn** [comment]
Dealing with the small problem that my PGP keys expired.

Also that they're in an encrypted filesystem that I apparently can't remember the master key for.

I AM AWESOME

**Comment by bhilburn** [comment]
Update: I'm pretty sure I'm super close to remembering my password

**Comment by bhilburn** [comment]
WHY DID I DO TO THIS TO MYSELF

**Comment by bhilburn** [comment]
Well, my PGP keys are expired, anyway. If I can't figure this out shortly I'm just going to create new ones. /me sighs

**Comment by robobenklein** [comment]
Might I ask here, why not sign the git commits as well when you get your key back?

**Comment by shibumi** [comment]
For signing commits add this to your gitconfig:
```
[user]
    name = <your name>
    email = <your mail>
    signingkey = <your key ID>
[commit]
    gpgsign = true
```

**Comment by shibumi** [comment]
@bhilburn Well this is a bad situation now :D my "paranoid"-me would say now:"Check all commits since last version, maybe bhilburns account turned into an NSA Agent",

my "friendly"-me says:"Just generate a new Key, get a password manager, set the expiration date to 2 years and be fine"

**Comment by bhilburn** [comment]
@shibumi - Hah, I never lost access to my SSH keys, which are how I manage P9k, so you don't have to worry about commits, here. Signing them with PGP is a good idea, though - I'll set that up going forward.

Anyway, it would great if I could regain access to my existing PGP keys and just renew them. If I can't, I'll just gen some new ones and move on.

**Comment by shibumi** [comment]
@bhilburn do you have the private key and the public key? :D you could generate a password list with passwords you remember and then you iterate through it with john the ripper or hashcat or something like this..

**Comment by bhilburn** [comment]
@shibumi - It's not the password for the key I've forgotten, but rather the password for the encrypted filesystem I keep it on, hah. With some back-of-the-envelope math, it would cost something like $20T to break it.

Anyway, if I can't remember it shortly, I'll just gen some new keys. The old ones are expired anyway, hah.

**Comment by shibumi** [comment]
any update? it's already one week and I want to push the newest version to our repositories

**Comment by shibumi** [comment]
Any update? the Arch Linux users are waiting for an update. They are currently still on version 0.6.4

**Comment by bhilburn** [comment]
Hey @shibumi - So sorry for dropping the line, here. I'm going to get it signed & updated, but we're going to push out a v0.6.6 ASAP - Arch users will probably be better off, to be honest, if they skip v0.6.5 altogether and just go straight to v0.6.6.

Expect to see a lot of activity moving towards this soon, but I'll get the v0.6.5 signed and uploaded soon, regardless, too.

**Comment by shibumi** [comment]
Hey @bhilburn do you have already a release date for 0.6.6? Because if it will take more than 4 weeks I would like to have version 0.6.5 in our repositories, but I really need a signature for the release then.

**Comment by bhilburn** [comment]
@shibumi - It'll be out LONG before then ;)

**Comment by bhilburn** [comment]
@shibumi - v0.6.6 is pending, and will have a signature =)

**Comment by bhilburn** [comment]
@shibumi - v0.6.6 just released and pushed, and it includes a signature! =)
