### ISSUE TITLE
Context is Orange on Black with battery prompt error (prompt_battery:99: unknown condition: -v)

### ISSUE THREAD

**Issue by Maxattax97** [bhilburn/powerlevel9k#906]
#### Describe Your Issue

I just ran `zplug update` today after a long while.
Context is orange/yellow on black, despite configuration.
Battery prompt displays an error and interrupts print: `prompt_battery:99: unknown condition: -v`

![screenshot_2018-07-13_08-45-00](https://user-images.githubusercontent.com/4708067/42692246-0e24a656-8679-11e8-9644-c68aee45f493.png)

#### Have you tried to debug or fix it?

I am using the latest version from the master branch (`d031b3e`). I rolled back to commit `c36b47b` and the issues have disappeared. I also tried rolling back to the more recent `fcea56b` (contains a distro fix I submitted), but this only repaired the battery prompt; the context is still broken.

#### Environment Information

  - ZSH v5.1.1
  - ZPlug: `zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme`
  - I am using the latest version from the master branch (`d031b3e`)
  - Konsole
  - Linux Mint 18.3 Sylvia
  - `.zshrc` is accessible [here](https://github.com/Maxattax97/miscellaneous/blob/master/.zshrc)

**Comment by bhilburn** [comment]
Hey @Maxattax97! Thanks for the bug report!

We just merged some fixes into `master`. Can you do a quick pull and let me know if anything is different for you?

**Comment by Maxattax97** [comment]
I am on my home desktop for the weekend, the problem occurred on my work laptop (which is at the office).

I have pulled latest on this machine and while the battery prompt issue is not visible (since my desktop does not have a battery), the orange context still is. I've discovered that it only turns orange after I execute a command with `sudo`. One thing to note is that my work laptop's primary user has root privileges (it does not need `sudo`).

![screenshot_20180714_161903](https://user-images.githubusercontent.com/4708067/42728140-a992d802-8781-11e8-9504-4b2ec0adfc84.png)

**Environment Information (for my desktop)**

 - ZSH v5.5.1
 - ZPlug: `zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme`
 - I am using the latest version from the master branch (`a7b3f31`)
 - Konsole
 - OpenSUSE Tumbleweed
 - `.zshrc` is the same as stated previously

**Comment by dritter** [comment]
The context segment has new states, including `sudo` and `remote_sudo`. You can change the colors for this as stated in the [readme](https://github.com/bhilburn/powerlevel9k/blob/master/README.md#context).

**Comment by Maxattax97** [comment]
That's fixed, thanks for the information. I'll let you know more about the battery prompt when I get back to the office.

**Comment by Maxattax97** [comment]
Latest version fixed the battery prompt issue. Thanks guys, you made this a pleasant experience!

**Comment by bhilburn** [comment]
Thanks so much for working with us, @Maxattax97, and being a P9k user! Cheers! `=)`
