### ISSUE TITLE
Custom icons have disappeared/changed

### ISSUE THREAD

**Issue by vaskark** [bhilburn/powerlevel9k#908]
I recently upgraded to the latest Powerlevel9k (from git) and noticed some changes to my prompt icons. My user icon has been changed to an unlocked lock icon, and there's now a clock icon in the time status when it wasn't there before.

I have these settings in my .zsh config file:

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user ssh dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time)
POWERLEVEL9K_USER_ICON="\uf007 "
POWERLEVEL9K_TIME_FORMAT="%D{%I:%M %p}"
POWERLEVEL9K_HOME_ICON="\uf015 "
POWERLEVEL9K_HOME_SUB_ICON="\uf07c "
POWERLEVEL9K_FOLDER_ICON="\uf07c "
POWERLEVEL9K_MODE='nerdfont-complete'

Environment:
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
OH-My-ZSH (latest)
P9K cloned from git repo
urxvt, gnome-terminal,tilix

Fonts:
UbuntuMono Nerd Font Mono for urxvt (never could get powerline fonts to work there)
Source Code for Powerline for gnome-term & tilix
Mode: nerdfont-complete
font-issues.sh: 
get_term:16: command not found: get_ppid
get_term:17: command not found: get_process_name
.. over and over
get_icon_names: looks correct

Not sure what else I can describe, although I've had no end of trouble getting these fonts to play nicely :)
Hope someone can help!

**Comment by bhilburn** [comment]
Hi @vaskark - 

The `time` segment does now make use of the clock icon. If you'd prefer not to use it, just set that icon to blank.

Depending on how old your previous version was, the `user` segment is now able to show you states including sudo and root. See docs here: [user segment](https://github.com/bhilburn/powerlevel9k#user)

If you are seeing an unlocked icon, that means you have `sudo` privileges. You can disable that icon by setting it to a blank string.

Let us know if this helps!

**Comment by vaskark** [comment]
Thank you so much for responding so quickly!

I just figured out I needed to set the time icon to blank before I checked back in here ... so at least I did something right ;)

Setting the sudo icon to blank also worked. Although, getting my former user icon back in there doesn't seem to be working. Maybe keeping the new default unlocked icon is the way to go.

One question, though: when I use Nerd Fonts for urxvt the icons all appear very small, yet when I use Powerline Fonts for Gnome-Term & Tilix the icons appear bigger and easier to see. Is this normal? But some icons are still kinda small here anyway. Like the os_icon and ssh icons. Anything I can do to make those bigger like the rest?

**Comment by bhilburn** [comment]
That's an artifact of the font you choose, and not something P9k can control, unfortunately. Some fonts simply have larger glyphs than others.

Overriding the USER icon should still work, by the way. If it's not, can you show a screenshot of what's happening?

**Comment by vaskark** [comment]
K, here's what I got in my config:

POWERLEVEL9K_USER_ICON="\uF007 "
POWERLEVEL9K_SUDO_ICON=""

[Screenshot](https://i.imgur.com/LXvIH9o.png)

**Comment by onaforeignshore** [comment]
If you set `POWERLEVEL9K_SUDO_ICON="\uF007"` then the icons will be the same for both states.

**Comment by vaskark** [comment]
That did it! Thanks so much for all your patient help, guys.

**Comment by bhilburn** [comment]
Closing as resolved. Thanks so much, @onaforeignshore for the support, and glad you are up and running, @vaskark!
