### ISSUE TITLE
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD set to true display error

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [bhilburn/powerlevel9k#910]
Thanks for opening an issue! For a project that deals with as many different things as P9k, debugging problems can be difficult. Please follow the guide, below, to create a bug report that will help us help you!

### Before Opening a Bug
P9k is lovingly maintained by volunteers, and we are happy to help you! You can help us by first making sure your issue hasn't already been solved before opening a new one. Please check the [Troubleshooting Guide](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting) first. Many issues are actually local configuration problems, which may have previously been solved by another user - be sure to also [search the existing issues](https://github.com/bhilburn/powerlevel9k/issues?utf8=%E2%9C%93&q=is%3Aissue) before opening a new one.

Once you've done these things, you can delete this section and proceed `=)`

-----

#### Describe Your Issue
What is happening?

my config is below:
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_VCS_HIDE_TAGS=true
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true

output is below:
<img width="274" alt="screen shot 2018-07-14 at 10 05 09 pm" src="https://user-images.githubusercontent.com/2133400/42725181-0a8cb710-87b2-11e8-9428-2faa6e11891b.png">

#### Have you tried to debug or fix it?

no

#### Environment Information
This information will help us understand your configuration. 
macos iterm2 oh-my-zsh

**Comment by onaforeignshore** [comment]
Please supply the P9k version - You can find this by opening `CHANGELOG.md` and looking for the version number at the top of the file. If the version isn't `v0.6.5`, please update your P9k installation and see if the error persists.

**Comment by FinallyFinancialFreedom** [comment]
it install it yestoday. the version is v0.6.5

**Comment by onaforeignshore** [comment]
Please check your iTerm2 settings

[cid:image001.png@01D41C42.A31BE2C0]

[cid:image002.png@01D41C42.A31BE2C0]

**Comment by onaforeignshore** [comment]
Please check your iTerm2 settings

![https://user-images.githubusercontent.com/704406/42732647-34b4ab90-8836-11e8-9f89-5854a07cd452.png](Check Draw bold text in bold font)

![https://user-images.githubusercontent.com/704406/42732651-434c3006-8836-11e8-8f10-121012cf1447.png](Check your color settings)

**Comment by onaforeignshore** [comment]
Did that resolve the issue, or as you still having problems?

**Comment by FinallyFinancialFreedom** [comment]
no, i changed my iterm2 config base on your screenshot, the issue is not resolved.
I give up to set bold, now i set dir foreground to white color.  it's good

**Comment by onaforeignshore** [comment]
The `POWERLEVEL9K_DIR_PATH_HIGHLIGHT_*` variables are there to highlight the last part of the dir path. Did you also set `POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND`, as that would determine the colour of the last part?

**Comment by FinallyFinancialFreedom** [comment]
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
i config like this. i don't need HIGHLIGHT any more.

**Comment by onaforeignshore** [comment]
Ok, but you might want to add `POWERLEVEL9K_DIR_HOME_FOREGROUND="white"` to your config for the home folder.

**Comment by onaforeignshore** [comment]
If your issue is resolved, please close this thread. Thank you
