### ISSUE TITLE
truncate-to-unique crashes the prompt generation

### ISSUE THREAD

**Issue by toadjaune** [bhilburn/powerlevel9k#917]
This is likely related to https://github.com/bhilburn/powerlevel9k/issues/895, but I'm not entirely sure, so here is a bugreport !

#### Describe Your Issue

When using "truncate-to-unique" shortening strategy with a DIR_LENGTH, the path segment crashes, displaying an error in my terminal, and preventing the rest of the prompt from appearing correctly.

Here is the relevant part of my configuration :
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
```
If I cd to `~/a/b`, the error message is the following :
```
prompt_dir:66: no matches found: //a*/
```

#### Have you tried to debug or fix it?

I haven't yet dug deep in the code, but I think the crash is probably happening around [here](https://github.com/bhilburn/powerlevel9k/blob/22a761208d24027a26daa947a7b4034365fefc16/powerlevel9k.zsh-theme#L822).

I have however full reproduction steps with a minimal configuration. On a minimal non-graphical Ubuntu 18.04 fresh install :
```bash
sudo apt-get update && sudo apt-get dist-upgrade
sudo apt-get install vim zsh git
git clone https://github.com/bhilburn/powerlevel9k.git ~/powerlevel9k
echo > .zshrc << EOF
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
source ~/powerlevel9k/powerlevel9k.zsh-theme
EOF
mkdir -p a/b
cd a/b
zsh
```
This gets us on a zsh shell with the behaviour described above on each prompt regeneration.

#### Environment Information
* p9k version : Current `master`, ie `22a76120`, installed from git and manually sourced
* zsh version : `zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`

Since this issue has been reproduced on a clean setup over ssh, and is not a display issue ; my local configuration (terminal emulator, fonts, etc…) is not relevant.

**Comment by toadjaune** [comment]
Just tried it right now, and so far it works perfectly !
Thanks for the fix, and sorry for the duplicate bugreport.

**Comment by bhilburn** [comment]
Thanks so much for the bug report, @toadjaune, and I'm happy to hear that #915 solves your problem!
