### ISSUE TITLE
Transparent background broke

### ISSUE THREAD

**Issue by xufab** [bhilburn/powerlevel9k#918]
#### Describe Your Issue
I was using the `none` color as described here https://github.com/bhilburn/powerlevel9k/issues/240#issuecomment-200072402 to get transparent background color but when I upgraded from 0e3c1924fe40835dfe189227b8a165de147e65a1 to afcb1b7f84466898c632f47a75d7f1cdf5334f13 it stopped working and my background is now dark grey

Is there a way to continue to have a transparent background?

#### Have you tried to debug or fix it?

I think it comes from the change `functions/colors.zsh` between these two commits.
Before (0e3c192): https://github.com/bhilburn/powerlevel9k/blob/0e3c1924fe40835dfe189227b8a165de147e65a1/functions/colors.zsh
After (afcb1b7): https://github.com/bhilburn/powerlevel9k/blob/afcb1b7f84466898c632f47a75d7f1cdf5334f13/functions/colors.zsh
https://github.com/bhilburn/powerlevel9k/compare/0e3c1924fe40835dfe189227b8a165de147e65a1...afcb1b7f84466898c632f47a75d7f1cdf5334f13

#### Environment Information
ZSH version: 5.5.1
Oh-My-ZSH: Yes
P9k install: cloned in `~/.oh-my-zsh/custom/themes/powerlevel9k`
Terminal emulator: Terminator

**Comment by JulienPivard** [comment]
I have a similar problem recently but only with the left prompt.
 
<img width="1243" alt="capture d ecran 2018-07-21 a 19 51 45" src="https://user-images.githubusercontent.com/16414723/43038750-a368527e-8d1f-11e8-9a84-383d8fb6d2a1.png">

At the end of the left prompt first's line background become dark

**Comment by JulienPivard** [comment]
I found a way to solve the problem. I open a pull request

**Comment by xufab** [comment]
@JulienPivard Thanks a lot for that
