### ISSUE TITLE
Question: multiline last prompt elements

### ISSUE THREAD

**Issue by xufab** [bhilburn/powerlevel9k#920]
When using a multiline prompt, There is `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX` and `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` variables to set prefixes.

For the first line, there is the `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` variable to set the differents segments.

Why there isn't something like a `POWERLEVEL9K_MULTILINE_LAST_PROMPT_ELEMENTS` variable to add segments on the last line (context segment for example) ?

**Comment by bhilburn** [comment]
This question confuses me, somewhat. So, fundamentally, the entire left prompt and the entire right prompt are actually a `single prompt` - we have no way of drawing, say, three or four prompts - ZSH does not allow that. We have the ability to split prompts by adding newlines, etc., but we can't add elements to a "top right prompt" and different ones to a "bottom right prompt" - they are all the same prompt.

Can you describe what you mean in a bit more detail? Is this related to #865 or #883?

**Comment by casajaso** [comment]
> This question confuses me, somewhat. So, fundamentally, the entire left prompt and the entire right prompt are actually a `single prompt` - we have no way of drawing, say, three or four prompts - ZSH does not allow that. We have the ability to split prompts by adding newlines, etc., but we can't add elements to a "top right prompt" and different ones to a "bottom right prompt" - they are all the same prompt.
> 
> Can you describe what you mean in a bit more detail? Is this related to #865 or #883?

Im speculating here (mostly since im wondering this same thing ..or at least my interpretation of it)

Is it possible to use the predefined segment elements on the second line rather then appending stdout to the last prompt prefix  like im doing below? 

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'user' 'dir_writable' 'dir')
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status' 'command_execution_time' 'vcs' )
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{black} `uname -n` %K{black}%F{white}\UE0BC : "

**Comment by numered** [comment]
> > This question confuses me, somewhat. So, fundamentally, the entire left prompt and the entire right prompt are actually a `single prompt` - we have no way of drawing, say, three or four prompts - ZSH does not allow that. We have the ability to split prompts by adding newlines, etc., but we can't add elements to a "top right prompt" and different ones to a "bottom right prompt" - they are all the same prompt.
> > Can you describe what you mean in a bit more detail? Is this related to #865 or #883?
> 
> Im speculating here (mostly since im wondering this same thing ..or at least my interpretation of it)
> 
> Is it possible to use the predefined segment elements on the second line rather then appending stdout to the last prompt prefix like im doing below?
> 
> POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'user' 'dir_writable' 'dir')
> POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status' 'command_execution_time' 'vcs' )
> POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{black} `uname -n` %K{black}%F{white}\UE0BC : "

Not the original author but this should be very cool

**Comment by bhilburn** [comment]
I am on a issue-cleaning spree. This issue hasn't had motion in quite some time, and so I am closing it out due to inactivity. If anyone would like to re-open it because they feel it is un-resolved and is something they care about, please feel free to re-raise the discussion!
