### ISSUE TITLE
Powerline Symbols have misaligned height to rest of text

### ISSUE THREAD

**Issue by thedonquixotic** [bhilburn/powerlevel9k#922]
#### Describe Your Issue
Powerline fonts are misaligned. You can also see a gap between the two parts of the arrow
![image](https://user-images.githubusercontent.com/9451726/43019468-b5a915d4-8c22-11e8-9317-5a2bc8b319f4.png)

#### Have you tried to debug or fix it?
This is default powerlevel9k install. I've been fiddling around with other settings in my terminal, Hyperterm but while I've fixed most of those issues this one remains. 

#### Environment Information
This information will help us understand your configuration. 

  - zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
  - Windows 10 WSL
  - Hyper 2 (aka hyperterm, hyper.js)
  - Oh-My-Zsh installation. Zsh hilighting plugin has been installed manually
  - Cloned into OMZ custom/themes folder as per instructions
  - Current

#### Issues with Fonts & Icons
Using just default powerline fonts. I'm going to try and patch my own version of Input Mono in a moment but till then I thought I should report on the simplest test case possible. 

  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? You can check this with (`echo $POWERLEVEL9K_MODE`).

   I installed through the system. When I run the command above I get a blank response. 

  - Please share the contents of `$P9k/debug/font-issues.zsh`.
The contents of the .sh file? That seems weird. But it's below. I also tried running that shell script to see if I could give the output in case that's what the instructions meant, but what I got was an infinite loop:

![image](https://user-images.githubusercontent.com/9451726/43020024-5d7d96b2-8c24-11e8-93e2-1235ffd3b061.png)

```
#!/usr/bin/env zsh
#vim:ft=zsh ts=2 sw=2 sts=2 et fenc=utf-8

# Taken from NeoFetch (slightly modified)
get_term() {
    local term
    # If function was run, stop here.
    #((term_run == 1)) && return

    # Workaround for macOS systems that
    # don't support the block below.
    case "$TERM_PROGRAM" in
        "iTerm.app") term="iTerm2" ;;
        "Terminal.app") term="Apple Terminal" ;;
        "Hyper") term="HyperTerm" ;;
        *) term="${TERM_PROGRAM/\.app}" ;;
    esac

    # Check $PPID for terminal emulator.
    while [[ -z "$term" ]]; do
        parent="$(get_ppid "$parent")"
        name="$(get_process_name "$parent")"

        case "${name// }" in
            "${SHELL/*\/}" | *"sh" | "tmux"* | "screen" | "su"*) ;;
            "login"* | *"Login"* | "init" | "(init)") term="$(tty)" ;;
            "ruby" | "1" | "systemd" | "sshd"* | "python"* | "USER"*"PID"*) break ;;
            "gnome-terminal-") term="gnome-terminal" ;;
            *) term="${name##*/}" ;;
        esac
    done

    # Log that the function was run.
    #term_run=1

    echo "${term}"
}

get_term_font() {
    local term="${1}"
    #((term_run != 1)) && get_term

    case "$term" in
        "alacritty"*)
            term_font="$(awk -F ':|#' '/normal:/ {getline; print}' "${XDG_CONFIG_HOME}/alacritty/alacritty.yml")"
            term_font="${term_font/*family:}"
            term_font="${term_font/$'\n'*}"
            term_font="${term_font/\#*}"
        ;;

        "Apple_Terminal")
            term_font="$(osascript -e 'tell application "Terminal" to font name of window frontmost')"
        ;;
        "iTerm2")
            # Unfortunately the profile name is not unique, but it seems to be the only thing
            # that identifies an active profile. There is the "id of current session of current window"
            # thou, but that does not match to a guid in the plist.
            # So, be warned! Collisions may occur!
            # See: https://groups.google.com/forum/#!topic/iterm2-discuss/0tO3xZ4Zlwg
            # and: https://gitlab.com/gnachman/iterm2/issues/5586
            local currentProfileName=$(osascript -e 'tell application "iTerm2" to profile name of current session of current window')

            # Warning: Dynamic profiles are not taken into account here!
            # https://www.iterm2.com/documentation-dynamic-profiles.html

            local nonAsciiFont
            
            # Count Guids in "New Bookmarks"; they should be unique
            local profilesCount=$(/usr/libexec/PlistBuddy -c "Print :New\ Bookmarks:" ~/Library/Preferences/com.googlecode.iterm2.plist 2>/dev/null | grep -c "Guid")
            for idx in $(seq 0 "${profilesCount}"); do
                local profileName=$(/usr/libexec/PlistBuddy -c "Print :New\ Bookmarks:${idx}:Name:" ~/Library/Preferences/com.googlecode.iterm2.plist 2>/dev/null)
                if [[ "${profileName}" == "${currentProfileName}" ]]; then
                    # "Normal Font"
                    term_font=$(/usr/libexec/PlistBuddy -c "Print :New\ Bookmarks:${idx}:Normal\ Font:" ~/Library/Preferences/com.googlecode.iterm2.plist)
            
                    # Font for non-ascii characters
                    # Only check for a different non-ascii font, if the user checked
                    # the "use a different font for non-ascii text" switch.
                    local useDifferentFont=$(/usr/libexec/PlistBuddy -c "Print :New\ Bookmarks:${idx}:Use\ Non-ASCII\ Font:" ~/Library/Preferences/com.googlecode.iterm2.plist)
                    if [[ "$useDifferentFont" == "true" ]]; then
                        local nonAsciiFont=$(/usr/libexec/PlistBuddy -c "Print :New\ Bookmarks:${idx}:Non\ Ascii\ Font:" ~/Library/Preferences/com.googlecode.iterm2.plist)
                        if [[ "$term_font" != "$nonAsciiFont" ]]; then
                            term_font="$term_font (normal) / $nonAsciiFont (non-ascii)"
                        fi
                    fi
                fi
            done
        ;;

        "deepin-terminal"*)
            term_font="$(awk -F '=' '/font=/ {a=$2} /font_size/ {b=$2} END{print a " " b}' "${XDG_CONFIG_HOME}/deepin/deepin-terminal/config.conf")"
        ;;

        "Hyper"*)
            term_font="$(awk -F "," '/fontFamily/ {a=$1} END{print a}' "${HOME}/.hyper.js" | awk -F "'" '{a=$2} END{print a}')"
        ;;

        "konsole"*)
            # Get Process ID of current konsole window / tab
            child="$(get_ppid "$$")"

            konsole_instances=($(qdbus | grep 'org.kde.konsole'))

            for i in "${konsole_instances[@]}"; do
                konsole_sessions=($(qdbus "${i}" | grep '/Sessions/'))
                for session in "${konsole_sessions[@]}"; do
                    if ((child == "$(qdbus "${i}" "${session}" processId)")); then
                        profile="$(qdbus "${i}" "${session}" environment | awk -F '=' '/KONSOLE_PROFILE_NAME/ {print $2}')"
                        break
                    fi
                done
                [[ "$profile" ]] && break
            done

            # We could have two profile files for the same profile name, take first match
            profile_filename="$(grep -l "Name=${profile}" "${HOME}"/.local/share/konsole/*.profile)"
            profile_filename="${profile_filename/$'\n'*}"
            [[ "$profile_filename" ]] && term_font="$(awk -F '=|,' '/Font=/ {print $2 " " $3}' "$profile_filename")"
        ;;

        "mintty")
            term_font="$(awk -F '=' '!/^($|#)/ && /Font/ {printf $2; exit}' "${HOME}/.minttyrc")"
        ;;

        "pantheon"*)
            term_font="$(gsettings get org.pantheon.terminal.settings font)"
            [[ -z "${term_font//\'}" ]] && term_font="$(gsettings get org.gnome.desktop.interface monospace-font-name)"
            term_font="$(trim_quotes "$term_font")"
        ;;

        "sakura"*)
            term_font="$(awk -F '=' '/^font=/ {a=$2} END{print a}' "${XDG_CONFIG_HOME}/sakura/sakura.conf")"
        ;;

        "terminology")
            term_font="$(strings "${XDG_CONFIG_HOME}/terminology/config/standard/base.cfg" | awk '/^font\.name$/{print a}{a=$0}')"
            term_font="${term_font/.pcf}"
            term_font="${term_font/:*}"
        ;;

        "termite")
            [[ -f "${XDG_CONFIG_HOME}/termite/config" ]] && termite_config="${XDG_CONFIG_HOME}/termite/config"
            term_font="$(awk -F '= ' '/\[options\]/ {opt=1} /^font/ {if(opt==1) a=$2; opt=0} END{print a}' "/etc/xdg/termite/config" "$termite_config")"
        ;;

        "urxvt" | "urxvtd" | "rxvt-unicode" | "xterm")
            term_font="$(grep -i -F "${term/d}*font" < <(xrdb -query))"
            term_font="${term_font/*font:}"
            term_font="$(trim "$term_font")"

            # Xresources has two different font formats, this checks which
            # one is in use and formats it accordingly.
            case "$term_font" in
                *"xft:"*)
                    term_font="${term_font/xft:}"
                    term_font="${term_font/:*}"
                ;;

                "-"*) term_font="$(awk -F '\\-' '{printf $3}' <<< "$term_font")" ;;
            esac
        ;;

        "xfce4-terminal")
            term_font="$(awk -F '=' '/^FontName/ {a=$2} END{print a}' "${XDG_CONFIG_HOME}/xfce4/terminal/terminalrc")"
        ;;
    esac

    echo "${term_font}"
}

local currentTerminal=$(get_term)
local currentFont=$(get_term_font "${currentTerminal}")
print -P "===== Font debugging ====="
print -P "You are using %F{blue}${currentTerminal}%f with Font %F{blue}${currentFont}%f\n"

if [[ $(echo "${currentFont}" | grep -c -E "Powerline|Awesome|Nerd") -eq 0 ]]; then
    print -P "%F{yellow}WARNING%f It does not seem like you use an Powerline-enabled or Awesome Terminal Font!"
    print -P "Please make sure that your font settings are correct!"
else
    print -P "Your font settings seem to be all right. If you still have issues,"
    print -P "it is more likely to be a font issue than a Powerlevel9k related one."
fi

```

  - If this is an icon problem, does the output of `$ get_icon_names` look correct?
Yes it looks correct

**Comment by JulienPivard** [comment]
Try to adjust your terminal policy to another value. I have the same problem if i set size to 10, 11 or 13pt but if I set to 10 or 14pt symbols are aligned. I think you should report the issue to Powerline project.

**Comment by thedonquixotic** [comment]
This does not seem to be the problem. I have tried 8, 10 ,12, 14, 17, 18, 30, and 75pt and all seem to be basically the same proportion of misaligned. I think it might be Hyper.js putting a custom line height or something on the text, but not really sure. 

@JulienPivard  Are you also using Hyper 2?

**Comment by JulienPivard** [comment]
I see that problem with iTerm2 on my Mac but also on my debian with gnome-term, this is why I think it come from Powerline project rather than powerlevel9k.

**Comment by JulienPivard** [comment]
I also use Nerd Fonts and render is really clean only with some font-size. But this won't change the problem this issue cannot be solved here. Try report an issue on the font project pages.

**Comment by thedonquixotic** [comment]
Sorry not sure which page that is. Is that this page?  https://github.com/ryanoasis/powerline-extra-symbols

I can't find any page specifically for the powerline symbols alone.

**Comment by thedonquixotic** [comment]
Actually I imagine ya'll mean this one: https://github.com/powerline/powerline/issues

**Comment by thedonquixotic** [comment]
@JulienPivard I installed by double clicking on the ttf file and having Windows 10 install it like normal. Then I told hyper to use PowerlineSymbols as it's default font. 

I've found a number of other unresolved issues of similar nature. I am now going to try patching my own custom nerd font and try again.

**Comment by JulienPivard** [comment]
Ok good luck ! but the others issues are opened from a while so I do not know if it will be solved one day.

**Comment by onaforeignshore** [comment]
I'm downloaded SauceCodePro NF (AKA Source Code Pro Nerd Font Complete) from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts). I installed Hyperterm and configured it to use wsl. My fonts render correctly when I set `$POWERLEVEL9K_MODE="nerdfont-complete"`. Can you please check what font you are using?

**Comment by thedonquixotic** [comment]
I will do that promptly tomorrow. I spent today trying to patch my own custom font but I seem to be running into some weird errors. I'll try with an already rendered font tomorrow morning.

**Comment by thedonquixotic** [comment]
@onaforeignshore (btw love your username) So I got fontforge working on my linux machine and was able to generate a font using the NerdFonts script. When I use it in Hyper it appears to get rid of the little lines seperating the arrows but the other powerline symbols are boxxed out. I try to set the mode to "nerdfont-complete" but when I do that I get the message `/home/david/.zshrc:127: nerdfont-complete not found` back which I'm not really sure what to do with. I'm going to check to make sure that the font is in fact render my input font and not some fallback. 

EDIT: Yes it is in fact not loading my InputCodeMonoNerd font in Hyper. Maybe the name needs to be different. I'm going to check on that too.

**Comment by thedonquixotic** [comment]
Okay so I got it loading! Apparently it went by font family name and not the name of the font itself. Anyway here's what it looks like. It looks better than it did before but still has wonky height stuff:

![image](https://user-images.githubusercontent.com/9451726/43050921-497a021e-8dd6-11e8-8a58-05d88fa0c9d7.png)

**Comment by thedonquixotic** [comment]
Oh... it looks like input just has the powerline fonts by default and I didn't actually install the new version like I thought I had. The new version name didn't save correctly in FontForge so I'll have to rename it and then resource it. 

This perhaps provides a clue though on what's causing the issue.

![image](https://user-images.githubusercontent.com/9451726/43050985-6e9ea71a-8dd7-11e8-9553-8f7e19390960.png)

**Comment by onaforeignshore** [comment]
Can I ask why you want to generate the font yourself and not just download a precompiled version? I can understand a generated font if you are changing some of the settings, but it really is not worth the trouble if you can use a precompiled version.

**Comment by thedonquixotic** [comment]
I'll also give a precompiled version a shot, it's just I like some of the characteristics of Input in particular. Plus, I don't know if I mentioned it but I'm actually a designer learning to code so fiddling around with this stuff is kind of the way I'm learning. Delving into stuff and pushing around the edges gives me better context to understand how stuff works and why. It's good practice! :)

**Comment by thedonquixotic** [comment]
Well I got my patched font working in Hyper 2 but it's still looking kind of wonky. 

![image](https://user-images.githubusercontent.com/9451726/43113323-8daad9ce-8ebf-11e8-96fa-bb21c5811af6.png)

I decided to install one of the precompiled one, specifically FuraCode NF and....

![image](https://user-images.githubusercontent.com/9451726/43113480-2cceb426-8ec0-11e8-8b36-0f4aec8f6eb8.png)
Kind of fixed? But also kind of broken in other ways. 

I'm to my knowledge just using the default prompt so... not really sure what the deal is there.

**Comment by thedonquixotic** [comment]
On the plus side I did figure out how to more properly format my `POWERLEVEL9K_MODE="nerdfont-complete"` so that it wasn't throwing an error. Unfortunately it does not appear the icons are actually working...

**Comment by dritter** [comment]
The font is now working correctly. Now you have to setup your terminal and P9K accordingly:
1. Set `POWERLEVEL9K_MODE="nerdfont-complete"` at the very top of your `~/.zshrc` to show more icons.
2. Set your terminal to treat ambiguous characters not as double width (I don't know how that setting is called in hyper) to get rid of the space after the right segment separator.

Btw. a better way to show all icons is to call `get_icon_names` in your shell. The `test_icons` segment just prints out all icons as segments with random colors. With your narrow color scheme chances are high to print the icon name (as segment text) in the same color as the background.
The occasional gaps in the left prompt may be related to #929

**Comment by thedonquixotic** [comment]
Yes @dritter  you are indeed correct. I downloaded cmder to see how stuff appeared on another terminal emulator and it came out correctly:
![image](https://user-images.githubusercontent.com/9451726/43121399-408462ea-8ee3-11e8-89f1-80d0aa66ec52.png)

I'm closing this issue out and I'll move over to the hyperterm repo to see if I can get the rest of little bits fixed up. But it looks mostly done! Thanks everyone!
