### ISSUE TITLE
Add fallback icon for missing linux distro icons

### ISSUE THREAD

**Issue by eloo** [bhilburn/powerlevel9k#936]
#### Describe Your Issue
I've just updated to the latest version of the theme and now my OS_ICON is broken.
I'm using a Debian and now the icon is only "Deb" instead of the Tux icon.
I guess it would be great that at least for fonts which are containing the Tux icon this Icon will be used instead of a simple string.
What do you think?

#### Environment Information
This information will help us understand your configuration. 

  - Debian
  - Font: source code pro + powerline awesome
  - Font-Mode: awesome-patched

**Comment by dritter** [comment]
Hi @eloo !

Sorry for the late response. I agree that, as we add more fine-grained control over the Linux icons in Nerd-Fonts, it feels like a bug for other fonts to fall back to a textual representation. That is probably why we get more and more bug reports like this..

Long story short: Would you mind creating a PR for that?

**Comment by eloo** [comment]
yes i can.
i hope i will find time on the weekend for that

**Comment by bhilburn** [comment]
Merged into master as part of #944! Will be in the v0.6.6 release.
