### ISSUE TITLE
Theme doesnt' show when i go supersuser

### ISSUE THREAD

**Issue by miguelcarax** [bhilburn/powerlevel9k#94]
After i do a "sudo su" or "su" the theme disappear and i have no theme.

![captura de pantalla de 2015-09-13 18-22-27](https://cloud.githubusercontent.com/assets/9194709/9837583/7c7cd010-5a44-11e5-8a3b-fd65f85c4a8d.png)

**Comment by dritter** [comment]
`su` switches the user completly. Either you have to install the theme for root as well, or you try to get superuser-rights by using `sudo -s`.

**Comment by miguelcarax** [comment]
How can i install theme for root?

**Comment by dritter** [comment]
Same way as for normal user, clone this repository and source it from your `~/.zshrc` (or install your favorite ZSH-Framework). 

But it strongly recommend to use `sudo -s`, as you don't need to install the theme again.

**Comment by miguelcarax** [comment]
Looks like sudo -s doesn't work for me

I copy my ~/.zshrc and /.oh-my-zsh into /root/ and that's work!!

**Comment by dritter** [comment]
@miguelcarax Glad to hear that!
Can you close this issue then?

**Comment by miguelcarax** [comment]
Closes bhilburn/powerlevel9k#94
