### ISSUE TITLE
Oh my zsh installation failed: path ~/.oh_my_zsh/custom/themes changed?

### ISSUE THREAD

**Issue by juliangaal** [bhilburn/powerlevel9k#942]
####  Issue
After following oh my zsh installation instructions: 
```bash
/home/chitt/.oh-my-zsh/oh-my-zsh.sh:source:110: no such file or directory: /home/chitt/.oh-my-zsh/themes/powerlevel9k/powerlevel9k.zsh-theme
```

#### Environment Information
* zsh 5.1.1 xubuntu16.04
* oh my zsh
* installation: cloning

Not sure if some backend stuff of zsh changed since you wrote the wiki, but changing 
```bash
$ git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
```
to 
```bash
$ git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/themes/powerlevel9k
```
fixed the problem!

Cheers

**Comment by onaforeignshore** [comment]
Updated [Install Instructions](https://github.com/bhilburn/powerlevel9k/wiki/Install-Instructions)

**Comment by dritter** [comment]
Hmm. I am not sure if this is the right solution. Placing the theme in `themes/` Directory might cause problems if you update Oh-My-ZSH.. Secondly, putting custom themes in `custom/themes` is still the [recommended way](https://github.com/robbyrussell/oh-my-zsh#custom-plugins-and-themes) of installing external themes.

Looking into the source, line 110 of `oh-my-zsh.sh` is just an `if` statement. Is your OMZ installation up to date? And did you overwrite `ZSH_CUSTOM`?

**Comment by juliangaal** [comment]
Ah, there's my mistake. I didn't set that. Totally forgot. Sry for the confusion... Tutorial was indeed correct. Cheers

**Comment by dritter** [comment]
Erm. Wait.. Did you now set `ZSH_CUSTOM` and it worked? I am asking, because that should not be necessary at all. This is a variable set by OMZ automatically, if it was not set before. If you want, you could change it..

**Comment by juliangaal** [comment]
I used the default config file, and right now ZSH_CUSTOM is not used at all. Meaning, it is still set to `# ZSH_CUSTOM .....`.

**Comment by dritter** [comment]
Glad you got it working. Closing now.

**Comment by nikita-fuchs** [comment]
I landed here by follwing [this](https://medium.com/@Clovis_app/configuration-of-a-beautiful-efficient-terminal-and-prompt-on-osx-in-7-minutes-827c29391961) tutorial, which gave me the error: 
```
/Users/XYZ/.oh-my-zsh/oh-my-zsh.sh:source:114: no such file or directory: /Users/XYZ/.oh-my-zsh/themes/powerlevel9k/powerlevel9k.zsh-theme
```
what is it now that one needs to do exactly to fix this?

**Comment by Syphdias** [comment]
@nikita-fuchs As far as I can tell this should work. OMZ's line 114 looks like is only called if it didn't find the fitting file in the custom folders. (But I can't be sure without knowing the exact omz version)

Could you do a `ls $ZSH_CUSTOM/themes/${ZSH_THEME}*`? This should be where you cloned p9k to. `ZSH_THEME="powerlevel9k/powerlevel9k"` basically selects the folder and the file that is being sourced.
