### ISSUE TITLE
Seeing a strange gear icon in the bar.

### ISSUE THREAD

**Issue by shahzeb1** [bhilburn/powerlevel9k#946]
Thanks for opening an issue! For a project that deals with as many different things as P9k, debugging problems can be difficult. Please follow the guide, below, to create a bug report that will help us help you!

### Before Opening a Bug
P9k is lovingly maintained by volunteers, and we are happy to help you! You can help us by first making sure your issue hasn't already been solved before opening a new one. Please check the [Troubleshooting Guide](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting) first. Many issues are actually local configuration problems, which may have previously been solved by another user - be sure to also [search the existing issues](https://github.com/bhilburn/powerlevel9k/issues?utf8=%E2%9C%93&q=is%3Aissue) before opening a new one.

Once you've done these things, you can delete this section and proceed `=)`

-----

#### Describe Your Issue
What is happening?

I see a strange gear icon. Not sure why.

Most issues are best explained with a screenshot. Please share one if you can!

<img width="383" alt="gear icon" src="https://user-images.githubusercontent.com/1383831/43736124-618f68d4-9971-11e8-9d98-bf649acd7f30.png">

#### Have you tried to debug or fix it?

Yes I have tried looking around to see if this is a theme issue or an iTerm issue, I can't seem to figure it out.

**Comment by dritter** [comment]
It's not a bug, it's a feature ;)
This gear icon shows if you have background jobs running. You can see them with `jobs`. To bring a command to the foreground you can enter `fg`.

**Comment by shahzeb1** [comment]
Thank you. That is what I ended up finding. Is there any setting which will allow me to turn the gear off? It just ends up taking a lot of space in the row.

**Comment by dritter** [comment]
Yes, just remove `background_jobs` from your `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`..

**Comment by bhilburn** [comment]
Just realized it's likely you are using the default settings. See this part of the docs to customize the segments: https://github.com/bhilburn/powerlevel9k#customizing-prompt-segments

**Comment by shahzeb1** [comment]
Thank you both very much.
