### ISSUE TITLE
White segment separators on the left side

### ISSUE THREAD

**Issue by NightWolf007** [bhilburn/powerlevel9k#948]
#### Describe Your Issue
I was using non-standard colors like mediumpurple4 or grey11 and get white segment separators on the left side.

<img width="834" alt="screen shot 2018-08-09 at 22 29 28" src="https://user-images.githubusercontent.com/3897626/43921331-16aab5f2-9c24-11e8-8373-c12df785161a.png">

#### Have you tried to debug or fix it?
I've found that issue comes from using variable $CURRENT_BG as foreground color directly without converting it to color id through foregroundColor function.
https://github.com/bhilburn/powerlevel9k/blob/571a859413866897cf962396f02f65a288f677ac/powerlevel9k.zsh-theme#L134
https://github.com/bhilburn/powerlevel9k/blob/571a859413866897cf962396f02f65a288f677ac/powerlevel9k.zsh-theme#L183

#### Environment Information
  - ZSH version: 5.1.1
  - Frameworks: Antigen and Oh-My-ZSH
  - P9k install: through Antigen
  - P9k version: v0.6.5
  - Terminal emulator: iTerm2

**Comment by dritter** [comment]
Hi @NightWolf007 !

We already have a fix for that in our preparation branch #944 for the upcoming version. It would be super helpful, if you could try out this branch and report any issues.

Thx

**Comment by NightWolf007** [comment]
Hi @dritter !
Thank you for reply.

I've checked preparation branch. It fixes this issue.
But i noticed, that custom foreground color is not working on the right pane. I think it comes from here:
https://github.com/dritter/powerlevel9k/blob/a0d57bc455e654ba688d108219bd254863bca438/powerlevel9k.zsh-theme#L234
I think there should be foregroundColor variable.

**Comment by NightWolf007** [comment]
Thanks! I will close the issue then.
