### ISSUE TITLE
Ubuntu Icon Missing

### ISSUE THREAD

**Issue by mustafaturksavas** [bhilburn/powerlevel9k#949]
I realized recently that I can't see the icon for Ubuntu anymore. Mac icon and any other icons work just fine, but instead of the ubuntu icon, I just get the text "Ubu".

  - I use "SourceCodePro+Powerline+Awesome+Regular" font
  - My font configuration mode is: "awesome-patched"
  - Contents of `$P9k/debug/font-issues.zsh`:
get_term:16: command not found: get_ppid
get_term:17: command not found: get_process_name
  - When I enter `echo $get_icon_names` I get nothing.

**Comment by dritter** [comment]
Hi @mustafaturksavas !

Yes, we implemented a more fine-grained distinction between the different Linux distributions because `nerd-fonts` have icons for them. Other fonts don't.
In short: You can get back the Tux icon, if you set `POWERLEVEL9K_LINUX_UBUNTU_ICON=$'\uE271'`

Hope that helps.

**Comment by mustafaturksavas** [comment]
Thanks for the fast reply @dritter 

So in long-term, nerd-fonts would be the best bet for using this theme without problems?

**Comment by rjorgenson** [comment]
Would it be possible for awesome fonts to set the icons for ubuntu and other linux systems to the generic tux icon rather than plain text?

**Comment by dritter** [comment]
@rjorgenson Yes, absolutely. This is what @eloo suggested in #936 and I scheduled that Issue in [the v0.6.6](https://github.com/bhilburn/powerlevel9k/projects/2). We should do that.
