### ISSUE TITLE
Switching `awesome-patched`-mode to nerd-fonts

### ISSUE THREAD

**Issue by dritter** [bhilburn/powerlevel9k#95]
I recently stumbled upon another font-patching project [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) which looks quite nice and foremost uses the same codepoints as the original fonts. Using this fonts instead of the awesome-terminal-fonts would improve the code in a sustainable way. We just have to test two font-settings and the users would have a nice overview of the available glyphs (in case they want to override one or another).

It still has some issues with the glyph sizes, but once that is cleaned up, I'll give it a chance. This issue is just to remember me (or to inform anybody who wants to get involved).

**Comment by rjorgenson** [comment]
I found the same thing and tried out a swap the other day. All of the font-awesome icons were narrow and squished, but I was just trying their patched fonts which are about a month old. Might have better luck patching myself. There were also a few glyphs still missing from font-awesome and octicons, but I found suitable replacements for them with what was included.

**Comment by dritter** [comment]
@rjorgenson I had exactly the same experience with nerd-fonts. Thats why this is a long-term issue. The plan to switch fonts is in #97

**Comment by martinpelikan** [comment]
I actually didn't have luck with awesome-terminal-fonts before, because I didn't like any of the pre-patched fonts and urxvt does not like the fontconfig fallback approach. nerd-fonts seems like an outright improvement, at least in my case.

The glyph sizes are appropriate in gnome-terminal (seen on the right). However, I think some/most of these are "double-wide glyphs", so urxvt shrinks them to occupy just one cell (seen on the left). I'm not sure how to configure urxvt to handle this properly and I'm out of ideas at this point. ryanoasis/vim-devicons#11 may be relevant. 

I'm actually amazed at how annoying and complicated fonts are to deal with in the grand scheme of things, but at least this is something.

![2015-10-25-195131_1280x70_scrot](https://cloud.githubusercontent.com/assets/3248296/10720237/04d4f63a-7b52-11e5-92ed-4499852193d2.png)

**Comment by ariscn** [comment]
It looks like none of powerline9k's modes work with nerd-tools? I'm using a pre-patched nerd-tools font (fontawesome, octicons, pomicons, and implicit devicons), and while `awesome-fontconfig` comes close, it still has some gaps:

<img width="1114" alt="screenshot 2015-11-01 00 34 50" src="https://cloud.githubusercontent.com/assets/13629660/10867746/6f7d88e8-8030-11e5-81f2-a8224916158a.png">
 
It's pretty clear how to add a new mode to powerline9k, but how can I figure out the corresponding nerd-tools codepoints?

**Comment by ryanoasis** [comment]
Ah font fun :smirk: 

@dritter Yeah unfortunately there are quite a few serious issues still :worried: so I have mostly been focusing on the low hanging fruit to keep the project moving :smile: . I was initially just creating it for another project I had but the more useful others find it the more I try to put into it.

@rjorgenson All of the "pure" mono versions currently have the squished issue/effect. If you can use the double width glyph version (if your terminal allows it) you might get better results

@martinpelikan Yeah the primary driving force behind the "pure" mono versions was to get the glyphs to show up in terminal emulators like urxvt where seems to skip them if they are too wide.

@ariscn see my comment on: https://github.com/ryanoasis/nerd-fonts/issues/40#issuecomment-152863133

**Comment by dritter** [comment]
@ryanoasis Don't worry, I'll wait till everything is ready :wink:

**Comment by DanielGGordon** [comment]
I tried a few nerd fonts (using Babun with Zsh on Windows via Mintty), but none of them worked properly. Getting these fonts to work with Windows is a big pain.

**Comment by ryanoasis** [comment]
@DanielGGordon Yeah I have not had a lot of time recently and I never really tested the fonts on Windows fully. Nevertheless your feedback is helpful for me to focus on the pain points :+1:

**Comment by DanielGGordon** [comment]
[Meslo LG M for Powerline](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Meslo/M/complete/Meslo%20LG%20M%20Regular%20for%20Powerline%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf) actually seems to work fine for me - this is a nerd font.

Although all the icons are a bit small.

**Comment by biax** [comment]
i tried several nerd fonts and none seem to display the clock: 
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \uE868  %d.%m.%y}"

anyone have the below working?
DejaVu Sans Mono for Powerline Nerd Font Plus Font Awesome Mono Windows Compatible.ttf

all i get is a weird compressed block.

**Comment by akrueger** [comment]
@martinpelikan What unicode symbols are you using in that photo to connect your first and second line? I have something like that but it's not nearly so smooth.

**Comment by TheDoctorsLife** [comment]
Whats the current status of this?

**Comment by bhilburn** [comment]
I will be pulling in a separate font config option for nerd-fonts via @lcorsini's #390 PR!

**Comment by SirDoctors** [comment]
@bhilburn Could I just send in a pr for it to be on the "next" branch? I'd rather have this sooner than later.

**Comment by bhilburn** [comment]
We finally have nerd-fonts support!

**Comment by DanielGGordon** [comment]
The problem is for windows users - I'm trying to use nerd fonts with the new Ubuntu For Windows terminal. A lot of the icons look small - and you have to use monospace.

**Comment by DanielGGordon** [comment]
The problem is for windows users - I'm trying to use nerd fonts with the new Ubuntu For Windows terminal. A lot of the icons look small - and you have to use monospace.

**Comment by ryanoasis** [comment]
@DanielGGordon Yeah the monospace ones will have to be small to maintain scale to fit as a single-width glyph. As for Windows and non-mono fonts... I don't know too much on what is possible so I'd have to get back to you on that!

**Comment by batousik** [comment]
@DanielGGordon same issue
