### ISSUE TITLE
The awesome font doesn't work automatically

### ISSUE THREAD

**Issue by aoitechs** [bhilburn/powerlevel9k#953]
I have installed the awesome font patched, and the config in `~/.zshrc` is:
`POWERLEVEL9K_MODE='awesome-patched'`
However I have found the font doesn't apply automatically, and when I force reload the zshrc file manually, the awesome font works, just like:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/18051759/44145580-b64aee76-a0be-11e8-9392-0aedd38d95e5.png">

and whenever I opened a new terminal, it just goes back to that without the awesome font.

how to make this work properly?

**Comment by onaforeignshore** [comment]
Did you call the font code definition scripts before or after sourcing powerlevel9k? My guess is that they are after, which is why it works after sourcing `.zshrc` again. You should source them before you source powerlevel9k.

**Comment by aoitechs** [comment]
@onaforeignshore 
I'm using iTerm2 and ohmyzsh but I didn't write any script defining font. Is there any possible that it has conflict with these two? 
or may I ask how does zsh source powerlevel9k, maybe I can have a recheck?

**Comment by aoitechs** [comment]
Well a little bit embarrassing, I just put this line
`POWERLEVEL9K_MODE='awesome-patched'`
just after `ZSH_THEME="powerlevel9k/powerlevel9k"`
and it finally works.
So I guess what you have guessed is right xd
@onaforeignshore
