### ISSUE TITLE
Required to Load Source for zsrc Konsole is launched

### ISSUE THREAD

**Issue by DanitiKain** [bhilburn/powerlevel9k#954]
https://streamable.com/07mqf

I have a video showing have it have to do to get this to work.

I have tried based on suggestions in stackoverflow to move the source $ZSH/oh-my-zsh.sh after the POWERLEVEL9k command line parameters. This did not work and even when I load the source file would not show the line as it should.

Here is my config file. https://hastebin.com/otolobihuw.makefile

Sorry I don't know where the best place to get support on this is so I am trying the issues section on powerlevel9k.  I tried stackoverflow as well and didn't hear anything back.

**Comment by rjorgenson** [comment]
Hi @DanitiKain,

Try sourcing the p9k theme file after setting all the p9k variables. You need to move 
```source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme```
to the end of your zshrc file.

I'm also not really sure what conflicts there may or may not be with having an ohmyzsh theme set in addition to sourcing p9k, but if it works okay for you after manually sourcing your zshrc again then moving the loading of the theme to after all the theme settings should be sufficient.

**Comment by DanitiKain** [comment]
That resolved the issue and I also disabled the theme for oh-my-zsh.  I thought it would just make things faster.  Why load 2 themes?  :)  Thank you for pointing that out.

**Comment by rjorgenson** [comment]
No problem, glad to help =]
