### ISSUE TITLE
vi-mode segment

### ISSUE THREAD

**Issue by christian-schulze** [bhilburn/powerlevel9k#96]
I'm using the `vi-mode` plugin, and have hacked together a custom segment to indicate the editing mode. Is this something you would consider adding to your theme? 
```zsh
prompt_vi_mode() {
  local mode="${${KEYMAP/vicmd/NORMAL}/(main|viins)/INSERT}"
  if [[ "$mode" == "NORMAL" ]]; then
    $1_prompt_segment "$0" "$DEFAULT_COLOR" "default" "$mode"
  else
    $1_prompt_segment "$0" "$DEFAULT_COLOR" "blue" "$mode"
  fi
}
```

**Comment by dritter** [comment]
@christian-schulze Cool! Thanks for your contribution. Could you make a proper pull request? I think there are a couple people using vi-mode.

**Comment by bhilburn** [comment]
Added in PR #98 merge!
