### ISSUE TITLE
[Question]: What is the difference between the git clean and git untracked?

### ISSUE THREAD

**Issue by Who23** [bhilburn/powerlevel9k#967]
I just wasn't sure what the difference is between the vcs prompt colors, and i couldn't find it anywhere else. Apologies if I missed it in the docs.

**Comment by CanRau** [comment]
I'm still not a git expert myself, yet as far as I understand

a clean git repo means you have no unstaged, uncommited nor untracked files

git untracked in this case would mean you've got a clean repo except for untracked files

as a reference
**untracked file**: a file never added to the git index, so for example you commited everything, so have a clean repo, than created a new file and before you do the first `git add newfile.md` it'll be untracked

**unstaged file**: this one has already been added to your git index using `git add` and was committed and then you edited it but haven't `git add`ed it so far, in this state it's been *tracked* but not *staged*
so the stage is the status where it has been prepared to be committed but the commit hasn't happened so far

does that answer your question?

**Comment by Who23** [comment]
yes @CanRau thank you so much!

**Comment by CanRau** [comment]
you're very welcome, glad I could help 👍

**Comment by Tundee** [comment]
Thank U CanRau
