### ISSUE TITLE
`truncate_with_package_name` shorten strategy does not seem to work

### ISSUE THREAD

**Issue by Sasszem** [bhilburn/powerlevel9k#968]
#### Describe Your Issue
I've just installed PL9k from git, and tried to set the `truncate_with_package_name` shortening strategy, but it does not seem to work, the path stays expanded. 

I added the line `POWERLEVEL9K_SHORTEN_STRATEGY="truncate_with_package_name"` to my `.zshrc`.

**Comment by onaforeignshore** [comment]
Did you add the line before or after you source the theme? All settings should be done before sourcing the theme

**Comment by Sasszem** [comment]
In fact, I did not. I've done it now, but it still does not work.
Now the config(part of my `.zshrc`)
```bash

# Powerlevel9k customization

source ~/.fonts/*.sh

POWERLEVEL9K_MODE='awesome-fontconfig'

DEFAULT_USER=$USER

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_with_package_name"
POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json)

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"
```

PS: I have OMZsh

**Comment by onaforeignshore** [comment]
Could you send a screenshot of what you are seeing please?

**Comment by dritter** [comment]
@Sasszem Sorry for the late response.
The `package.json`/`composer.json` must be in the root folder of a git repo to make the code work. Could you double check that your directory is a git repo?

@onaforeignshore I agree, this could be refactored to work with `upsearch`. That way we could get rid of the `git` dependency here.

**Comment by xel-x** [comment]
As far as I can tell you need to add a POWERLEVEL9K_SHORTEN_DIR_LENGTH for it to take effect (which does not seem to make sense, but works for me)

I personally added the following to my config, which brought truncation to live
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1024
```

**Comment by dritter** [comment]
Interesting @xel-x . The `SHORTEN_DIR_LENGTH` is there because of historical reasons. At the beginnings we only had truncation strategies that operated on directories or folders; they always had something to do with a specific length. Because of that making no sense, [we changed the condition](https://github.com/bhilburn/powerlevel9k/blob/ad14807cef372994c3ba00632117f6d43b798ffb/powerlevel9k.zsh-theme#L806) that triggered the truncation.

@Sasszem Could you post the output of:
```zsh
if [[ -n "$POWERLEVEL9K_SHORTEN_DIR_LENGTH" || "$POWERLEVEL9K_SHORTEN_STRATEGY" == "truncate_with_folder_marker" || "$POWERLEVEL9K_SHORTEN_STRATEGY" == "truncate_to_last" ]]; then
 echo "Shorten Strategy active";
fi
```
