### ISSUE TITLE
Something between tag 0.6.4 and tag 0.6.5 is causing the history prompt to break on remote server

### ISSUE THREAD

**Issue by drhay53** [bhilburn/powerlevel9k#969]
I have been pulling my hair out over a weird issue with the history prompt that I started seeing after a fresh install of powerlevel9k. I have tested it over several of the powerline fonts and see the same thing. 

These are my prompt elements:
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir anaconda vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)

On tag 0.6.4, I see this:
<img width="722" alt="historybug0 6 4" src="https://user-images.githubusercontent.com/5826711/44592641-2ce27280-a78f-11e8-9c03-51cd10c6ade2.png">

On 0.6.5 I see this:
<img width="725" alt="historybug0 6 5" src="https://user-images.githubusercontent.com/5826711/44592679-48e61400-a78f-11e8-86c3-4a37dae23601.png">

Requested details:
-zsh version: zsh 5.0.2 (x86_64-redhat-linux-gnu)
-Have tested with and without oh-my-zsh, which I normally use. Above screenshots without oh-my-zsh installed.
-P9K was installed by cloning the repo, adding `source  ~/powerlevel9k/powerlevel9k.zsh-theme` to my ~.zshrc, and then to debug I started switching tags and checking behavior.
-I use iterm2, and in this case I am ssh'ed into a remote server.

-Behavior persists across powerline fonts, but the font in the screenshots is Source Code Pro for Powerline
-$POWERLEVEL9K_MODE is not set in my environment.
-$P9k/debug/font-issues.zsh is empty
-there are some blank icons in get_icon_names, but nothing that looks out of the ordinary.

**Comment by dritter** [comment]
Hi @drhay53 ,
You are using a quite old ZSH version that is [not supported](https://github.com/bhilburn/powerlevel9k/wiki/Minimum-System-Requirements) by P9K any more. Could you update your Shell and try again?

**Comment by drhay53** [comment]
My mistake, I did not notice the minimum requirements for ZSH on the wiki. Unfortunately I don't have control over this on the server, and so I will have to stick with 0.6.4 until something changes.

**Comment by dritter** [comment]
There is still a thing you could do: The problem appears with certain colors only and the default history segment uses `grey50` as background color. So, if you set `POWERLEVEL9K_HISTORY_BACKGROUND='244'` the problem should disappear.
