### ISSUE TITLE
Wrong commit hash icon on awesome-fontconfig mode

### ISSUE THREAD

**Issue by irftokped** [bhilburn/powerlevel9k#972]
#### Describe Your Issue
I've got the symbol for female instead of the commit hash icon in left prompt elements
![image](https://user-images.githubusercontent.com/29912981/44849571-c2489f80-ac84-11e8-9a01-e8c863427491.png)

#### Have you tried to debug or fix it?
It's quite a normal installation with the font config file as follows:
```<fontconfig>
  <alias>
    <family>monospace</family>
    <prefer>
            <!--<family>Pomodoro</family> -->
            <!-- <family>FontAwesome</family> -->
            <!-- <family>Octicons</family> -->
            <!-- <family>Icomoon</family> -->
             <family>PowerlineSymbols</family>
    </prefer>
  </alias>c

</fontconfig>
```

and the config override i got on .zshrc are as follow
```export TERM="xterm-256color"
source ~/.fonts/*.sh
# Path to your oh-my-zsh installation.
  export ZSH="/home/nakama/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
POWERLEVEL9K_MODE='awesome-fontconfig'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time docker_machine)

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHOW_CHANGESET=true
ZSH_THEME="powerlevel9k/powerlevel9k"
```

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using? You can use `zsh --version` to see this. : zsh 5.4.2
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)? : Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)? : cloning into oh-my-zsh theme folder
  - What version of P9k are you using? current master branch (as of now, [this commit])(https://github.com/bhilburn/powerlevel9k/commit/22a761208d24027a26daa947a7b4034365fefc16)
  - Which terminal emulator do you use? : tilda? does it break it?

#### Issues with Fonts & Icons
You may delete this section if your issue is not font / icon related.

  - Which font do you use?  : awesome-terminal fonts
  - Which [font configuration mode](https://github.com/bhilburn/powerlevel9k/wiki/About-Fonts) are you using? You can check this with (`echo $POWERLEVEL9K_MODE`). : awesome-fontconfig
  - Please share the contents of `$P9k/debug/font-issues.zsh`. : can't found this file
  - If this is an icon problem, does the output of `$ get_icon_names` look correct? nope, it shows the "female icon" 
![image](https://user-images.githubusercontent.com/29912981/44849915-d3de7700-ac85-11e8-97e8-11e81739fe0f.png)

**Comment by onaforeignshore** [comment]
What do you get when you do `echo ${CODEPOINT_OF_OCTICONS_BOOKMARK}`?

**Comment by onaforeignshore** [comment]
In awesome-fontconfig we make use of `${CODEPOINT_OF_xxx}` which is the codepoints specified in `source ~/.fonts/*.sh`. If a font is not available on the system for that codepoint, or if another font takes president and has a different glyph for that number, it will display. Thus, you would have to ensure the order of president has glyph fonts before powerline fonts. Alternatively, you could use a nerd font, which already has all of the other fonts built into it.

**Comment by irftokped** [comment]
Hi, thanks for answering

the echo comand that you gives me return nothing, it's just a newline
there might be something wrong with my setup, though i manage to replicate it on another machine

I'll check the .sh file that you mentioned
thanks

**Comment by irftokped** [comment]
Yeah, given up on awesome-terminals and used the nerdfont instead
now it works everywhere

closing this issue now
