### ISSUE TITLE
/etc/os-release does not exist

### ISSUE THREAD

**Issue by EmreAtes** [bhilburn/powerlevel9k#974]
#### Describe Your Issue
At log in, the error message `grep: /etc/os-release: No such file or directory` is printed

#### Have you tried to debug or fix it?
In the file funcitons/utilities.zsh:105 the grep tries finding an `/etc/os-release` file, and doesn't work if that file doesn't exist.

#### Environment Information
I'm using the master branch of powerlevel9k, and my OS is Centos 6.4 (in `/etc/centos-release`, it says `CentOS release 6.4 (Final)`)

**Comment by pgierz** [comment]
I also have this problem under redhat:

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.10 (Santiago)
```

**Comment by bhilburn** [comment]
Closed by merge of #988. Trying to fix it in `master` in #981, too.

**Comment by HipHopCoderS** [comment]
> I also have this problem under redhat:
> 
> ```
> $ cat /etc/redhat-release
> Red Hat Enterprise Linux Server release 6.10 (Santiago)
> ```

I have same probleme!

**Comment by dritter** [comment]
Good point @jandk008 , I added #981  to the [upcoming version](https://github.com/bhilburn/powerlevel9k/projects/5).
