### ISSUE TITLE
Version Control segment puts color entire line

### ISSUE THREAD

**Issue by pgierz** [bhilburn/powerlevel9k#980]
#### Describe Your Issue
When I change directories into a version controlled directory, the prompt colors the entire line and doesn't display my git status as I expect. This seems to be machine dependent?

Example 1 (broken case):
On a redhat machine:
```
$ cat /etc/redhat-release                                                                                           
Red Hat Enterprise Linux Server release 6.10 (Santiago)
```
![screen shot 2018-09-07 at 08 02 13](https://user-images.githubusercontent.com/2444231/45201155-637eb980-b274-11e8-9938-231b9acfe8ee.png)

Example 2 (working case):
On a CentOS:
```
$ cat /etc/os-release                                                                                                       
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
![screen shot 2018-09-07 at 08 04 15](https://user-images.githubusercontent.com/2444231/45201200-9fb21a00-b274-11e8-94ed-9b0f2e6be24e.png)
On my MacBook:
![screen shot 2018-09-07 at 08 04 44](https://user-images.githubusercontent.com/2444231/45201214-b35d8080-b274-11e8-8959-af80ddd77cb8.png)

#### Environment Information
This information will help us understand your configuration. 

  - What version of ZSH are you using?
On the broken machine, I have: zsh 4.3.11 (x86_64-redhat-linux-gnu)
  - Do you use a ZSH framework (e.g., Oh-My-ZSH, Antigen)?
I'm using Oh-My-ZSH
  - How did you install P9k (cloning the repo, by tarball, a package from your OS, etc.,)?
Clone the repo
  - What version of P9k are you using?
The master as of this morning (f73c29a)
  - Which terminal emulator do you use?
Apple's default terminal program (Terminal, v. 2.8.2)
#### Issues with Fonts & Icons
All hosts are using the same terminal profile, and I am using Hack Regular Nerd Font Complete

Thanks very much for any help!

**Comment by bhilburn** [comment]
Hey @pgierz - It looks like on the broken machine you are way, _way_ below the minimum supported version of ZSH (see here: [Minimum System Requirements](https://github.com/bhilburn/powerlevel9k/wiki/Minimum-System-Requirements)).

ZSH-4.3.11 was released in 2010. Is there any chance you can upgrade the version of ZSH being used, there? :-/

**Comment by pgierz** [comment]
That might be part of the problem. My laptop has zsh 5.3 (x86_64-apple-darwin17.0), and the other supercomputer (with working prompts) I work one has zsh 5.0.2 (x86_64-redhat-linux-gnu). I'll send an email to the support guys who run the other cluster, maybe they can update the version.

If not, do you know if it would be difficult to locally install my own zsh?

**Comment by pgierz** [comment]
Updating to a newer version seems to have solved this problem, thanks!
