### ISSUE TITLE
Arrow is small and not aligned nicely

### ISSUE THREAD

**Issue by SarKurd** [bhilburn/powerlevel9k#984]
If anyone has a suggestion please let me know

i don't have much info with Powerline and ZSH so here the files

.zshrc zsh 5.3

```
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_MODE='nerdfont-complete'

zsh_wifi_signal(){
    local color='%F{black}'
    echo -n "%{$color%}\uf186"
}

POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="zsh_wifi_signal"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( custom_wifi_signal dir vcs )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm time)
POWERLEVEL9K_CHRUBY_SHOW_ENGINE=true
```

Terminal
https://imgur.com/g8vx6I1

https://imgur.com/RTUHhhy

**Comment by dritter** [comment]
Hi @SarKurd 

Issues like that are a matter of how the font was build, and how the terminal displays them. Both are out of scope for P9K. Could you head over to the nerd-fonts repo, and file your issue there?
