### ISSUE TITLE
P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON not converting unicode

### ISSUE THREAD

**Issue by sambadevi** [bhilburn/powerlevel9k#995]
#### Describe Your Issue
What is happening?

`P9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="\uF460"` does not seem to work anymore on `next` branch. I get the literal "\uF640" in my prompt

#### Have you tried to debug or fix it?

Just by changing the value and checking whether the font is installed correctly. It did work on `master`

#### Environment Information
This information will help us understand your configuration. 

  - zsh 5.3.1
  - antigen and oh-my-zsh
  - installed with `antigen theme bhilburn/powerlevel9k@next`
  - iTerm 2

#### Issues with Fonts & Icons

  - SauceCode Pro Nerd Font
  - `P9K_MODE='nerdfont-complete'`
  - Please share the contents of `$P9k/debug/font-issues.zsh`.
This is probably due to using this on a machine I sshed into.
```
$ .antigen/bundles/bhilburn/powerlevel9k-next/debug/font-issues.zsh
functions/colors.zsh:source:4: datei oder Verzeichnis nicht gefunden: functions/colors.zsh
functions/icons.zsh:source:5: datei oder Verzeichnis nicht gefunden: functions/icons.zsh
functions/utilities.zsh:source:6: datei oder Verzeichnis nicht gefunden: functions/utilities.zsh
===== Font debugging =====
You are using  with Font

WARNING It does not seem like you use an Powerline-enabled or Awesome Terminal Font!
Please make sure that your font settings are correct!
```
  - If this is an icon problem, does the output of `$ get_icon_names` look correct?
Seems like it outputs the `awesome` font-config

**Comment by onaforeignshore** [comment]
To use Unicode characters in a string, you have to use this format `'$\uF640'` to be interpreted as a character and not a string.

**Comment by onaforeignshore** [comment]
Updated Wiki - [Troubleshooting](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#strange-characters-in-a-segment-icon--multiline-prompt-prefix)

**Comment by sambadevi** [comment]
Thanks, it worked!
